CREATE TABLE [dbo].[AkusherskoeUzi] (
    [ID]                                    INT          NOT NULL,
    [PatID]                                 INT          NULL,
    [VidIssledovanie]                       INT          NULL,
    [Beremennost]                           INT          NULL,
    [KolichestvoPlodovVMatke]               INT          NULL,
    [Polozhenie]                            INT          NULL,
    [Predlezhanie]                          INT          NULL,
    [Serdtsebienie]                         INT          NULL,
    [BezOsobennostey]                       NVARCHAR (1) NULL,
    [SmeshenieSredinnogoMEho]               NVARCHAR (1) NULL,
    [CisternaMagna]                         INT          NULL,
    [BokovieZheludochkiMozga]               INT          NULL,
    [ZhidkostVSubarohnoidalnomProstranstve] INT          NULL,
    [RazmerMozzhechka]                      FLOAT (53)   NULL,
    [RazmerMozzhechka1]                     FLOAT (53)   NULL,
    [RazmerMozzhechka2]                     FLOAT (53)   NULL,
    [ZheludochnoPolusharniyIndeks]          INT          NULL,
    [Sostavlyaet]                           FLOAT (53)   NULL,
    [Razmei]                                INT          NULL,
    [Lotsiruetsya]                          INT          NULL,
    [Chetirehkamernoe]                      NVARCHAR (1) NULL,
    [Trehkamernoe]                          NVARCHAR (1) NULL,
    [PeregorodkaVPredserdiyah]              NVARCHAR (1) NULL,
    [PeregorodkaVZheludochkah]              NVARCHAR (1) NULL,
    [DlinaBedra]                            FLOAT (53)   NULL,
    [SredniyDiametrZhivota]                 FLOAT (53)   NULL,
    [YadroBeklara]                          FLOAT (53)   NULL,
    [Data]                                  DATETIME     NULL,
    [NomerIssledovaniya]                    INT          NULL,
    [Kontur]                                INT          NULL,
    [BryushnayaPolostNeZamknuta]            NVARCHAR (1) NULL,
    [RazmerPecheni]                         INT          NULL,
    [EhoPlotnost]                           INT          NULL,
    [VnutripechenochnieZhelchnieProtoki]    INT          NULL,
    [ZhelchniyPuzir]                        INT          NULL,
    [Selezenka]                             INT          NULL,
    [Zheludok]                              INT          NULL,
    [Forma]                                 INT          NULL,
    [Kishechnik]                            INT          NULL,
    [ImeetsyaPeristaltika]                  NVARCHAR (1) NULL,
    [Pochka]                                INT          NULL,
    [Razmer]                                INT          NULL,
    [FormaMochevogoPuzirya]                 INT          NULL,
    [Obem]                                  INT          NULL,
    [ChashechnoLohanochnayaSistema]         INT          NULL,
    [SostoyanieOrganovBezOsobennostey]      NVARCHAR (1) NULL,
    [OkoloplodnieVodi]                      INT          NULL,
    [NalichieAmnioticheskoyPeregorodki]     NVARCHAR (1) NULL,
    [Lokalizatsiya]                         INT          NULL,
    [RaspolozhenaOtVnutrennegoZevaNizheNa]  FLOAT (53)   NULL,
    [TolshinaPlatsenti]                     INT          NULL,
    [StepenZrelostiPlatsenti]               INT          NULL,
    [UchastkiKaltsifikatov]                 NVARCHAR (1) NULL,
    [DopolnitelnieObrazovaniya]             NVARCHAR (1) NULL,
    [OtsloykaPlatsenti]                     NVARCHAR (1) NULL,
    [SredniyDiametrGrudi]                   FLOAT (53)   NULL,
    [RazmerMozzhechka3]                     FLOAT (53)   NULL,
    [OkruzhnostGolovki]                     FLOAT (53)   NULL,
    [FormaGolovki]                          INT          NULL,
    [DopolnitelnieDannieUzi]                NTEXT        NULL,
    [BeremennostNedel]                      INT          NULL,
    [Zaklyuchenie]                          INT          NULL,
    [Rekomendatsii]                         INT          NULL,
    [Zakluchenie]                           NTEXT        NULL,
    [Vrach]                                 INT          NULL,
    [PredlezhaniePlacenti]                  INT          NULL,
    CONSTRAINT [AkusherskoeUziPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [AkusherskoeUziToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

