CREATE TABLE [dbo].[AkusherskiyOsmotr] (
    [ID]                                  INT           NOT NULL,
    [PatID]                               INT           NULL,
    [PerenesennieZabolevaniya]            NTEXT         NULL,
    [Allergoanamnez]                      NTEXT         NULL,
    [LichnayaZhizn]                       NTEXT         NULL,
    [Gemotransfuzii]                      NTEXT         NULL,
    [MenstrualnayaFunktsiya]              NTEXT         NULL,
    [PredidushieBeremennostiIIhIshodi]    NTEXT         NULL,
    [DataPosledneyMenstruatsii]           DATETIME      NULL,
    [DistanciaSpinarum]                   NVARCHAR (50) NULL,
    [DistanciaCristarum]                  NVARCHAR (50) NULL,
    [DistanciaTrochanterica]              NVARCHAR (50) NULL,
    [ConExterna]                          NVARCHAR (50) NULL,
    [RombMihaelisa]                       NVARCHAR (50) NULL,
    [IndeksSoloveva]                      NVARCHAR (50) NULL,
    [VisotaDnaMatki]                      NVARCHAR (50) NULL,
    [PredpolagaemayaMassaPloda]           NVARCHAR (50) NULL,
    [Zhalobi]                             NTEXT         NULL,
    [Sostoyanie]                          NVARCHAR (50) NULL,
    [PS]                                  NVARCHAR (50) NULL,
    [AD]                                  NVARCHAR (50) NULL,
    [EditBox1]                            NVARCHAR (50) NULL,
    [Zhivot]                              NVARCHAR (50) NULL,
    [SimptomShetkinaBlyumberga]           NVARCHAR (50) NULL,
    [Matka]                               NVARCHAR (50) NULL,
    [PolozheniePloda]                     NVARCHAR (50) NULL,
    [PredlezhashayaChast]                 NVARCHAR (50) NULL,
    [SerdtsebieniePloda]                  NVARCHAR (50) NULL,
    [Vodi]                                NVARCHAR (50) NULL,
    [Oteki]                               NVARCHAR (1)  NULL,
    [Oteki1]                              NVARCHAR (1)  NULL,
    [Oteki2]                              NVARCHAR (1)  NULL,
    [Oteki3]                              NVARCHAR (1)  NULL,
    [Oteki4]                              NVARCHAR (1)  NULL,
    [NaruzhniePolovieOrganiRazviti]       NVARCHAR (50) NULL,
    [SheykaMatkiDlinoy]                   NVARCHAR (50) NULL,
    [SheykaMatkiDlinoy1]                  NVARCHAR (50) NULL,
    [TservikalniyKanalProhodimDlya]       NVARCHAR (50) NULL,
    [NaruzhniyZevPropuskaetKonchikPaltsa] NVARCHAR (1)  NULL,
    [OsmotrSheykiMatkiPriPomoshiZerkal]   NTEXT         NULL,
    [PredlezhashayaChast1]                NVARCHAR (50) NULL,
    [Mis]                                 NVARCHAR (50) NULL,
    [EkzostovVMalomTazuNet]               NVARCHAR (1)  NULL,
    [VideleniyaIzPolovihPutey]            NTEXT         NULL,
    [Osobennosti]                         NTEXT         NULL,
    [Diagnoz]                             NTEXT         NULL,
    [Zaklyuchenie]                        NTEXT         NULL,
    [Rekomendatsii]                       NTEXT         NULL,
    [Memo1]                               NTEXT         NULL,
    [Richedit1]                           NTEXT         NULL,
    [Memo2]                               NTEXT         NULL,
    [Memo3]                               NTEXT         NULL,
    [Memo4]                               NTEXT         NULL,
    [DateBox1]                            DATETIME      NULL,
    [DateBox2]                            DATETIME      NULL,
    CONSTRAINT [AkusherskiyOsmotrPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [AkusherskiyOsmotrToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

