CREATE TABLE [dbo].[Allergolog] (
    [ID]                                            INT           NOT NULL,
    [PatID]                                         INT           NULL,
    [Vrach]                                         NVARCHAR (50) NULL,
    [Data]                                          DATETIME      NULL,
    [Zhalobi]                                       NTEXT         NULL,
    [AnamnezZabolevaniya]                           NTEXT         NULL,
    [LichnayaGigiena]                               NVARCHAR (50) NULL,
    [Inektsii]                                      NVARCHAR (1)  NULL,
    [LechenieUStomatologa]                          NVARCHAR (1)  NULL,
    [Operatsii]                                     NVARCHAR (1)  NULL,
    [Transfuzii]                                    NVARCHAR (1)  NULL,
    [Tb]                                            NVARCHAR (1)  NULL,
    [Vich]                                          NVARCHAR (1)  NULL,
    [Malyariya]                                     NVARCHAR (1)  NULL,
    [Tif]                                           NVARCHAR (1)  NULL,
    [Paratif]                                       NVARCHAR (1)  NULL,
    [Gepatit]                                       NVARCHAR (1)  NULL,
    [AdNaPravoyVerhneyKonechnosti2]                 INT           NULL,
    [AdNaLevoyVerhneyKonechnosti2]                  INT           NULL,
    [AdNaLevoyNizhneyKonechnosti2]                  INT           NULL,
    [AdNaPravoyNizhneyKonechnosti2]                 INT           NULL,
    [PulsatsiyaBryushnoyChastiAorti1]               NVARCHAR (1)  NULL,
    [Medikamentov]                                  NTEXT         NULL,
    [Produktov]                                     NTEXT         NULL,
    [NalichieOslozhneniyTransfuzii]                 NTEXT         NULL,
    [GruppaKrovi]                                   NVARCHAR (50) NULL,
    [Rh]                                            NVARCHAR (50) NULL,
    [TransfuziiRanshe]                              NVARCHAR (50) NULL,
    [BitovieUsloviya]                               NVARCHAR (50) NULL,
    [UpotreblenieNarkotikov]                        NVARCHAR (50) NULL,
    [IstochnikPitevoyVodi]                          NVARCHAR (50) NULL,
    [UpotreblenieSiroyVodi]                         NVARCHAR (50) NULL,
    [NalichieTb]                                    NVARCHAR (50) NULL,
    [Zpp]                                           NVARCHAR (50) NULL,
    [ObektivniyStatus]                              NTEXT         NULL,
    [SosudiVerhnihKonechnostey]                     NTEXT         NULL,
    [SosudiNizhnihKonechnostey]                     NTEXT         NULL,
    [PulsNaLevoySonnoyArterii]                      INT           NULL,
    [PulsNaPravoySonnoyArterii]                     INT           NULL,
    [AdNaPravoyVerhneyKonechnosti]                  INT           NULL,
    [AdNaLevoyVerhneyKonechnosti]                   INT           NULL,
    [AdNaLevoyNizhneyKonechnosti]                   INT           NULL,
    [AdNaPravoyNizhneyKonechnosti]                  INT           NULL,
    [KozhniePokrovi]                                NVARCHAR (60) NULL,
    [DopolnitelnieDannie]                           NVARCHAR (50) NULL,
    [AnamnezZhizni]                                 NTEXT         NULL,
    [AnamnezZhizni1]                                NTEXT         NULL,
    [AnamnezZhizni2]                                NTEXT         NULL,
    [AnamnezZhizni3]                                NTEXT         NULL,
    [NalichieTbVichMalyariiTifaParatifaGepatitaZpp] NVARCHAR (50) NULL,
    CONSTRAINT [AllergologPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [AllergologToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

