CREATE TABLE [dbo].[AnalizOtdelyaemogoMochepolovihOrganov] (
    [ID]                       INT           NOT NULL,
    [PatID]                    INT           NULL,
    [Nomer]                    NVARCHAR (50) NULL,
    [DataVzyatiyaBiomateriala] DATETIME      NULL,
    [Epiteliy]                 NVARCHAR (50) NULL,
    [Epiteliy1]                NVARCHAR (50) NULL,
    [Epiteliy2]                NVARCHAR (50) NULL,
    [Leykotsiti]               NVARCHAR (50) NULL,
    [Leykotsiti1]              NVARCHAR (50) NULL,
    [Leykotsiti2]              NVARCHAR (50) NULL,
    [Eritrotsiti]              NVARCHAR (50) NULL,
    [Eritrotsiti1]             NVARCHAR (50) NULL,
    [Eritrotsiti2]             NVARCHAR (50) NULL,
    [Mikroflora]               NVARCHAR (50) NULL,
    [Mikroflora1]              NVARCHAR (50) NULL,
    [Mikroflora2]              NVARCHAR (50) NULL,
    [Trihomonadi]              NVARCHAR (50) NULL,
    [Trihomonadi1]             NVARCHAR (50) NULL,
    [Trihomonadi2]             NVARCHAR (50) NULL,
    [Gonokokki]                NVARCHAR (50) NULL,
    [Gonokokki1]               NVARCHAR (50) NULL,
    [Gonokokki2]               NVARCHAR (50) NULL,
    [KletkiSPriznakamiAtipii]  NVARCHAR (50) NULL,
    [KletkiSPriznakamiAtipii1] NVARCHAR (50) NULL,
    [KletkiSPriznakamiAtipii2] NVARCHAR (50) NULL,
    [DataVidachiAnaliza]       DATETIME      NULL,
    CONSTRAINT [AnalizOtdelyaemogoMochepolovihOrganovPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [AnalizOtdelyaemogoMochepolovihOrganovToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

