CREATE TABLE [dbo].[AnalizSpinnomozgovoyZhidkostiP] (
    [ID]                                    INT           NOT NULL,
    [PatID]                                 INT           NULL,
    [EditBox1]                              NVARCHAR (50) NULL,
    [Combo1]                                NVARCHAR (50) NULL,
    [EditBox2]                              NVARCHAR (8)  NULL,
    [DateBox1]                              DATETIME      NULL,
    [Vrach]                                 INT           NULL,
    [EditBox4]                              FLOAT (53)    NULL,
    [Combo2]                                NVARCHAR (50) NULL,
    [Ksantohromiya]                         NVARCHAR (1)  NULL,
    [EditBox5]                              NVARCHAR (20) NULL,
    [Combo3]                                NVARCHAR (50) NULL,
    [EditBox3]                              NVARCHAR (20) NULL,
    [ReaktsiyaPandi]                        NVARCHAR (1)  NULL,
    [EditBox6]                              NVARCHAR (20) NULL,
    [EditBox7]                              NVARCHAR (10) NULL,
    [EditBox8]                              NVARCHAR (10) NULL,
    [EditBox9]                              NVARCHAR (10) NULL,
    [EditBox10]                             NVARCHAR (10) NULL,
    [EditBox11]                             NVARCHAR (10) NULL,
    [EditBox12]                             NVARCHAR (10) NULL,
    [EditBox13]                             NVARCHAR (10) NULL,
    [EditBox14]                             NVARCHAR (10) NULL,
    [EditBox15]                             NVARCHAR (10) NULL,
    [EditBox16]                             NVARCHAR (10) NULL,
    [EditBox17]                             INT           NULL,
    [PredsedatelKek]                        NVARCHAR (50) NULL,
    [KsantohromiyaPosleTsentrifugirovaniya] NVARCHAR (1)  NULL,
    CONSTRAINT [AnalizSpinnomozgovoyZhidkostiPPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [AnalizSpinnomozgovoyZhidkostiPToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

