CREATE TABLE [dbo].[AnalizPlevralnoyZhidkostiP] (
    [ID]                            INT           NOT NULL,
    [PatID]                         INT           NULL,
    [NomerAnaliza]                  INT           NULL,
    [Vrach]                         INT           NULL,
    [DataProvedeniyaAnaliza]        DATETIME      NULL,
    [EditBox1]                      FLOAT (53)    NULL,
    [EditBox4]                      NVARCHAR (50) NULL,
    [EditBox5]                      NVARCHAR (50) NULL,
    [EditBox6]                      FLOAT (53)    NULL,
    [EditBox7]                      NVARCHAR (50) NULL,
    [EditBox8]                      FLOAT (53)    NULL,
    [EditBox9]                      NVARCHAR (50) NULL,
    [Memo1]                         NTEXT         NULL,
    [Vrach2]                        INT           NULL,
    [Patsient]                      NVARCHAR (50) NULL,
    [Otdelenie]                     NVARCHAR (50) NULL,
    [NomerIstoriiBolezni]           NVARCHAR (8)  NULL,
    [Kolichestvo]                   FLOAT (53)    NULL,
    [Prozrachnost]                  NVARCHAR (50) NULL,
    [Tsvet]                         NVARCHAR (50) NULL,
    [UdelnayaPlotnost]              FLOAT (53)    NULL,
    [Harakter]                      NVARCHAR (50) NULL,
    [Belok]                         FLOAT (53)    NULL,
    [ProbaRivalta]                  NVARCHAR (50) NULL,
    [MikroskopicheskoeIssledovanie] NTEXT         NULL,
    CONSTRAINT [AnalizPlevralnoyZhidkostiPPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [AnalizPlevralnoyZhidkostiPToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

