CREATE TABLE [dbo].[AnketaNarkologa] (
    [ID]                                          INT           NOT NULL,
    [PatID]                                       INT           NULL,
    [MasterID]                                    INT           NULL,
    [Zhalobi]                                     NVARCHAR (50) NULL,
    [KontaktSBolnimi]                             NVARCHAR (50) NULL,
    [LechenieUStomatologov]                       NVARCHAR (50) NULL,
    [SluchayniyPolovoyKontakt]                    NVARCHAR (50) NULL,
    [NaPriemS]                                    NVARCHAR (50) NULL,
    [ZapoiPo]                                     NVARCHAR (50) NULL,
    [BoliVSerdtse]                                NVARCHAR (50) NULL,
    [RvotniyRefleks]                              NVARCHAR (50) NULL,
    [NasledstvennostOtyagoshenaAlkogolizatsiey]   NVARCHAR (50) NULL,
    [RostIRazvivalsya]                            NVARCHAR (50) NULL,
    [Okonchil]                                    NVARCHAR (50) NULL,
    [PoluchilSpetsialnost]                        NVARCHAR (50) NULL,
    [VNastoyasheeVremyaRbotaet]                   NVARCHAR (50) NULL,
    [SemeynoePolozhenie]                          NVARCHAR (50) NULL,
    [Deti]                                        NVARCHAR (50) NULL,
    [SluzhbaVArmii]                               NVARCHAR (50) NULL,
    [PerenesennieZabolevaniya]                    NVARCHAR (50) NULL,
    [PervayaRyumkaV]                              NVARCHAR (50) NULL,
    [BitovoePyanstvoS]                            NVARCHAR (50) NULL,
    [PerviyZapoyV]                                NVARCHAR (50) NULL,
    [Dnevniy]                                     NVARCHAR (50) NULL,
    [PeriodicheskieZapoiS]                        NVARCHAR (50) NULL,
    [Dney]                                        NVARCHAR (50) NULL,
    [Cherez]                                      NVARCHAR (50) NULL,
    [ZatemZapoiUchastilisDo]                      NVARCHAR (50) NULL,
    [VMesyatsPo]                                  NVARCHAR (50) NULL,
    [NarastayushayaTolerantnostKAlkogolyu]        NVARCHAR (50) NULL,
    [EzhednevnoePyanstvo]                         NVARCHAR (50) NULL,
    [Upotreblyaet]                                NVARCHAR (50) NULL,
    [SutochnayaTolerantnost]                      NVARCHAR (50) NULL,
    [AmneziyaOpyaneniyaS]                         NVARCHAR (50) NULL,
    [Palimpsesti]                                 NVARCHAR (50) NULL,
    [IschezKontrolKolichestvom]                   NVARCHAR (50) NULL,
    [PoyavilosPatologicheskoeVlechenieKAlkogolyu] NVARCHAR (50) NULL,
    [PoslednyayaAlkogolizatsiya]                  NVARCHAR (50) NULL,
    [SoSnizheniemTolerantnosti]                   NVARCHAR (50) NULL,
    [OtnosheniyaNaRabote]                         NVARCHAR (50) NULL,
    [VSeme]                                       NVARCHAR (50) NULL,
    [Sostoyanie]                                  NVARCHAR (50) NULL,
    [KozhaISlizistie]                             NVARCHAR (50) NULL,
    [Ad]                                          NVARCHAR (50) NULL,
    [Ad1]                                         NVARCHAR (50) NULL,
    [MmRtStChss]                                  NVARCHAR (50) NULL,
    [SerdtseToni]                                 NVARCHAR (50) NULL,
    [EditBox46]                                   NVARCHAR (50) NULL,
    [EditBox47]                                   NVARCHAR (50) NULL,
    [EditBox48]                                   NVARCHAR (50) NULL,
    [EditBox49]                                   NVARCHAR (50) NULL,
    [EditBox50]                                   NVARCHAR (50) NULL,
    [EditBox51]                                   NVARCHAR (50) NULL,
    [EditBox53]                                   NVARCHAR (50) NULL,
    [EditBox52]                                   NVARCHAR (50) NULL,
    [EditBox54]                                   NVARCHAR (50) NULL,
    [EditBox55]                                   NVARCHAR (50) NULL,
    [EditBox56]                                   NVARCHAR (50) NULL,
    [EditBox57]                                   NVARCHAR (50) NULL,
    [EditBox58]                                   NVARCHAR (50) NULL,
    [EditBox59]                                   NVARCHAR (50) NULL,
    [EditBox60]                                   NVARCHAR (50) NULL,
    [EditBox61]                                   NVARCHAR (50) NULL,
    [EditBox62]                                   NVARCHAR (50) NULL,
    [EditBox63]                                   NVARCHAR (50) NULL,
    [EditBox64]                                   NVARCHAR (50) NULL,
    [EditBox65]                                   NVARCHAR (50) NULL,
    [EditBox66]                                   NVARCHAR (50) NULL,
    [Date]                                        DATETIME      NULL,
    [Vrach]                                       INT           NULL,
    [EditBox45]                                   NVARCHAR (50) NULL,
    [Data]                                        DATETIME      NULL,
    CONSTRAINT [AnketaNarkologaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [AnketaNarkologaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

