CREATE TABLE [dbo].[BESOftalmometriyaUsechennaya] (
    [ID]       INT        NOT NULL,
    [PatID]    INT        NULL,
    [OdCentr]  FLOAT (53) NULL,
    [OsCentr1] FLOAT (53) NULL,
    [OdN1]     FLOAT (53) NULL,
    [OdT1]     FLOAT (53) NULL,
    [OdI1]     FLOAT (53) NULL,
    [OdS4]     FLOAT (53) NULL,
    [OdT4]     FLOAT (53) NULL,
    [OdN4]     FLOAT (53) NULL,
    [OdI4]     FLOAT (53) NULL,
    [OdI8]     FLOAT (53) NULL,
    [OdS8]     FLOAT (53) NULL,
    [OdT8]     FLOAT (53) NULL,
    [OdN8]     FLOAT (53) NULL,
    [OdI12]    FLOAT (53) NULL,
    [OdS12]    FLOAT (53) NULL,
    [OdT12]    FLOAT (53) NULL,
    [OdN12]    FLOAT (53) NULL,
    [OsN1]     FLOAT (53) NULL,
    [OsT1]     FLOAT (53) NULL,
    [OsI1]     FLOAT (53) NULL,
    [OsS4]     FLOAT (53) NULL,
    [OsT4]     FLOAT (53) NULL,
    [OsN4]     FLOAT (53) NULL,
    [OsI4]     FLOAT (53) NULL,
    [OsI8]     FLOAT (53) NULL,
    [OsS8]     FLOAT (53) NULL,
    [OsT8]     FLOAT (53) NULL,
    [OsN8]     FLOAT (53) NULL,
    [OsI12]    FLOAT (53) NULL,
    [OsS12]    FLOAT (53) NULL,
    [OsT12]    FLOAT (53) NULL,
    [OsN12]    FLOAT (53) NULL,
    [OsS1]     FLOAT (53) NULL,
    [OdS1]     FLOAT (53) NULL,
    [Prim]     NTEXT      NULL,
    CONSTRAINT [BESOftalmometriyaUsechennayaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [BESOftalmometriyaUsechennayaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

