CREATE TABLE [dbo].[BiohimicheskiyIssledovanie1] (
    [ID]                     INT        NOT NULL,
    [PatID]                  INT        NULL,
    [NomerAnaliza]           INT        NULL,
    [DataProvedeniyaAnaliza] DATETIME   NULL,
    [Alat]                   INT        NULL,
    [Asat]                   INT        NULL,
    [ObshiyBillirubin]       FLOAT (53) NULL,
    [PryamoyBillirubin]      FLOAT (53) NULL,
    [ShelochnayaFosfotaza]   INT        NULL,
    [Ggtp]                   FLOAT (53) NULL,
    [Amilaza]                FLOAT (53) NULL,
    [Triglitseridi]          FLOAT (53) NULL,
    [Holesterin]             INT        NULL,
    [HolesterinLpvp]         FLOAT (53) NULL,
    [HolesterinLpnp]         FLOAT (53) NULL,
    [TimolovayaProba]        INT        NULL,
    [ObshiyBelok]            FLOAT (53) NULL,
    [Kfk]                    INT        NULL,
    [KfkMb]                  FLOAT (53) NULL,
    [Ldg]                    INT        NULL,
    [Mochevina]              FLOAT (53) NULL,
    [MochevayaKislotaSiv]    FLOAT (53) NULL,
    [MochevayaKislotaVMoche] FLOAT (53) NULL,
    [SaVKrovi]               FLOAT (53) NULL,
    [SaVMoche]               FLOAT (53) NULL,
    [KaliyVKrovi]            FLOAT (53) NULL,
    [NatriyVKrovi]           FLOAT (53) NULL,
    [Glyukoza]               FLOAT (53) NULL,
    [GlikolizirovanniyHb]    FLOAT (53) NULL,
    [KreatininVKrovi]        FLOAT (53) NULL,
    [KreatininVMoche]        FLOAT (53) NULL,
    [ObshieLipidi]           FLOAT (53) NULL,
    [OstatochniyAzot]        FLOAT (53) NULL,
    [Fosfolipidi]            FLOAT (53) NULL,
    [Lipaza]                 INT        NULL,
    [Holinesteraza]          FLOAT (53) NULL,
    [Ammiak]                 FLOAT (53) NULL,
    [Vrach]                  INT        NULL,
    CONSTRAINT [BiohimicheskiyIssledovanie1PrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [BiohimicheskiyIssledovanie1ToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

