CREATE TABLE [dbo].[BiohimicheskoeIssledovanieP] (
    [ID]                       INT           NOT NULL,
    [PatID]                    INT           NULL,
    [DataVzyatiyaBiomateriala] DATETIME      NULL,
    [EditBox1]                 NVARCHAR (50) NULL,
    [EditBox2]                 NVARCHAR (8)  NULL,
    [Combo1]                   NVARCHAR (50) NULL,
    [Vrach]                    INT           NULL,
    [EditBox3]                 NVARCHAR (50) NULL,
    [EditBox4]                 NVARCHAR (50) NULL,
    [EditBox5]                 NVARCHAR (50) NULL,
    [EditBox6]                 NVARCHAR (50) NULL,
    [EditBox7]                 NVARCHAR (50) NULL,
    [EditBox8]                 NVARCHAR (50) NULL,
    [EditBox9]                 NVARCHAR (50) NULL,
    [EditBox10]                NVARCHAR (50) NULL,
    [EditBox11]                NVARCHAR (50) NULL,
    [EditBox12]                NVARCHAR (50) NULL,
    [EditBox13]                NVARCHAR (50) NULL,
    [EditBox14]                NVARCHAR (50) NULL,
    [EditBox15]                NVARCHAR (50) NULL,
    [EditBox16]                NVARCHAR (50) NULL,
    [EditBox17]                NVARCHAR (50) NULL,
    [EditBox18]                NVARCHAR (50) NULL,
    [EditBox19]                NVARCHAR (50) NULL,
    [EditBox20]                NVARCHAR (50) NULL,
    [EditBox21]                NVARCHAR (50) NULL,
    [EditBox22]                NVARCHAR (50) NULL,
    [EditBox23]                NVARCHAR (50) NULL,
    [EditBox24]                NVARCHAR (50) NULL,
    [EditBox25]                NVARCHAR (50) NULL,
    [EditBox26]                NVARCHAR (50) NULL,
    [EditBox27]                NVARCHAR (50) NULL,
    [Combo2]                   NVARCHAR (50) NULL,
    [Combo3]                   NVARCHAR (50) NULL,
    [Combo4]                   NVARCHAR (50) NULL,
    [Combo5]                   NVARCHAR (50) NULL,
    [Combo6]                   NVARCHAR (50) NULL,
    [Combo7]                   NVARCHAR (50) NULL,
    [Combo8]                   NVARCHAR (50) NULL,
    [Combo9]                   NVARCHAR (50) NULL,
    [Combo10]                  NVARCHAR (50) NULL,
    [Combo11]                  NVARCHAR (50) NULL,
    [Combo12]                  NVARCHAR (50) NULL,
    [Combo13]                  NVARCHAR (50) NULL,
    [Combo14]                  NVARCHAR (50) NULL,
    [Combo15]                  NVARCHAR (50) NULL,
    [Combo16]                  NVARCHAR (50) NULL,
    [Combo17]                  NVARCHAR (50) NULL,
    [Combo18]                  NVARCHAR (50) NULL,
    [Combo19]                  NVARCHAR (50) NULL,
    [Combo20]                  NVARCHAR (50) NULL,
    [Combo21]                  NVARCHAR (50) NULL,
    [Combo22]                  NVARCHAR (50) NULL,
    [Combo23]                  NVARCHAR (50) NULL,
    [Combo24]                  NVARCHAR (50) NULL,
    [Combo25]                  NVARCHAR (50) NULL,
    [Combo26]                  NVARCHAR (50) NULL,
    [EditBox28]                NVARCHAR (50) NULL,
    [Vrach2]                   INT           NULL,
    CONSTRAINT [BiohimicheskoeIssledovaniePPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [BiohimicheskoeIssledovaniePToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

