CREATE TABLE [dbo].[BiohimicheskiyIssledovanie2] (
    [ID]                          INT        NOT NULL,
    [PatID]                       INT        NULL,
    [NomerAnaliza]                INT        NULL,
    [DataProvedeniyaAnaliza]      DATETIME   NULL,
    [FosforVKrovi]                FLOAT (53) NULL,
    [FosforVMoche]                FLOAT (53) NULL,
    [KaliyVMoche]                 FLOAT (53) NULL,
    [NatriyVMoche]                FLOAT (53) NULL,
    [NatriyVNogtyah]              FLOAT (53) NULL,
    [MedVSiv]                     FLOAT (53) NULL,
    [Tseruloplazmin]              FLOAT (53) NULL,
    [Hloridi]                     FLOAT (53) NULL,
    [Zhelezo]                     INT        NULL,
    [Ntzh]                        FLOAT (53) NULL,
    [Ozhss]                       FLOAT (53) NULL,
    [MagniySiv]                   FLOAT (53) NULL,
    [MagniyVMoche]                FLOAT (53) NULL,
    [ASO]                         INT        NULL,
    [CReaktivniyBelok]            INT        NULL,
    [RHF]                         INT        NULL,
    [Albumini]                    FLOAT (53) NULL,
    [Globulini]                   FLOAT (53) NULL,
    [Alfa1]                       FLOAT (53) NULL,
    [Alfa2]                       FLOAT (53) NULL,
    [Betta]                       FLOAT (53) NULL,
    [Gamma]                       FLOAT (53) NULL,
    [KoeffAlbGlob]                FLOAT (53) NULL,
    [IzofermentiKfk]              INT        NULL,
    [IzofermentiLdg]              INT        NULL,
    [KreatininMochi]              FLOAT (53) NULL,
    [MinutniyDiurez]              FLOAT (53) NULL,
    [KlubochkovayaFiltratsiya]    FLOAT (53) NULL,
    [KanalchikovayaReabsorbtsiya] INT        NULL,
    [Vrach]                       INT        NULL,
    CONSTRAINT [BiohimicheskiyIssledovanie2PrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [BiohimicheskiyIssledovanie2ToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

