CREATE TABLE [dbo].[BMIS_amst_tmp] (
    [ID]        INT             NOT NULL,
    [DATE]      DATETIME        NULL,
    [AMSTFL]    NUMERIC (1)     NULL,
    [MNTK]      NUMERIC (1)     NULL,
    [STACNUM]   NUMERIC (5)     NULL,
    [AGE]       NUMERIC (3)     NULL,
    [SEX]       NUMERIC (1)     NULL,
    [VOS]       NUMERIC (1)     NULL,
    [OTD]       NUMERIC (2)     NULL,
    [BED_DAY]   NUMERIC (2)     NULL,
    [PAY]       NUMERIC (2)     NULL,
    [NUMBER]    NUMERIC (7)     NULL,
    [DOG]       NVARCHAR (6)    NULL,
    [COMPL]     NUMERIC (1)     NULL,
    [KAT]       NUMERIC (1)     NULL,
    [DEP]       NUMERIC (2)     NULL,
    [EYE]       NUMERIC (1)     NULL,
    [DIAG1]     NUMERIC (3)     NULL,
    [DIAG2]     NUMERIC (3)     NULL,
    [PRIME]     NUMERIC (2)     NULL,
    [KINDLECH]  NUMERIC (1)     NULL,
    [VK]        NUMERIC (2)     NULL,
    [CODE1]     NUMERIC (3)     NULL,
    [CODE2]     NUMERIC (3)     NULL,
    [SUR]       NUMERIC (4)     NULL,
    [ALP1]      NUMERIC (4)     NULL,
    [ALP2]      NUMERIC (4)     NULL,
    [ALP3]      NUMERIC (4)     NULL,
    [ALP4]      NUMERIC (4)     NULL,
    [OSL1]      NUMERIC (3)     NULL,
    [OSL2]      NUMERIC (3)     NULL,
    [IOL]       NVARCHAR (3)    NULL,
    [IOL_DPT]   NUMERIC (5, 1)  NULL,
    [ANEST]     NUMERIC (1)     NULL,
    [REG]       NUMERIC (3)     NULL,
    [TOWN_V]    NUMERIC (1)     NULL,
    [OPBLK]     NUMERIC (1)     NULL,
    [DOC]       NUMERIC (4)     NULL,
    [OLK]       NUMERIC (4)     NULL,
    [SOST]      NUMERIC (5, 3)  NULL,
    [VGD]       NUMERIC (2)     NULL,
    [SETCH]     NUMERIC (1)     NULL,
    [UNIQ]      NUMERIC (1)     NULL,
    [STAT_PAT]  NUMERIC (2)     NULL,
    [GATHERED]  NUMERIC (1)     NULL,
    [PAYMENT]   NUMERIC (2)     NULL,
    [LGOTA]     NUMERIC (2)     NULL,
    [BRIEFNAME] NVARCHAR (25)   NULL,
    [S_SUR]     NUMERIC (11, 2) NULL,
    [S_BED]     NUMERIC (11, 2) NULL,
    [STANDARD]  NVARCHAR (6)    NULL,
    [SERTIF]    NVARCHAR (6)    NULL,
    [S_KD]      NUMERIC (11, 2) NULL,
    [S_DOPGZ]   NUMERIC (11, 2) NULL,
    [OLK1]      NUMERIC (1)     NULL,
    [OLK2]      NUMERIC (1)     NULL,
    [OLK3]      NUMERIC (1)     NULL,
    [OLK4]      NUMERIC (1)     NULL,
    [OLK5]      NUMERIC (1)     NULL,
    [OLK6]      NUMERIC (1)     NULL,
    [OLK7]      NUMERIC (1)     NULL,
    [OLK8]      NUMERIC (1)     NULL,
    [OLK9]      NUMERIC (1)     NULL,
    [OLK10]     NUMERIC (1)     NULL,
    [PAY1]      NUMERIC (2)     NULL,
    [DATE_OPER] DATETIME        NULL,
    [F25]       NUMERIC (1)     NULL,
    [GAGE]      NVARCHAR (10)   NULL,
    [RASH]      NVARCHAR (30)   NULL,
    [CODE1OO]   NUMERIC (3)     NULL,
    [CODE1O]    NUMERIC (3)     NULL,
    [CODE2O]    NUMERIC (3)     NULL,
    [ANEST1]    NUMERIC (3)     NULL,
    [ANEST2]    NUMERIC (3)     NULL,
    [ANEST3]    NUMERIC (3)     NULL
);

