CREATE TABLE [dbo].[BryushnoyKompleks] (
    [ID]                                                 INT           NOT NULL,
    [PatID]                                              INT           NULL,
    [Lotsiruetsya]                                       INT           NULL,
    [VRazmerah]                                          INT           NULL,
    [Konturi]                                            INT           NULL,
    [Chetkost]                                           INT           NULL,
    [PoZadneVerhneyPoverhnosti]                          NVARCHAR (1)  NULL,
    [PoPeredneeVerhneyPoverhnosti]                       NVARCHAR (1)  NULL,
    [PoBokovoyPoverhnosti]                               NVARCHAR (1)  NULL,
    [PoNizhneyPoverhnosti]                               NVARCHAR (1)  NULL,
    [VOblastiVorotPecheni]                               NVARCHAR (1)  NULL,
    [NizhniyKray]                                        INT           NULL,
    [Chetkost1]                                          INT           NULL,
    [VistupaetIzPodRebernoyDugiNa]                       FLOAT (53)    NULL,
    [EhoPlotnostParenhimi]                               INT           NULL,
    [Neodnorodna]                                        NVARCHAR (1)  NULL,
    [EhoStruktura]                                       INT           NULL,
    [UplotnenaPoHoduZhelchnihProtokov]                   NVARCHAR (1)  NULL,
    [KaltsinatiVPravoyDolePecheni]                       NVARCHAR (1)  NULL,
    [Razmerom]                                           INT           NULL,
    [KaltsinatiVLevoyDolePecheni]                        NVARCHAR (1)  NULL,
    [Razmerom1]                                          INT           NULL,
    [Rasshireni]                                         NVARCHAR (1)  NULL,
    [Izviti]                                             NVARCHAR (1)  NULL,
    [Sdavleni]                                           NVARCHAR (1)  NULL,
    [RazmeriVV]                                          FLOAT (53)    NULL,
    [AmputirovaniVV]                                     NVARCHAR (1)  NULL,
    [SdavleniVV]                                         NVARCHAR (1)  NULL,
    [IzvitiVV]                                           NVARCHAR (1)  NULL,
    [RasshireniVV]                                       NVARCHAR (1)  NULL,
    [RasshireniPV]                                       NVARCHAR (1)  NULL,
    [IzvitiPV]                                           NVARCHAR (1)  NULL,
    [SdavleniPV]                                         NVARCHAR (1)  NULL,
    [RazmeriPortalnoyVeniPV]                             FLOAT (53)    NULL,
    [OpredelyaetsyaPreportalniyFibroz]                   NVARCHAR (1)  NULL,
    [PravayaDolya]                                       FLOAT (53)    NULL,
    [LevayaDolya]                                        FLOAT (53)    NULL,
    [SosudiSistemiVPortae]                               INT           NULL,
    [DictCombo1]                                         NVARCHAR (50) NULL,
    [Data]                                               DATETIME      NULL,
    [NomerIssledovaniya]                                 INT           NULL,
    [VnutripechenochnieZhelchnieProtoki]                 INT           NULL,
    [Uplotneni]                                          NVARCHAR (1)  NULL,
    [StenkiObichnie]                                     NVARCHAR (1)  NULL,
    [Izviti1]                                            NVARCHAR (1)  NULL,
    [OpredelyayutsyaKonkrementi]                         NVARCHAR (1)  NULL,
    [LokalizatsiyaKonkrementi]                           INT           NULL,
    [OpredelyayutsyaVnutriprotokovieObrazovaniya]        NVARCHAR (1)  NULL,
    [PovishennoyEhogennosti]                             NVARCHAR (1)  NULL,
    [StenkiVnutripechenochnihZhelchnihProtokov]          INT           NULL,
    [RazmerHoledoha]                                     INT           NULL,
    [DopolnitelnoeObrazovanie]                           NVARCHAR (1)  NULL,
    [Lotsiruetsya1]                                      INT           NULL,
    [RazmeriObrazovanie]                                 FLOAT (53)    NULL,
    [RazmeriiObrazovanie]                                FLOAT (53)    NULL,
    [RazmeriiObrazovanie1]                               FLOAT (53)    NULL,
    [Obrazovanie]                                        INT           NULL,
    [FormaObrazovanie]                                   INT           NULL,
    [ChetkostObrazovanie]                                INT           NULL,
    [EhoPlotnostObrazovanie]                             INT           NULL,
    [BezOtrazheniyaUltrazvuka]                           NVARCHAR (1)  NULL,
    [EhoStrukturaObrazovanie]                            INT           NULL,
    [KonturiObrazovanie]                                 INT           NULL,
    [KapsulaObrazovanie]                                 INT           NULL,
    [SUsileniemZaDorzalnoyStenkoy]                       NVARCHAR (1)  NULL,
    [UsilenieZaDorzalnoyStenkoy]                         NVARCHAR (1)  NULL,
    [NalichieObodka]                                     NVARCHAR (1)  NULL,
    [NalichieHalo]                                       NVARCHAR (1)  NULL,
    [IzmeneniyaVDinamikiObrazovanie]                     INT           NULL,
    [Astsit]                                             NVARCHAR (1)  NULL,
    [ObshiyZhelchniyProtok]                              INT           NULL,
    [Rasshiren]                                          NVARCHAR (1)  NULL,
    [RazmeramiKonkrement31]                              INT           NULL,
    [RazmeramiKonkrement41]                              INT           NULL,
    [RazmeramiKonkrement51]                              INT           NULL,
    [RazmeramiKonkrement3]                               INT           NULL,
    [RazmeramiKonkrement4]                               INT           NULL,
    [RazmeramiKonkrement5]                               INT           NULL,
    [LotsiruetsyaGP]                                     INT           NULL,
    [RazmerGP]                                           INT           NULL,
    [RazmerGP1]                                          INT           NULL,
    [RazmerSostavlyaet]                                  FLOAT (53)    NULL,
    [RazmerSostavlyaet1]                                 FLOAT (53)    NULL,
    [RazmerSostavlyaet2]                                 FLOAT (53)    NULL,
    [FormaGP]                                            INT           NULL,
    [IzgibVOblasti]                                      INT           NULL,
    [IzgibVOblasti1]                                     INT           NULL,
    [Fiksirovan]                                         NVARCHAR (1)  NULL,
    [RazmeriGP]                                          INT           NULL,
    [Plotnaya]                                           NVARCHAR (1)  NULL,
    [Obichnaya]                                          NVARCHAR (1)  NULL,
    [Utolshena]                                          NVARCHAR (1)  NULL,
    [Uplotnena]                                          NVARCHAR (1)  NULL,
    [Otechna]                                            NVARCHAR (1)  NULL,
    [SDvoynimKonturom]                                   NVARCHAR (1)  NULL,
    [NechetkostStenki]                                   NVARCHAR (1)  NULL,
    [PriznakiDestruktsiiVOblasti]                        NVARCHAR (50) NULL,
    [VospalitelnayaInfiltratsiyaVOblasti]                NVARCHAR (50) NULL,
    [MelkodispersnoeSoderzhimoe]                         NVARCHAR (1)  NULL,
    [GomogennoeSoderzhimoe]                              NVARCHAR (1)  NULL,
    [ZamazkoobraznayaZhelch]                             NVARCHAR (1)  NULL,
    [ZhelchSOsadkom]                                     NVARCHAR (1)  NULL,
    [KonkrementiVPolostiPuziryaNeViyavleni]              NVARCHAR (1)  NULL,
    [OpredelyayutsyaDopolnitelnieObrazovaniya]           NVARCHAR (1)  NULL,
    [VPolostiPuziryaOpredelyaetsyaKonkrement]            NVARCHAR (1)  NULL,
    [KonkrementGP]                                       INT           NULL,
    [LotsiruetsyaObrazovanie]                            INT           NULL,
    [FormaObrazovanie1]                                  INT           NULL,
    [RazmerObrazovanie]                                  FLOAT (53)    NULL,
    [RazmerObrazovanie1]                                 FLOAT (53)    NULL,
    [RazmerObrazovanie2]                                 FLOAT (53)    NULL,
    [SgushennayaZhelch]                                  NVARCHAR (1)  NULL,
    [NePeremeshayushiesyaPriPeremenePolozheniyaTela]     NVARCHAR (1)  NULL,
    [CAkusticheskoyTenyu]                                NVARCHAR (1)  NULL,
    [RazmerObrazovanie3]                                 FLOAT (53)    NULL,
    [EhoStrukturaObrazovanie1]                           INT           NULL,
    [RazmerObrazovanie4]                                 FLOAT (53)    NULL,
    [RazmerObrazovanie5]                                 FLOAT (53)    NULL,
    [EhoPlotnostObrazovanie1]                            INT           NULL,
    [BezOtrazheniyaUltrazvukaObrazovanie]                NVARCHAR (1)  NULL,
    [DictCombo2]                                         NVARCHAR (50) NULL,
    [Lotsiruetsya2]                                      INT           NULL,
    [RazmerGolovki]                                      FLOAT (53)    NULL,
    [Normalniy]                                          NVARCHAR (1)  NULL,
    [RazmerTela]                                         FLOAT (53)    NULL,
    [NormalniyTela]                                      NVARCHAR (1)  NULL,
    [RazmerHvosta]                                       FLOAT (53)    NULL,
    [NormalniyHvost]                                     NVARCHAR (1)  NULL,
    [KonturGP]                                           INT           NULL,
    [ChetkostPG]                                         INT           NULL,
    [EhoPlotnostPG]                                      INT           NULL,
    [EhoStrukturaPG]                                     INT           NULL,
    [Fibroz]                                             INT           NULL,
    [OpredelyayutsyaOchagovieObrazovaniya]               NVARCHAR (1)  NULL,
    [VirslungovProtok]                                   INT           NULL,
    [Rasshiren1]                                         NVARCHAR (1)  NULL,
    [DiametrPG]                                          INT           NULL,
    [SelezenochnayaVena]                                 INT           NULL,
    [DiametrSelezVena]                                   INT           NULL,
    [OpredelyayutsyaPriznakiOtekaPodzheludochnoyZhelezi] NVARCHAR (1)  NULL,
    [BezOtrazheniyaUltrazvuka1]                          NVARCHAR (1)  NULL,
    [SUsileniemZaDorzalnoyStenkoy1]                      NVARCHAR (1)  NULL,
    [KolichestvoPG]                                      INT           NULL,
    [VProektsii]                                         NVARCHAR (50) NULL,
    [StrukturaPG]                                        INT           NULL,
    [KonturiGP]                                          INT           NULL,
    [Razmeri2GP]                                         FLOAT (53)    NULL,
    [Razmeri1GP]                                         FLOAT (53)    NULL,
    [RazmeriGP1]                                         FLOAT (53)    NULL,
    [RaspolozheniPochki]                                 INT           NULL,
    [RazmerLohankiDoMiktsii]                             INT           NULL,
    [PosleMiktsii1]                                      INT           NULL,
    [VRazmerah1]                                         INT           NULL,
    [SostavlyaetPochka]                                  FLOAT (53)    NULL,
    [SostavlyaetPochka1]                                 FLOAT (53)    NULL,
    [FormaPochka]                                        INT           NULL,
    [EhoPlotnostParenhimiPochka]                         INT           NULL,
    [EhoStrukturaParenhimiPochka]                        INT           NULL,
    [EhoPlotnostPochechnogoSinusa]                       INT           NULL,
    [PochkaRotirovana]                                   NVARCHAR (1)  NULL,
    [PochechniySinusNeRasshiren]                         NVARCHAR (1)  NULL,
    [ChashechnoLohanochnayaSistemaNeRasshirena]          NVARCHAR (1)  NULL,
    [SootnosheniePochechnogoSinusaIParenhimiPravilnoe]   NVARCHAR (1)  NULL,
    [ChashechnoLohanochnayaSistema]                      INT           NULL,
    [ObuslovlennimiVeroyatno]                            INT           NULL,
    [RazmeriTsek]                                        FLOAT (53)    NULL,
    [RazmeriParenhimi]                                   FLOAT (53)    NULL,
    [RazmeriKs]                                          FLOAT (53)    NULL,
    [OpredelyayutsyaKonkrementiPochka]                   NVARCHAR (1)  NULL,
    [SostavlyaetPochka2]                                 FLOAT (53)    NULL,
    [VizualiziruetsyaPochka]                             INT           NULL,
    [DopolnitelnieObrazovaniyaPochka]                    NVARCHAR (1)  NULL,
    [RazmerObrazovaniyaPochka]                           FLOAT (53)    NULL,
    [RazmerObrazovaniyaPochka1]                          FLOAT (53)    NULL,
    [SostavlyaetPochkaPochka2]                           FLOAT (53)    NULL,
    [FormaObrazovaniePochka]                             INT           NULL,
    [KonturiObrazovaniePochka]                           INT           NULL,
    [ChetkieObrazovaniePochka]                           INT           NULL,
    [Politsiklicheskie]                                  NVARCHAR (1)  NULL,
    [EhoStrukturaObrazovaniePochka]                      INT           NULL,
    [EhoPlotnostObrazovaniePochka]                       INT           NULL,
    [BezOtrazheniyaUltrazvuka2]                          NVARCHAR (1)  NULL,
    [SUsileniemZaDorzalnoyStenkoy2]                      NVARCHAR (1)  NULL,
    [ImeetsyaKapsula]                                    NVARCHAR (1)  NULL,
    [Peregorodki]                                        NVARCHAR (1)  NULL,
    [Obizvestvleniya]                                    NVARCHAR (1)  NULL,
    [VProektsiiPochaka]                                  INT           NULL,
    [KolichestvoObrazovaniePochka]                       INT           NULL,
    [LokalizatsiyaObrazovaniePochka]                     INT           NULL,
    [RazmerKonkrementPochka]                             FLOAT (53)    NULL,
    [RazmerKonkrementPochka1]                            FLOAT (53)    NULL,
    [SostavlyaetKonkrementPochka]                        FLOAT (53)    NULL,
    [RaspolozheniPochkiL]                                INT           NULL,
    [RazmerLohankiDoMiktsiiL]                            INT           NULL,
    [PosleMiktsii1L]                                     INT           NULL,
    [VizualiziruetsyaPochkaL]                            INT           NULL,
    [VRazmerahL]                                         INT           NULL,
    [SostavlyaetPochkaL]                                 FLOAT (53)    NULL,
    [SostavlyaetPochka1L]                                FLOAT (53)    NULL,
    [FormaPochkaL]                                       INT           NULL,
    [EhoPlotnostParenhimiPochkaL]                        INT           NULL,
    [EhoStrukturaParenhimiPochkaL]                       INT           NULL,
    [EhoPlotnostPochechnogoSinusaL]                      INT           NULL,
    [PochkaRotirovanaL]                                  NVARCHAR (1)  NULL,
    [PochechniySinusNeRasshirenL]                        NVARCHAR (1)  NULL,
    [ChashechnoLohanochnayaSistemaNeRasshirenaL]         NVARCHAR (1)  NULL,
    [SootnosheniePochechnogoSinusaIParenhimiPravilnoeL]  NVARCHAR (1)  NULL,
    [ChashechnoLohanochnayaSistemaL]                     INT           NULL,
    [ObuslovlennimiVeroyatnoL]                           INT           NULL,
    [RazmeriTsekL]                                       FLOAT (53)    NULL,
    [RazmeriParenhimiL]                                  FLOAT (53)    NULL,
    [RazmeriKsL]                                         FLOAT (53)    NULL,
    [OpredelyayutsyaKonkrementiL]                        NVARCHAR (1)  NULL,
    [SostavlyaetPochka2L]                                FLOAT (53)    NULL,
    [DopolnitelnieObrazovaniyaPochkaL]                   NVARCHAR (1)  NULL,
    [RazmerObrazovaniyaPochkaL]                          FLOAT (53)    NULL,
    [RazmerObrazovaniyaPochka1L]                         FLOAT (53)    NULL,
    [SostavlyaetPochkaPochka2L]                          FLOAT (53)    NULL,
    [FormaObrazovaniePochkaL]                            INT           NULL,
    [KonturiObrazovaniePochkaL]                          INT           NULL,
    [ChetkieObrazovaniePochkaL]                          INT           NULL,
    [PolitsiklicheskieL]                                 NVARCHAR (1)  NULL,
    [EhoStrukturaObrazovaniePochkaL]                     INT           NULL,
    [EhoPlotnostObrazovaniePochkaL]                      INT           NULL,
    [BezOtrazheniyaUltrazvukaL]                          NVARCHAR (1)  NULL,
    [SUsileniemZaDorzalnoyStenkoyL]                      NVARCHAR (1)  NULL,
    [ImeetsyaKapsulaL]                                   NVARCHAR (1)  NULL,
    [PeregorodkiL]                                       NVARCHAR (1)  NULL,
    [ObizvestvleniyaL]                                   NVARCHAR (1)  NULL,
    [VProektsiiPochakaL]                                 INT           NULL,
    [KolichestvoObrazovaniePochkaL]                      INT           NULL,
    [LokalizatsiyaObrazovaniePochkaL]                    INT           NULL,
    [RazmerKonkrementPochkaL]                            FLOAT (53)    NULL,
    [RazmerKonkrementPochka1L]                           FLOAT (53)    NULL,
    [SostavlyaetKonkrementPochkaL]                       FLOAT (53)    NULL,
    [DopolnitelnieDannieUzi]                             NTEXT         NULL,
    [Vrach]                                              INT           NULL,
    [Image]                                              IMAGE         NULL,
    [DannieNaPechat]                                     NTEXT         NULL,
    [Zaklyuchenie]                                       NTEXT         NULL,
    [Vrach1]                                             NVARCHAR (50) NULL,
    [Data2]                                              DATETIME      NULL,
    [OLE1]                                               IMAGE         NULL,
    CONSTRAINT [BryushnoyKompleksPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [BryushnoyKompleksToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

