CREATE TABLE [dbo].[CardMZ] (
    [Id]                         INT             NOT NULL,
    [PatId]                      INT             NULL,
    [Descr]                      VARCHAR (150)   NULL,
    [ExecDate]                   DATETIME        NULL,
    [BTrans]                     VARCHAR (255)   NULL,
    [Inocs]                      VARCHAR (255)   NULL,
    [InocsRe]                    VARCHAR (255)   NULL,
    [Diab]                       VARCHAR (255)   NULL,
    [InfIll]                     NTEXT           NULL,
    [Carps]                      NTEXT           NULL,
    [Heredity]                   NTEXT           NULL,
    [WasIll]                     NTEXT           NULL,
    [Anamnesis]                  NTEXT           NULL,
    [G1]                         VARCHAR (50)    NULL,
    [G2]                         VARCHAR (50)    NULL,
    [G3]                         VARCHAR (50)    NULL,
    [G4]                         VARCHAR (50)    NULL,
    [G4_1]                       VARCHAR (150)   NULL,
    [G5]                         VARCHAR (150)   NULL,
    [G6]                         VARCHAR (50)    NULL,
    [G7]                         VARCHAR (50)    NULL,
    [G8]                         VARCHAR (50)    NULL,
    [G9]                         VARCHAR (255)   NULL,
    [G10]                        VARCHAR (255)   NULL,
    [G11]                        VARCHAR (255)   NULL,
    [G12]                        VARCHAR (255)   NULL,
    [G13]                        VARCHAR (50)    NULL,
    [G14]                        VARCHAR (50)    NULL,
    [G15]                        VARCHAR (50)    NULL,
    [G16]                        VARCHAR (50)    NULL,
    [G17]                        NTEXT           NULL,
    [G18]                        VARCHAR (50)    NULL,
    [G19]                        VARCHAR (50)    NULL,
    [G20]                        VARCHAR (50)    NULL,
    [G21]                        VARCHAR (50)    NULL,
    [G22]                        NTEXT           NULL,
    [S1]                         NTEXT           NULL,
    [S2]                         NTEXT           NULL,
    [O1]                         NTEXT           NULL,
    [O2]                         VARCHAR (255)   NULL,
    [O3]                         VARCHAR (255)   NULL,
    [O4]                         VARCHAR (255)   NULL,
    [O5]                         VARCHAR (255)   NULL,
    [O6]                         VARCHAR (255)   NULL,
    [GS1]                        VARCHAR (255)   NULL,
    [GS2]                        VARCHAR (255)   NULL,
    [GS3]                        VARCHAR (255)   NULL,
    [GS4]                        NTEXT           NULL,
    [GS5]                        NTEXT           NULL,
    [GS6]                        VARCHAR (255)   NULL,
    [GS7]                        VARCHAR (255)   NULL,
    [GS8]                        VARCHAR (255)   NULL,
    [GS9]                        VARCHAR (255)   NULL,
    [PayNeed]                    BIT             NULL,
    [Payed]                      BIT             NULL,
    [PaySum]                     MONEY           NULL,
    [PayedSum]                   MONEY           NULL,
    [PayDate]                    DATETIME        NULL,
    [PayComment]                 VARCHAR (255)   NULL,
    [OperId]                     INT             NULL,
    [OriginalID]                 INT             NULL,
    [OtOsmotraOtkazalas]         BIT             NULL,
    [EditBox1]                   NVARCHAR (3)    NULL,
    [EditBox2]                   NVARCHAR (3)    NULL,
    [Combo3]                     NVARCHAR (50)   NULL,
    [Drugoe]                     NVARCHAR (1)    NULL,
    [EditBox6]                   NVARCHAR (4000) NULL,
    [EditBox3]                   NVARCHAR (50)   NULL,
    [EditBox4]                   NVARCHAR (50)   NULL,
    [EditBox5]                   NVARCHAR (50)   NULL,
    [S11]                        NTEXT           NULL,
    [Combo1]                     NVARCHAR (4000) NULL,
    [DopolnitelnieObsledovaniya] NVARCHAR (1)    NULL,
    [S13]                        NTEXT           NULL,
    [Height1]                    INT             NULL,
    [Weight]                     INT             NULL,
    [AccIll]                     NTEXT           NULL,
    [Badies]                     NTEXT           NULL,
    [Allergy]                    NTEXT           NULL,
    [AllRe]                      NTEXT           NULL,
    [Opers]                      NTEXT           NULL,
    [GynIll]                     NTEXT           NULL,
    CONSTRAINT [PK_CardMZ] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_CardMZ_PatForm] FOREIGN KEY ([Id]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

