CREATE TABLE [dbo].[chist_pat] (
    [ID]                INT            NOT NULL,
    [MasterID]          INT            NULL,
    [lastname]          NVARCHAR (20)  NULL,
    [id_zaezda]         INT            NULL,
    [FirstName]         NVARCHAR (20)  NULL,
    [SecondName]        NVARCHAR (50)  NULL,
    [SEX]               NVARCHAR (50)  NULL,
    [BirthDate]         DATETIME       NULL,
    [Telefon]           NVARCHAR (50)  NULL,
    [AdresStrana]       NVARCHAR (50)  NULL,
    [Updatetime]        DATETIME       NULL,
    [AdresRegionDict]   NVARCHAR (10)  NULL,
    [AdresStranaDict]   NVARCHAR (10)  NULL,
    [RegionCodeEditBox] NVARCHAR (10)  NULL,
    [RaionCodeEditBox]  NVARCHAR (10)  NULL,
    [GorodCodeEditBox]  NVARCHAR (10)  NULL,
    [useKLADR]          BIT            NULL,
    [UlCodeEditBox]     NVARCHAR (17)  NULL,
    [AdresRaionGor]     NVARCHAR (50)  NULL,
    [AdresRegion]       NVARCHAR (50)  NULL,
    [AdresRaionReg]     NVARCHAR (50)  NULL,
    [AdresGorod]        NVARCHAR (100) NULL,
    [AdresUlitsa]       NVARCHAR (70)  NULL,
    [AdresDom0]         NVARCHAR (10)  NULL,
    [AdresKvartira0]    NVARCHAR (10)  NULL,
    [Prof_zabol]        NVARCHAR (50)  NULL,
    [DiagDict]          NVARCHAR (50)  NULL,
    [DiagLabel]         NVARCHAR (300) NULL,
    [DiagCode]          NVARCHAR (6)   NULL,
    [VrachNaprav]       NVARCHAR (300) NULL,
    [Uchrezhd]          NVARCHAR (300) NULL,
    [NomerPolisa]       NVARCHAR (16)  NULL,
    [TFOMS]             INT            NULL,
    [SMO]               INT            NULL,
    [Data_zap]          DATETIME       NULL,
    [avtor]             INT            NULL,
    [spravVrach]        NVARCHAR (200) NULL,
    [PatId]             INT            NULL,
    [issled]            NTEXT          NULL,
    [DiagOsn]           NTEXT          NULL,
    [DiagSop]           NTEXT          NULL,
    [DiagKlin]          NTEXT          NULL,
    [Doehal1]           NVARCHAR (9)   NULL,
    [NomGospit]         NVARCHAR (50)  NULL,
    [doehal]            BIT            NULL,
    CONSTRAINT [chist_patPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [zaezdi]
    ON [dbo].[chist_pat]([id_zaezda] ASC);

