CREATE TABLE [dbo].[DannieObshegoObsledovaniya] (
    [ID]                               INT           NOT NULL,
    [PatID]                            INT           NULL,
    [AnomaliiRazvitiya]                NTEXT         NULL,
    [Konstitutsiya]                    NVARCHAR (50) NULL,
    [RostStoya]                        NVARCHAR (50) NULL,
    [Sidya]                            NVARCHAR (50) NULL,
    [Ves]                              NVARCHAR (50) NULL,
    [Kozha]                            NVARCHAR (50) NULL,
    [Kozha1]                           NVARCHAR (50) NULL,
    [Kozha2]                           NVARCHAR (50) NULL,
    [Kozha3]                           NVARCHAR (50) NULL,
    [Kozha4]                           NVARCHAR (50) NULL,
    [UchastkiDepigmentatsii]           NVARCHAR (50) NULL,
    [Rubtsi]                           NVARCHAR (50) NULL,
    [SosudistieZvezdochki]             NVARCHAR (50) NULL,
    [Krovoizliyaniya]                  NVARCHAR (50) NULL,
    [TroficheskieIzmeneniya]           NVARCHAR (50) NULL,
    [PzhkRazvita]                      NVARCHAR (50) NULL,
    [PreimushestvennoVOblasti]         NTEXT         NULL,
    [Oteki]                            NVARCHAR (50) NULL,
    [VOblasti]                         NTEXT         NULL,
    [VidimieSlizistie3]                NTEXT         NULL,
    [VidimieSlizistie2]                NVARCHAR (50) NULL,
    [VidimieSlizistie1]                NVARCHAR (50) NULL,
    [VidimieSlizistie]                 NVARCHAR (50) NULL,
    [Nogti]                            NVARCHAR (50) NULL,
    [Nogti1]                           NVARCHAR (50) NULL,
    [Nogti2]                           NVARCHAR (50) NULL,
    [Nogti3]                           NVARCHAR (50) NULL,
    [MishtsiRazviti]                   NVARCHAR (50) NULL,
    [PriPalpatsii2]                    NVARCHAR (50) NULL,
    [PriPalpatsii3]                    NVARCHAR (50) NULL,
    [DeformatsiiKostey]                NVARCHAR (1)  NULL,
    [DeformatsiiSustavov]              NVARCHAR (1)  NULL,
    [PriPalpatsii4]                    NVARCHAR (50) NULL,
    [ObemDvizheniyVSustavah]           NVARCHAR (50) NULL,
    [ObemDvizheniyVSustavah1]          NVARCHAR (50) NULL,
    [Memo1]                            NTEXT         NULL,
    [Puls]                             INT           NULL,
    [Defitsit]                         INT           NULL,
    [Napryazhenie]                     INT           NULL,
    [ToniSerdtsa]                      INT           NULL,
    [GranitsiSerdtsa]                  INT           NULL,
    [VerhushechniyTolchok]             INT           NULL,
    [Napolnenie]                       INT           NULL,
    [NadSosudami]                      NVARCHAR (35) NULL,
    [AktsentVtorogoTonaNadAortoy]      INT           NULL,
    [NadLegochnoyArteriey]             INT           NULL,
    [AdNaPravoyRuke]                   INT           NULL,
    [AdNaPravoyRuke1]                  INT           NULL,
    [Harakteristika]                   NVARCHAR (60) NULL,
    [ShumiSerdtsa]                     NVARCHAR (33) NULL,
    [AdNaLevoyRuke]                    INT           NULL,
    [AdNaLevoyRuke1]                   INT           NULL,
    [Memo2]                            NTEXT         NULL,
    [DihaniePrimechanie2]              NTEXT         NULL,
    [Hripi5]                           INT           NULL,
    [Hripi3]                           INT           NULL,
    [NadVseyPoverhnostyuLegkihSlishen] NVARCHAR (50) NULL,
    [LegochniyZvuk]                    NVARCHAR (50) NULL,
    [GolosovoeDrozhanie1]              NVARCHAR (50) NULL,
    [GolosovoeDrozhanie]               NVARCHAR (50) NULL,
    [GrudnayaKletka]                   NVARCHAR (50) NULL,
    [Chdd]                             NVARCHAR (50) NULL,
    [Mindalini2]                       NVARCHAR (35) NULL,
    [DihanieCherezNos]                 NVARCHAR (50) NULL,
    [PriPalpatsii]                     NVARCHAR (50) NULL,
    [PriPalpatsii1]                    NVARCHAR (50) NULL,
    [PatologicheskieIzmeneniya]        NVARCHAR (50) NULL,
    [RitmDihaniya]                     NVARCHAR (50) NULL,
    [Kashel1]                          NVARCHAR (1)  NULL,
    [Odishka1]                         NVARCHAR (1)  NULL,
    [Dihanie2]                         INT           NULL,
    [Memo3]                            NTEXT         NULL,
    [Zhivot]                           NVARCHAR (50) NULL,
    [Zhivot1]                          NVARCHAR (50) NULL,
    [PriPalpatsiiBoleznennost]         NVARCHAR (1)  NULL,
    [PriPalpatsiiBoleznennost5]        NVARCHAR (1)  NULL,
    [PriPalpatsiiBoleznennost4]        NVARCHAR (50) NULL,
    [PriPalpatsiiBoleznennost1]        NVARCHAR (50) NULL,
    [DictCombo1]                       NVARCHAR (50) NULL,
    [PriPalpatsiiBoleznennost2]        NVARCHAR (50) NULL,
    [PriPalpatsiiBoleznennost3]        NVARCHAR (50) NULL,
    [MishechnayaZashita]               NVARCHAR (50) NULL,
    [Pechen]                           NVARCHAR (50) NULL,
    [VistupaetIzPodreberyaNa]          INT           NULL,
    [Kray]                             NVARCHAR (50) NULL,
    [Kray1]                            NVARCHAR (50) NULL,
    [Stul]                             NVARCHAR (50) NULL,
    [OtKi]                             NVARCHAR (50) NULL,
    [OtKi1]                            NVARCHAR (50) NULL,
    [Memo4]                            NTEXT         NULL,
    [NervnoPsihicheskiyStatus]         NVARCHAR (20) NULL,
    [OtekiLica]                        NVARCHAR (1)  NULL,
    [Zabkost]                          NVARCHAR (1)  NULL,
    [SuhostKogi]                       NVARCHAR (1)  NULL,
    [Zapori]                           NVARCHAR (1)  NULL,
    [sonlivost]                        NVARCHAR (1)  NULL,
    [ObsheeSostoyanie]                 NTEXT         NULL,
    [VtorichniePolPriznaki]            INT           NULL,
    [Libido]                           NVARCHAR (20) NULL,
    [Razmer2]                          INT           NULL,
    [Razmer1]                          INT           NULL,
    [Razmer]                           INT           NULL,
    [Konsistentsiya]                   NVARCHAR (20) NULL,
    [Uzli]                             NVARCHAR (20) NULL,
    [Boleznennost]                     NTEXT         NULL,
    [Tahicardia]                       NVARCHAR (1)  NULL,
    [DrojanieRuk]                      NVARCHAR (1)  NULL,
    [Ekzoftalm]                        NVARCHAR (1)  NULL,
    [Grefe]                            NVARCHAR (1)  NULL,
    [DopolnitelnieDannie]              NTEXT         NULL,
    [VneshniyOsmor]                    NTEXT         NULL,
    [VidimieSlizistie4]                INT           NULL,
    [Prikus]                           NVARCHAR (20) NULL,
    [VerhiyRadR28]                     NVARCHAR (3)  NULL,
    [VerhiyRadR27]                     NVARCHAR (3)  NULL,
    [VerhiyRadR26]                     NVARCHAR (3)  NULL,
    [VerhiyRadR25]                     NVARCHAR (3)  NULL,
    [VerhiyRadR24]                     NVARCHAR (3)  NULL,
    [VerhiyRadR23]                     NVARCHAR (3)  NULL,
    [VerhiyRadR22]                     NVARCHAR (3)  NULL,
    [VerhiyRadR21]                     NVARCHAR (3)  NULL,
    [VerhiyRadL21]                     NVARCHAR (3)  NULL,
    [VerhiyRadL22]                     NVARCHAR (3)  NULL,
    [VerhiyRadL23]                     NVARCHAR (3)  NULL,
    [VerhiyRadL24]                     NVARCHAR (3)  NULL,
    [VerhiyRadL25]                     NVARCHAR (3)  NULL,
    [VerhiyRadL26]                     NVARCHAR (3)  NULL,
    [VerhiyRadL27]                     NVARCHAR (3)  NULL,
    [VerhiyRadL28]                     NVARCHAR (3)  NULL,
    [VerhiyRadL18]                     NVARCHAR (3)  NULL,
    [VerhiyRadL17]                     NVARCHAR (3)  NULL,
    [VerhiyRadL16]                     NVARCHAR (3)  NULL,
    [VerhiyRadL15]                     NVARCHAR (3)  NULL,
    [VerhiyRadL14]                     NVARCHAR (3)  NULL,
    [VerhiyRadL13]                     NVARCHAR (3)  NULL,
    [VerhiyRadL12]                     NVARCHAR (3)  NULL,
    [VerhiyRadL11]                     NVARCHAR (3)  NULL,
    [VerhiyRadR11]                     NVARCHAR (3)  NULL,
    [VerhiyRadR12]                     NVARCHAR (3)  NULL,
    [VerhiyRadR13]                     NVARCHAR (3)  NULL,
    [VerhiyRadR14]                     NVARCHAR (3)  NULL,
    [VerhiyRadR15]                     NVARCHAR (3)  NULL,
    [VerhiyRadR16]                     NVARCHAR (3)  NULL,
    [VerhiyRadR17]                     NVARCHAR (3)  NULL,
    [VerhiyRadR18]                     NVARCHAR (3)  NULL,
    [NijniyRadR18]                     NVARCHAR (3)  NULL,
    [NijniyRadR28]                     NVARCHAR (3)  NULL,
    [NijniyRadR17]                     NVARCHAR (3)  NULL,
    [NijniyRadR27]                     NVARCHAR (3)  NULL,
    [NijniyRadR16]                     NVARCHAR (3)  NULL,
    [NijniyRadR26]                     NVARCHAR (3)  NULL,
    [NijniyRadR15]                     NVARCHAR (3)  NULL,
    [NijniyRadR25]                     NVARCHAR (3)  NULL,
    [NijniyRadR14]                     NVARCHAR (3)  NULL,
    [NijniyRadR24]                     NVARCHAR (3)  NULL,
    [NijniyRadR13]                     NVARCHAR (3)  NULL,
    [NijniyRadR23]                     NVARCHAR (3)  NULL,
    [NijniyRadR12]                     NVARCHAR (3)  NULL,
    [NijniyRadR22]                     NVARCHAR (3)  NULL,
    [NijniyRadR11]                     NVARCHAR (3)  NULL,
    [NijniyRadR21]                     NVARCHAR (3)  NULL,
    [NijniyRadL11]                     NVARCHAR (3)  NULL,
    [NijniyRadL12]                     NVARCHAR (3)  NULL,
    [NijniyRadL21]                     NVARCHAR (3)  NULL,
    [NijniyRadL22]                     NVARCHAR (3)  NULL,
    [NijniyRadL24]                     NVARCHAR (3)  NULL,
    [NijniyRadL23]                     NVARCHAR (3)  NULL,
    [NijniyRadL13]                     NVARCHAR (3)  NULL,
    [NijniyRadL14]                     NVARCHAR (3)  NULL,
    [NijniyRadL15]                     NVARCHAR (3)  NULL,
    [NijniyRadL25]                     NVARCHAR (3)  NULL,
    [NijniyRadL16]                     NVARCHAR (3)  NULL,
    [NijniyRadL26]                     NVARCHAR (3)  NULL,
    [NijniyRadL17]                     NVARCHAR (3)  NULL,
    [NijniyRadL27]                     NVARCHAR (3)  NULL,
    [NijniyRadL18]                     NVARCHAR (3)  NULL,
    [NijniyRadL28]                     NVARCHAR (3)  NULL,
    [Richedit1]                        NTEXT         NULL,
    CONSTRAINT [DannieObshegoObsledovaniyaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [DannieObshegoObsledovaniyaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

