CREATE TABLE [dbo].[DSVNKk] (
    [ID]                         INT           NOT NULL,
    [PatID]                      INT           NULL,
    [Vrach2]                     INT           NULL,
    [zakl]                       NTEXT         NULL,
    [FIO]                        NVARCHAR (75) NULL,
    [Data1]                      DATETIME      NULL,
    [Krovotok]                   NVARCHAR (50) NULL,
    [Prohod]                     NVARCHAR (3)  NULL,
    [PriznKlap]                  NVARCHAR (3)  NULL,
    [RegKrov]                    NVARCHAR (3)  NULL,
    [Sinsdih]                    NVARCHAR (3)  NULL,
    [KrovotokKomment]            NTEXT         NULL,
    [ProhodimiKomment]           NTEXT         NULL,
    [PriznakiKomment]            NTEXT         NULL,
    [SinhronizirovanniyKomment]  NTEXT         NULL,
    [PriznKlapL]                 NVARCHAR (3)  NULL,
    [SinsdihL]                   NVARCHAR (3)  NULL,
    [RegKrovL]                   NVARCHAR (3)  NULL,
    [ProhodL]                    NVARCHAR (3)  NULL,
    [KrovotokL]                  NVARCHAR (50) NULL,
    [ProhodimiKommentL]          NTEXT         NULL,
    [SinhronizirovanniyKommentL] NTEXT         NULL,
    [PriznakiKommentL]           NTEXT         NULL,
    [KrovotokKommentL]           NTEXT         NULL,
    CONSTRAINT [DSVNKkPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [DSVNKkToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

