CREATE TABLE [dbo].[DupleksnoeSkanirovanieVenNizhnihKonechnostey] (
    [ID]              INT           NOT NULL,
    [PatID]           INT           NULL,
    [AdDiametropv]    INT           NULL,
    [AdKrovotok]      NVARCHAR (50) NULL,
    [AdProsvet]       NVARCHAR (50) NULL,
    [AdSzhimaemost]   NVARCHAR (50) NULL,
    [AdReflex]        NVARCHAR (50) NULL,
    [AdDiametropv1]   INT           NULL,
    [AdProsvet1]      NVARCHAR (50) NULL,
    [AdSzhimaemost1]  NVARCHAR (50) NULL,
    [AdKrovotok1]     NVARCHAR (50) NULL,
    [AdReflex1]       NVARCHAR (50) NULL,
    [AdDiametropv2]   INT           NULL,
    [AdProsvet2]      NVARCHAR (50) NULL,
    [AdSzhimaemost2]  NVARCHAR (50) NULL,
    [AdKrovotok2]     NVARCHAR (50) NULL,
    [AdReflex2]       NVARCHAR (50) NULL,
    [AdDiametropv3]   INT           NULL,
    [AdProsvet3]      NVARCHAR (50) NULL,
    [AdSzhimaemost3]  NVARCHAR (50) NULL,
    [AdKrovotok3]     NVARCHAR (50) NULL,
    [AdReflex3]       NVARCHAR (50) NULL,
    [AdReflex4]       NVARCHAR (50) NULL,
    [AdReflex5]       NVARCHAR (50) NULL,
    [AdReflex6]       NVARCHAR (50) NULL,
    [AdReflex7]       NVARCHAR (50) NULL,
    [AdKrovotok7]     NVARCHAR (50) NULL,
    [AdKrovotok6]     NVARCHAR (50) NULL,
    [AdKrovotok5]     NVARCHAR (50) NULL,
    [AdKrovotok4]     NVARCHAR (50) NULL,
    [AdSzhimaemost4]  NVARCHAR (50) NULL,
    [AdSzhimaemost5]  NVARCHAR (50) NULL,
    [AdSzhimaemost6]  NVARCHAR (50) NULL,
    [AdSzhimaemost7]  NVARCHAR (50) NULL,
    [AdProsvet7]      NVARCHAR (50) NULL,
    [AdProsvet6]      NVARCHAR (50) NULL,
    [AdProsvet5]      NVARCHAR (50) NULL,
    [AdProsvet4]      NVARCHAR (50) NULL,
    [AdDiametropv4]   INT           NULL,
    [AdDiametropv5]   INT           NULL,
    [AdDiametropv6]   INT           NULL,
    [AdDiametropv7]   INT           NULL,
    [AdReflex8]       NVARCHAR (50) NULL,
    [AdReflex9]       NVARCHAR (50) NULL,
    [AdReflex10]      NVARCHAR (50) NULL,
    [AdReflex11]      NVARCHAR (50) NULL,
    [AdKrovotok11]    NVARCHAR (50) NULL,
    [AdKrovotok10]    NVARCHAR (50) NULL,
    [AdKrovotok9]     NVARCHAR (50) NULL,
    [AdKrovotok8]     NVARCHAR (50) NULL,
    [AdSzhimaemost8]  NVARCHAR (50) NULL,
    [AdSzhimaemost9]  NVARCHAR (50) NULL,
    [AdSzhimaemost10] NVARCHAR (50) NULL,
    [AdSzhimaemost11] NVARCHAR (50) NULL,
    [AdProsvet11]     NVARCHAR (50) NULL,
    [AdProsvet10]     NVARCHAR (50) NULL,
    [AdProsvet9]      NVARCHAR (50) NULL,
    [AdProsvet8]      NVARCHAR (50) NULL,
    [AdDiametropv8]   INT           NULL,
    [AdDiametropv9]   INT           NULL,
    [AdDiametropv10]  INT           NULL,
    [AdDiametropv11]  INT           NULL,
    [AdReflex12]      NVARCHAR (50) NULL,
    [AdReflex13]      NVARCHAR (50) NULL,
    [AdReflex14]      NVARCHAR (50) NULL,
    [AdReflex15]      NVARCHAR (50) NULL,
    [AdKrovotok15]    NVARCHAR (50) NULL,
    [AdKrovotok14]    NVARCHAR (50) NULL,
    [AdKrovotok13]    NVARCHAR (50) NULL,
    [AdKrovotok12]    NVARCHAR (50) NULL,
    [AdSzhimaemost12] NVARCHAR (50) NULL,
    [AdSzhimaemost13] NVARCHAR (50) NULL,
    [AdSzhimaemost14] NVARCHAR (50) NULL,
    [AdSzhimaemost15] NVARCHAR (50) NULL,
    [AdProsvet15]     NVARCHAR (50) NULL,
    [AdProsvet14]     NVARCHAR (50) NULL,
    [AdProsvet13]     NVARCHAR (50) NULL,
    [AdProsvet12]     NVARCHAR (50) NULL,
    [AdDiametropv12]  INT           NULL,
    [AdDiametropv13]  INT           NULL,
    [AdDiametropv14]  INT           NULL,
    [AdDiametropv15]  INT           NULL,
    [AdReflex16]      NVARCHAR (50) NULL,
    [AdReflex17]      NVARCHAR (50) NULL,
    [AdReflex18]      NVARCHAR (50) NULL,
    [AdReflex19]      NVARCHAR (50) NULL,
    [AdCombo19]       NVARCHAR (50) NULL,
    [AdCombo18]       NVARCHAR (50) NULL,
    [AdCombo17]       NVARCHAR (50) NULL,
    [AdKrovotok16]    NVARCHAR (50) NULL,
    [AdSzhimaemost16] NVARCHAR (50) NULL,
    [AdSzhimaemost17] NVARCHAR (50) NULL,
    [AdSzhimaemost18] NVARCHAR (50) NULL,
    [AdSzhimaemost19] NVARCHAR (50) NULL,
    [AdProsvet19]     NVARCHAR (50) NULL,
    [AdProsvet18]     NVARCHAR (50) NULL,
    [AdProsvet17]     NVARCHAR (50) NULL,
    [AdProsvet16]     NVARCHAR (50) NULL,
    [AdDiametropv16]  INT           NULL,
    [AdDiametropv17]  INT           NULL,
    [AdDiametropv18]  INT           NULL,
    [AdDiametropv19]  INT           NULL,
    [AdDiametropv20]  INT           NULL,
    [AdProsvet20]     NVARCHAR (50) NULL,
    [AdSzhimaemost20] NVARCHAR (50) NULL,
    [Adcombo20]       NVARCHAR (50) NULL,
    [AdReflex20]      NVARCHAR (50) NULL,
    [zaklprav]        NTEXT         NULL,
    [AsDiametropv1]   INT           NULL,
    [AsKrovotok1]     NVARCHAR (50) NULL,
    [AsProsvet1]      NVARCHAR (50) NULL,
    [AsSzhimaemost1]  NVARCHAR (50) NULL,
    [AsReflex1]       NVARCHAR (50) NULL,
    [AsDiametropv2]   INT           NULL,
    [AsProsvet2]      NVARCHAR (50) NULL,
    [AsSzhimaemost2]  NVARCHAR (50) NULL,
    [AsKrovotok2]     NVARCHAR (50) NULL,
    [AsReflex2]       NVARCHAR (50) NULL,
    [AsDiametropv3]   INT           NULL,
    [AsProsvet3]      NVARCHAR (50) NULL,
    [AsSzhimaemost3]  NVARCHAR (50) NULL,
    [AsKrovotok3]     NVARCHAR (50) NULL,
    [AsReflex3]       NVARCHAR (50) NULL,
    [AsDiametropv4]   INT           NULL,
    [AsProsvet4]      NVARCHAR (50) NULL,
    [AsSzhimaemost4]  NVARCHAR (50) NULL,
    [AsKrovotok4]     NVARCHAR (50) NULL,
    [AsReflex4]       NVARCHAR (50) NULL,
    [AsReflex5]       NVARCHAR (50) NULL,
    [AsReflex6]       NVARCHAR (50) NULL,
    [AsReflex7]       NVARCHAR (50) NULL,
    [AsReflex8]       NVARCHAR (50) NULL,
    [AsKrovotok8]     NVARCHAR (50) NULL,
    [AsKrovotok7]     NVARCHAR (50) NULL,
    [AsKrovotok6]     NVARCHAR (50) NULL,
    [AsKrovotok5]     NVARCHAR (50) NULL,
    [AsSzhimaemost5]  NVARCHAR (50) NULL,
    [AsSzhimaemost6]  NVARCHAR (50) NULL,
    [AsSzhimaemost7]  NVARCHAR (50) NULL,
    [AsSzhimaemost8]  NVARCHAR (50) NULL,
    [AsProsvet8]      NVARCHAR (50) NULL,
    [AsProsvet7]      NVARCHAR (50) NULL,
    [AsProsvet6]      NVARCHAR (50) NULL,
    [AsProsvet5]      NVARCHAR (50) NULL,
    [AsDiametropv5]   INT           NULL,
    [AsDiametropv6]   INT           NULL,
    [AsDiametropv7]   INT           NULL,
    [AsDiametropv8]   INT           NULL,
    [AsReflex9]       NVARCHAR (50) NULL,
    [AsReflex10]      NVARCHAR (50) NULL,
    [AsReflex11]      NVARCHAR (50) NULL,
    [AsReflex12]      NVARCHAR (50) NULL,
    [AsKrovotok12]    NVARCHAR (50) NULL,
    [AsKrovotok11]    NVARCHAR (50) NULL,
    [AsKrovotok10]    NVARCHAR (50) NULL,
    [AsKrovotok9]     NVARCHAR (50) NULL,
    [AsSzhimaemost9]  NVARCHAR (50) NULL,
    [AsSzhimaemost10] NVARCHAR (50) NULL,
    [AsSzhimaemost11] NVARCHAR (50) NULL,
    [AsSzhimaemost12] NVARCHAR (50) NULL,
    [AsProsvet12]     NVARCHAR (50) NULL,
    [AsProsvet11]     NVARCHAR (50) NULL,
    [AsProsvet10]     NVARCHAR (50) NULL,
    [AsProsvet9]      NVARCHAR (50) NULL,
    [AsDiametropv9]   INT           NULL,
    [AsDiametropv10]  INT           NULL,
    [AsDiametropv11]  INT           NULL,
    [AsDiametropv12]  INT           NULL,
    [AsReflex13]      NVARCHAR (50) NULL,
    [AsReflex14]      NVARCHAR (50) NULL,
    [AsReflex15]      NVARCHAR (50) NULL,
    [AsReflex16]      NVARCHAR (50) NULL,
    [AsKrovotok16]    NVARCHAR (50) NULL,
    [AsKrovotok15]    NVARCHAR (50) NULL,
    [AsKrovotok14]    NVARCHAR (50) NULL,
    [AsKrovotok13]    NVARCHAR (50) NULL,
    [AsSzhimaemost13] NVARCHAR (50) NULL,
    [AsSzhimaemost14] NVARCHAR (50) NULL,
    [AsSzhimaemost15] NVARCHAR (50) NULL,
    [AsSzhimaemost16] NVARCHAR (50) NULL,
    [AsProsvet16]     NVARCHAR (50) NULL,
    [AsProsvet15]     NVARCHAR (50) NULL,
    [AsProsvet14]     NVARCHAR (50) NULL,
    [AsProsvet13]     NVARCHAR (50) NULL,
    [AsDiametropv13]  INT           NULL,
    [AsDiametropv14]  INT           NULL,
    [AsDiametropv15]  INT           NULL,
    [AsDiametropv16]  INT           NULL,
    [AsReflex17]      NVARCHAR (50) NULL,
    [AsReflex18]      NVARCHAR (50) NULL,
    [AsReflex19]      NVARCHAR (50) NULL,
    [AsReflex20]      NVARCHAR (50) NULL,
    [AsCombo20]       NVARCHAR (50) NULL,
    [AsCombo19]       NVARCHAR (50) NULL,
    [AsCombo18]       NVARCHAR (50) NULL,
    [AsCombo17]       NVARCHAR (50) NULL,
    [AsSzhimaemost17] NVARCHAR (50) NULL,
    [AsSzhimaemost18] NVARCHAR (50) NULL,
    [AsSzhimaemost19] NVARCHAR (50) NULL,
    [AsSzhimaemost20] NVARCHAR (50) NULL,
    [AsProsvet20]     NVARCHAR (50) NULL,
    [AsProsvet19]     NVARCHAR (50) NULL,
    [AsProsvet18]     NVARCHAR (50) NULL,
    [AsProsvet17]     NVARCHAR (50) NULL,
    [AsDiametropv17]  INT           NULL,
    [AsDiametropv18]  INT           NULL,
    [AsDiametropv19]  INT           NULL,
    [AsDiametropv20]  INT           NULL,
    [AsDiametropv21]  INT           NULL,
    [AsProsvet21]     NVARCHAR (50) NULL,
    [AsSzhimaemost21] NVARCHAR (50) NULL,
    [AsKrovotok21]    NVARCHAR (50) NULL,
    [AsReflex21]      NVARCHAR (50) NULL,
    [zakllev]         NTEXT         NULL,
    [Vrach2]          INT           NULL,
    CONSTRAINT [DupleksnoeSkanirovanieVenNizhnihKonechnosteyPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [DupleksnoeSkanirovanieVenNizhnihKonechnosteyToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

