CREATE TABLE [dbo].[DupleksnoeSkanirovanieArteriyNizhnihKonechnostey] (
    [ID]         INT           NOT NULL,
    [PatID]      INT           NULL,
    [Specalist]  NVARCHAR (50) NULL,
    [Data1]      DATETIME      NULL,
    [DocTime]    DATETIME      NULL,
    [Combo1]     NVARCHAR (50) NULL,
    [Combo2]     NVARCHAR (50) NULL,
    [Combo3]     NVARCHAR (50) NULL,
    [Combo4]     NVARCHAR (50) NULL,
    [Combo5]     NVARCHAR (50) NULL,
    [Combo6]     NVARCHAR (50) NULL,
    [Combo7]     NVARCHAR (50) NULL,
    [Combo8]     NVARCHAR (50) NULL,
    [Combo9]     NVARCHAR (50) NULL,
    [Combo10]    NVARCHAR (50) NULL,
    [Combo11]    NVARCHAR (50) NULL,
    [Combo12]    NVARCHAR (50) NULL,
    [Combo13]    NVARCHAR (50) NULL,
    [EditBox1]   INT           NULL,
    [EditBox2]   INT           NULL,
    [EditBox3]   INT           NULL,
    [EditBox4]   INT           NULL,
    [EditBox5]   INT           NULL,
    [EditBox6]   INT           NULL,
    [EditBox7]   INT           NULL,
    [EditBox8]   INT           NULL,
    [EditBox9]   INT           NULL,
    [EditBox10]  INT           NULL,
    [EditBox11]  INT           NULL,
    [EditBox12]  INT           NULL,
    [EditBox13]  INT           NULL,
    [EditBox14]  INT           NULL,
    [EditBox15]  INT           NULL,
    [EditBox16]  INT           NULL,
    [EditBox17]  INT           NULL,
    [EditBox18]  INT           NULL,
    [EditBox19]  INT           NULL,
    [EditBox20]  INT           NULL,
    [EditBox21]  INT           NULL,
    [EditBox22]  INT           NULL,
    [EditBox23]  INT           NULL,
    [EditBox24]  INT           NULL,
    [Combo14]    NVARCHAR (50) NULL,
    [Combo21]    NVARCHAR (50) NULL,
    [Combo31]    NVARCHAR (50) NULL,
    [Combo41]    NVARCHAR (50) NULL,
    [Combo51]    NVARCHAR (50) NULL,
    [Combo61]    NVARCHAR (50) NULL,
    [Combo71]    NVARCHAR (50) NULL,
    [Combo81]    NVARCHAR (50) NULL,
    [Combo91]    NVARCHAR (50) NULL,
    [Combo101]   NVARCHAR (50) NULL,
    [Combo111]   NVARCHAR (50) NULL,
    [Combo121]   NVARCHAR (50) NULL,
    [Combo131]   NVARCHAR (50) NULL,
    [EditBox110] INT           NULL,
    [EditBox25]  INT           NULL,
    [EditBox31]  INT           NULL,
    [EditBox41]  INT           NULL,
    [EditBox51]  INT           NULL,
    [EditBox61]  INT           NULL,
    [EditBox71]  INT           NULL,
    [EditBox81]  INT           NULL,
    [EditBox91]  INT           NULL,
    [EditBox101] INT           NULL,
    [EditBox111] INT           NULL,
    [EditBox121] INT           NULL,
    [EditBox131] INT           NULL,
    [EditBox141] INT           NULL,
    [EditBox151] INT           NULL,
    [EditBox161] INT           NULL,
    [EditBox171] INT           NULL,
    [EditBox181] INT           NULL,
    [EditBox191] INT           NULL,
    [EditBox201] INT           NULL,
    [EditBox211] INT           NULL,
    [EditBox221] INT           NULL,
    [EditBox231] INT           NULL,
    [EditBox241] INT           NULL,
    [EditBox26]  NVARCHAR (50) NULL,
    [HKОП]       NVARCHAR (50) NULL,
    [hknp]       NVARCHAR (50) NULL,
    [hkob]       NVARCHAR (50) NULL,
    [hkpb]       NVARCHAR (50) NULL,
    [hkgb]       NVARCHAR (50) NULL,
    [hkmb]       NVARCHAR (50) NULL,
    [hkzb]       NVARCHAR (50) NULL,
    [hkTAC]      NVARCHAR (50) NULL,
    [hktpc]      NVARCHAR (50) NULL,
    [hkperb]     NVARCHAR (50) NULL,
    [hkp]        NVARCHAR (50) NULL,
    [hketba]     NVARCHAR (50) NULL,
    [skop]       FLOAT (53)    NULL,
    [sknp]       FLOAT (53)    NULL,
    [skob]       FLOAT (53)    NULL,
    [skgb]       FLOAT (53)    NULL,
    [skpb]       FLOAT (53)    NULL,
    [skp]        FLOAT (53)    NULL,
    [skperb]     FLOAT (53)    NULL,
    [sktpc]      FLOAT (53)    NULL,
    [ssop]       FLOAT (53)    NULL,
    [ssob]       FLOAT (53)    NULL,
    [ssgb]       FLOAT (53)    NULL,
    [sspb]       FLOAT (53)    NULL,
    [ssp]        FLOAT (53)    NULL,
    [ssperb]     FLOAT (53)    NULL,
    [sstpc]      FLOAT (53)    NULL,
    [hkopL]      NVARCHAR (50) NULL,
    [hknpL]      NVARCHAR (50) NULL,
    [hkobL]      NVARCHAR (50) NULL,
    [hkpbL]      NVARCHAR (50) NULL,
    [hkgbL]      NVARCHAR (50) NULL,
    [hktpcL]     NVARCHAR (50) NULL,
    [hkperbL]    NVARCHAR (50) NULL,
    [hkpL]       NVARCHAR (50) NULL,
    [skopL]      FLOAT (53)    NULL,
    [sknpL]      FLOAT (53)    NULL,
    [skobL]      FLOAT (53)    NULL,
    [skgbL]      FLOAT (53)    NULL,
    [skpbL]      FLOAT (53)    NULL,
    [skpL]       FLOAT (53)    NULL,
    [skperbL]    FLOAT (53)    NULL,
    [sktpcL]     FLOAT (53)    NULL,
    [ssopL]      FLOAT (53)    NULL,
    [ssnpL]      FLOAT (53)    NULL,
    [ssobL]      FLOAT (53)    NULL,
    [ssgbL]      FLOAT (53)    NULL,
    [sspbL]      FLOAT (53)    NULL,
    [sspL]       FLOAT (53)    NULL,
    [ssperbL]    FLOAT (53)    NULL,
    [sstpcL]     FLOAT (53)    NULL,
    [skzb]       FLOAT (53)    NULL,
    [skmb]       FLOAT (53)    NULL,
    [skTAC]      FLOAT (53)    NULL,
    [sketba]     FLOAT (53)    NULL,
    [sszb]       FLOAT (53)    NULL,
    [ssmb]       FLOAT (53)    NULL,
    [ssTAC]      FLOAT (53)    NULL,
    [ssetba]     FLOAT (53)    NULL,
    [hkmbL]      NVARCHAR (50) NULL,
    [hkzbL]      NVARCHAR (50) NULL,
    [hkTACL]     NVARCHAR (50) NULL,
    [hketbaL]    NVARCHAR (50) NULL,
    [skzbL]      FLOAT (53)    NULL,
    [skmbL]      FLOAT (53)    NULL,
    [skTACL]     FLOAT (53)    NULL,
    [sketbaL]    FLOAT (53)    NULL,
    [sszbL]      FLOAT (53)    NULL,
    [ssmbL]      FLOAT (53)    NULL,
    [ssTACL]     FLOAT (53)    NULL,
    [ssetbaL]    INT           NULL,
    [Zakl]       NTEXT         NULL,
    [hkop]       NVARCHAR (50) NULL,
    [ssnp1]      INT           NULL,
    [Vrach2]     INT           NULL,
    CONSTRAINT [DupleksnoeSkanirovanieArteriyNizhnihKonechnosteyPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC)
);

