CREATE TABLE [dbo].[ECFExams] (
    [Id]                     INT            NOT NULL,
    [ParentId]               INT            NULL,
    [PatId]                  INT            NULL,
    [ExecDate]               DATETIME       NULL,
    [M_AIDS]                 BIT            NULL,
    [M_AIDS_Comment]         VARCHAR (255)  NULL,
    [M_AIDS_ExecDate]        DATETIME       NULL,
    [M_HepB]                 BIT            NULL,
    [M_HepB_Comment]         VARCHAR (255)  NULL,
    [M_HepB_ExecDate]        DATETIME       NULL,
    [M_HepC]                 BIT            NULL,
    [M_HepC_Comment]         VARCHAR (255)  NULL,
    [M_HepC_ExecDate]        DATETIME       NULL,
    [M_Syp]                  BIT            NULL,
    [M_Syp_Comment]          VARCHAR (255)  NULL,
    [M_Syp_ExecDate]         DATETIME       NULL,
    [M_Spermo]               BIT            NULL,
    [M_Spermo_Comment]       VARCHAR (255)  NULL,
    [M_Spermo_ExecDate]      DATETIME       NULL,
    [W_AIDS]                 BIT            NULL,
    [W_AIDS_Comment]         VARCHAR (255)  NULL,
    [W_AIDS_ExecDate]        DATETIME       NULL,
    [W_HepB]                 BIT            NULL,
    [W_HepB_Comment]         VARCHAR (255)  NULL,
    [W_HepB_ExecDate]        DATETIME       NULL,
    [W_HepC]                 BIT            NULL,
    [W_HepC_Comment]         VARCHAR (255)  NULL,
    [W_HepC_ExecDate]        DATETIME       NULL,
    [W_Syp]                  BIT            NULL,
    [W_Syp_Comment]          VARCHAR (255)  NULL,
    [W_Syp_ExecDate]         DATETIME       NULL,
    [W_BlClin]               BIT            NULL,
    [W_BlClin_Comment]       VARCHAR (255)  NULL,
    [W_BlClin_ExecDate]      DATETIME       NULL,
    [W_BlBio]                BIT            NULL,
    [W_BlBio_Comment]        VARCHAR (255)  NULL,
    [W_BlBio_ExecDate]       DATETIME       NULL,
    [W_Rubella]              BIT            NULL,
    [W_Rubella_Comment]      VARCHAR (255)  NULL,
    [W_Rubella_ExecDate]     DATETIME       NULL,
    [W_Uro]                  BIT            NULL,
    [W_Uro_Comment]          VARCHAR (255)  NULL,
    [W_Uro_ExecDate]         DATETIME       NULL,
    [W_Smear]                BIT            NULL,
    [W_Smear_Comment]        VARCHAR (255)  NULL,
    [W_Smear_ExecDate]       DATETIME       NULL,
    [W_Cyto]                 BIT            NULL,
    [W_Cyto_Comment]         VARCHAR (255)  NULL,
    [W_Cyto_ExecDate]        DATETIME       NULL,
    [W_USG]                  BIT            NULL,
    [W_USG_Comment]          VARCHAR (255)  NULL,
    [W_USG_ExecDate]         DATETIME       NULL,
    [W_ECG]                  BIT            NULL,
    [W_ECG_Comment]          VARCHAR (255)  NULL,
    [W_ECG_ExecDate]         DATETIME       NULL,
    [W_PhysOpinion]          BIT            NULL,
    [W_PhysOpinion_Comment]  VARCHAR (255)  NULL,
    [W_PhysOpinion_ExecDate] DATETIME       NULL,
    [W_PhysOpinion_OperId]   INT            NULL,
    [W_Hemo]                 BIT            NULL,
    [W_Hemo_Comment]         VARCHAR (255)  NULL,
    [W_Hemo_ExecDate]        DATETIME       NULL,
    [W_Fluo]                 BIT            NULL,
    [W_Fluo_Comment]         VARCHAR (255)  NULL,
    [W_Fluo_ExecDate]        DATETIME       NULL,
    [OriginalID]             INT            NULL,
    [W_mammolog]             BIT            NULL,
    [W_mammolog_Comment]     NVARCHAR (255) NULL,
    [W_mammolog_ExecDate]    DATETIME       NULL,
    [W_other_ExecDate]       DATETIME       NULL,
    [W_other_Comment]        NVARCHAR (255) NULL,
    [W_other]                BIT            NULL,
    CONSTRAINT [PK_ExamsECF] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ECFExams_PatForm] FOREIGN KEY ([Id]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

