CREATE TABLE [dbo].[ECFPunc] (
    [Id]            INT            NOT NULL,
    [ParentId]      INT            NULL,
    [PatId]         INT            NULL,
    [ExecDate]      DATETIME       NULL,
    [ExecTime]      DATETIME       NULL,
    [Stim]          BIT            NULL,
    [PuncFoll]      INT            NULL,
    [WashFoll]      INT            NULL,
    [GotOocytes]    INT            NULL,
    [Seq]           NTEXT          NULL,
    [AnaesLast]     FLOAT (53)     NULL,
    [AnaesSeq]      NTEXT          NULL,
    [EmbrOperId]    INT            NULL,
    [Embr2OperId]   INT            NULL,
    [OperId]        INT            NULL,
    [PostTime]      DATETIME       NULL,
    [PostProblem]   VARCHAR (255)  NULL,
    [PostState]     VARCHAR (255)  NULL,
    [PostDescr]     VARCHAR (255)  NULL,
    [PostPuls]      VARCHAR (255)  NULL,
    [PostAD]        VARCHAR (255)  NULL,
    [PostOperId]    INT            NULL,
    [OriginalID]    INT            NULL,
    [Seq_blood]     BIT            NULL,
    [Seq_Infection] BIT            NULL,
    [AnastOperId]   INT            NULL,
    [PostAD1]       NVARCHAR (255) NULL,
    [Anesteziolog]  BIT            NULL,
    [DonorNum]      NVARCHAR (20)  NULL,
    [CancelTrans]   BIT            NULL,
    [CancelTransId] INT            NULL,
    [Estradiol]     FLOAT (53)     NULL,
    [Progesteron]   FLOAT (53)     NULL,
    CONSTRAINT [PK_ECFPunc] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ECFPunc_PatForm] FOREIGN KEY ([Id]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

