CREATE TABLE [dbo].[ECFStim] (
    [Id]               INT           NOT NULL,
    [ParentId]         INT           NULL,
    [PatId]            INT           NULL,
    [ExecDateProto]    DATETIME      NULL,
    [DayMCProto]       INT           NULL,
    [CureProto]        NTEXT         NULL,
    [DoseProto]        FLOAT (53)    NULL,
    [LenProto]         INT           NULL,
    [UZIDays]          INT           NULL,
    [HGDate]           DATETIME      NULL,
    [HGTime]           DATETIME      NULL,
    [HGDoze]           NVARCHAR (15) NULL,
    [HGComment]        VARCHAR (255) NULL,
    [PuncDay]          INT           NULL,
    [PuncTime]         DATETIME      NULL,
    [TransDay]         INT           NULL,
    [TransTime]        DATETIME      NULL,
    [TransDay1]        INT           NULL,
    [TransTime1]       DATETIME      NULL,
    [ExecDate]         DATETIME      NULL,
    [DayMC]            INT           NULL,
    [CancelDay]        INT           NULL,
    [CancelStimId]     INT           NULL,
    [UZIExecDate]      DATETIME      NULL,
    [UZMatrix]         VARCHAR (15)  NULL,
    [MEHO]             VARCHAR (15)  NULL,
    [ROvary]           VARCHAR (15)  NULL,
    [RFoll]            VARCHAR (15)  NULL,
    [LOvary]           VARCHAR (15)  NULL,
    [LFoll]            VARCHAR (15)  NULL,
    [UZComment]        VARCHAR (150) NULL,
    [OperId]           INT           NULL,
    [OriginalID]       INT           NULL,
    [PuncDayDate]      DATETIME      NULL,
    [TransDayDate]     DATETIME      NULL,
    [TransDay1Date]    DATETIME      NULL,
    [PuncResource]     INT           NULL,
    [TransResource]    INT           NULL,
    [Trans1Resource]   INT           NULL,
    [PuncResource2]    INT           NULL,
    [TransResource2]   INT           NULL,
    [Trans1Resource2]  INT           NULL,
    [PuncDuration]     INT           NULL,
    [TransDuration]    INT           NULL,
    [Trans1Duration]   INT           NULL,
    [VMIDate]          DATETIME      NULL,
    [VMITime]          DATETIME      NULL,
    [VMIDay]           INT           NULL,
    [VMIResource]      INT           NULL,
    [VMIResource2]     INT           NULL,
    [VMIDuration]      INT           NULL,
    [PuncTitle]        NVARCHAR (50) NULL,
    [TransTitle]       NVARCHAR (50) NULL,
    [Trans1Title]      NVARCHAR (50) NULL,
    [VMITitle]         NVARCHAR (50) NULL,
    [CancelPunc]       BIT           NULL,
    [CancelPuncReason] NVARCHAR (30) NULL,
    [FollCount]        INT           NULL,
    [NeedAnest]        BIT           NULL,
    [DonorSp]          NVARCHAR (50) NULL,
    CONSTRAINT [PK_ECFStim] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ECFStim_PatForm] FOREIGN KEY ([Id]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

