CREATE TABLE [dbo].[ECFStimProto] (
    [Id]         INT           NOT NULL,
    [DocTypeId]  INT           NULL,
    [MasterID]   INT           NULL,
    [StimModeId] INT           NULL,
    [AfterPunc]  BIT           NULL,
    [_1]         FLOAT (53)    NULL,
    [_2]         FLOAT (53)    NULL,
    [_3]         FLOAT (53)    NULL,
    [_4]         FLOAT (53)    NULL,
    [_5]         FLOAT (53)    NULL,
    [_6]         FLOAT (53)    NULL,
    [_7]         FLOAT (53)    NULL,
    [_8]         FLOAT (53)    NULL,
    [_9]         FLOAT (53)    NULL,
    [_10]        FLOAT (53)    NULL,
    [_11]        FLOAT (53)    NULL,
    [_12]        FLOAT (53)    NULL,
    [_13]        FLOAT (53)    NULL,
    [_14]        FLOAT (53)    NULL,
    [_15]        FLOAT (53)    NULL,
    [_16]        FLOAT (53)    NULL,
    [_17]        FLOAT (53)    NULL,
    [_18]        FLOAT (53)    NULL,
    [_19]        FLOAT (53)    NULL,
    [_20]        FLOAT (53)    NULL,
    [_21]        FLOAT (53)    NULL,
    [_22]        FLOAT (53)    NULL,
    [_23]        FLOAT (53)    NULL,
    [_24]        FLOAT (53)    NULL,
    [_25]        FLOAT (53)    NULL,
    [_26]        FLOAT (53)    NULL,
    [_27]        FLOAT (53)    NULL,
    [_28]        FLOAT (53)    NULL,
    [Comment]    VARCHAR (255) NULL,
    [OriginalID] INT           NULL,
    CONSTRAINT [PK_ECFStimProto] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ECFStimProto_ECFStim] FOREIGN KEY ([MasterID]) REFERENCES [dbo].[ECFStim] ([Id]) ON DELETE CASCADE
);

