CREATE TABLE [dbo].[ECFTrans] (
    [Id]                                     INT           NOT NULL,
    [ParentId]                               INT           NULL,
    [PatId]                                  INT           NULL,
    [ExecDate]                               DATETIME      NULL,
    [DayMC]                                  INT           NULL,
    [DonorNum]                               NVARCHAR (20) NULL,
    [ExecTime]                               DATETIME      NULL,
    [CancelDay]                              INT           NULL,
    [CancelTransId]                          INT           NULL,
    [QtyFresh]                               INT           NULL,
    [QtyUncryo]                              INT           NULL,
    [QtyCryo]                                INT           NULL,
    [Comment]                                NTEXT         NULL,
    [CathId]                                 INT           NULL,
    [CathNewId]                              INT           NULL,
    [CathBlood]                              VARCHAR (150) NULL,
    [PulCrow]                                BIT           NULL,
    [DupTrans]                               BIT           NULL,
    [DupTransComment]                        VARCHAR (255) NULL,
    [Others]                                 VARCHAR (255) NULL,
    [OHS]                                    VARCHAR (150) NULL,
    [OHSCureAmb]                             BIT           NULL,
    [TransCharId]                            INT           NULL,
    [TransLast]                              FLOAT (53)    NULL,
    [HormTransId]                            INT           NULL,
    [Endo]                                   FLOAT (53)    NULL,
    [Anaest]                                 BIT           NULL,
    [EmbrOperId]                             INT           NULL,
    [PayNeed]                                BIT           NULL,
    [Payed]                                  BIT           NULL,
    [PaySum]                                 MONEY         NULL,
    [PayedSum]                               MONEY         NULL,
    [PayDate]                                DATETIME      NULL,
    [PayComment]                             VARCHAR (255) NULL,
    [OperId]                                 INT           NULL,
    [OriginalID]                             INT           NULL,
    [SurMother]                              INT           NULL,
    [StimModeID]                             INT           NULL,
    [StimDose]                               FLOAT (53)    NULL,
    [StimPattern]                            NVARCHAR (50) NULL,
    [CryoKind]                               NVARCHAR (30) NULL,
    [af_Gidrosalpinks]                       BIT           NULL,
    [af_GisteroskopiyaZaPoslednie6Mesyatsev] BIT           NULL,
    [af_PolipEndometriya]                    BIT           NULL,
    [af_HrEndometrit]                        BIT           NULL,
    [af_GiperplaziyaEndometriya]             BIT           NULL,
    [af_GenitalniyEndometrioz]               BIT           NULL,
    [af_Adenomioz]                           BIT           NULL,
    [af_MiomaMatkiDo3Sm]                     BIT           NULL,
    [af_MiomaMatkiBolee3Sm]                  BIT           NULL,
    [af_PatologiyaSheykiMatki]               BIT           NULL,
    [af_OperirovannieYaichniki]              NVARCHAR (10) NULL,
    [Spkya]                                  BIT           NULL,
    CONSTRAINT [PK_ECFTrans] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ECFTrans_PatForm] FOREIGN KEY ([Id]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

