CREATE TABLE [dbo].[EfiErg] (
    [ID]          INT           NOT NULL,
    [PatID]       INT           NULL,
    [IntW]        FLOAT (53)    NULL,
    [IntR]        FLOAT (53)    NULL,
    [IntB]        FLOAT (53)    NULL,
    [ODAaW]       INT           NULL,
    [ODAaR]       INT           NULL,
    [ODAaB]       INT           NULL,
    [ODLaW]       INT           NULL,
    [ODLaR]       INT           NULL,
    [ODLaB]       INT           NULL,
    [ODAbW]       INT           NULL,
    [ODAbR]       INT           NULL,
    [ODAbB]       INT           NULL,
    [ODLbW]       INT           NULL,
    [ODLbR]       INT           NULL,
    [ODLbB]       INT           NULL,
    [OSAaW]       INT           NULL,
    [OSAaR]       INT           NULL,
    [OSAaB]       INT           NULL,
    [OSLaW]       INT           NULL,
    [OSLaR]       INT           NULL,
    [OSLaB]       INT           NULL,
    [OSAbW]       INT           NULL,
    [OSAbR]       INT           NULL,
    [OSAbB]       INT           NULL,
    [OSLbW]       INT           NULL,
    [OSLbR]       INT           NULL,
    [OSLbB]       INT           NULL,
    [ERGOD]       NVARCHAR (50) NULL,
    [ERGOS]       NVARCHAR (50) NULL,
    [Zakluchenie] NTEXT         NULL,
    CONSTRAINT [EfiErgPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [EfiErgToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

