CREATE TABLE [dbo].[EfiVp] (
    [ID]          INT           NOT NULL,
    [PatID]       INT           NULL,
    [ODINT]       FLOAT (53)    NULL,
    [OSINT]       FLOAT (53)    NULL,
    [ODCvet]      NVARCHAR (50) NULL,
    [ODAP100]     FLOAT (53)    NULL,
    [ODLP100]     INT           NULL,
    [ODAP200]     FLOAT (53)    NULL,
    [ODLP200]     INT           NULL,
    [OSCvet]      NVARCHAR (50) NULL,
    [OSAP100]     FLOAT (53)    NULL,
    [OSLP100]     INT           NULL,
    [OSAP200]     FLOAT (53)    NULL,
    [OSLP200]     INT           NULL,
    [ODINT2]      FLOAT (53)    NULL,
    [OSINT2]      FLOAT (53)    NULL,
    [ODKontrast]  INT           NULL,
    [OSKontrast]  INT           NULL,
    [2ODAP100]    FLOAT (53)    NULL,
    [OS2AP100]    FLOAT (53)    NULL,
    [OD2LP100]    INT           NULL,
    [OS2LP100]    INT           NULL,
    [OD2AP200]    FLOAT (53)    NULL,
    [OS2AP200]    FLOAT (53)    NULL,
    [OD2LP200]    INT           NULL,
    [OS2LP200]    INT           NULL,
    [ODMaxOtveta] FLOAT (53)    NULL,
    [OSMaxOtveta] FLOAT (53)    NULL,
    [ODINT3]      FLOAT (53)    NULL,
    [OSINT3]      FLOAT (53)    NULL,
    [ODCvet3]     NVARCHAR (50) NULL,
    [OSCvet3]     NVARCHAR (50) NULL,
    [ODKCVR]      INT           NULL,
    [OSKCVR]      INT           NULL,
    [Zaklucenie]  NTEXT         NULL,
    CONSTRAINT [EfiVpPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [EfiVpToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

