CREATE TABLE [dbo].[Elektroentsefalografiya] (
    [ID]                                            INT          NOT NULL,
    [PatID]                                         INT          NULL,
    [NomerIssledovaniya]                            INT          NULL,
    [DataIssledovanie]                              DATETIME     NULL,
    [ObshayaHarakteristikaElektricheskoyAktivnosti] INT          NULL,
    [AlfaAktivnost]                                 INT          NULL,
    [Chastota]                                      INT          NULL,
    [Regulyarnost]                                  INT          NULL,
    [Amplituda]                                     INT          NULL,
    [ZonalnieRazlichiya]                            INT          NULL,
    [FormaAlfaVoln]                                 INT          NULL,
    [ModulyatsiiAlfaVoln]                           INT          NULL,
    [AktivatsiyaAlfaVoln]                           INT          NULL,
    [VirazhennostAlfaVoln]                          INT          NULL,
    [TopografiyaAlfaVoln]                           INT          NULL,
    [TetaAktivnost]                                 INT          NULL,
    [VirazhennostTetaVoln]                          INT          NULL,
    [TopografiyaTetaVoln]                           INT          NULL,
    [DeltaAktivnost]                                INT          NULL,
    [VirazhennostDeltaVoln]                         INT          NULL,
    [TopografiyaDeltaVoln]                          INT          NULL,
    [ParoksizmalnayaAktivnost]                      NVARCHAR (1) NULL,
    [ProvotsiruetsyaFunktsionalnimiNagruzkami]      NVARCHAR (1) NULL,
    [ZvukovoyStimulyatsiey]                         NVARCHAR (1) NULL,
    [SvetovoyStimulyatsiey]                         NVARCHAR (1) NULL,
    [Giperventilyatsiey]                            NVARCHAR (1) NULL,
    [Proyavleniya]                                  INT          NULL,
    [VirazhennostParoksizmalnoyAktivnosti]          INT          NULL,
    [TopografiyaParoksizmalnoyAktivnosti]           INT          NULL,
    [ProbaSOtkrivaniemGlaz]                         INT          NULL,
    [ZvukovayaStimulyatsiya]                        INT          NULL,
    [Fotostimulyatsiya]                             INT          NULL,
    [Topografiya]                                   INT          NULL,
    [Giperventilyatsiya]                            INT          NULL,
    [Zaklyuchenie]                                  NTEXT        NULL,
    [Vrach]                                         INT          NULL,
    CONSTRAINT [ElektroentsefalografiyaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [ElektroentsefalografiyaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

