CREATE TABLE [dbo].[Elektrokardiografiya] (
    [ID]                      INT           NOT NULL,
    [PatID]                   INT           NULL,
    [PQ]                      INT           NULL,
    [QRS]                     INT           NULL,
    [QT]                      INT           NULL,
    [ElektricheskayaOs]       INT           NULL,
    [Zaklyuchenie]            NTEXT         NULL,
    [Vrach]                   INT           NULL,
    [NomerIssledovaniya1]     INT           NULL,
    [DataIssledovanie1]       DATETIME      NULL,
    [Vozrast]                 INT           NULL,
    [Rost]                    INT           NULL,
    [Ves]                     INT           NULL,
    [Sist]                    INT           NULL,
    [Diast]                   NVARCHAR (50) NULL,
    [Chss]                    NVARCHAR (50) NULL,
    [RRcp]                    INT           NULL,
    [RRmin]                   INT           NULL,
    [RRmax]                   INT           NULL,
    [ST]                      INT           NULL,
    [TP]                      INT           NULL,
    [TQ]                      INT           NULL,
    [TR]                      INT           NULL,
    [TT]                      INT           NULL,
    [TS]                      INT           NULL,
    [UgolOtklEosGradusov]     INT           NULL,
    [DolzhnoeQTPoBazetta]     INT           NULL,
    [SistolicheskiyPokazatel] INT           NULL,
    [IndeksMakruza]           INT           NULL,
    CONSTRAINT [ElektrokardiografiyaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [ElektrokardiografiyaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

