CREATE TABLE [dbo].[EmiasAppointment] (
    [ID]                    INT            NOT NULL,
    [complexResourceId]     INT            NULL,
    [availableResourceId]   INT            NULL,
    [resourceFullname]      NVARCHAR (100) NULL,
    [resourceName]          NVARCHAR (50)  NULL,
    [appointmentBeginTime]  DATETIME       NULL,
    [appointmentEndTime]    DATETIME       NULL,
    [patFullname]           NVARCHAR (255) NULL,
    [patBirthDate]          DATETIME       NULL,
    [omsNumber]             NVARCHAR (30)  NULL,
    [patientId]             INT            NULL,
    [phone1]                NVARCHAR (20)  NULL,
    [phone2]                NVARCHAR (20)  NULL,
    [patAddress]            NVARCHAR (200) NULL,
    [patAddress2]           NVARCHAR (200) NULL,
    [patCardNum]            NVARCHAR (50)  NULL,
    [patSections]           NVARCHAR (50)  NULL,
    [patCardLocation]       NVARCHAR (50)  NULL,
    [receptionTypeName]     NVARCHAR (100) NULL,
    [status]                NVARCHAR (50)  NULL,
    [sourceType]            NVARCHAR (50)  NULL,
    [receptionFailedReason] NVARCHAR (50)  NULL,
    [liveQueueTicketNumber] NVARCHAR (10)  NULL,
    [receptionLpuShortName] NVARCHAR (50)  NULL,
    [duration]              INT            NULL,
    [importedOn]            DATETIME       NULL,
    [settingsIdReg]         INT            NULL,
    [settingsIdDoc]         INT            NULL,
    [linkedUsrID]           INT            NULL,
    [ShowInSchedule]        BIT            NULL,
    [HiddenByUser]          INT            NULL,
    [PatId]                 INT            NULL,
    [NapravlenieId]         INT            NULL,
    [HiddenOn]              DATETIME       NULL,
    CONSTRAINT [EmiasAppointmentPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC)
);

