CREATE TABLE [dbo].[f066] (
    [ID]                          INT            NOT NULL,
    [PatID]                       INT            NULL,
    [SozStatus]                   INT            NULL,
    [KemNapravlen]                NVARCHAR (100) NULL,
    [NumNapravl]                  NVARCHAR (10)  NULL,
    [DateNapravl]                 DATETIME       NULL,
    [DiagNapravl]                 NVARCHAR (6)   NULL,
    [DiagPriemOtd]                NVARCHAR (6)   NULL,
    [Alkogol]                     BIT            NULL,
    [Narkot]                      BIT            NULL,
    [PervPovt]                    NVARCHAR (20)  NULL,
    [ExtrenoPlan]                 NVARCHAR (30)  NULL,
    [InputDate]                   DATETIME       NULL,
    [InputTime]                   DATETIME       NULL,
    [OutputDate]                  DATETIME       NULL,
    [OutputTime]                  DATETIME       NULL,
    [Vipisan]                     BIT            NULL,
    [Ishod]                       INT            NULL,
    [Result]                      INT            NULL,
    [ListBegDate]                 DATETIME       NULL,
    [ListEndDate]                 DATETIME       NULL,
    [Yeas]                        INT            NULL,
    [ListSex]                     NVARCHAR (1)   NULL,
    [OsnDiag]                     NVARCHAR (6)   NULL,
    [OslDiag]                     NVARCHAR (6)   NULL,
    [SopDiag]                     NVARCHAR (6)   NULL,
    [OsnDiag1]                    NVARCHAR (6)   NULL,
    [OslDiag1]                    NVARCHAR (6)   NULL,
    [SopDiag1]                    NVARCHAR (6)   NULL,
    [DeadDiag]                    NVARCHAR (6)   NULL,
    [DefLater]                    BIT            NULL,
    [DefObsl]                     BIT            NULL,
    [DefLech]                     BIT            NULL,
    [DefDiag]                     BIT            NULL,
    [LechVrach]                   INT            NULL,
    [ZavOtd]                      INT            NULL,
    [ObsledVich]                  INT            NULL,
    [ObsledSif]                   INT            NULL,
    [DeptId]                      INT            NULL,
    [InputDeptDate]               DATETIME       NULL,
    [InputDeptTime]               DATETIME       NULL,
    [DeptVrach]                   INT            NULL,
    [Tr]                          INT            NULL,
    [AfterTime]                   NVARCHAR (50)  NULL,
    [KemDost]                     NVARCHAR (50)  NULL,
    [Naryad]                      NVARCHAR (20)  NULL,
    [CardNum]                     NVARCHAR (20)  NULL,
    [PatFullName]                 NVARCHAR (50)  NULL,
    [Sex]                         NVARCHAR (1)   NULL,
    [BirthDate]                   DATETIME       NULL,
    [Document]                    NVARCHAR (100) NULL,
    [Adres]                       NVARCHAR (50)  NULL,
    [Lgoti]                       NVARCHAR (50)  NULL,
    [Policy]                      NVARCHAR (50)  NULL,
    [Type]                        INT            NULL,
    [NeUchitivatVihodnieDni]      NVARCHAR (1)   NULL,
    [DayCountOnBed]               INT            NULL,
    [Obrazovanije]                NVARCHAR (100) NULL,
    [Uchitsya]                    BIT            NULL,
    [IstochnikSredstv]            NVARCHAR (100) NULL,
    [Prozhivayet]                 NVARCHAR (30)  NULL,
    [ProzhivayetUsl]              NVARCHAR (50)  NULL,
    [IshodZabolevanija]           NVARCHAR (50)  NULL,
    [DateNachalaZabolev]          DATETIME       NULL,
    [DatePervogoObrasch]          DATETIME       NULL,
    [NumPrinudLech]               INT            NULL,
    [VidAmbulatornNabl]           NVARCHAR (100) NULL,
    [DatePredVypiskiStat]         DATETIME       NULL,
    [DneyLTM]                     INT            NULL,
    [DneyOtpuskov]                INT            NULL,
    [NumOtpuskov]                 INT            NULL,
    [Dead]                        NVARCHAR (100) NULL,
    [PoriadokPostuplenija]        NVARCHAR (50)  NULL,
    [ReshenijeSuda]               NVARCHAR (50)  NULL,
    [OtkudaPostupil]              NVARCHAR (50)  NULL,
    [SocStatus]                   INT            NULL,
    [CardNum066]                  NVARCHAR (20)  NULL,
    [VidOplaty]                   NVARCHAR (50)  NULL,
    [PervPovtHere]                NVARCHAR (20)  NULL,
    [InvalidnostPriVypiskePsikh]  NVARCHAR (50)  NULL,
    [ObsledovanAIDS]              NVARCHAR (50)  NULL,
    [InvalidnostPriVypiskeCommon] NVARCHAR (50)  NULL,
    [UchastnikVov]                BIT            NULL,
    [InvalidVov]                  BIT            NULL,
    [ID001]                       INT            NULL,
    [TcelNapravl]                 NVARCHAR (50)  NULL,
    [DiagNapravlLabel]            NTEXT          NULL,
    [DiagPriemOtdLabel]           NTEXT          NULL,
    [IstFinans]                   NVARCHAR (50)  NULL,
    [IstFin]                      INT            NULL,
    [Polis]                       NVARCHAR (50)  NULL,
    CONSTRAINT [f066PrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [f066ToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

