CREATE TABLE [dbo].[F089ukv] (
    [ID]                       INT            NOT NULL,
    [PatID]                    INT            NULL,
    [VrachTerNaub]             NVARCHAR (200) NULL,
    [Organiz]                  NVARCHAR (50)  NULL,
    [Uchrezhdenie]             NVARCHAR (50)  NULL,
    [VrachViyav]               NVARCHAR (50)  NULL,
    [kontaktbolnogo]           NVARCHAR (1)   NULL,
    [donor]                    NVARCHAR (1)   NULL,
    [donor1]                   NVARCHAR (1)   NULL,
    [drugieobstoyatelstva]     NVARCHAR (1)   NULL,
    [VoVremyaRodov]            NVARCHAR (1)   NULL,
    [DrugieObstoyatelstvaText] NVARCHAR (200) NULL,
    [SpecialistText]           NVARCHAR (200) NULL,
    [VTChPoKontaktu]           NVARCHAR (1)   NULL,
    [ProfilKoiki]              NVARCHAR (200) NULL,
    [EditBox1]                 NVARCHAR (200) NULL,
    [Rmp]                      NVARCHAR (1)   NULL,
    [Rpga]                     NVARCHAR (1)   NULL,
    [Rpr]                      NVARCHAR (1)   NULL,
    [Ifa]                      NVARCHAR (1)   NULL,
    [Rif]                      NVARCHAR (1)   NULL,
    [Ribt]                     NVARCHAR (1)   NULL,
    [Ksr]                      NVARCHAR (1)   NULL,
    [KatBolnogo]               NVARCHAR (50)  NULL,
    [LastName]                 NVARCHAR (20)  NULL,
    [FirstName]                NVARCHAR (20)  NULL,
    [SecondName]               NVARCHAR (50)  NULL,
    [BirthDate]                DATETIME       NULL,
    [AdresRaionReg]            NVARCHAR (50)  NULL,
    [AdresGorod]               NVARCHAR (100) NULL,
    [AdresUlitsa]              NVARCHAR (70)  NULL,
    [AdresDom]                 NVARCHAR (10)  NULL,
    [AdresKvartira]            NVARCHAR (10)  NULL,
    [AdresRaionRegF]           NVARCHAR (50)  NULL,
    [AdresGorodF]              NVARCHAR (100) NULL,
    [AdresUlitsaF]             NVARCHAR (70)  NULL,
    [AdresDomF]                NVARCHAR (10)  NULL,
    [AdresKvartiraF]           NVARCHAR (10)  NULL,
    [Zhitel]                   NVARCHAR (50)  NULL,
    [SocStat]                  NVARCHAR (50)  NULL,
    [RodZanyat]                NVARCHAR (50)  NULL,
    [DiagDict]                 NVARCHAR (50)  NULL,
    [DiagCode]                 NVARCHAR (6)   NULL,
    [Reinfekciya]              NVARCHAR (50)  NULL,
    [LabPodtverzhd]            NVARCHAR (50)  NULL,
    [Drugoe]                   NVARCHAR (50)  NULL,
    [Vozbuditel]               NVARCHAR (50)  NULL,
    [PutiPeredachi]            NVARCHAR (50)  NULL,
    [MestoZabolev]             NVARCHAR (50)  NULL,
    [Anonimno]                 NVARCHAR (1)   NULL,
    [DrugoeZabol]              NVARCHAR (50)  NULL,
    [ObstoyatelViyavlen]       NVARCHAR (50)  NULL,
    [SrokBeremen]              NVARCHAR (120) NULL,
    [DetUchrezhd]              NVARCHAR (150) NULL,
    [DataDiagnoza]             DATETIME       NULL,
    [Vrach]                    NVARCHAR (200) NULL,
    [Zamechaniya]              NVARCHAR (50)  NULL,
    [Akt]                      NVARCHAR (1)   NULL,
    [Sex]                      NVARCHAR (50)  NULL,
    [TerNab]                   NVARCHAR (50)  NULL,
    [DiagLabel]                NVARCHAR (300) NULL,
    [NomIzv]                   INT            NULL,
    [Avtor]                    INT            NULL,
    [AdresKorpus]              NVARCHAR (50)  NULL,
    [AdresStroenie]            NVARCHAR (8)   NULL,
    [Updatetime]               DATETIME       NULL,
    [AdresRegionDict]          NVARCHAR (10)  NULL,
    [AdresStranaDict]          NVARCHAR (10)  NULL,
    [RegionCodeEditBox]        NVARCHAR (10)  NULL,
    [RaionCodeEditBox]         NVARCHAR (10)  NULL,
    [GorodCodeEditBox]         NVARCHAR (10)  NULL,
    [useKLADR]                 BIT            NULL,
    [AdresOther]               NVARCHAR (200) NULL,
    [UlCodeEditBox]            NVARCHAR (17)  NULL,
    [AdresRaionGor]            NVARCHAR (50)  NULL,
    [AdresRegion]              NVARCHAR (50)  NULL,
    [AdresStrana]              NVARCHAR (50)  NULL,
    [DiagLabelU]               NVARCHAR (200) NULL,
    [AdresRegionF]             NVARCHAR (50)  NULL,
    [AdresDom0]                NVARCHAR (10)  NULL,
    [AdresKvartira0]           NVARCHAR (10)  NULL,
    [AdresKorpusF]             NVARCHAR (50)  NULL,
    CONSTRAINT [F089ukvPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [F089ukvToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);


GO
ALTER TABLE [dbo].[F089ukv] NOCHECK CONSTRAINT [F089ukvToPatForm];

