CREATE TABLE [dbo].[Fgs] (
    [ID]                                                        INT            NOT NULL,
    [PatID]                                                     INT            NULL,
    [NomerIssledovaniya]                                        INT            NULL,
    [DataIssledovanie]                                          DATETIME       NULL,
    [Vrach]                                                     INT            NULL,
    [TubusFibrogastroskopa]                                     NVARCHAR (50)  NULL,
    [IzZa]                                                      INT            NULL,
    [Slizistaya]                                                INT            NULL,
    [VidSlizitoy]                                               INT            NULL,
    [GiperemirovanaOtechna]                                     NVARCHAR (1)   NULL,
    [PokritaSerimNaletomTochechnimiKrovoizliyaniyami]           NVARCHAR (1)   NULL,
    [DiffuznoYarkoGiperemirovanaOtechna]                        NVARCHAR (1)   NULL,
    [PokritaTochechnimiKrovoizliyaniyamiOchagovimiEroziyami]    NVARCHAR (1)   NULL,
    [VirazhennayaProdolnayaSkladchatos]                         NVARCHAR (1)   NULL,
    [IstonchenaSglazhena]                                       NVARCHAR (1)   NULL,
    [LegkoRanima]                                               NVARCHAR (1)   NULL,
    [Peristaltika]                                              INT            NULL,
    [Stenki]                                                    INT            NULL,
    [ProsvetPishevoda]                                          INT            NULL,
    [SuzhenNaRasstoyanii]                                       NVARCHAR (1)   NULL,
    [KardialniyZhomP]                                           INT            NULL,
    [OtmechaetsyaP]                                             INT            NULL,
    [VarikoznoeRasshirenieVenP]                                 NVARCHAR (1)   NULL,
    [NaFoneP]                                                   INT            NULL,
    [VidniSeroGolubieTyazhi]                                    NVARCHAR (1)   NULL,
    [SerogolubieNyagiP]                                         INT            NULL,
    [SerogolubieNyagiP1]                                        INT            NULL,
    [ZaSchet]                                                   INT            NULL,
    [PorazhayusheyP]                                            INT            NULL,
    [Lokalizatsiya]                                             INT            NULL,
    [VidPoverhnosti]                                            INT            NULL,
    [Poverhnost]                                                INT            NULL,
    [PovishennayaKrovotochivost]                                NVARCHAR (1)   NULL,
    [SlizistayaLegkoObrivaetsya]                                NVARCHAR (1)   NULL,
    [VTsentreObrazovaniyaOpredelyaetsyaYazva]                   NVARCHAR (1)   NULL,
    [DivertikuliP]                                              NVARCHAR (1)   NULL,
    [NaRasstoyaniiP]                                            FLOAT (53)     NULL,
    [Obrazovanie]                                               NVARCHAR (1)   NULL,
    [NaRasstoyaniiP1]                                           FLOAT (53)     NULL,
    [DopolnenieP]                                               NVARCHAR (100) NULL,
    [Ezofagiti]                                                 INT            NULL,
    [Lokalizatsiya1]                                            INT            NULL,
    [FormaEzofagita]                                            INT            NULL,
    [GrizhaPishevodnogoOtverstiyaDiafragmi]                     INT            NULL,
    [Divertikuli]                                               INT            NULL,
    [VarikoznoeRasshirenieVen]                                  INT            NULL,
    [LokalizatsiyaVen]                                          INT            NULL,
    [Stepen]                                                    INT            NULL,
    [DobrokachestvennayaOpuholP]                                INT            NULL,
    [LokalizatsiyaDOP]                                          INT            NULL,
    [OslozhnenieDKOpuholi]                                      INT            NULL,
    [ZlokachestvennayaOpuhol]                                   INT            NULL,
    [LokalizatsiyaZOP]                                          INT            NULL,
    [FormaRostaP]                                               INT            NULL,
    [LokalizatsiyaP]                                            INT            NULL,
    [VidSlizistoyP]                                             INT            NULL,
    [CoderzhashieP]                                             INT            NULL,
    [Nadpis5]                                                   FLOAT (53)     NULL,
    [RazmeromP3]                                                FLOAT (53)     NULL,
    [RazmeromP4]                                                FLOAT (53)     NULL,
    [FormaObrazovaniyaP]                                        INT            NULL,
    [RazmeromP]                                                 FLOAT (53)     NULL,
    [RazmeromP1]                                                FLOAT (53)     NULL,
    [RazmeromP2]                                                FLOAT (53)     NULL,
    [OsnovanieP]                                                INT            NULL,
    [Ctenka]                                                    INT            NULL,
    [Slizistaya1]                                               INT            NULL,
    [PolostZheludka]                                            INT            NULL,
    [LokalizatsiyaG]                                            INT            NULL,
    [SoderzhimoeG]                                              INT            NULL,
    [KolichestvoG]                                              INT            NULL,
    [SkladkiG]                                                  INT            NULL,
    [PriInsuflyatsiiplohoRaspravlyayutsyaPolnostyuNeIschezayut] NVARCHAR (1)   NULL,
    [GrebniSkladokGiperemirovaniOtechni]                        NVARCHAR (1)   NULL,
    [PokritiG]                                                  INT            NULL,
    [LokalizatsiyaSkladkiG]                                     INT            NULL,
    [KriviznaG]                                                 INT            NULL,
    [SlizistayaG]                                               INT            NULL,
    [NaEtomFoneG]                                               INT            NULL,
    [TipG]                                                      INT            NULL,
    [ObnaruzhenaG]                                              INT            NULL,
    [FormaG]                                                    INT            NULL,
    [OsnovanieG]                                                INT            NULL,
    [RazmeramiG]                                                FLOAT (53)     NULL,
    [RazmeramiG1]                                               FLOAT (53)     NULL,
    [RazmeramiG2]                                               FLOAT (53)     NULL,
    [DnoG]                                                      INT            NULL,
    [PokritoG]                                                  INT            NULL,
    [KrayaG]                                                    INT            NULL,
    [OkruzhayushayaSlizistayaG]                                 INT            NULL,
    [PriPritselnoyBiopsiiSlizistaG]                             INT            NULL,
    [OtmechaetsyaPovishennayaKrovotochivost]                    NVARCHAR (1)   NULL,
    [StenkiG]                                                   INT            NULL,
    [PoverhnostSlizistoyG]                                      INT            NULL,
    [PrivratnikG]                                               INT            NULL,
    [NeProhodimDlyaTubusa]                                      NVARCHAR (1)   NULL,
    [Gastrit]                                                   INT            NULL,
    [LokalizatsiyaG1]                                           INT            NULL,
    [DuodenoGastralniyReflyuks]                                 NVARCHAR (1)   NULL,
    [YazvaG]                                                    INT            NULL,
    [LokalizatsiyaYazvaG]                                       INT            NULL,
    [VStadiiG]                                                  INT            NULL,
    [DinamikaG]                                                 INT            NULL,
    [CInfiltratsiey]                                            NVARCHAR (1)   NULL,
    [ZlokachestvennieOpuholi]                                   INT            NULL,
    [DobrokachestvennayaOpuhol]                                 INT            NULL,
    [LokalizatsiyaOpuholZ]                                      INT            NULL,
    [LokalizatsiyaOpuholD]                                      INT            NULL,
    [MalignizatsiyaPodslizistiyCancerInfiltrativniyCancer]      INT            NULL,
    [SostoyaniePosleSubtotalnoyRezektsiiZheludka]               NVARCHAR (1)   NULL,
    [DopolnitelnoG]                                             NVARCHAR (150) NULL,
    [AnastamozG]                                                INT            NULL,
    [PolostLukovitsiDeformirovana]                              NVARCHAR (1)   NULL,
    [DlyaTubusaDPK]                                             INT            NULL,
    [SlizistayaLukovitsi12PerstnoyKishki]                       INT            NULL,
    [LokalizatsiyaDPK]                                          INT            NULL,
    [Lokalizatsiya2]                                            INT            NULL,
    [PokritaDPK]                                                INT            NULL,
    [Krovoizliyaniya]                                           NVARCHAR (1)   NULL,
    [VidKrovoizliyaniya]                                        INT            NULL,
    [KolichestvoKrov]                                           INT            NULL,
    [OchagovieErozii]                                           NVARCHAR (1)   NULL,
    [KolichestvoErozii]                                         INT            NULL,
    [SlizistayaNachalnihOtdelov12PerstnoyKishki]                INT            NULL,
    [LokalizatsiyaSlizistayaDPK]                                INT            NULL,
    [LokalizatsiyaSlizistayaDPK1]                               INT            NULL,
    [PokritaSlizistayaDPK]                                      INT            NULL,
    [Opredelyaetsya]                                            INT            NULL,
    [LokalizatsiyaYazvaPolipDPK]                                INT            NULL,
    [NaFoneDeformatsiiLukovitsi]                                NVARCHAR (1)   NULL,
    [RazmeramiDPK]                                              FLOAT (53)     NULL,
    [RazmeramiDPK1]                                             FLOAT (53)     NULL,
    [RazmeramiDPK2]                                             FLOAT (53)     NULL,
    [DnoDPK]                                                    INT            NULL,
    [PokritoDPK]                                                INT            NULL,
    [KrayaDPK]                                                  INT            NULL,
    [VoVremyaOsmotraDPK]                                        INT            NULL,
    [FormaG1]                                                   INT            NULL,
    [Bulbit]                                                    INT            NULL,
    [Duodeniti]                                                 INT            NULL,
    [DivertikuliDPK]                                            INT            NULL,
    [YazvaDPK]                                                  INT            NULL,
    [RubtsovayaDeformatsiyaDPK]                                 INT            NULL,
    [DopolnitelnoDPK]                                           NVARCHAR (150) NULL,
    [LokalizatsiyaBulbit]                                       INT            NULL,
    [LokalizatsiyaDuodenitDPK]                                  INT            NULL,
    [LokalizatsiyaDivertikulitDPK]                              INT            NULL,
    [VpervieViyavlenniyBolnoy]                                  NVARCHAR (1)   NULL,
    [RekomenduetsyaEndoskopicheskayaPolipektomiya]              NVARCHAR (1)   NULL,
    [ZamechaniyaDlyaVrachaGistologa]                            NTEXT          NULL,
    [Rekomendatsii]                                             NTEXT          NULL,
    [DopolnitelnieDannieUzi]                                    NTEXT          NULL,
    [Image]                                                     IMAGE          NULL,
    [Zaklyuchenie]                                              NTEXT          NULL,
    CONSTRAINT [FgsPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FgsToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

