CREATE TABLE [dbo].[Formadla001u] (
    [ID]                                INT            NOT NULL,
    [PatID]                             INT            NULL,
    [Uchrezhdenie1]                     NVARCHAR (100) NULL,
    [CardNum]                           INT            NULL,
    [Otmetka]                           NVARCHAR (50)  NULL,
    [Primechanie]                       NTEXT          NULL,
    [DataPerevoda]                      DATETIME       NULL,
    [BirthDate]                         DATETIME       NULL,
    [SecondName]                        NVARCHAR (20)  NULL,
    [FirstName]                         NVARCHAR (20)  NULL,
    [LastName]                          NVARCHAR (20)  NULL,
    [NomerTelefona]                     NVARCHAR (20)  NULL,
    [AddPatAddress]                     NVARCHAR (200) NULL,
    [Дата]                              DATETIME       NULL,
    [Время]                             DATETIME       NULL,
    [Uchrezhdenie]                      NVARCHAR (50)  NULL,
    [IshodObrasheniya]                  NVARCHAR (50)  NULL,
    [IshodObrasheniya1]                 NVARCHAR (50)  NULL,
    [NeBilGospitalizirovan]             INT            NULL,
    [OtkazVPriMe]                       NVARCHAR (50)  NULL,
    [PrichinaIPrinyatieMeri]            NTEXT          NULL,
    [DiagnozNapravivshegoUchrezhdeniya] NVARCHAR (80)  NULL,
    [Datasoob]                          DATETIME       NULL,
    [PatAddress]                        NVARCHAR (100) NULL,
    [Otdelenie]                         INT            NULL,
    [Автор]                             INT            NULL,
    CONSTRAINT [Formadla001uPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [Formadla001uToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

