CREATE TABLE [dbo].[Forma090] (
    [ID]                         INT            NOT NULL,
    [PatID]                      INT            NULL,
    [Muzhskoy]                   NVARCHAR (1)   NULL,
    [Zensky]                     NVARCHAR (1)   NULL,
    [NeOpredelen]                NVARCHAR (1)   NULL,
    [Goroda]                     NVARCHAR (1)   NULL,
    [Sela]                       NVARCHAR (1)   NULL,
    [ProffesionalnayaGruppa]     NVARCHAR (50)  NULL,
    [DataRozdeniya]              DATETIME       NULL,
    [DataPervogoObrasenia]       DATETIME       NULL,
    [DataUstanovleniyaDiagnoza]  DATETIME       NULL,
    [NomerOpuholi]               INT            NULL,
    [LokalizaciaOpuholi]         NTEXT          NULL,
    [MorfologiceskiyTipOpuholi]  NTEXT          NULL,
    [T]                          NVARCHAR (50)  NULL,
    [N]                          NVARCHAR (50)  NULL,
    [M]                          NVARCHAR (50)  NULL,
    [IA]                         NVARCHAR (1)   NULL,
    [Ib]                         NVARCHAR (1)   NULL,
    [IC]                         NVARCHAR (1)   NULL,
    [IStadiya]                   NVARCHAR (1)   NULL,
    [IIStadiya]                  NVARCHAR (1)   NULL,
    [IIC]                        NVARCHAR (1)   NULL,
    [IIA]                        NVARCHAR (1)   NULL,
    [IIB]                        NVARCHAR (1)   NULL,
    [IIIA]                       NVARCHAR (1)   NULL,
    [IIIB]                       NVARCHAR (1)   NULL,
    [IIIC]                       NVARCHAR (1)   NULL,
    [IIIStadiya]                 NVARCHAR (1)   NULL,
    [IVA]                        NVARCHAR (1)   NULL,
    [IVB]                        NVARCHAR (1)   NULL,
    [IVC]                        NVARCHAR (1)   NULL,
    [IVStadiya]                  NVARCHAR (1)   NULL,
    [INSitu]                     NVARCHAR (1)   NULL,
    [NePrimenimo]                NVARCHAR (1)   NULL,
    [NeIzvestno]                 NVARCHAR (1)   NULL,
    [NeIzvestno16]               NVARCHAR (1)   NULL,
    [OtdalennieLimfUzli]         NVARCHAR (1)   NULL,
    [Pochki]                     NVARCHAR (1)   NULL,
    [Kosti]                      NVARCHAR (1)   NULL,
    [Pechen]                     NVARCHAR (1)   NULL,
    [LegkiePlerva]               NVARCHAR (1)   NULL,
    [GolovnoyMozg]               NVARCHAR (1)   NULL,
    [Kozha]                      NVARCHAR (1)   NULL,
    [Yaichniki]                  NVARCHAR (1)   NULL,
    [Bryushina]                  NVARCHAR (1)   NULL,
    [KostniyMozg]                NVARCHAR (1)   NULL,
    [DrugieOrgani]               NVARCHAR (1)   NULL,
    [Mnozhestvennie]             NVARCHAR (1)   NULL,
    [NeIzvestna]                 NVARCHAR (1)   NULL,
    [Morfologicheskiy]           NVARCHAR (1)   NULL,
    [Tsitologicheskiy]           NVARCHAR (1)   NULL,
    [EksplorativnayaOperatsiya]  NVARCHAR (1)   NULL,
    [LaboratornoInstrumentalniy] NVARCHAR (1)   NULL,
    [TolkoKlinicheskiy]          NVARCHAR (1)   NULL,
    [NeIzvestno18]               NVARCHAR (1)   NULL,
    [ObratilsyaSam]              NVARCHAR (1)   NULL,
    [AktivnoPriProfosmotre]      NVARCHAR (1)   NULL,
    [AktivnoVSmotrovomKabinete]  NVARCHAR (1)   NULL,
    [PriDrugihObstoyatelstvah]   NVARCHAR (1)   NULL,
    [PosmertnoPriAutopsii]       NVARCHAR (1)   NULL,
    [PosmertnoBezAutopsii]       NVARCHAR (1)   NULL,
    [Neizvestno19]               NVARCHAR (1)   NULL,
    [DataZapolneniya]            DATETIME       NULL,
    [TelefonVracha]              NVARCHAR (50)  NULL,
    [DictCombo1]                 NVARCHAR (50)  NULL,
    [NapravlenV]                 NVARCHAR (100) NULL,
    [ZapolnenoV]                 NVARCHAR (100) NULL,
    [NapravlenoV]                NVARCHAR (100) NULL,
    [EditBox1]                   NVARCHAR (50)  NULL,
    CONSTRAINT [Forma090PrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [Forma090ToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

