CREATE TABLE [dbo].[Form] (
    [ID]                  INT            NOT NULL,
    [TypeID]              INT            NULL,
    [GroupID]             INT            NULL,
    [Name]                NVARCHAR (200) NULL,
    [Security]            TINYINT        NULL,
    [TableName]           NVARCHAR (100) NULL,
    [Data]                IMAGE          NULL,
    [Hidden]              BIT            NULL,
    [MasterID]            INT            NULL,
    [Color]               INT            NULL,
    [FontColor]           INT            NULL,
    [UseColors]           BIT            NULL,
    [IsTemplate]          BIT            NULL,
    [Comment]             NTEXT          NULL,
    [System]              BIT            NULL,
    [LinkID]              INT            NULL,
    [OrderPos]            SMALLINT       NULL,
    [Status]              INT            NULL,
    [StatusDate]          DATETIME       NULL,
    [StatusUserName]      NVARCHAR (50)  NULL,
    [StatusNotes]         NTEXT          NULL,
    [UserCreate]          NVARCHAR (50)  NULL,
    [DateCreate]          DATETIME       NULL,
    [UserUpdate]          NVARCHAR (50)  NULL,
    [DateUpdate]          DATETIME       NULL,
    [GUID]                NVARCHAR (32)  NULL,
    [MasterGUID]          NVARCHAR (32)  NULL,
    [LinkGUID]            NVARCHAR (32)  NULL,
    [DuplicationsAllowed] INT            NULL,
    [DuplicationString]   NVARCHAR (250) NULL,
    [Sign1]               NVARCHAR (60)  NULL,
    [Sign2]               NVARCHAR (60)  NULL,
    [Sign3]               NVARCHAR (60)  NULL,
    [SolutionGUID]        NVARCHAR (32)  NULL,
    [NameSystem]          VARCHAR (50)   NULL,
    [TypeGUID]            NVARCHAR (32)  NULL,
    [RootGUID]            NVARCHAR (32)  NULL,
    [MetaXML]             NTEXT          NULL,
    CONSTRAINT [PK_Form] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PK_Form_2] UNIQUE NONCLUSTERED ([GUID] ASC)
);

