CREATE TABLE [dbo].[Forma0272] (
    [ID]                                                 INT            NOT NULL,
    [PatID]                                              INT            NULL,
    [DataRozdeniya]                                      DATETIME       NULL,
    [Muzhskoy]                                           NVARCHAR (1)   NULL,
    [Zensky]                                             NVARCHAR (1)   NULL,
    [NeOpredelen]                                        NVARCHAR (1)   NULL,
    [LokalizaciaOpuholi]                                 NTEXT          NULL,
    [MorfologiceskiyTipOpuholi]                          NTEXT          NULL,
    [T]                                                  NVARCHAR (50)  NULL,
    [N]                                                  NVARCHAR (50)  NULL,
    [M]                                                  NVARCHAR (50)  NULL,
    [IIIA]                                               NVARCHAR (1)   NULL,
    [IIIB]                                               NVARCHAR (1)   NULL,
    [IIIC]                                               NVARCHAR (1)   NULL,
    [IIIStadiya]                                         NVARCHAR (1)   NULL,
    [IVStadiya]                                          NVARCHAR (1)   NULL,
    [CheckBox1]                                          NVARCHAR (1)   NULL,
    [IVB]                                                NVARCHAR (1)   NULL,
    [IVA]                                                NVARCHAR (1)   NULL,
    [NeIzvestno16]                                       NVARCHAR (1)   NULL,
    [NePrimenimo]                                        NVARCHAR (1)   NULL,
    [OtdalennieLimfUzli]                                 NVARCHAR (1)   NULL,
    [Kosti]                                              NVARCHAR (1)   NULL,
    [Pechen]                                             NVARCHAR (1)   NULL,
    [LegkiePlerva]                                       NVARCHAR (1)   NULL,
    [GolovnoyMozg]                                       NVARCHAR (1)   NULL,
    [Bryushina]                                          NVARCHAR (1)   NULL,
    [KostniyMozg]                                        NVARCHAR (1)   NULL,
    [Yaichniki]                                          NVARCHAR (1)   NULL,
    [Pochki]                                             NVARCHAR (1)   NULL,
    [Kozha]                                              NVARCHAR (1)   NULL,
    [DrugieOrgani]                                       NVARCHAR (1)   NULL,
    [Mnozhestvennie]                                     NVARCHAR (1)   NULL,
    [NeIzvestna]                                         NVARCHAR (1)   NULL,
    [Morfologicheskiy]                                   NVARCHAR (1)   NULL,
    [Tsitologicheskiy]                                   NVARCHAR (1)   NULL,
    [EksplorativnayaOperatsiya]                          NVARCHAR (1)   NULL,
    [NeIzvestno18]                                       NVARCHAR (1)   NULL,
    [TolkoKlinicheskiy]                                  NVARCHAR (1)   NULL,
    [LaboratornoInstrumentalniy]                         NVARCHAR (1)   NULL,
    [DataUstanovleniyaZapushenosti]                      DATETIME       NULL,
    [DataPoyavleniyaPriznakovZabolenanya]                DATETIME       NULL,
    [DataPervogoObrasheniya]                             DATETIME       NULL,
    [NazvanieLpu]                                        NVARCHAR (100) NULL,
    [AdresLpu]                                           NVARCHAR (100) NULL,
    [DataPervichnogoDiagnoza]                            DATETIME       NULL,
    [AdresLpuPer]                                        NVARCHAR (100) NULL,
    [NazvanieLpuPerv]                                    NVARCHAR (100) NULL,
    [PricinyPozdneyDiagnostkiki]                         NVARCHAR (50)  NULL,
    [DannieKlinicheskogoRazbora]                         NTEXT          NULL,
    [NaimenovanieUchrezhdeniyaGdeProvedenaKonferentsiya] NVARCHAR (100) NULL,
    [DataKonferentsii]                                   DATETIME       NULL,
    [OrganizatsionnieVivodi]                             NTEXT          NULL,
    [DataSostavleniyaProtokola]                          DATETIME       NULL,
    CONSTRAINT [Forma0272PrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [Forma0272ToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

