CREATE TABLE [dbo].[forma001] (
    [ID]                     INT            NOT NULL,
    [PatID]                  INT            NULL,
    [Uchrezhdenie1]          NVARCHAR (200) NULL,
    [CardNum]                NVARCHAR (50)  NULL,
    [Otmetka]                NVARCHAR (50)  NULL,
    [Primechanie]            NTEXT          NULL,
    [DataPerevoda]           DATETIME       NULL,
    [BirthDate]              DATETIME       NULL,
    [SecondName]             NVARCHAR (20)  NULL,
    [FirstName]              NVARCHAR (20)  NULL,
    [LastName]               NVARCHAR (20)  NULL,
    [NomerTelefona]          NVARCHAR (20)  NULL,
    [AddPatAddress]          NVARCHAR (200) NULL,
    [Дата]                   DATETIME       NULL,
    [Время]                  DATETIME       NULL,
    [Uchrezhdenie]           NTEXT          NULL,
    [IshodObrasheniya]       INT            NULL,
    [IshodObrasheniya1]      NVARCHAR (50)  NULL,
    [NeBilGospitalizirovan]  INT            NULL,
    [OtkazVPriMe]            NVARCHAR (50)  NULL,
    [PrichinaIPrinyatieMeri] NTEXT          NULL,
    [Datasoob]               DATETIME       NULL,
    [PatAddress]             NVARCHAR (100) NULL,
    [Otdelenie]              INT            NULL,
    [Автор]                  INT            NULL,
    [DiagNapravl]            NVARCHAR (6)   NULL,
    [DiagNapravlName]        NVARCHAR (255) NULL,
    [Uchrezhdenie2]          NVARCHAR (100) NULL,
    [NomNapr]                INT            NULL,
    [DataNapr]               DATETIME       NULL,
    [KemNapr]                NVARCHAR (50)  NULL,
    [VrachNapr]              INT            NULL,
    [MOnapr]                 INT            NULL,
    [IstFin]                 INT            NULL,
    [MOnapr_podr]            INT            NULL,
    CONSTRAINT [forma001PrimKey] PRIMARY KEY CLUSTERED ([ID] ASC)
);

