CREATE TABLE [dbo].[FRep_UnitedOperationReport] (
    [GUID]                                      UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [ReportID]                                  INT              NULL,
    [ConnectionID]                              INT              NULL,
    [Дата оказания услуги]                      DATETIME         NULL,
    [ФИО мед. работника]                        NVARCHAR (100)   NULL,
    [Наименование специальности мед. работника] NVARCHAR (100)   NULL,
    [ФИО пациента]                              NVARCHAR (250)   NULL,
    [Дата рождения]                             DATETIME         NULL,
    [Возраст]                                   NVARCHAR (20)    NULL,
    [Пол]                                       NVARCHAR (10)    NULL,
    [Наименование контрагента]                  NVARCHAR (MAX)   NULL,
    [Номер договора]                            NVARCHAR (100)   NULL,
    [Дата договора]                             DATETIME         NULL,
    [Доп. соглашения №]                         NVARCHAR (100)   NULL,
    [Дата заключения доп. соглашения]           DATETIME         NULL,
    [Наименование программы]                    NVARCHAR (MAX)   NULL,
    [Дата прикрепления]                         DATETIME         NULL,
    [Дата открепления]                          DATETIME         NULL,
    [Канал продаж]                              NVARCHAR (20)    NULL,
    [Код услуги]                                NVARCHAR (100)   NULL,
    [Наименование услуги]                       NVARCHAR (MAX)   NULL,
    [Вид оплаты]                                NVARCHAR (50)    NULL,
    [Кол-во услуг]                              FLOAT (53)       NULL,
    [Цена за 1-ну услугу]                       MONEY            NULL,
    [Стоимость оказанных услуг]                 MONEY            NULL,
    CONSTRAINT [FRep_UnitedOperationReportPrimKey] PRIMARY KEY CLUSTERED ([GUID] ASC),
    CONSTRAINT [FRep_UnitedOperationReportToConsolidatedReport] FOREIGN KEY ([ReportID]) REFERENCES [dbo].[ConsolidatedReport] ([ID]) ON DELETE CASCADE
);

