CREATE TABLE [dbo].[FunktsiyaVneshnegoDihaniya] (
    [ID]           INT           NOT NULL,
    [PatID]        INT           NULL,
    [Data]         DATETIME      NULL,
    [Vrach]        NVARCHAR (50) NULL,
    [Rost]         INT           NULL,
    [Ves]          INT           NULL,
    [Pol]          NVARCHAR (50) NULL,
    [PosleProbiS]  NVARCHAR (50) NULL,
    [Chastota]     INT           NULL,
    [Glubina]      NVARCHAR (50) NULL,
    [Zhel]         INT           NULL,
    [Zhel2]        INT           NULL,
    [Zhel1]        INT           NULL,
    [Zhel4]        INT           NULL,
    [Zhel3]        INT           NULL,
    [Mod]          INT           NULL,
    [Fzhel]        INT           NULL,
    [Ofv1]         INT           NULL,
    [Mos25]        INT           NULL,
    [Mos50]        INT           NULL,
    [Mos75]        INT           NULL,
    [Ofv1Fzhel]    INT           NULL,
    [Mod1]         INT           NULL,
    [Fzhel1]       INT           NULL,
    [Ofv11]        INT           NULL,
    [Mos251]       INT           NULL,
    [Mos501]       INT           NULL,
    [Mos751]       INT           NULL,
    [Ofv1Fzhel1]   INT           NULL,
    [Mod2]         INT           NULL,
    [Fzhel2]       INT           NULL,
    [Ofv12]        INT           NULL,
    [Mos252]       INT           NULL,
    [Mos502]       INT           NULL,
    [Mos752]       INT           NULL,
    [Ofv1Fzhel2]   INT           NULL,
    [Mod3]         INT           NULL,
    [Fzhel3]       INT           NULL,
    [Ofv14]        INT           NULL,
    [Mos253]       INT           NULL,
    [Mos503]       INT           NULL,
    [Mos753]       INT           NULL,
    [Ofv1Fzhel3]   INT           NULL,
    [Mod4]         INT           NULL,
    [Fzhel4]       INT           NULL,
    [Ofv13]        INT           NULL,
    [Mos254]       INT           NULL,
    [Mos504]       INT           NULL,
    [Mos754]       INT           NULL,
    [Ofv1Fzhel4]   INT           NULL,
    [Zaklyuchenie] NTEXT         NULL,
    [Primechaniya] NTEXT         NULL,
    CONSTRAINT [FunktsiyaVneshnegoDihaniyaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FunktsiyaVneshnegoDihaniyaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

