CREATE TABLE [dbo].[GinekologicheskoeUzi] (
    [ID]                                                                INT           NOT NULL,
    [PatID]                                                             INT           NULL,
    [VidIssledovaniya]                                                  INT           NULL,
    [MatkaV]                                                            INT           NULL,
    [RazmerMatki]                                                       INT           NULL,
    [DlinaTela]                                                         FLOAT (53)    NULL,
    [ShirinaTela]                                                       FLOAT (53)    NULL,
    [TolshinaTela]                                                      FLOAT (53)    NULL,
    [Matka]                                                             INT           NULL,
    [Raspolozhenie]                                                     INT           NULL,
    [KonturMatki]                                                       INT           NULL,
    [Chetkosst]                                                         INT           NULL,
    [EhoStrukturaMiometriya]                                            INT           NULL,
    [EhoPlotnost]                                                       INT           NULL,
    [DopolnitelnieObrazovaniyaVMiometrii]                               NVARCHAR (1)  NULL,
    [MEho]                                                              INT           NULL,
    [RazmeriM]                                                          FLOAT (53)    NULL,
    [Neodnorodnoe]                                                      NVARCHAR (1)  NULL,
    [SootvetstvuetDnyuMenstrualnogoTsikla]                              NVARCHAR (1)  NULL,
    [NeSootvetstvuetFazeMenstrualnogoTsikla]                            NVARCHAR (1)  NULL,
    [Deformirovano]                                                     NVARCHAR (1)  NULL,
    [Smeshenie]                                                         NVARCHAR (1)  NULL,
    [EhoGennost]                                                        INT           NULL,
    [VProektsiiMEhoOpredelyayutsyaDopolnitelnieObrazovaniya]            NVARCHAR (1)  NULL,
    [PolostMatki]                                                       INT           NULL,
    [Raspolozhena]                                                      INT           NULL,
    [VPolostiMatkiDvoynoeDno]                                           NVARCHAR (1)  NULL,
    [SEmbrionom]                                                        NVARCHAR (1)  NULL,
    [Diametrom]                                                         FLOAT (53)    NULL,
    [VPolostiMatkiVms]                                                  NVARCHAR (1)  NULL,
    [Endometriy]                                                        INT           NULL,
    [NomerIssledovaniya]                                                INT           NULL,
    [Data]                                                              DATETIME      NULL,
    [VKolichestve]                                                      INT           NULL,
    [OkrugloyFormi]                                                     NVARCHAR (1)  NULL,
    [TolshinaTela1]                                                     FLOAT (53)    NULL,
    [AkusticheskayaTen]                                                 NVARCHAR (1)  NULL,
    [Matka2]                                                            INT           NULL,
    [VVideGiperehogennihVklyucheniy]                                    NVARCHAR (1)  NULL,
    [NeVizualiziruetsya]                                                NVARCHAR (1)  NULL,
    [Otsutstvuet]                                                       NVARCHAR (1)  NULL,
    [Uvelichen]                                                         NVARCHAR (1)  NULL,
    [VProektsiiYaichnikaLotsiruetsyaZhidkostnoeAnehogennoeObrazovanie]  NVARCHAR (1)  NULL,
    [IntaktniyYaichnik]                                                 NVARCHAR (1)  NULL,
    [RazmeriYaichnik]                                                   NVARCHAR (50) NULL,
    [RazmeriYaichnik1]                                                  NVARCHAR (50) NULL,
    [RazmeriYaichnik2]                                                  NVARCHAR (50) NULL,
    [KonturiYaichnik]                                                   INT           NULL,
    [EhoStrukturaYaichnik]                                              INT           NULL,
    [Follikul]                                                          INT           NULL,
    [KapsulaYaichnika]                                                  INT           NULL,
    [DiametrYaichnik]                                                   FLOAT (53)    NULL,
    [EhoPlotnostYaichnik]                                               INT           NULL,
    [ChetkostYaichnik]                                                  INT           NULL,
    [KolichestvoKamer]                                                  INT           NULL,
    [RazmerYaichnikDO]                                                  FLOAT (53)    NULL,
    [RazmerYaichnikDO1]                                                 NVARCHAR (50) NULL,
    [RazmerYaichnikDO2]                                                 NVARCHAR (50) NULL,
    [STonkoyKapsuloy]                                                   NVARCHAR (1)  NULL,
    [SNalichiemPristenochnogoKomponenta]                                NVARCHAR (1)  NULL,
    [VProektsiiYaichnikaLotsiruetsyaObrazovanie]                        NVARCHAR (1)  NULL,
    [StrukturaObrazovaniyaYaichnik]                                     INT           NULL,
    [VProektsiiYaichnikaLotsiruetsyaSolidnoeObrazovane]                 NVARCHAR (1)  NULL,
    [PonizhennoyPlotnosti]                                              NVARCHAR (1)  NULL,
    [KonturiYaichnikDO]                                                 INT           NULL,
    [RazmerYaichnikDO6]                                                 FLOAT (53)    NULL,
    [RazmerYaichnikDO7]                                                 NVARCHAR (50) NULL,
    [RazmerYaichnikDO8]                                                 NVARCHAR (50) NULL,
    [RazmerYaichnikDO5]                                                 NVARCHAR (50) NULL,
    [RazmerYaichnikDO4]                                                 NVARCHAR (50) NULL,
    [RazmerYaichnikDO3]                                                 FLOAT (53)    NULL,
    [NeVizualiziruetsyaL]                                               NVARCHAR (1)  NULL,
    [OtsutstvuetL]                                                      NVARCHAR (1)  NULL,
    [UvelichenL]                                                        NVARCHAR (1)  NULL,
    [VProektsiiYaichnikaLotsiruetsyaZhidkostnoeAnehogennoeObrazovanieL] NVARCHAR (1)  NULL,
    [IntaktniyYaichnikL]                                                NVARCHAR (1)  NULL,
    [RazmeriYaichnikL]                                                  NVARCHAR (50) NULL,
    [KonturiYaichnikL]                                                  INT           NULL,
    [EhoStrukturaYaichnikL]                                             INT           NULL,
    [KapsulaYaichnikaL]                                                 INT           NULL,
    [RazmeriYaichnik1L]                                                 NVARCHAR (50) NULL,
    [RazmeriYaichnik2L]                                                 NVARCHAR (50) NULL,
    [ChetkostYaichnikL]                                                 INT           NULL,
    [EhoPlotnostYaichnikL]                                              INT           NULL,
    [DiametrYaichnikL]                                                  FLOAT (53)    NULL,
    [FollikulL]                                                         INT           NULL,
    [KolichestvoKamerL]                                                 INT           NULL,
    [STonkoyKapsuloyL]                                                  NVARCHAR (1)  NULL,
    [SNalichiemPristenochnogoKomponentaL]                               NVARCHAR (1)  NULL,
    [VProektsiiYaichnikaLotsiruetsyaObrazovanieL]                       NVARCHAR (1)  NULL,
    [RazmerYaichnikDOL]                                                 FLOAT (53)    NULL,
    [RazmerYaichnikDO1L]                                                NVARCHAR (50) NULL,
    [RazmerYaichnikDO2L]                                                NVARCHAR (50) NULL,
    [StrukturaObrazovaniyaYaichnikL]                                    INT           NULL,
    [RazmerYaichnikDO3L]                                                FLOAT (53)    NULL,
    [RazmerYaichnikDO4L]                                                NVARCHAR (50) NULL,
    [RazmerYaichnikDO5L]                                                NVARCHAR (50) NULL,
    [VProektsiiYaichnikaLotsiruetsyaSolidnoeObrazovaneL]                NVARCHAR (1)  NULL,
    [PonizhennoyPlotnostiL]                                             NVARCHAR (1)  NULL,
    [KonturiYaichnikDOL]                                                INT           NULL,
    [RazmerYaichnikDO6L]                                                FLOAT (53)    NULL,
    [RazmerYaichnikDO7L]                                                NVARCHAR (50) NULL,
    [RazmerYaichnikDO8L]                                                NVARCHAR (50) NULL,
    [Diametr]                                                           INT           NULL,
    [VEeProektsiiObrazovanie]                                           NVARCHAR (1)  NULL,
    [ImeetsyaPristenochniyKomponent]                                    NVARCHAR (1)  NULL,
    [DiametrL]                                                          INT           NULL,
    [VEeProektsiiObrazovanieL]                                          NVARCHAR (1)  NULL,
    [ImeetsyaPristenochniyKomponentL]                                   NVARCHAR (1)  NULL,
    [UgolMezhduSheykoyIMatkoy]                                          INT           NULL,
    [FormaSheykaMatki]                                                  INT           NULL,
    [EhoStrukturaSheykaMatki]                                           INT           NULL,
    [RazmeriSheykaMatki]                                                INT           NULL,
    [KonturiSheykaMatki]                                                INT           NULL,
    [DopolnitelnoeObrazovanie]                                          NVARCHAR (1)  NULL,
    [AnehogennoeObrazovanie]                                            NVARCHAR (1)  NULL,
    [DopolnitelnoeObrazovanieVlagalishe]                                NVARCHAR (1)  NULL,
    [SAnomaliyamiRazvitiya]                                             NVARCHAR (1)  NULL,
    [UdovletvoritelnogoNapolneniya]                                     NVARCHAR (1)  NULL,
    [KolichestvoSheykaMatki]                                            INT           NULL,
    [EhoPlotnostSheykaMatki]                                            INT           NULL,
    [Razmerami]                                                         FLOAT (53)    NULL,
    [Razmerami1]                                                        FLOAT (53)    NULL,
    [Razmerami2]                                                        FLOAT (53)    NULL,
    [EhoStrukturaSheykaMatkiDO]                                         INT           NULL,
    [KolichestvoSheykaMatkiDO]                                          INT           NULL,
    [RazmeramiSheykaMatkiDO]                                            FLOAT (53)    NULL,
    [RazmeramiSheykaMatkiDO1]                                           FLOAT (53)    NULL,
    [RazmeramiSheykaMatkiDO2]                                           FLOAT (53)    NULL,
    [KolichestvoVlagalishe]                                             INT           NULL,
    [FormaVlagalishe]                                                   INT           NULL,
    [KonturiVlagalishe]                                                 INT           NULL,
    [StrukturaObrazovaniyaVlagalishe]                                   INT           NULL,
    [Vrach]                                                             NVARCHAR (50) NULL,
    [DopolnitelnieDannieUzi]                                            NTEXT         NULL,
    [Zaklyuchenie]                                                      INT           NULL,
    [Rekomendovano]                                                     INT           NULL,
    [Image]                                                             IMAGE         NULL,
    [DannieNaPechat]                                                    NTEXT         NULL,
    [Data2]                                                             DATETIME      NULL,
    CONSTRAINT [GinekologicheskoeUziPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [GinekologicheskoeUziToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

