CREATE TABLE [dbo].[GormonalnoeIssledovanie] (
    [ID]                          INT        NOT NULL,
    [PatID]                       INT        NULL,
    [NomerAnaliza1]               INT        NULL,
    [DataProvedeniyaAnaliza]      DATETIME   NULL,
    [VMoche17Oksikortikosteroidi] FLOAT (53) NULL,
    [VKrovi17Oksikortikosteroidi] FLOAT (53) NULL,
    [Des]                         FLOAT (53) NULL,
    [Testosteron]                 FLOAT (53) NULL,
    [Progesteron]                 FLOAT (53) NULL,
    [Estradiol]                   FLOAT (53) NULL,
    [Prolaktin]                   FLOAT (53) NULL,
    [Insulin]                     FLOAT (53) NULL,
    [TireoglobulinTg]             FLOAT (53) NULL,
    [AntitelaKTg]                 FLOAT (53) NULL,
    [T3Obshiy]                    FLOAT (53) NULL,
    [T3Svobodniy]                 FLOAT (53) NULL,
    [T4Svobodniy]                 FLOAT (53) NULL,
    [Ttg]                         FLOAT (53) NULL,
    [Kortizol]                    FLOAT (53) NULL,
    [Fsg]                         FLOAT (53) NULL,
    [Lg]                          FLOAT (53) NULL,
    [Aktg]                        FLOAT (53) NULL,
    [T4Obshiy]                    FLOAT (53) NULL,
    [Adrenalin]                   FLOAT (53) NULL,
    [Dofa]                        FLOAT (53) NULL,
    [Dofamin]                     FLOAT (53) NULL,
    [Vrach]                       INT        NULL,
    CONSTRAINT [GormonalnoeIssledovaniePrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [GormonalnoeIssledovanieToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

