CREATE TABLE [dbo].[Gyn1App] (
    [Id]                         INT            NOT NULL,
    [PatId]                      INT            NULL,
    [Descr]                      VARCHAR (150)  NULL,
    [ExecDate]                   DATETIME       NULL,
    [Badies]                     NTEXT          NULL,
    [BadiesP]                    NTEXT          NULL,
    [AccIllP]                    NTEXT          NULL,
    [AccIll]                     NTEXT          NULL,
    [Allergy]                    NTEXT          NULL,
    [AllRe]                      NTEXT          NULL,
    [GynIll]                     NTEXT          NULL,
    [Opers]                      NTEXT          NULL,
    [Histo]                      NTEXT          NULL,
    [MarLen]                     VARCHAR (15)   NULL,
    [WOPres]                     VARCHAR (5)    NULL,
    [ChildM]                     VARCHAR (255)  NULL,
    [ChildW]                     VARCHAR (255)  NULL,
    [PChildM1]                   NVARCHAR (50)  NULL,
    [PChildW1]                   NVARCHAR (50)  NULL,
    [PChildM2]                   INT            NULL,
    [PChildW2]                   INT            NULL,
    [PChildM3]                   INT            NULL,
    [PChildW3]                   INT            NULL,
    [PChildM4]                   INT            NULL,
    [PChildW4]                   INT            NULL,
    [ASterType]                  INT            NULL,
    [APreg1]                     INT            NULL,
    [APreg2]                     INT            NULL,
    [SterType]                   NVARCHAR (50)  NULL,
    [SterTypeDescr]              VARCHAR (150)  NULL,
    [Preg1]                      INT            NULL,
    [Preg2]                      INT            NULL,
    [Accouch]                    INT            NULL,
    [Ceasar]                     INT            NULL,
    [Aborts]                     INT            NULL,
    [Slink]                      INT            NULL,
    [SlinkAge]                   VARCHAR (255)  NULL,
    [Ect]                        INT            NULL,
    [Died]                       INT            NULL,
    [DiedAge]                    INT            NULL,
    [DiedComment]                NTEXT          NULL,
    [MensCycle]                  VARCHAR (50)   NULL,
    [PMS]                        VARCHAR (10)   NULL,
    [LMP]                        DATETIME       NULL,
    [DayMC]                      INT            NULL,
    [MCComment]                  VARCHAR (150)  NULL,
    [SterFac_1]                  BIT            NULL,
    [SterFac_2]                  BIT            NULL,
    [SterFac_3]                  BIT            NULL,
    [SterFac_4]                  BIT            NULL,
    [SterFac_5]                  BIT            NULL,
    [SterFac_6]                  BIT            NULL,
    [SterFac_7]                  BIT            NULL,
    [SterFac_8]                  BIT            NULL,
    [SterFac_9]                  BIT            NULL,
    [SterFac_10]                 BIT            NULL,
    [SterFacOther]               NTEXT          NULL,
    [SterFac1Id]                 INT            NULL,
    [SterFac2Id]                 INT            NULL,
    [SterFac3Id]                 INT            NULL,
    [SterFac4Id]                 INT            NULL,
    [SterFac5]                   BIT            NULL,
    [SterFac6]                   BIT            NULL,
    [OrgansState]                NTEXT          NULL,
    [SpermExecDate]              DATETIME       NULL,
    [Sperm1]                     VARCHAR (10)   NULL,
    [Sperm2]                     VARCHAR (10)   NULL,
    [Sperm3]                     VARCHAR (10)   NULL,
    [Sperm4]                     VARCHAR (10)   NULL,
    [Sperm5]                     VARCHAR (10)   NULL,
    [Sperm6]                     VARCHAR (10)   NULL,
    [SpermComment]               NTEXT          NULL,
    [Height]                     INT            NULL,
    [Weight]                     INT            NULL,
    [Girsu]                      INT            NULL,
    [Gala]                       INT            NULL,
    [Fat]                        INT            NULL,
    [ImgId]                      IMAGE          NULL,
    [MComment]                   NTEXT          NULL,
    [UZIExecDate]                DATETIME       NULL,
    [UZIDayMC]                   INT            NULL,
    [UZMatrix]                   VARCHAR (255)  NULL,
    [MEHO]                       VARCHAR (15)   NULL,
    [ROvary]                     NVARCHAR (100) NULL,
    [RFoll]                      VARCHAR (15)   NULL,
    [LOvary]                     NVARCHAR (100) NULL,
    [LFoll]                      VARCHAR (15)   NULL,
    [UZComment]                  NTEXT          NULL,
    [ResResult]                  NTEXT          NULL,
    [RGraph]                     NTEXT          NULL,
    [MRT]                        NTEXT          NULL,
    [Other]                      NTEXT          NULL,
    [Mammo]                      NTEXT          NULL,
    [MammoOperId]                INT            NULL,
    [Endo]                       NTEXT          NULL,
    [EndoOperId]                 INT            NULL,
    [Phys]                       NTEXT          NULL,
    [PhysOperId]                 INT            NULL,
    [Img1Id]                     IMAGE          NULL,
    [KolpoComment]               NTEXT          NULL,
    [Diagnosis]                  NTEXT          NULL,
    [Zakl]                       NTEXT          NULL,
    [Recommendations]            NTEXT          NULL,
    [PayNeed]                    BIT            NULL,
    [Payed]                      BIT            NULL,
    [PaySum]                     MONEY          NULL,
    [PayedSum]                   MONEY          NULL,
    [PayDate]                    DATETIME       NULL,
    [PayComment]                 VARCHAR (255)  NULL,
    [OperId]                     INT            NULL,
    [OriginalID]                 INT            NULL,
    [MensCycle1]                 NVARCHAR (50)  NULL,
    [MensCycle2]                 NVARCHAR (50)  NULL,
    [Predshestvuyushee_Lechenie] NTEXT          NULL,
    [Diagnoz_sop]                NTEXT          NULL,
    [OrgansStateDate]            DATETIME       NULL,
    [AccIll1]                    NTEXT          NULL,
    [AccIllP1]                   NTEXT          NULL,
    [OrgansStateResearch]        NVARCHAR (50)  NULL,
    [AMGConcentration]           FLOAT (53)     NULL,
    [AMGRating]                  NVARCHAR (50)  NULL,
    CONSTRAINT [PK_Gyn1App] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Gyn1App_PatForm] FOREIGN KEY ([Id]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

