CREATE TABLE [dbo].[HairTerapistTounguePuncture] (
    [ID]                 INT           NOT NULL,
    [PatID]              INT           NULL,
    [Procedure]          NVARCHAR (50) NULL,
    [Image]              IMAGE         NULL,
    [None]               NVARCHAR (1)  NULL,
    [Pain]               NVARCHAR (1)  NULL,
    [Itchy]              NVARCHAR (1)  NULL,
    [Weak]               NVARCHAR (1)  NULL,
    [Blocked]            NVARCHAR (1)  NULL,
    [Heat]               NVARCHAR (1)  NULL,
    [Thin]               NVARCHAR (1)  NULL,
    [Wiry]               NVARCHAR (1)  NULL,
    [Empty]              NVARCHAR (1)  NULL,
    [Slippery]           NVARCHAR (1)  NULL,
    [Weak_cb]            NVARCHAR (50) NULL,
    [Blocked_cb]         NVARCHAR (50) NULL,
    [Heat_cb]            NVARCHAR (50) NULL,
    [Thin_cb]            NVARCHAR (50) NULL,
    [Wiry_cb]            NVARCHAR (50) NULL,
    [Slippery_cb]        NVARCHAR (50) NULL,
    [Empty_cb]           NVARCHAR (50) NULL,
    [LIV]                NVARCHAR (1)  NULL,
    [GB]                 NVARCHAR (1)  NULL,
    [PC]                 NVARCHAR (1)  NULL,
    [TH]                 NVARCHAR (1)  NULL,
    [KID]                NVARCHAR (1)  NULL,
    [BL]                 NVARCHAR (1)  NULL,
    [LU]                 NVARCHAR (1)  NULL,
    [CO]                 NVARCHAR (1)  NULL,
    [HT]                 NVARCHAR (1)  NULL,
    [SI]                 NVARCHAR (1)  NULL,
    [CV]                 NVARCHAR (1)  NULL,
    [GV]                 NVARCHAR (1)  NULL,
    [ST]                 NVARCHAR (1)  NULL,
    [SP]                 NVARCHAR (1)  NULL,
    [LIV_cb]             NVARCHAR (50) NULL,
    [GB_cb]              NVARCHAR (50) NULL,
    [PC_cb]              NVARCHAR (50) NULL,
    [TH_cb]              NVARCHAR (50) NULL,
    [KID_cb]             NVARCHAR (50) NULL,
    [BL_cb]              NVARCHAR (50) NULL,
    [LU_cb]              NVARCHAR (50) NULL,
    [CO_cb]              NVARCHAR (50) NULL,
    [HT_cb]              NVARCHAR (50) NULL,
    [SI_cb]              NVARCHAR (50) NULL,
    [CV_cb]              NVARCHAR (50) NULL,
    [GV_cb]              NVARCHAR (50) NULL,
    [ST_cb]              NVARCHAR (50) NULL,
    [SP_cb]              NVARCHAR (50) NULL,
    [PuncturePoints]     NTEXT         NULL,
    [Anamnesis]          NTEXT         NULL,
    [ExaminationResults] NTEXT         NULL,
    [Recommendations]    NTEXT         NULL,
    [DocDate]            DATETIME      NULL,
    [DocTime]            DATETIME      NULL,
    [DoctorID]           INT           NULL,
    CONSTRAINT [HairTerapistTounguePuncturePrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [HairTerapistTounguePunctureToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

