CREATE TABLE [dbo].[HH_UziBeremennoy1014] (
    [ID]             INT            NOT NULL,
    [PatID]          INT            NULL,
    [Vrach]          NVARCHAR (50)  NULL,
    [Data]           DATETIME       NULL,
    [DataMenstr]     DATETIME       NULL,
    [SrokBeremNedel] INT            NULL,
    [PredDataRodov]  DATETIME       NULL,
    [SrokBeremDney]  INT            NULL,
    [VidIssled]      NVARCHAR (20)  NULL,
    [VisualPlod]     NVARCHAR (20)  NULL,
    [KolPlodov]      INT            NULL,
    [RazmerPloda]    INT            NULL,
    [RazmerSootv]    NVARCHAR (20)  NULL,
    [ChastotaSerd]   INT            NULL,
    [TolschVorotn]   INT            NULL,
    [ZheltMeshok]    NVARCHAR (20)  NULL,
    [ZheltDiam]      INT            NULL,
    [LocalizHor]     NVARCHAR (30)  NULL,
    [StructHor]      NVARCHAR (100) NULL,
    [OsobPridatkov]  NVARCHAR (100) NULL,
    [OsobStenok]     NVARCHAR (100) NULL,
    [Zakluchenie]    NVARCHAR (200) NULL,
    [Visualizacia]   NVARCHAR (50)  NULL,
    [Osobennosti]    NVARCHAR (100) NULL,
    [Rekomend]       NVARCHAR (200) NULL,
    [UZContr]        INT            NULL,
    CONSTRAINT [HH_UziBeremennoy1014PrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [HH_UziBeremennoy1014ToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

