CREATE TABLE [dbo].[HH_UziGinekologicheskoe] (
    [ID]                   INT            NOT NULL,
    [PatID]                INT            NULL,
    [Faza]                 NVARCHAR (50)  NULL,
    [Zakluchenie]          NTEXT          NULL,
    [Data]                 DATETIME       NULL,
    [Vrach]                INT            NULL,
    [Matka_Raspol]         NVARCHAR (20)  NULL,
    [RazmeriMatki1]        FLOAT (53)     NULL,
    [RazmeriMatki2]        FLOAT (53)     NULL,
    [RazmeriMatki3]        FLOAT (53)     NULL,
    [Endo_Odnorodn]        NVARCHAR (20)  NULL,
    [Mio_Odnorodn]         NVARCHAR (20)  NULL,
    [Endo_Razm]            FLOAT (53)     NULL,
    [Matka_Raspol_Comment] NVARCHAR (80)  NULL,
    [Uzly]                 NVARCHAR (10)  NULL,
    [Endo_Comment]         NVARCHAR (60)  NULL,
    [Uzly_Comment]         NVARCHAR (250) NULL,
    [RazmerSh1]            FLOAT (53)     NULL,
    [RazmerSh2]            FLOAT (53)     NULL,
    [RazmerSh3]            FLOAT (53)     NULL,
    [Sh_Comment]           NVARCHAR (70)  NULL,
    [Cervikal]             NVARCHAR (40)  NULL,
    [Lev_Ya]               NVARCHAR (50)  NULL,
    [Lev_Ya_Comment]       NVARCHAR (250) NULL,
    [Prav_Ya]              NVARCHAR (50)  NULL,
    [Prav_Ya_Comment]      NVARCHAR (250) NULL,
    [Dop_Data]             NVARCHAR (100) NULL,
    CONSTRAINT [HH_UziGinekologicheskoePrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [HH_UziGinekologicheskoeToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

