CREATE TABLE [dbo].[IfaImmunoflyuoristsentniyAnaliz] (
    [ID]                       INT      NOT NULL,
    [PatID]                    INT      NULL,
    [NomerAnaliza]             INT      NULL,
    [DataProvedeniyaAnaliza]   DATETIME NULL,
    [VirusProstogoGerpesaIgM]  INT      NULL,
    [HSVIIITipIgG]             INT      NULL,
    [TsitomegalovirusIgM]      INT      NULL,
    [CMVIgG]                   INT      NULL,
    [VirusKrasnuhiIgM]         INT      NULL,
    [RubellaIgG]               INT      NULL,
    [VirusProstogoGerpesaIgM6] INT      NULL,
    [VirusProstogoGerpesaIgM7] INT      NULL,
    [HlamidiozIgM]             INT      NULL,
    [ChlamidiaTrahomatisIgG]   INT      NULL,
    [ChlamidiaTrahomatisIgA]   INT      NULL,
    [HominisMikroplazmaIgM]    INT      NULL,
    [MicroplazmaHominisIgG]    INT      NULL,
    [TrihomoniazIgM]           INT      NULL,
    [TrichomatisVaginalisIgG]  INT      NULL,
    [UreaplazmozIgM]           INT      NULL,
    [UreaplazmaUrealyticumIgG] INT      NULL,
    [AntiHelicobacterPylori]   INT      NULL,
    [OpistorhozIgG]            INT      NULL,
    [LyambliozAnti]            INT      NULL,
    [ToksokarozAnti]           INT      NULL,
    [Trihenellez]              INT      NULL,
    [EhinokokkozAnti]          INT      NULL,
    [Vrach]                    INT      NULL,
    CONSTRAINT [IfaImmunoflyuoristsentniyAnalizPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [IfaImmunoflyuoristsentniyAnalizToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

