CREATE TABLE [dbo].[IKR] (
    [ID]         INT           NOT NULL,
    [PatID]      INT           NULL,
    [KODREL]     NVARCHAR (13) NULL,
    [NOMAMB]     NVARCHAR (8)  NULL,
    [NOMERIB]    NVARCHAR (6)  NULL,
    [ITR]        INT           NULL,
    [SNTR]       INT           NULL,
    [IFR]        INT           NULL,
    [SNFR]       INT           NULL,
    [S]          DATETIME      NULL,
    [PO]         DATETIME      NULL,
    [RG]         NVARCHAR (1)  NULL,
    [DATOTCH]    DATETIME      NULL,
    [F24]        FLOAT (53)    NULL,
    [F25]        FLOAT (53)    NULL,
    [CITO]       NVARCHAR (4)  NULL,
    [OLK2]       FLOAT (53)    NULL,
    [OLK3]       INT           NULL,
    [OLK4]       FLOAT (53)    NULL,
    [OLK5]       FLOAT (53)    NULL,
    [OLK6]       FLOAT (53)    NULL,
    [OLK7]       FLOAT (53)    NULL,
    [OLK8]       FLOAT (53)    NULL,
    [OLK9]       FLOAT (53)    NULL,
    [OLK10]      FLOAT (53)    NULL,
    [OSL1KRD]    NVARCHAR (3)  NULL,
    [OSL2KRD]    NVARCHAR (3)  NULL,
    [OSL1]       NVARCHAR (3)  NULL,
    [OSL2]       NVARCHAR (3)  NULL,
    [GPP]        NVARCHAR (1)  NULL,
    [GVPR]       INT           NULL,
    [G]          NVARCHAR (2)  NULL,
    [RecNo]      INT           NULL,
    [ExportTime] DATETIME      NULL,
    CONSTRAINT [IKRPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [IKRToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

