CREATE TABLE [dbo].[ImmunogrammaRtmlRbtl] (
    [ID]                     INT        NOT NULL,
    [PatID]                  INT        NULL,
    [NomerAnaliza]           INT        NULL,
    [DataProvedeniyaAnaliza] DATETIME   NULL,
    [Leykotsiti]             FLOAT (53) NULL,
    [Limfotsiti]             FLOAT (53) NULL,
    [AbsLimfotsiti]          FLOAT (53) NULL,
    [TLimfotsiti]            FLOAT (53) NULL,
    [AbsTLimfotsiti]         FLOAT (53) NULL,
    [VLimfotsiti]            FLOAT (53) NULL,
    [AbsVLimfotsiti]         FLOAT (53) NULL,
    [OKletki]                FLOAT (53) NULL,
    [THelperi]               FLOAT (53) NULL,
    [THelTSup]               FLOAT (53) NULL,
    [FzOt]                   FLOAT (53) NULL,
    [FzDo]                   FLOAT (53) NULL,
    [FiOt]                   FLOAT (53) NULL,
    [FiDo]                   FLOAT (53) NULL,
    [Izf]                    FLOAT (53) NULL,
    [Tsik]                   FLOAT (53) NULL,
    [N202]                   FLOAT (53) NULL,
    [TSupressori]            FLOAT (53) NULL,
    [Rtml]                   INT        NULL,
    [Fga]                    FLOAT (53) NULL,
    [Analgin]                FLOAT (53) NULL,
    [Milipromin]             FLOAT (53) NULL,
    [Deksazon]               FLOAT (53) NULL,
    [SGerpesom]              FLOAT (53) NULL,
    [Tuberkulin]             FLOAT (53) NULL,
    [Brutselin]              FLOAT (53) NULL,
    [Toksoplazmin]           FLOAT (53) NULL,
    [Spontannaya]            FLOAT (53) NULL,
    [Vrach]                  INT        NULL,
    CONSTRAINT [ImmunogrammaRtmlRbtlPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [ImmunogrammaRtmlRbtlToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

