CREATE TABLE [dbo].[ImportPatientBuffer] (
    [ID]                      INT            IDENTITY (1, 1) NOT NULL,
    [MasterId]                INT            NOT NULL,
    [LASTNAME]                NVARCHAR (40)  NULL,
    [FIRSTNAME]               NVARCHAR (40)  NULL,
    [SECONDNAME]              NVARCHAR (40)  NULL,
    [BIRTHDATE]               DATETIME       NULL,
    [CARD_NUM]                NVARCHAR (50)  NULL,
    [SEX]                     NVARCHAR (1)   NULL,
    [FULLADRESS]              NVARCHAR (200) NULL,
    [TELEPHONE]               NVARCHAR (50)  NULL,
    [JOB_TELEPHONE]           NVARCHAR (50)  NULL,
    [POLICY]                  NVARCHAR (50)  NULL,
    [BEG_DATE]                DATETIME       NULL,
    [END_DATE]                DATETIME       NULL,
    [PROGRAM_MEDSERVICE]      NVARCHAR (200) NULL,
    [JOB_LOCATION]            NVARCHAR (200) NULL,
    [POST]                    NVARCHAR (50)  NULL,
    [REGISTER_CHECK_RESULT]   INT            DEFAULT ((0)) NOT NULL,
    [ATTACHMENT_CHECK_RESULT] INT            DEFAULT ((0)) NOT NULL,
    [PATIENT_ID]              INT            NULL,
    [IS_CHECKED]              BIT            DEFAULT ((0)) NOT NULL,
    [IS_REGISTERED]           BIT            DEFAULT ((0)) NOT NULL,
    [IS_ATTACHED]             BIT            DEFAULT ((0)) NOT NULL,
    [MobTelephone]            NVARCHAR (50)  NULL,
    [Before_END_DATE]         DATETIME       NULL,
    [IS_PROFADDED]            BIT            NULL,
    [Staj]                    NVARCHAR (50)  NULL,
    [Vrednost]                NVARCHAR (255) NULL,
    [Comment]                 NTEXT          NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([MasterId]) REFERENCES [dbo].[ImportPatientLog] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);

