CREATE TABLE [dbo].[InostrantsiIzStoronnihLpu] (
    [ID]           INT           NOT NULL,
    [PatID]        INT           NULL,
    [Data]         DATETIME      NULL,
    [KemNapr]      NTEXT         NULL,
    [Prichina]     NTEXT         NULL,
    [VrachNapr]    INT           NULL,
    [Lechenie]     NVARCHAR (50) NULL,
    [num]          INT           NULL,
    [FIOHide]      NVARCHAR (50) NULL,
    [GrazhdanHide] NVARCHAR (50) NULL,
    [DRHide]       DATETIME      NULL,
    [PatSex]       NVARCHAR (50) NULL,
    [Document]     NVARCHAR (50) NULL,
    [DateVhod]     DATETIME      NULL,
    [DateVihod]    DATETIME      NULL,
    [Adress]       NVARCHAR (50) NULL,
    [Jobs]         NVARCHAR (50) NULL,
    [Napravl]      NVARCHAR (50) NULL,
    [DomNapr]      NVARCHAR (50) NULL,
    [DateNapr]     DATETIME      NULL,
    [CelNapr]      NVARCHAR (50) NULL,
    [CelNaprIN]    NVARCHAR (50) NULL,
    [KemVidan]     NVARCHAR (50) NULL,
    [DateVidan]    DATETIME      NULL,
    [Family]       NVARCHAR (50) NULL,
    [DateObrash]   DATETIME      NULL,
    [Zhalobi]      NTEXT         NULL,
    [Anamnez]      NTEXT         NULL,
    [RezObsled]    NTEXT         NULL,
    [DateBox1]     DATETIME      NULL,
    [Diagnoz]      NTEXT         NULL,
    [KodMKB]       NVARCHAR (50) NULL,
    [DateBox2]     DATETIME      NULL,
    [DateSved]     DATETIME      NULL,
    [NomerDiag]    NVARCHAR (50) NULL,
    [ObosnovDiag]  NTEXT         NULL,
    [DateOtkaz]    DATETIME      NULL,
    [DateNachTer]  DATETIME      NULL,
    [ShemTer]      NTEXT         NULL,
    [DateKonTer]   DATETIME      NULL,
    [DateZaklVK]   DATETIME      NULL,
    CONSTRAINT [InostrantsiIzStoronnihLpuPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [InostrantsiIzStoronnihLpuToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

