CREATE TABLE [dbo].[Instr_Diag_TDSAVK] (
    [ID]                       INT        NOT NULL,
    [PatID]                    INT        NULL,
    [SrednieMozgArtSSKSprava]  FLOAT (53) NULL,
    [SrednieMozgArtPISprava]   FLOAT (53) NULL,
    [SrednieMozgArtLSKSleva]   FLOAT (53) NULL,
    [SrednieMozgArtSSKSleva]   FLOAT (53) NULL,
    [SrednieMozgArtPISleva]    FLOAT (53) NULL,
    [PerednieMozgArtLSKSprava] FLOAT (53) NULL,
    [PerednieMozgArtSSKSprava] FLOAT (53) NULL,
    [PerednieMozgArtPISprava]  FLOAT (53) NULL,
    [PerednieMozgArtLSKSleva]  FLOAT (53) NULL,
    [PerednieMozgArtSSKSleva]  FLOAT (53) NULL,
    [PerednieMozgArtPISleva]   FLOAT (53) NULL,
    [ZadnieMozgArtSSKSprava]   FLOAT (53) NULL,
    [ZadnieMozgArtPISprava]    FLOAT (53) NULL,
    [ZadnieMozgArtLSKSleva]    FLOAT (53) NULL,
    [ZadnieMozgArtSSKSleva]    FLOAT (53) NULL,
    [ZadnieMozgArtPISleva]     FLOAT (53) NULL,
    [PozvonochnieArtLSKSprava] FLOAT (53) NULL,
    [PozvonochnieArtSSKSprava] FLOAT (53) NULL,
    [PozvonochnieArtPISprava]  FLOAT (53) NULL,
    [PozvonochnieArtLSKSleva]  FLOAT (53) NULL,
    [PozvonochnieArtSSKSleva]  FLOAT (53) NULL,
    [PozvonochnieArtPISleva]   FLOAT (53) NULL,
    [OsnovnajaArtLSKSprava]    FLOAT (53) NULL,
    [OsnovnajaArtSSKSprava]    FLOAT (53) NULL,
    [OsnovnajaArtPISprava]     FLOAT (53) NULL,
    [zakl]                     NTEXT      NULL,
    [SrednieMozgArtLSKSprava]  FLOAT (53) NULL,
    [ZadnieMozgArtLSKSprava]   FLOAT (53) NULL,
    [VeniRozentalaSprava]      FLOAT (53) NULL,
    [VeniRozentalaSleva]       FLOAT (53) NULL,
    [otgrad]                   INT        NULL,
    [dograd]                   INT        NULL,
    CONSTRAINT [Instr_Diag_TDSAVKPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [Instr_Diag_TDSAVKToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

