CREATE TABLE [dbo].[InstrDiag_shitovidnayaZheleza] (
    [ID]                                                            INT           NOT NULL,
    [PatID]                                                         INT           NULL,
    [akyst_dostup]                                                  NVARCHAR (50) NULL,
    [raspolojenie]                                                  NVARCHAR (50) NULL,
    [chetkie_nechetkie]                                             NVARCHAR (50) NULL,
    [izmenea_Nizmenena_kapsyla]                                     NVARCHAR (50) NULL,
    [ExogennostParenximi]                                           NVARCHAR (50) NULL,
    [StepenIzmenenijaExogennosti]                                   NVARCHAR (50) NULL,
    [ExostryktyraParenximi]                                         NVARCHAR (50) NULL,
    [StepenNeodnosti]                                               NVARCHAR (50) NULL,
    [ObjemnieObrazovanija]                                          NVARCHAR (50) NULL,
    [RegionarnieLimfaticheskieUzli]                                 NVARCHAR (50) NULL,
    [UzliPole]                                                      NTEXT         NULL,
    [ParashitovidnieZelezi]                                         NVARCHAR (50) NULL,
    [VProektsiiIhPatologicheskihObrazovaniyNeViyavleno]             NVARCHAR (1)  NULL,
    [CDK]                                                           NVARCHAR (50) NULL,
    [UltrazvukovihPriznakovPatologiiNeViyavleno]                    NVARCHAR (1)  NULL,
    [UzPriznakiDiffuznoyGiperplaziiDiffuznogoZoba]                  NVARCHAR (1)  NULL,
    [UzPriznakiTireoidita]                                          NVARCHAR (1)  NULL,
    [UzPriznakiMnogouzlovogoOdnouzlovogoZobaEhogrammiPrilagayutsya] NVARCHAR (1)  NULL,
    [SostoyaniePosleOperatsiiNaShitovidnoyZheleze]                  NVARCHAR (1)  NULL,
    [UzPriznakiGipoplaziiShitovidnoyZhelezi]                        NVARCHAR (1)  NULL,
    [UzPriznakiAnomaliiFormiShitovidnoyZhelezi]                     NVARCHAR (1)  NULL,
    [Differenciryetsa]                                              NVARCHAR (50) NULL,
    [AnatomForma]                                                   NTEXT         NULL,
    [PravajaDolaObjem]                                              FLOAT (53)    NULL,
    [LevajaDolaObjem]                                               FLOAT (53)    NULL,
    [ObrazovanijaPole]                                              NTEXT         NULL,
    [Lokalizachija]                                                 NTEXT         NULL,
    [posleoperaciinashitovidnoyzheleze]                             NVARCHAR (50) NULL,
    [PravajaDolaTolshina]                                           FLOAT (53)    NULL,
    [LevajaDolaTolshina]                                            FLOAT (53)    NULL,
    [PravajaDolaShirina]                                            FLOAT (53)    NULL,
    [LevajaDolaShirina]                                             FLOAT (53)    NULL,
    [PravajaDolaDlinnik]                                            FLOAT (53)    NULL,
    [LevajaDolaDlinnik]                                             FLOAT (53)    NULL,
    [PeresheekTolshina]                                             FLOAT (53)    NULL,
    [JeleziPole]                                                    NTEXT         NULL,
    [Primechanija]                                                  NTEXT         NULL,
    [cdkmemo]                                                       NTEXT         NULL,
    [Zakluchenie]                                                   NTEXT         NULL,
    CONSTRAINT [InstrDiag_shitovidnayaZhelezaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [InstrDiag_shitovidnayaZhelezaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

