CREATE TABLE [dbo].[InstrDiag_Ophtalmolog_BiomicroskopiashelevayaLampa] (
    [ID]                 INT           NOT NULL,
    [PatID]              INT           NULL,
    [KonyuktivaOD]       NTEXT         NULL,
    [KonyuktivaOS]       NTEXT         NULL,
    [SkleraOD]           NTEXT         NULL,
    [SkleraOS]           NTEXT         NULL,
    [RogovitcaOD]        NTEXT         NULL,
    [PerednayaKameraOD]  NTEXT         NULL,
    [PerednayaKameraOS]  NTEXT         NULL,
    [RogovitcaOS]        NTEXT         NULL,
    [RadujkaOD]          NTEXT         NULL,
    [ZrachokOD]          NTEXT         NULL,
    [HrustalikOD]        NTEXT         NULL,
    [SteklovidnoeTeloOD] NTEXT         NULL,
    [SteklovidnoeTeloOS] NTEXT         NULL,
    [HrustalikOS]        NTEXT         NULL,
    [ZrachokOS]          NTEXT         NULL,
    [RadujkaOS]          NTEXT         NULL,
    [ReflexGLDnaOS]      NTEXT         NULL,
    [ReflexGLDnaOD]      NTEXT         NULL,
    [MasterID]           INT           NULL,
    [SkleraOD1]          NTEXT         NULL,
    [FormaOD]            NVARCHAR (50) NULL,
    [FormaOS]            NVARCHAR (50) NULL,
    [SynechiaeOD]        NVARCHAR (50) NULL,
    [SynechiaeOS]        NVARCHAR (50) NULL,
    [ReactionOD]         NVARCHAR (50) NULL,
    [ReactionOS]         NVARCHAR (50) NULL,
    [SizeOD]             NVARCHAR (50) NULL,
    [SizeOS]             NVARCHAR (50) NULL,
    [HrustalOD]          NVARCHAR (50) NULL,
    [HrustalOS]          NVARCHAR (50) NULL,
    [StekloOD]           NVARCHAR (50) NULL,
    [Steklo0S]           NVARCHAR (50) NULL,
    [DZNOD]              NVARCHAR (50) NULL,
    [DZNOS]              NVARCHAR (50) NULL,
    [MakylaOD]           NVARCHAR (50) NULL,
    [MakylaOS]           NVARCHAR (50) NULL,
    [SetchatkaOD]        NVARCHAR (50) NULL,
    [SetchatkaOS]        NVARCHAR (50) NULL,
    [EyegroundOD]        NTEXT         NULL,
    [EyegroundOS]        NTEXT         NULL,
    CONSTRAINT [InstrDiag_Ophtalmolog_BiomicroskopiashelevayaLampaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [InstrDiag_Ophtalmolog_BiomicroskopiashelevayaLampaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

