CREATE TABLE [dbo].[InstrDiag_Ehokardiographiya] (
    [ID]                                 INT           NOT NULL,
    [PatID]                              INT           NULL,
    [MaxPerzadRazmLevPredserdiya]        FLOAT (53)    NULL,
    [KonDiagRazmLevJeludochka]           FLOAT (53)    NULL,
    [TolshMejJeludPeregVdiastolu]        FLOAT (53)    NULL,
    [TolshinaZadStenLevJel]              FLOAT (53)    NULL,
    [MaxRasStvorkAortalKlapana]          FLOAT (53)    NULL,
    [DiametrKornyaAorti]                 FLOAT (53)    NULL,
    [MaxPeredzadRazmerVinTraktPravJel]   FLOAT (53)    NULL,
    [MaxDiametrNijPolVeni]               FLOAT (53)    NULL,
    [FracWibrosa]                        INT           NULL,
    [UtolsheniyaStenokLevJeludochka]     NVARCHAR (50) NULL,
    [NarusheniyaLokSokratLevJeludochka]  NVARCHAR (50) NULL,
    [PriDoplerIsledTransmitKrov]         NTEXT         NULL,
    [MaxObLevPredserdia]                 INT           NULL,
    [MaxObPravPredserdia]                INT           NULL,
    [NijnyayaPolVena]                    NTEXT         NULL,
    [MitralnayaRegurigaciya]             NTEXT         NULL,
    [StepenTrikuspidalnayaReguritacii]   NVARCHAR (50) NULL,
    [RazmeriPolostiPravJeludchka]        NTEXT         NULL,
    [RazmeriPolostiLevJeludochka]        NTEXT         NULL,
    [VpolostiLevJel]                     NTEXT         NULL,
    [GlobalnayaSokratimostLevJeludochka] NTEXT         NULL,
    [TrikuspidalnayaRegurigaciya]        NTEXT         NULL,
    [MaxOLP]                             NTEXT         NULL,
    [MaxOPP]                             NTEXT         NULL,
    [AortalReguritaciya]                 NTEXT         NULL,
    [StepenMitrReguritacii]              NVARCHAR (50) NULL,
    [StepenAortalReguritacii]            NVARCHAR (50) NULL,
    [Dopolnenie]                         NTEXT         NULL,
    [mitralniyklapan]                    NTEXT         NULL,
    [aortalniyklapan]                    NTEXT         NULL,
    [trikucpidalniyklapan]               NTEXT         NULL,
    [klapanlegochnoyarteriimemo]         NTEXT         NULL,
    [klapanlegochnoyarteriimemo2]        NTEXT         NULL,
    [Stepenklapanlegochnoyarterii]       NVARCHAR (50) NULL,
    [sistolicheskoedavlenie]             INT           NULL,
    CONSTRAINT [InstrDiag_EhokardiographiyaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [InstrDiag_EhokardiographiyaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

