CREATE TABLE [dbo].[InstrDiag_TDSVOBA] (
    [ID]                                                          INT           NOT NULL,
    [PatID]                                                       INT           NULL,
    [KompleksIntimaMediaObshixSonnixArteri]                       NVARCHAR (50) NULL,
    [KompleksDO]                                                  FLOAT (53)    NULL,
    [Intima]                                                      NVARCHAR (50) NULL,
    [DifferNaSloiSoxranena]                                       NTEXT         NULL,
    [LSKpoSonnoiArteriSleva]                                      FLOAT (53)    NULL,
    [LSKpoVnutrenneiArteriSleva]                                  FLOAT (53)    NULL,
    [LSKpoSonnoiArteriSpava]                                      NVARCHAR (50) NULL,
    [LSKpoVnutrenneiArteriSprava]                                 FLOAT (53)    NULL,
    [XodPozvonochnixArteri]                                       NTEXT         NULL,
    [KrovotokPoPozvonochnimArteriamVRezhimeCDK]                   NTEXT         NULL,
    [LSKvIntravertebralnomOtdeleSleva]                            FLOAT (53)    NULL,
    [LSKvIntravertebralnomOtdeleSprava]                           FLOAT (53)    NULL,
    [DiametrPozvonochnixArteriSleva]                              NVARCHAR (50) NULL,
    [DiametrPozvonochnixArteriSprava]                             FLOAT (53)    NULL,
    [SkorostniePokazateli]                                        NVARCHAR (50) NULL,
    [Prosveti]                                                    NVARCHAR (50) NULL,
    [Primechania]                                                 NTEXT         NULL,
    [Zakluchenie]                                                 NTEXT         NULL,
    [DistralniOtdelPlechegolovnogoStvola]                         NVARCHAR (50) NULL,
    [KrovotokPoPodkluchichnumArteriam]                            NVARCHAR (50) NULL,
    [PodkluchennieJaremniePozvonochnieVeni]                       NVARCHAR (50) NULL,
    [differencirovka]                                             NVARCHAR (1)  NULL,
    [LeftNaruzhnayaVnutrennyayaIObshayaSonnayaArteriyaProhodimi]  NVARCHAR (1)  NULL,
    [RightNaruzhnayaVnutrennyayaIObshayaSonnayaArteriyaProhodimi] NVARCHAR (1)  NULL,
    [slevaneprohodimimemo]                                        NTEXT         NULL,
    [spravaneprohodimimemo]                                       NTEXT         NULL,
    CONSTRAINT [InstrDiag_TDSVOBAPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [InstrDiag_TDSVOBAToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

