CREATE TABLE [dbo].[IssledovanieMokrotiP] (
    [ID]                     INT           NOT NULL,
    [PatID]                  INT           NULL,
    [NomerAnaliza]           INT           NULL,
    [DataProvedeniyaAnaliza] DATETIME      NULL,
    [Vrach]                  INT           NULL,
    [HarakterMokroti]        INT           NULL,
    [Tsvet]                  INT           NULL,
    [Konsistentsiya]         INT           NULL,
    [Leykotsiti]             NVARCHAR (1)  NULL,
    [SpiraliKurshmana]       NVARCHAR (1)  NULL,
    [KristalliSharkoLeydena] NVARCHAR (1)  NULL,
    [Eritrotsiti]            NVARCHAR (1)  NULL,
    [EpitKletki]             NVARCHAR (1)  NULL,
    [AlveslyarnieKl]         NVARCHAR (1)  NULL,
    [Kum]                    NVARCHAR (1)  NULL,
    [BatsilliPfeyfera]       NVARCHAR (1)  NULL,
    [EditBox1]               FLOAT (53)    NULL,
    [EditBox2]               NVARCHAR (50) NULL,
    [Eozinofili]             NVARCHAR (1)  NULL,
    [ElastichnieVolokna]     NVARCHAR (1)  NULL,
    [DiplokokkiFrenkelya]    NVARCHAR (1)  NULL,
    [DrugieMikroorganizmi]   NVARCHAR (1)  NULL,
    [Memo1]                  NTEXT         NULL,
    [EditBox3]               NVARCHAR (50) NULL,
    [Combo1]                 NVARCHAR (50) NULL,
    [EditBox4]               NVARCHAR (8)  NULL,
    [Vrach2]                 INT           NULL,
    [EditBox5]               FLOAT (53)    NULL,
    [EditBox6]               FLOAT (53)    NULL,
    [EditBox7]               FLOAT (53)    NULL,
    [EditBox8]               FLOAT (53)    NULL,
    [EditBox9]               FLOAT (53)    NULL,
    CONSTRAINT [IssledovanieMokrotiPPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [IssledovanieMokrotiPToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

