CREATE TABLE [dbo].[IssledovanieSomatosensornihVizvannihPotentsialov] (
    [ID]                    INT           NOT NULL,
    [PatID]                 INT           NULL,
    [Data]                  DATETIME      NULL,
    [Vrach]                 NVARCHAR (50) NULL,
    [StimuliruemiyNerv]     NVARCHAR (50) NULL,
    [TochkaStimulyatsii]    NVARCHAR (50) NULL,
    [TochkiRegistratsii]    NTEXT         NULL,
    [DanniePatsienta]       NVARCHAR (50) NULL,
    [DanniePatsienta1]      NVARCHAR (50) NULL,
    [DanniePatsienta3]      NVARCHAR (50) NULL,
    [DanniePatsienta2]      NVARCHAR (50) NULL,
    [DanniePatsienta4]      NVARCHAR (50) NULL,
    [DanniePatsienta5]      NVARCHAR (50) NULL,
    [DanniePatsienta6]      NVARCHAR (50) NULL,
    [DanniePatsienta7]      NVARCHAR (50) NULL,
    [Parametri]             NVARCHAR (50) NULL,
    [AbsolyutnieNormativi]  NVARCHAR (50) NULL,
    [Parametri1]            NVARCHAR (50) NULL,
    [IntersideDifferences]  NVARCHAR (50) NULL,
    [AbsolyutnieNormativi1] NVARCHAR (50) NULL,
    [IntersideDifferences1] NVARCHAR (50) NULL,
    [AbsolyutnieNormativi2] NVARCHAR (50) NULL,
    [IntersideDifferences2] NVARCHAR (50) NULL,
    [AbsolyutnieNormativi3] NVARCHAR (50) NULL,
    [IntersideDifferences3] NVARCHAR (50) NULL,
    [DanniePatsienta8]      NVARCHAR (50) NULL,
    [EditBox22]             NVARCHAR (50) NULL,
    [AbsolyutnieNormativi4] NVARCHAR (50) NULL,
    [IntersideDifferences4] NVARCHAR (50) NULL,
    [DanniePatsienta9]      NVARCHAR (50) NULL,
    [DanniePatsienta10]     NVARCHAR (50) NULL,
    [AbsolyutnieNormativi5] NVARCHAR (50) NULL,
    [IntersideDifferences5] NVARCHAR (50) NULL,
    [Zaklyuchenie]          NTEXT         NULL,
    [Zaklyuchenie1]         NTEXT         NULL,
    CONSTRAINT [IssledovanieSomatosensornihVizvannihPotentsialovPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [IssledovanieSomatosensornihVizvannihPotentsialovToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

