CREATE TABLE [dbo].[IssledovanieMazkovNaFloruP] (
    [ID]                       INT           NOT NULL,
    [PatID]                    INT           NULL,
    [Nomer]                    NVARCHAR (50) NULL,
    [DataVzyatiyaBiomateriala] DATETIME      NULL,
    [Epiteliy]                 NVARCHAR (50) NULL,
    [Epiteliy1]                NVARCHAR (50) NULL,
    [Epiteliy2]                NVARCHAR (50) NULL,
    [Leykotsiti]               NVARCHAR (50) NULL,
    [Leykotsiti1]              NVARCHAR (50) NULL,
    [Leykotsiti2]              NVARCHAR (50) NULL,
    [Eritrotsiti]              NVARCHAR (50) NULL,
    [Eritrotsiti1]             NVARCHAR (50) NULL,
    [Eritrotsiti2]             NVARCHAR (50) NULL,
    [Mikroflora]               NVARCHAR (50) NULL,
    [Mikroflora1]              NVARCHAR (50) NULL,
    [Mikroflora2]              NVARCHAR (50) NULL,
    [Trihomonadi]              NVARCHAR (50) NULL,
    [Trihomonadi1]             NVARCHAR (50) NULL,
    [Trihomonadi2]             NVARCHAR (50) NULL,
    [Gonokokki]                NVARCHAR (50) NULL,
    [Gonokokki1]               NVARCHAR (50) NULL,
    [Gonokokki2]               NVARCHAR (50) NULL,
    [Sliz]                     NVARCHAR (50) NULL,
    [Sliz1]                    NVARCHAR (50) NULL,
    [Sliz2]                    NVARCHAR (50) NULL,
    [EditBox1]                 NVARCHAR (50) NULL,
    [EditBox2]                 NVARCHAR (8)  NULL,
    [Combo1]                   NVARCHAR (50) NULL,
    [Vrach]                    INT           NULL,
    [EditBox3]                 NVARCHAR (50) NULL,
    [EditBox4]                 NVARCHAR (50) NULL,
    [EditBox5]                 NVARCHAR (50) NULL,
    [EditBox6]                 NVARCHAR (50) NULL,
    [EditBox7]                 NVARCHAR (50) NULL,
    [EditBox8]                 NVARCHAR (50) NULL,
    [EditBox9]                 NVARCHAR (50) NULL,
    [EditBox10]                NVARCHAR (50) NULL,
    [EditBox11]                NVARCHAR (50) NULL,
    [EditBox12]                NVARCHAR (50) NULL,
    [EditBox13]                NVARCHAR (50) NULL,
    [EditBox14]                NVARCHAR (50) NULL,
    [EditBox15]                NVARCHAR (50) NULL,
    [EditBox16]                NVARCHAR (50) NULL,
    [EditBox17]                NVARCHAR (50) NULL,
    [EditBox18]                NVARCHAR (50) NULL,
    [EditBox19]                NVARCHAR (50) NULL,
    [EditBox20]                NVARCHAR (50) NULL,
    [EditBox21]                NVARCHAR (50) NULL,
    [Vrach2]                   INT           NULL,
    CONSTRAINT [IssledovanieMazkovNaFloruPPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [IssledovanieMazkovNaFloruPToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

