CREATE TABLE [dbo].[KartaLecheniyaVKabineteLfk] (
    [ID]                     INT            NOT NULL,
    [PatID]                  INT            NULL,
    [ZanimalsyaFkISportom]   BIT            NULL,
    [DiagPripostVHospital]   NVARCHAR (100) NULL,
    [DiagPriPostVLFK]        NVARCHAR (100) NULL,
    [BasicClinicData]        NTEXT          NULL,
    [DateFuncprob]           DATETIME       NULL,
    [PulseDoNagr]            NVARCHAR (50)  NULL,
    [ADDoNagr]               INT            NULL,
    [SlashdoNagr]            INT            NULL,
    [BreatheDoNagr]          NVARCHAR (50)  NULL,
    [PulsePosleNagr]         NVARCHAR (50)  NULL,
    [ADPosleNagr]            INT            NULL,
    [SlashPosleNagr]         INT            NULL,
    [BreathePosleNagr]       NVARCHAR (50)  NULL,
    [Restitution]            NVARCHAR (50)  NULL,
    [AntropDate]             DATETIME       NULL,
    [HeightStanding]         INT            NULL,
    [HeightSitting]          INT            NULL,
    [Weight]                 FLOAT (53)     NULL,
    [OkrugnostGrudnoyKletki] NVARCHAR (50)  NULL,
    [SpiroMetriya]           FLOAT (53)     NULL,
    [Dinamometrix]           FLOAT (53)     NULL,
    [InjureDate]             DATETIME       NULL,
    [DateGotToHospital]      DATETIME       NULL,
    [DaysSpentInHospital]    NVARCHAR (50)  NULL,
    [NaznachenVLFK]          DATETIME       NULL,
    [StartedCure]            DATETIME       NULL,
    [DaysSpentLFK]           INT            NULL,
    [Anamnez]                NVARCHAR (50)  NULL,
    [DoneCure]               NVARCHAR (50)  NULL,
    [Zhaloby]                NVARCHAR (50)  NULL,
    [ClinicData]             NVARCHAR (100) NULL,
    [TechBol]                NVARCHAR (100) NULL,
    [NaznVrachLFK]           NVARCHAR (100) NULL,
    [OtmInstrLFK]            NVARCHAR (100) NULL,
    [DateULFK]               DATETIME       NULL,
    [ADDoZanULFK]            INT            NULL,
    [SlashDoZanULFK]         INT            NULL,
    [PulseDoZanULFK]         NVARCHAR (50)  NULL,
    [PulsePosleNagrUchetLFK] NVARCHAR (50)  NULL,
    [ADPosleNagrULFK]        INT            NULL,
    [SPЯULFK]                INT            NULL,
    [PDNULВТ]                NVARCHAR (50)  NULL,
    [AdSubjDo]               INT            NULL,
    [SlashSubjDo]            INT            NULL,
    [PulseSubjPosle]         NVARCHAR (50)  NULL,
    [ADSubjposle]            INT            NULL,
    [SlashSubjPosle]         INT            NULL,
    [SubjectDate]            DATETIME       NULL,
    CONSTRAINT [KartaLecheniyaVKabineteLfkPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [KartaLecheniyaVKabineteLfkToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

