CREATE TABLE [dbo].[KartaBolnogoSahDiabetom] (
    [ID]                    INT           NOT NULL,
    [PatID]                 INT           NULL,
    [DiabetKoma]            NVARCHAR (50) NULL,
    [ZaderjkaRazv]          NVARCHAR (50) NULL,
    [DictCombo1]            NVARCHAR (50) NULL,
    [DiabetKatarakta]       NVARCHAR (50) NULL,
    [DiabetRetinopat]       NVARCHAR (50) NULL,
    [Nefropat]              NVARCHAR (50) NULL,
    [Sensor]                NVARCHAR (50) NULL,
    [Neyropat]              NVARCHAR (50) NULL,
    [Makroangiopat]         NVARCHAR (50) NULL,
    [GodUstOslojn]          INT           NULL,
    [GodUstOslojn1]         INT           NULL,
    [GodUstOslojn2]         INT           NULL,
    [GodUstOslojn3]         INT           NULL,
    [GodUstOslojn4]         INT           NULL,
    [GodUstOslojn5]         INT           NULL,
    [GodUstOslojn6]         INT           NULL,
    [GodUstOslojn7]         INT           NULL,
    [GodUstOslojn8]         INT           NULL,
    [DiabetStopa]           NVARCHAR (50) NULL,
    [Stenokard]             NVARCHAR (50) NULL,
    [GodUstOslojn9]         INT           NULL,
    [InfarktMiokarda]       NVARCHAR (50) NULL,
    [GodUstOslojn10]        INT           NULL,
    [GodUstOslojn11]        INT           NULL,
    [NarushMozgKrovoobr]    NVARCHAR (50) NULL,
    [GodUstOslojn12]        INT           NULL,
    [Gipertoniya]           NVARCHAR (50) NULL,
    [GodUstOslojn13]        INT           NULL,
    [StatsionarnoeLechenie] INT           NULL,
    [AmbulatornoeLechenie]  INT           NULL,
    [Gipoklemii]            INT           NULL,
    [Ketoatsidoz]           INT           NULL,
    [GodUstInInvalidn]      INT           NULL,
    [Invalidnost]           NVARCHAR (50) NULL,
    [PrichinaInvalidn]      NVARCHAR (50) NULL,
    [Beremennost]           NVARCHAR (50) NULL,
    [Vrach]                 INT           NULL,
    [GodUstDiagnoz]         INT           NULL,
    [GodNachInsulinoter]    INT           NULL,
    [TipDiabeta]            NVARCHAR (50) NULL,
    [Rost]                  FLOAT (53)    NULL,
    [Ves]                   FLOAT (53)    NULL,
    [AD]                    INT           NULL,
    [Dieta]                 NVARCHAR (50) NULL,
    [Date]                  DATETIME      NULL,
    [Tabletki]              NVARCHAR (50) NULL,
    [Tabletki1]             NVARCHAR (50) NULL,
    [Tabletki2]             NVARCHAR (50) NULL,
    [Insulin]               NVARCHAR (50) NULL,
    [Insulin1]              NVARCHAR (50) NULL,
    [Insulin2]              NVARCHAR (50) NULL,
    [Insulin3]              NVARCHAR (50) NULL,
    [HbAI]                  FLOAT (53)    NULL,
    [HbAIс]                 FLOAT (53)    NULL,
    [Kreatin]               FLOAT (53)    NULL,
    [MicroAlbuminur]        NVARCHAR (50) NULL,
    [Preteinuriya]          FLOAT (53)    NULL,
    [Holesterin]            FLOAT (53)    NULL,
    [AlfaHolest]            NVARCHAR (50) NULL,
    [Triglicerid]           NVARCHAR (50) NULL,
    [AD1]                   INT           NULL,
    [Samokontrol]           INT           NULL,
    [Tab1]                  INT           NULL,
    [Tab2]                  INT           NULL,
    [Tab3]                  INT           NULL,
    [Tab4]                  INT           NULL,
    [Tab5]                  INT           NULL,
    [Tab6]                  INT           NULL,
    [Tab7]                  INT           NULL,
    CONSTRAINT [KartaBolnogoSahDiabetomPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [KartaBolnogoSahDiabetomToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

