CREATE TABLE [dbo].[KartaEkspertnoyOtsenkiVStatsionare] (
    [ID]                    INT           NOT NULL,
    [PatID]                 INT           NULL,
    [DataVipiski]           DATETIME      NULL,
    [PlanExtren]            NVARCHAR (50) NULL,
    [Budzet]                NVARCHAR (50) NULL,
    [DefectObsled]          INT           NULL,
    [DiagnozPostavlen]      INT           NULL,
    [DefectLecheniya]       INT           NULL,
    [VTE]                   INT           NULL,
    [SrokLecheniya]         INT           NULL,
    [VedenieIstorii]        INT           NULL,
    [DefectAnestezologov]   INT           NULL,
    [DefectReanimazii]      INT           NULL,
    [ZavOtd]                INT           NULL,
    [DefectChuzii]          INT           NULL,
    [Result]                INT           NULL,
    [Avtor]                 INT           NULL,
    [DefectObsledE]         INT           NULL,
    [DiagnozPostavlenE]     INT           NULL,
    [DefectLecheniyaE]      INT           NULL,
    [VTEE]                  INT           NULL,
    [SrokLecheniyaE]        INT           NULL,
    [VedenieIstoriiE]       INT           NULL,
    [DefectAnestezologovE]  INT           NULL,
    [DefectReanimaziiE]     INT           NULL,
    [ZavOtdE]               INT           NULL,
    [ZavOtdE1]              INT           NULL,
    [DefectReanimaziiE1]    INT           NULL,
    [DefectAnestezologovE1] INT           NULL,
    [VedenieIstoriiE1]      INT           NULL,
    [SrokLecheniyaE1]       INT           NULL,
    [VTEE1]                 INT           NULL,
    [DefectLecheniyaE1]     INT           NULL,
    [DiagnozPostavlenE1]    INT           NULL,
    [DefectObsledE1]        INT           NULL,
    [DataVipiski1]          DATETIME      NULL,
    [DefectObsled1]         INT           NULL,
    [DiagnozPostavlen1]     INT           NULL,
    [DefectLecheniya1]      INT           NULL,
    [VTE1]                  INT           NULL,
    [SrokLecheniya1]        INT           NULL,
    [VedenieIstorii1]       INT           NULL,
    [DefectAnestezologov1]  INT           NULL,
    [DefectReanimazii1]     INT           NULL,
    [ZavOtd1]               INT           NULL,
    [DefectChuzii1]         INT           NULL,
    [Result1]               INT           NULL,
    [Avtor1]                INT           NULL,
    [Prichina]              INT           NULL,
    [Vrach]                 INT           NULL,
    [DefectOperLecheniya]   INT           NULL,
    [DefectOperLecheniya1]  INT           NULL,
    [DefectOperLecheniyaE]  INT           NULL,
    [DefectOperLecheniyaE1] INT           NULL,
    CONSTRAINT [KartaEkspertnoyOtsenkiVStatsionarePrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [KartaEkspertnoyOtsenkiVStatsionareToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

