CREATE TABLE [dbo].[KartaEkspertnoyOtsenkiVPoliklinike] (
    [ID]                                  INT           NOT NULL,
    [PatID]                               INT           NULL,
    [OpisanieZhalob]                      INT           NULL,
    [Anemniz]                             INT           NULL,
    [DataVipiski]                         DATETIME      NULL,
    [ObsledovaniePoOsnovnomuZab]          INT           NULL,
    [Osmotr]                              INT           NULL,
    [ObsledovaniePoVspomogateelnomuZab]   INT           NULL,
    [Diagnoz]                             INT           NULL,
    [LechenieReabilitaziya]               INT           NULL,
    [VTE]                                 INT           NULL,
    [KEK]                                 INT           NULL,
    [MSEK]                                INT           NULL,
    [SrokLecheniya]                       INT           NULL,
    [SledEtapLecheniya]                   INT           NULL,
    [Dokumentaziya]                       INT           NULL,
    [ZavOtdel]                            INT           NULL,
    [PlanExtren]                          NVARCHAR (50) NULL,
    [Budzet]                              NVARCHAR (50) NULL,
    [Avtor]                               INT           NULL,
    [OpisanieZhalobE]                     INT           NULL,
    [AnemnizE]                            INT           NULL,
    [OsmotrE]                             INT           NULL,
    [ObsledovaniePoOsnovnomuZabE]         INT           NULL,
    [ObsledovaniePoVspomogateelnomuZabE]  INT           NULL,
    [DiagnozE]                            INT           NULL,
    [LechenieReabilitaziyaE]              INT           NULL,
    [VTEE]                                INT           NULL,
    [KEKE]                                INT           NULL,
    [MSEKE]                               INT           NULL,
    [SrokLecheniyaE]                      INT           NULL,
    [SledEtapLecheniyaE]                  INT           NULL,
    [DokumentaziyaE]                      INT           NULL,
    [ZavOtdelE]                           INT           NULL,
    [OpisanieZhalob1]                     INT           NULL,
    [Anemniz1]                            INT           NULL,
    [DataVipiski1]                        DATETIME      NULL,
    [ObsledovaniePoOsnovnomuZab1]         INT           NULL,
    [Osmotr1]                             INT           NULL,
    [ObsledovaniePoVspomogateelnomuZab1]  INT           NULL,
    [Diagnoz1]                            INT           NULL,
    [LechenieReabilitaziya1]              INT           NULL,
    [VTE1]                                INT           NULL,
    [KEK1]                                INT           NULL,
    [MSEK1]                               INT           NULL,
    [SrokLecheniya1]                      INT           NULL,
    [SledEtapLecheniya1]                  INT           NULL,
    [Dokumentaziya1]                      INT           NULL,
    [ZavOtdel1]                           INT           NULL,
    [OpisanieZhalobE1]                    INT           NULL,
    [AnemnizE1]                           INT           NULL,
    [OsmotrE1]                            INT           NULL,
    [ObsledovaniePoOsnovnomuZabE1]        INT           NULL,
    [ObsledovaniePoVspomogateelnomuZabE1] INT           NULL,
    [DiagnozE1]                           INT           NULL,
    [LechenieReabilitaziyaE1]             INT           NULL,
    [VTEE1]                               INT           NULL,
    [KEKE1]                               INT           NULL,
    [MSEKE1]                              INT           NULL,
    [SrokLecheniyaE1]                     INT           NULL,
    [SledEtapLecheniyaE1]                 INT           NULL,
    [DokumentaziyaE1]                     INT           NULL,
    [ZavOtdelE1]                          INT           NULL,
    [Avtor1]                              INT           NULL,
    [PrichinaExpertizi]                   INT           NULL,
    [Vrach]                               INT           NULL,
    [Result]                              INT           NULL,
    [Result1]                             INT           NULL,
    [DefectChuzii]                        INT           NULL,
    [DefectChuzii1]                       INT           NULL,
    CONSTRAINT [KartaEkspertnoyOtsenkiVPoliklinikePrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [KartaEkspertnoyOtsenkiVPoliklinikeToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

