CREATE TABLE [dbo].[Karta_KEK_LKK] (
    [ID]                                         INT           NOT NULL,
    [PatID]                                      INT           NULL,
    [№ протокола разбора]                        INT           NULL,
    [DataRazbora]                                DATETIME      NULL,
    [NVskritiya]                                 INT           NULL,
    [Otdeleniye]                                 NVARCHAR (50) NULL,
    [Vrach]                                      INT           NULL,
    [DataPostupleniya]                           DATETIME      NULL,
    [DataSmerti]                                 DATETIME      NULL,
    [EditBox1]                                   INT           NULL,
    [DateBox4]                                   DATETIME      NULL,
    [KlinikDiagnoz]                              NTEXT         NULL,
    [ZaklyuchDiagnoz]                            NTEXT         NULL,
    [Memo1]                                      NTEXT         NULL,
    [PrichinDefektaKlinichDiagnoz]               NTEXT         NULL,
    [SopostDiagnoz]                              NVARCHAR (50) NULL,
    [KategorOshibDiagn]                          NVARCHAR (50) NULL,
    [OslojnPrivedKSmerti]                        NVARCHAR (50) NULL,
    [VajnSoputstZabolev]                         NVARCHAR (50) NULL,
    [NepolnocSborAnamneza]                       NVARCHAR (50) NULL,
    [NesvoevremennostObsledov]                   NVARCHAR (50) NULL,
    [NedostatObsled]                             NVARCHAR (50) NULL,
    [OslojnDiagnProced]                          NVARCHAR (50) NULL,
    [NevernInterpretKlinDannih]                  NVARCHAR (50) NULL,
    [NesvoevrLechen]                             NVARCHAR (50) NULL,
    [NeadekvViboraLechen]                        NVARCHAR (50) NULL,
    [OslojnLechPosobiy]                          NVARCHAR (50) NULL,
    [DefektTehnikiLechPosobiy]                   NVARCHAR (50) NULL,
    [DefectDiagnoz]                              NVARCHAR (50) NULL,
    [OformlenTitulLista]                         NVARCHAR (1)  NULL,
    [NeinformirovanDnevnikZapisey]               NVARCHAR (1)  NULL,
    [OtsutstvPlanObsledovanILechen]              NVARCHAR (1)  NULL,
    [OtsutstvNeinformirovanZapisZavOtdeleniya]   NVARCHAR (1)  NULL,
    [OtsutstviePredoperatsionnoyKontseptsii]     NVARCHAR (1)  NULL,
    [OtsutstvNeinformirovanKontseptAnesteziolog] NVARCHAR (1)  NULL,
    [DefektOpisanOperativVmeshatelstv]           NVARCHAR (1)  NULL,
    [DefektiZapiseyKonsultantov]                 NVARCHAR (1)  NULL,
    [DefektZaklyuchenPoInstrumentalnIssledov]    NVARCHAR (1)  NULL,
    [OshibkaEkg]                                 NVARCHAR (1)  NULL,
    [OshibkaUzi]                                 NVARCHAR (1)  NULL,
    [OshibkaEndoskopii]                          NVARCHAR (1)  NULL,
    [OshibkaRentgenologa]                        NVARCHAR (1)  NULL,
    [OshibkRadioizotopnAnaliza]                  NVARCHAR (1)  NULL,
    [OshibkDrugVidApparatnAnaliza]               NVARCHAR (1)  NULL,
    [OshibkaKlinicheskoyLaboratorii]             NVARCHAR (1)  NULL,
    [OshibkBiohimicheskLab]                      NVARCHAR (1)  NULL,
    [OshibkBakteriologicheskLab]                 NVARCHAR (1)  NULL,
    [NepravOcenkaKlinIssled]                     NVARCHAR (50) NULL,
    [NevozmDiagnTyajestiSostBoln]                NVARCHAR (50) NULL,
    [ObektivnNevozmDiagn]                        NVARCHAR (50) NULL,
    [KratkovrPrebVStac]                          NVARCHAR (50) NULL,
    [OtsutstvieUslovDiagn]                       NVARCHAR (50) NULL,
    [NeprPostrDiagn]                             NVARCHAR (50) NULL,
    [DrugiePrichinOchibok]                       NVARCHAR (50) NULL,
    [DiagnVDannOtdelNevozmozhPoObektivPrichine]  NVARCHAR (1)  NULL,
    [DiagnVozmozhenOshibkNePovliyala]            NVARCHAR (1)  NULL,
    [DiagnozVozmozhenOpredLetalniyIshod]         NVARCHAR (1)  NULL,
    [Recenzent]                                  NVARCHAR (50) NULL,
    [Podpis]                                     NVARCHAR (50) NULL,
    [Data]                                       DATETIME      NULL,
    [ZaklRekomedKEK]                             NTEXT         NULL,
    [ZaklRekomedLKK]                             NTEXT         NULL,
    [PodpisSekretar]                             NVARCHAR (50) NULL,
    [Data1]                                      DATETIME      NULL,
    [Vrach1]                                     INT           NULL,
    CONSTRAINT [Karta_KEK_LKKPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [Karta_KEK_LKKToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

