CREATE TABLE [dbo].[KFMNTK_NOZSTAT] (
    [ID]       INT             NOT NULL,
    [PR3]      VARCHAR (10)    NULL,
    [CODVID]   VARCHAR (10)    NULL,
    [NAMEVID]  NVARCHAR (1000) NULL,
    [NOZS_PR3] NVARCHAR (1000) NULL,
    [NN]       VARCHAR (10)    NULL,
    [CODVID1]  VARCHAR (10)    NULL,
    [NAMEVID1] NVARCHAR (1000) NULL,
    CONSTRAINT [KFMNTK_NOZSTATPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC)
);

