CREATE TABLE [dbo].[KFMNTK_PROTOPCOD] (
    [ID]     INT           NOT NULL,
    [KODOP1] NVARCHAR (3)  NULL,
    [KODOP2] NVARCHAR (3)  NULL,
    [GUID]   NVARCHAR (32) NULL,
    PRIMARY KEY NONCLUSTERED ([ID] ASC)
);

