CREATE TABLE [dbo].[KlinicheskiyAnalizKrovi] (
    [ID]                                              INT           NOT NULL,
    [PatID]                                           INT           NULL,
    [Data]                                            DATETIME      NULL,
    [Laborant]                                        NVARCHAR (50) NULL,
    [Leykotsiti]                                      FLOAT (53)    NULL,
    [Eritrotsiti]                                     FLOAT (53)    NULL,
    [Gemoglobin]                                      FLOAT (53)    NULL,
    [Gematokrit]                                      FLOAT (53)    NULL,
    [SredniyObemEritrotsitov]                         FLOAT (53)    NULL,
    [SredneeSoderzhanieGemoglobinaVEritrotsite]       FLOAT (53)    NULL,
    [SrednyayaKontsentratsiyaGemoglobinaVEritrotsite] FLOAT (53)    NULL,
    [PokazatelAnizotsitozaEritrotsitov]               FLOAT (53)    NULL,
    [Trombotsiti]                                     FLOAT (53)    NULL,
    [SredniyObemTrombotsitov]                         FLOAT (53)    NULL,
    [Trombokrit]                                      FLOAT (53)    NULL,
    [PokazatelAnizotsitozaTrombotsitov]               FLOAT (53)    NULL,
    [Soe]                                             FLOAT (53)    NULL,
    [Limfotsiti]                                      FLOAT (53)    NULL,
    [Monotsiti]                                       FLOAT (53)    NULL,
    [Neytrofili]                                      FLOAT (53)    NULL,
    [Eozinofili]                                      FLOAT (53)    NULL,
    [MonotsitiAbsolKolVo]                             FLOAT (53)    NULL,
    [NeytrofiliAbsolKolVo]                            FLOAT (53)    NULL,
    [EozinofiliAbsolKolVo]                            FLOAT (53)    NULL,
    [BazofiliAbsolKolVo]                              FLOAT (53)    NULL,
    [Bazofili]                                        FLOAT (53)    NULL,
    [LimfotsitiAbsolKolVo]                            FLOAT (53)    NULL,
    [SegmentoyadernieNeytrofiliMikroskopiya]          FLOAT (53)    NULL,
    [MonotsitiMikroskopiya]                           FLOAT (53)    NULL,
    [EozinofiliMikroskopiya]                          FLOAT (53)    NULL,
    [BazofiliMikroskopiya]                            FLOAT (53)    NULL,
    [LimfotsitiMikroskopiya]                          FLOAT (53)    NULL,
    [PlazmKletki]                                     FLOAT (53)    NULL,
    [AtipichnieMononukleari]                          FLOAT (53)    NULL,
    [Trombotsiti1]                                    FLOAT (53)    NULL,
    [Retikulotsiti]                                   FLOAT (53)    NULL,
    [Normoblasti]                                     NVARCHAR (50) NULL,
    [TeltsaKebota]                                    NVARCHAR (50) NULL,
    [TeltsaToli]                                      NVARCHAR (50) NULL,
    [BazofiliZernistie]                               NVARCHAR (50) NULL,
    [TeltsaGeynaErli]                                 NVARCHAR (50) NULL,
    [Anizotsitoz]                                     NVARCHAR (50) NULL,
    [Mikrotsitoz]                                     NVARCHAR (50) NULL,
    [Makrotsitoz]                                     NVARCHAR (50) NULL,
    [Smeshanniy]                                      NVARCHAR (50) NULL,
    [KletkiBotkinaGum]                                NVARCHAR (50) NULL,
    [Anizohromiya]                                    NVARCHAR (50) NULL,
    [Gipohromiya]                                     NVARCHAR (50) NULL,
    [Giperhromiya]                                    NVARCHAR (50) NULL,
    [Poykilohromatofiliya]                            NVARCHAR (50) NULL,
    [Poykilotsitoz]                                   NVARCHAR (50) NULL,
    [Sferotsiti]                                      NVARCHAR (50) NULL,
    [MishenevidnieEritrotsiti]                        NVARCHAR (50) NULL,
    [Ehinotsiti]                                      NVARCHAR (50) NULL,
    [Shizotsiti]                                      NVARCHAR (50) NULL,
    [SerpovidnieEritr]                                NVARCHAR (50) NULL,
    [KaplevidnieEritr]                                NVARCHAR (50) NULL,
    [Ovalotsiti]                                      NVARCHAR (50) NULL,
    [Okantotsiti]                                     NVARCHAR (50) NULL,
    [Stomatotsiti]                                    NVARCHAR (50) NULL,
    CONSTRAINT [KlinicheskiyAnalizKroviPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [KlinicheskiyAnalizKroviToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

