CREATE TABLE [dbo].[Koagulogramma] (
    [ID]                                     INT          NOT NULL,
    [PatID]                                  INT          NULL,
    [NomerAnaliza]                           INT          NULL,
    [DataProvedeniyaAnaliza]                 DATETIME     NULL,
    [VrVremyaRekaltsifikatsii]               FLOAT (53)   NULL,
    [AvrAktTRekaltsifikatsii]                INT          NULL,
    [KvKefalinovoeVremya]                    INT          NULL,
    [AchtvAktTChastTrombopl]                 INT          NULL,
    [FaktorVIIIAntigemofilicheskiyGlobulinA] INT          NULL,
    [FaktorIXAntigemofilicheskiyGlobulinB]   INT          NULL,
    [FaktorXStyuartaPrauera]                 INT          NULL,
    [FaktorXIRta]                            INT          NULL,
    [FaktorXIIHagemana]                      FLOAT (53)   NULL,
    [ProtrombinovoeVremyaIndeks]             INT          NULL,
    [TrombinovoeVremyaTv]                    INT          NULL,
    [HepatoQuichApparatn]                    INT          NULL,
    [FibrinogenApparatn]                     FLOAT (53)   NULL,
    [DDinnerApparatn]                        FLOAT (53)   NULL,
    [FibrinogenPlazmi]                       FLOAT (53)   NULL,
    [TolerantnostPlazmiKGeparinu]            FLOAT (53)   NULL,
    [Plazminogen]                            FLOAT (53)   NULL,
    [Antiplazmin2Apparatn]                   FLOAT (53)   NULL,
    [FaktorVillebranda]                      FLOAT (53)   NULL,
    [Trombotest]                             INT          NULL,
    [EtanoloviyTestPolozhitelniy]            NVARCHAR (1) NULL,
    [AntigenFaktoraVIII]                     FLOAT (53)   NULL,
    [Vrach]                                  INT          NULL,
    [TimeLiWayt]                             INT          NULL,
    [TimeDyuk]                               INT          NULL,
    [FibrinoliticheskayAktivnosty]           FLOAT (53)   NULL,
    CONSTRAINT [KoagulogrammaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [KoagulogrammaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

