CREATE TABLE [dbo].[Kolonofibroskopiya] (
    [ID]                                      INT           NOT NULL,
    [PatID]                                   INT           NULL,
    [NomerIssledovaniya]                      INT           NULL,
    [DataIssledovanie]                        DATETIME      NULL,
    [TubusFibroskopaVveden]                   INT           NULL,
    [ProsvetR]                                INT           NULL,
    [ProsvetR1]                               INT           NULL,
    [VProsvetePryamoyKishki]                  INT           NULL,
    [VidiSkladokR]                            INT           NULL,
    [SosudistiyRisunokR]                      INT           NULL,
    [SlizistayaR]                             INT           NULL,
    [PoverhnostR]                             INT           NULL,
    [OtekSlizistoyR]                          INT           NULL,
    [MelkotochechnieKrovoizliyaniyaR]         NVARCHAR (1)  NULL,
    [YazviR]                                  NVARCHAR (1)  NULL,
    [KolichestvoR]                            INT           NULL,
    [LokalizatsiyaYazvR]                      INT           NULL,
    [LokalizatsiyaYazvR1]                     INT           NULL,
    [FormaYazvR]                              INT           NULL,
    [FormaRostaDlyaOpuholiR]                  INT           NULL,
    [RazmeramiYaR]                            INT           NULL,
    [LokalizatsiyaKrovoizliyaniyR]            INT           NULL,
    [MelkotochenieKrovoizR]                   INT           NULL,
    [LokalizatsiyaKrovoizliyaniyR1]           INT           NULL,
    [PolipiR]                                 NVARCHAR (1)  NULL,
    [PolipiComboR]                            INT           NULL,
    [KartsinomaR]                             NVARCHAR (1)  NULL,
    [KarcinomaComboR]                         INT           NULL,
    [ImeetsyaR]                               INT           NULL,
    [SfinkterOBernaPirogovaMyute]             INT           NULL,
    [LokalizatsiyaPolipovR]                   INT           NULL,
    [FormaPolipovR]                           INT           NULL,
    [LokalizatsiyaPolipovR1]                  INT           NULL,
    [RazmerPolipovR]                          INT           NULL,
    [LokalizatsiyaKartsinomiR]                INT           NULL,
    [FormaKartsinomiR]                        INT           NULL,
    [FormaKartsinomiR1]                       INT           NULL,
    [LokalizatsiyaKartsinomiR1]               INT           NULL,
    [RazmerKarcinomiR]                        INT           NULL,
    [LokalizatsiyaR]                          INT           NULL,
    [LokalizatsiyaR1]                         INT           NULL,
    [FormaR1]                                 INT           NULL,
    [FormaR]                                  INT           NULL,
    [RazmerPatologicheskokogoObrazovaniyaR]   INT           NULL,
    [ProsvetSK]                               INT           NULL,
    [ProsvetSK1]                              INT           NULL,
    [VProsveteSK]                             INT           NULL,
    [VidiSkladokSK]                           INT           NULL,
    [SosudistiyRisunokSK]                     INT           NULL,
    [SlizistayaSK]                            INT           NULL,
    [PoverhnostSK]                            INT           NULL,
    [OtekSlizistoySK]                         INT           NULL,
    [MelkotochechnieKrovoizliyaniyaSK]        NVARCHAR (1)  NULL,
    [MelkotochenieKrovoizSK]                  INT           NULL,
    [LokalizatsiyaKrovoizliyaniySK]           NVARCHAR (50) NULL,
    [YazviSK]                                 NVARCHAR (1)  NULL,
    [KolichestvoSK]                           INT           NULL,
    [LokalizatsiyaYazvSK]                     NVARCHAR (50) NULL,
    [FormaYazvSK]                             INT           NULL,
    [FormaRostaDlyaOpuholiSK]                 INT           NULL,
    [RazmeramiYaSK]                           INT           NULL,
    [SfinkterRossiMyute]                      INT           NULL,
    [SfinkterBalli]                           INT           NULL,
    [PolipiSK]                                NVARCHAR (1)  NULL,
    [PolipiComboSK]                           INT           NULL,
    [LokalizatsiyaPolipovSK]                  INT           NULL,
    [FormaPolipovSK]                          INT           NULL,
    [LokalizatsiyaPolipovSK1]                 INT           NULL,
    [RazmerPolipovSK]                         INT           NULL,
    [KartsinomaSK]                            NVARCHAR (1)  NULL,
    [KarcinomaComboSK]                        INT           NULL,
    [LokalizatsiyaKartsinomiSK]               INT           NULL,
    [FormaKartsinomiSK]                       INT           NULL,
    [FormaKartsinomiSK1]                      INT           NULL,
    [LokalizatsiyaKartsinomiSK1]              INT           NULL,
    [RazmerKarcinomiSK]                       INT           NULL,
    [ImeetsyaSK]                              INT           NULL,
    [LokalizatsiyaSK]                         INT           NULL,
    [LokalizatsiyaSK1]                        INT           NULL,
    [FormaSK1]                                INT           NULL,
    [FormaSK]                                 INT           NULL,
    [RazmerPatologicheskokogoObrazovaniyaSK]  INT           NULL,
    [ProsvetSK2]                              INT           NULL,
    [ProsvetSK11]                             INT           NULL,
    [VProsveteSK1]                            INT           NULL,
    [VidiSkladokSK1]                          INT           NULL,
    [SosudistiyRisunokSK1]                    INT           NULL,
    [SlizistayaSK1]                           INT           NULL,
    [PoverhnostSK1]                           INT           NULL,
    [OtekSlizistoySK1]                        INT           NULL,
    [MelkotochechnieKrovoizliyaniyaSK1]       NVARCHAR (1)  NULL,
    [MelkotochenieKrovoizSK1]                 INT           NULL,
    [LokalizatsiyaKrovoizliyaniySK1]          NVARCHAR (50) NULL,
    [YazviNK]                                 NVARCHAR (1)  NULL,
    [KolichestvoSK1]                          INT           NULL,
    [LokalizatsiyaYazvSK1]                    NVARCHAR (50) NULL,
    [FormaYazvSK1]                            INT           NULL,
    [FormaRostaDlyaOpuholiSK1]                INT           NULL,
    [RazmeramiYaSK1]                          INT           NULL,
    [PolipiNK]                                NVARCHAR (1)  NULL,
    [PolipiComboNK]                           INT           NULL,
    [LokalizatsiyaPolipovSK2]                 INT           NULL,
    [FormaPolipovSK1]                         INT           NULL,
    [LokalizatsiyaPolipovSK11]                INT           NULL,
    [RazmerPolipovSK1]                        INT           NULL,
    [KartsinomaNK]                            NVARCHAR (1)  NULL,
    [KarcinomaComboNK]                        INT           NULL,
    [LokalizatsiyaKartsinomiSK2]              INT           NULL,
    [FormaKartsinomiSK2]                      INT           NULL,
    [FormaKartsinomiSK11]                     INT           NULL,
    [LokalizatsiyaKartsinomiSK12]             INT           NULL,
    [RazmerKarcinomiSK1]                      INT           NULL,
    [ImeetsyaNK]                              INT           NULL,
    [LokalizatsiyaSK2]                        INT           NULL,
    [LokalizatsiyaSK11]                       INT           NULL,
    [FormaSK11]                               INT           NULL,
    [FormaSK2]                                INT           NULL,
    [RazmerPatologicheskokogoObrazovaniyaSK1] INT           NULL,
    [ProsvetSK3]                              INT           NULL,
    [ProsvetSK12]                             INT           NULL,
    [VProsveteSK2]                            INT           NULL,
    [VidiSkladokSK2]                          INT           NULL,
    [SosudistiyRisunokSK2]                    INT           NULL,
    [SlizistayaSK2]                           INT           NULL,
    [PoverhnostSK2]                           INT           NULL,
    [OtekSlizistoySK2]                        INT           NULL,
    [MelkotochechnieKrovoizliyaniyaSK2]       NVARCHAR (1)  NULL,
    [MelkotochenieKrovoizSK2]                 INT           NULL,
    [LokalizatsiyaKrovoizliyaniySK2]          NVARCHAR (50) NULL,
    [YazviPK]                                 NVARCHAR (1)  NULL,
    [KolichestvoSK2]                          INT           NULL,
    [LokalizatsiyaYazvSK2]                    NVARCHAR (50) NULL,
    [FormaYazvSK2]                            INT           NULL,
    [FormaRostaDlyaOpuholiSK2]                INT           NULL,
    [RazmeramiYaSK2]                          INT           NULL,
    [PolipiPK]                                NVARCHAR (1)  NULL,
    [PolipiComboPK]                           INT           NULL,
    [LokalizatsiyaPolipovSK3]                 INT           NULL,
    [FormaPolipovSK2]                         INT           NULL,
    [LokalizatsiyaPolipovSK12]                INT           NULL,
    [RazmerPolipovSK2]                        INT           NULL,
    [KartsinomaPK]                            NVARCHAR (1)  NULL,
    [KarcinomaComboPK]                        INT           NULL,
    [LokalizatsiyaKartsinomiSK3]              INT           NULL,
    [FormaKartsinomiSK3]                      INT           NULL,
    [FormaKartsinomiSK12]                     INT           NULL,
    [LokalizatsiyaKartsinomiSK11]             INT           NULL,
    [RazmerKarcinomiSK2]                      INT           NULL,
    [ImeetsyaPK]                              INT           NULL,
    [LokalizatsiyaSK3]                        INT           NULL,
    [LokalizatsiyaSK12]                       INT           NULL,
    [FormaSK12]                               INT           NULL,
    [FormaSK3]                                INT           NULL,
    [RazmerPatologicheskokogoObrazovaniyaSK2] INT           NULL,
    [ProsvetSK4]                              INT           NULL,
    [ProsvetSK13]                             INT           NULL,
    [VProsveteSK3]                            INT           NULL,
    [VidiSkladokSK3]                          INT           NULL,
    [SosudistiyRisunokSK3]                    INT           NULL,
    [SlizistayaSK3]                           INT           NULL,
    [PoverhnostSK3]                           INT           NULL,
    [OtekSlizistoySK3]                        INT           NULL,
    [MelkotochechnieKrovoizliyaniyaSK3]       NVARCHAR (1)  NULL,
    [MelkotochenieKrovoizSK3]                 INT           NULL,
    [LokalizatsiyaKrovoizliyaniySK3]          NVARCHAR (50) NULL,
    [YazviVK]                                 NVARCHAR (1)  NULL,
    [KolichestvoSK3]                          INT           NULL,
    [LokalizatsiyaYazvSK3]                    NVARCHAR (50) NULL,
    [FormaYazvSK3]                            INT           NULL,
    [FormaRostaDlyaOpuholiSK3]                INT           NULL,
    [RazmeramiYaSK3]                          INT           NULL,
    [SfinkterRossiMyute1]                     INT           NULL,
    [SfinkterBalli1]                          INT           NULL,
    [PolipiVK]                                NVARCHAR (1)  NULL,
    [PolipiComboVK]                           INT           NULL,
    [LokalizatsiyaPolipovSK4]                 INT           NULL,
    [FormaPolipovSK3]                         INT           NULL,
    [LokalizatsiyaPolipovSK13]                INT           NULL,
    [RazmerPolipovSK3]                        INT           NULL,
    [KartsinomaVK]                            NVARCHAR (1)  NULL,
    [KarcinomaComboVK]                        INT           NULL,
    [LokalizatsiyaKartsinomiSK4]              INT           NULL,
    [FormaKartsinomiSK4]                      INT           NULL,
    [FormaKartsinomiSK13]                     INT           NULL,
    [LokalizatsiyaKartsinomiSK13]             INT           NULL,
    [RazmerKarcinomiSK3]                      INT           NULL,
    [ImeetsyaVK]                              INT           NULL,
    [LokalizatsiyaSK4]                        INT           NULL,
    [LokalizatsiyaSK13]                       INT           NULL,
    [FormaSK13]                               INT           NULL,
    [FormaSK4]                                INT           NULL,
    [RazmerPatologicheskokogoObrazovaniyaSK3] INT           NULL,
    [Proktit1]                                INT           NULL,
    [Proktit]                                 INT           NULL,
    [Proktosigmoidit]                         INT           NULL,
    [Sigmoidit]                               INT           NULL,
    [Kolit]                                   INT           NULL,
    [ZaporiPonosi]                            INT           NULL,
    [BoleznKrona]                             INT           NULL,
    [Polip]                                   INT           NULL,
    [Polipoz]                                 INT           NULL,
    [Divertikul]                              INT           NULL,
    [Divertikulez]                            INT           NULL,
    [Kartsinoma]                              INT           NULL,
    [Gemangioma]                              INT           NULL,
    [Zaklyuchenie]                            NTEXT         NULL,
    [TsitologicheskoeIssledovanieSigmKishki]  NVARCHAR (1)  NULL,
    [TsitologicheskoeIssledovaniePrKishki]    NVARCHAR (1)  NULL,
    [VpervieViyavlenniyBolnoy]                NVARCHAR (1)  NULL,
    [Image]                                   IMAGE         NULL,
    [Vrach]                                   INT           NULL,
    [DopolnitelnieDannieZakyucheniya]         NTEXT         NULL,
    [DannieVivodimieNaPechat]                 NTEXT         NULL,
    CONSTRAINT [KolonofibroskopiyaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [KolonofibroskopiyaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

