CREATE TABLE [dbo].[Kolonoskopiya] (
    [ID]                                          INT           NOT NULL,
    [PatID]                                       INT           NULL,
    [Data]                                        DATETIME      NULL,
    [KlinicheskiyDiagnoz]                         NTEXT         NULL,
    [Apparat]                                     NVARCHAR (50) NULL,
    [BauginievaZaslonka]                          NTEXT         NULL,
    [Osmotreni]                                   NTEXT         NULL,
    [Osmotreni1]                                  NVARCHAR (1)  NULL,
    [Osmotreni3]                                  NVARCHAR (1)  NULL,
    [Osmotreni4]                                  NVARCHAR (1)  NULL,
    [Osmotreni5]                                  NVARCHAR (1)  NULL,
    [Osmotreni6]                                  NVARCHAR (1)  NULL,
    [Osmotreni2]                                  NVARCHAR (1)  NULL,
    [Soderzhimoe]                                 NTEXT         NULL,
    [Soderzhimoe1]                                NVARCHAR (1)  NULL,
    [Soderzhimoe2]                                NVARCHAR (1)  NULL,
    [Soderzhimoe3]                                NVARCHAR (1)  NULL,
    [Prosvet]                                     NVARCHAR (50) NULL,
    [Stenka]                                      NVARCHAR (50) NULL,
    [Tonus]                                       NVARCHAR (50) NULL,
    [SlizistayaObolochka]                         NVARCHAR (50) NULL,
    [Patologiya]                                  NTEXT         NULL,
    [DopolnitelnieDiagnosticheskieManipulyatsii]  NVARCHAR (1)  NULL,
    [DopolnitelnieDiagnosticheskieManipulyatsii1] NVARCHAR (1)  NULL,
    [Zaklyuchenie]                                NTEXT         NULL,
    [Combo1]                                      NVARCHAR (50) NULL,
    [SosudistiyRisunok]                           NVARCHAR (50) NULL,
    [Biopsiya]                                    NTEXT         NULL,
    [Hromoskopiya]                                NTEXT         NULL,
    [Vrach]                                       NVARCHAR (50) NULL,
    CONSTRAINT [KolonoskopiyaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [KolonoskopiyaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

