CREATE TABLE [dbo].[KonsultatsiyaNevrologaPervichnaya] (
    [ID]                                               INT           NOT NULL,
    [PatID]                                            INT           NULL,
    [Zhalobi]                                          NTEXT         NULL,
    [AnamnezZabolevaniya]                              NTEXT         NULL,
    [PerenesennieZabolevaniyaOtnosyashiesyaKOsnovnomu] NTEXT         NULL,
    [Nasledstvennost]                                  NTEXT         NULL,
    [AllergologicheskiyAnaliz]                         NTEXT         NULL,
    [Sostoyanie]                                       NVARCHAR (50) NULL,
    [Ad]                                               NVARCHAR (50) NULL,
    [PS]                                               NVARCHAR (50) NULL,
    [Kozha]                                            NTEXT         NULL,
    [EmotsionalnoKognitivnayaSfera]                    NTEXT         NULL,
    [MeningealniySindrom]                              NTEXT         NULL,
    [Chmn]                                             NTEXT         NULL,
    [DvigatelnayaSfera]                                NTEXT         NULL,
    [ChuvstvitelnieNarusheniya]                        NTEXT         NULL,
    [KoordinatnieProbi]                                NTEXT         NULL,
    [NarusheniyaFunktsiyTazovihOrganov]                NTEXT         NULL,
    [VertebralniySindrom]                              NTEXT         NULL,
    [KoreshkoviySindrom]                               NTEXT         NULL,
    [Diagnoz]                                          NTEXT         NULL,
    [Rekomendatsii]                                    NTEXT         NULL,
    [Data]                                             DATETIME      NULL,
    [AllergologicheskiyAnamnez]                        NTEXT         NULL,
    [EditBox1]                                         NVARCHAR (50) NULL,
    CONSTRAINT [KonsultatsiyaNevrologaPervichnayaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [KonsultatsiyaNevrologaPervichnayaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

