CREATE TABLE [dbo].[Koprogramma] (
    [ID]                       INT          NOT NULL,
    [PatID]                    INT          NULL,
    [NomerAnaliza]             INT          NULL,
    [DataProvedeniyaAnaliza]   DATETIME     NULL,
    [Kolichestvo]              INT          NULL,
    [Oformlenniy]              NVARCHAR (1) NULL,
    [Konsistentsiya]           INT          NULL,
    [Tsvet]                    INT          NULL,
    [Detrit]                   INT          NULL,
    [MishechnieVolokna]        NVARCHAR (1) NULL,
    [NeperevarennieMV]         FLOAT (53)   NULL,
    [PerevarennieMV]           FLOAT (53)   NULL,
    [RastitelnieVolokna]       NVARCHAR (1) NULL,
    [NeperevarennieRV]         FLOAT (53)   NULL,
    [PerevarennieRV]           FLOAT (53)   NULL,
    [Krahmal]                  FLOAT (53)   NULL,
    [YodofilnayaFlora]         INT          NULL,
    [NeytralniyZhir1]          FLOAT (53)   NULL,
    [Prosteyshie]              NVARCHAR (1) NULL,
    [TsistiLyambliy]           NVARCHAR (1) NULL,
    [KishechnieAmebi]          NVARCHAR (1) NULL,
    [YaytsaGlist]              NVARCHAR (1) NULL,
    [Ostritsi]                 NVARCHAR (1) NULL,
    [Askaridi]                 NVARCHAR (1) NULL,
    [Tiniidi]                  NVARCHAR (1) NULL,
    [Opistorhoz]               NVARCHAR (1) NULL,
    [KarlikovogoTsepnya]       NVARCHAR (1) NULL,
    [DrozhevieGribki]          FLOAT (53)   NULL,
    [Leykotsiti]               FLOAT (53)   NULL,
    [Eritrotsiti]              FLOAT (53)   NULL,
    [SoedinitelnayaTkan]       FLOAT (53)   NULL,
    [KristalliSharkoLeydena]   FLOAT (53)   NULL,
    [TsilindricheskiyEpiteliy] FLOAT (53)   NULL,
    [Reaktsiya]                INT          NULL,
    [ZhirnieKisloti]           FLOAT (53)   NULL,
    [NeytralniyZhir]           FLOAT (53)   NULL,
    [Mila]                     FLOAT (53)   NULL,
    [AlfaAmilazaObshaya]       FLOAT (53)   NULL,
    [AlfaAmilazaStabilnaya]    FLOAT (53)   NULL,
    [AlfaAmilazaLabilnaya]     FLOAT (53)   NULL,
    [OksalatCa]                FLOAT (53)   NULL,
    [Tripelfosfati]            FLOAT (53)   NULL,
    [Vrach]                    INT          NULL,
    CONSTRAINT [KoprogrammaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [KoprogrammaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

