CREATE TABLE [dbo].[LabResults] (
    [ID]                   INT            NOT NULL,
    [PatID]                INT            NULL,
    [Patient_LastName]     NVARCHAR (100) NULL,
    [Patient_FirstName]    NVARCHAR (100) NULL,
    [Patient_SecondName]   NVARCHAR (100) NULL,
    [Patient_BirthDate]    DATETIME       NULL,
    [Patient_MWPatID]      NVARCHAR (50)  NULL,
    [Patient_ExternalID]   NVARCHAR (50)  NULL,
    [Patient_ReserveID]    NVARCHAR (50)  NULL,
    [Patient_Sex]          NVARCHAR (1)   NULL,
    [ReqID]                NVARCHAR (50)  NULL,
    [ArrivedToLab]         DATETIME       NULL,
    [OrderingInstitution]  NVARCHAR (50)  NULL,
    [LabName]              NVARCHAR (50)  NULL,
    [Comment]              NVARCHAR (100) NULL,
    [LabCode]              NVARCHAR (20)  NULL,
    [DeptID]               INT            NULL,
    [AuthorUserGivenName]  NVARCHAR (50)  NULL,
    [AuthorUserFamilyName] NVARCHAR (50)  NULL,
    [AuthorUserID]         INT            NULL,
    [RegCode]              NVARCHAR (20)  NULL,
    [CollectDate]          DATETIME       NULL,
    [FinishDate]           DATETIME       NULL,
    [IDs]                  INT            NULL,
    [VrachId]              INT            NULL,
    CONSTRAINT [LabResultsPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [LabResultsToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

