CREATE TABLE [dbo].[LgotniiRecept] (
    [ID]               INT           NOT NULL,
    [MasterID]         INT           NULL,
    [LastName]         NVARCHAR (50) NULL,
    [PatId]            INT           NULL,
    [CardNum]          INT           NULL,
    [FirstName]        NVARCHAR (50) NULL,
    [SecondName]       NVARCHAR (50) NULL,
    [Дата]             DATETIME      NULL,
    [Nomer]            INT           NULL,
    [Primechanie]      NTEXT         NULL,
    [Автор]            INT           NULL,
    [RecipeNum]        NVARCHAR (50) NULL,
    [SNILSNum]         NVARCHAR (50) NULL,
    [OMSSeries]        NVARCHAR (50) NULL,
    [OMSNum]           INT           NULL,
    [Drug]             NVARCHAR (50) NULL,
    [PrivilegeValue]   NVARCHAR (50) NULL,
    [DiagnozPoMkb10]   INT           NULL,
    [ExtractDate]      DATETIME      NULL,
    [ValidityDate]     DATETIME      NULL,
    [MedicinalForm]    NVARCHAR (50) NULL,
    [FinancingSource]  NVARCHAR (50) NULL,
    [RecipeType]       NVARCHAR (50) NULL,
    [ApplicationWay]   NTEXT         NULL,
    [ReleasedPackings] NVARCHAR (50) NULL,
    [DoseMeasureUnits] NVARCHAR (50) NULL,
    [EB_CodeMKB]       NVARCHAR (20) NULL,
    [Doctor]           INT           NULL,
    [RecipeID]         NVARCHAR (50) NULL,
    CONSTRAINT [LgotniiReceptPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC)
);

