CREATE TABLE [dbo].[LN_Naznacheniya] (
    [ID]                                    INT             NOT NULL,
    [PatID]                                 INT             NULL,
    [MasterID]                              INT             NULL,
    [Preparat]                              NVARCHAR (1024) NULL,
    [Doza]                                  FLOAT (53)      NULL,
    [Kontsentratsiya]                       NVARCHAR (50)   NULL,
    [EdIzm]                                 NVARCHAR (12)   NULL,
    [DataNachala]                           DATETIME        NULL,
    [DataOkonchaniya]                       DATETIME        NULL,
    [DataOtmeni]                            DATETIME        NULL,
    [KolichestvoRazVDen]                    INT             NULL,
    [Utro]                                  NVARCHAR (1)    NULL,
    [Den]                                   NVARCHAR (1)    NULL,
    [Vecher]                                NVARCHAR (1)    NULL,
    [Noch]                                  NVARCHAR (1)    NULL,
    [OtklonenieOtGrafikaPriemaVSluchaeText] NTEXT           NULL,
    [OtklonenieOtGrafikaPriemaVSluchae]     NTEXT           NULL,
    [DniPriema]                             INT             NULL,
    [Period]                                INT             NULL,
    [OtklonenieOtGrafikaPriema]             NVARCHAR (1)    NULL,
    [ShowedPreparat]                        NVARCHAR (80)   NULL,
    [ShowedSummaryPreparat]                 NVARCHAR (100)  NULL,
    [PreparatID]                            NVARCHAR (50)   NULL,
    [MaterialID]                            INT             NULL,
    [StorageID]                             INT             NULL,
    [StorageCheckBox]                       NVARCHAR (1)    NULL,
    [ServiceID]                             INT             NULL,
    [Quantity]                              INT             NULL,
    [ServType]                              NVARCHAR (50)   NULL,
    [TakeConditions]                        NVARCHAR (50)   NULL,
    [ServiceNodeType]                       NVARCHAR (50)   NULL,
    [Resource]                              INT             NULL,
    [Place]                                 NVARCHAR (50)   NULL,
    [ShowInSched]                           BIT             NULL,
    [Duration]                              INT             NULL,
    [NochTimeBeg]                           DATETIME        NULL,
    [NochTimeEnd]                           DATETIME        NULL,
    [VecherTimeBeg]                         DATETIME        NULL,
    [VecherTimeEnd]                         DATETIME        NULL,
    [DenTimeBeg]                            DATETIME        NULL,
    [DenTimeEnd]                            DATETIME        NULL,
    [UtroTimeBeg]                           DATETIME        NULL,
    [UtroTimeEnd]                           DATETIME        NULL,
    [Changed]                               NVARCHAR (1)    NULL,
    [Service]                               NVARCHAR (12)   NULL,
    [Comment]                               NVARCHAR (1000) NULL,
    [PrichinaOtmeni]                        NTEXT           NULL,
    CONSTRAINT [LN_NaznacheniyaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [LN_NaznacheniyaToLN_ListNaznacheniy] FOREIGN KEY ([MasterID]) REFERENCES [dbo].[LN_ListNaznacheniy] ([ID]) ON DELETE CASCADE
);

