CREATE TABLE [dbo].[MedapLisObservationRequest] (
    [ID]                            INT            NOT NULL,
    [PatID]                         INT            NULL,
    [Observation_ID]                NVARCHAR (256) NULL,
    [ReportDate]                    NVARCHAR (256) NULL,
    [OrderDate]                     NVARCHAR (256) NULL,
    [OrderID]                       NVARCHAR (256) NULL,
    [SpecimenTypeID]                NVARCHAR (256) NULL,
    [CategoryID]                    NVARCHAR (256) NULL,
    [Patient_ID]                    NVARCHAR (256) NULL,
    [Patient_ExternalID]            NVARCHAR (256) NULL,
    [Patient_GivenName]             NVARCHAR (256) NULL,
    [Patient_FamilyName]            NVARCHAR (256) NULL,
    [Patient_Gender]                NVARCHAR (256) NULL,
    [Patient_BirthDate]             NVARCHAR (256) NULL,
    [Patient_RegDate]               NVARCHAR (256) NULL,
    [OrderingInstitution_LocalName] NVARCHAR (256) NULL,
    [Subcontractor_ID]              NVARCHAR (256) NULL,
    [Subcontractor_LocalName]       NVARCHAR (256) NULL,
    [Observation_IDs]               NVARCHAR (256) NULL,
    [RegDate]                       NVARCHAR (256) NULL,
    [VisitID]                       NVARCHAR (256) NULL,
    [Status]                        NVARCHAR (256) NULL,
    [SpecimenType]                  NVARCHAR (50)  NULL,
    [Category]                      NVARCHAR (50)  NULL,
    CONSTRAINT [MedapLisObservationRequestPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [MedapLisObservationRequestToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

