CREATE TABLE [dbo].[MeditsinskayaKartaStatsionarnogoBolnogoF003U] (
    [ID]                                      INT           NOT NULL,
    [PatID]                                   INT           NULL,
    [Nomer]                                   FLOAT (53)    NULL,
    [DataIVremyaPostupleniya]                 DATETIME      NULL,
    [DataIVremyaVipiski]                      DATETIME      NULL,
    [DataIVremyaVipiski1]                     FLOAT (53)    NULL,
    [DataIVremyaPostupleniya1]                FLOAT (53)    NULL,
    [Otdelenie]                               INT           NULL,
    [PalataNomer]                             INT           NULL,
    [PerevedenVOtdelenie]                     NVARCHAR (50) NULL,
    [ProvedenoKoykoDney]                      INT           NULL,
    [VidiTransportirovki]                     NVARCHAR (50) NULL,
    [GruppaKrovi]                             NVARCHAR (50) NULL,
    [PobochnoeDeystvieLekarstvNeperenosimost] NTEXT         NULL,
    [RezusPrinadlezhnost]                     NVARCHAR (50) NULL,
    [Otchestvo]                               NVARCHAR (50) NULL,
    [familia]                                 NVARCHAR (50) NULL,
    [Imya]                                    NVARCHAR (50) NULL,
    [pol]                                     NVARCHAR (50) NULL,
    [vozrast]                                 NVARCHAR (50) NULL,
    [mesto]                                   NVARCHAR (50) NULL,
    [adres]                                   NTEXT         NULL,
    [adres1]                                  NTEXT         NULL,
    [rabota]                                  NVARCHAR (50) NULL,
    [rabota1]                                 NTEXT         NULL,
    [kemnapravlen]                            NVARCHAR (50) NULL,
    [dostavlen]                               NVARCHAR (50) NULL,
    [chas]                                    NVARCHAR (50) NULL,
    [Cherez]                                  NVARCHAR (1)  NULL,
    [GospitalizirovanVPlanovomPoryadke]       NVARCHAR (1)  NULL,
    [ChasovPosle]                             NVARCHAR (50) NULL,
    [Diagnoznapravivshego]                    NVARCHAR (50) NULL,
    [Diagnozklinicheskiy]                     NVARCHAR (50) NULL,
    [DataUstanovleniya]                       DATETIME      NULL,
    [Diagnozpripostuplenii]                   NVARCHAR (50) NULL,
    [AOsnovnoy]                               NVARCHAR (50) NULL,
    [BOslozhnenieOsnovnogo]                   NVARCHAR (50) NULL,
    [VSoputstvuyushiy]                        NVARCHAR (50) NULL,
    [gospitalizirovan]                        NVARCHAR (50) NULL,
    [Vsego]                                   NVARCHAR (50) NULL,
    [drogoelechenie]                          NTEXT         NULL,
    [speclechenie]                            NVARCHAR (50) NULL,
    [speclechenie1]                           NVARCHAR (50) NULL,
    [palliativnoe]                            NVARCHAR (50) NULL,
    [simptomaticheskoe]                       NVARCHAR (50) NULL,
    [Nomer1]                                  INT           NULL,
    [S]                                       DATETIME      NULL,
    [S1]                                      DATETIME      NULL,
    [Nomer2]                                  INT           NULL,
    [Nomer3]                                  INT           NULL,
    [S2]                                      DATETIME      NULL,
    [Po]                                      DATETIME      NULL,
    [Po1]                                     DATETIME      NULL,
    [Po2]                                     DATETIME      NULL,
    [V]                                       NVARCHAR (50) NULL,
    [Vipisan]                                 NVARCHAR (50) NULL,
    [Vipisan1]                                NVARCHAR (1)  NULL,
    [UmerVPriemnomOtdelenii]                  NVARCHAR (1)  NULL,
    [UmerlaBeremennayaDo28NedelBeremennosti]  NVARCHAR (1)  NULL,
    [UmerlaPosle28NedelBeremennosti]          NVARCHAR (1)  NULL,
    [trudosposobnost]                         NVARCHAR (50) NULL,
    [zakluchenie]                             NTEXT         NULL,
    [osobieotmetki]                           NTEXT         NULL,
    [LechashiyVrach]                          NVARCHAR (50) NULL,
    [ZavOtdeleniem]                           NVARCHAR (50) NULL,
    [Data]                                    DATETIME      NULL,
    [Vrach]                                   NVARCHAR (50) NULL,
    [zapis]                                   NTEXT         NULL,
    [Zhalobi]                                 NTEXT         NULL,
    [AnamnezZabolevaniya]                     NTEXT         NULL,
    [LichnayaJizny]                           NTEXT         NULL,
    [PerenesennieZabolevaniya]                NTEXT         NULL,
    [CemeyniyAnamnez]                         NTEXT         NULL,
    [VredniePrivichki]                        NTEXT         NULL,
    [Produktov]                               NTEXT         NULL,
    [Medikamentov]                            NTEXT         NULL,
    [GruppaKrovi1]                            NVARCHAR (50) NULL,
    [Rh]                                      NVARCHAR (50) NULL,
    [TransfuziiRanshe]                        NVARCHAR (50) NULL,
    [NalichieOslozhneniyTransfuzii]           NTEXT         NULL,
    [UpotreblenieNarkotikov]                  NVARCHAR (50) NULL,
    [LichnayaGigiena]                         NVARCHAR (50) NULL,
    [UpotreblenieSiroyVodi]                   NVARCHAR (50) NULL,
    [IstochnikPitevoyVodi]                    NVARCHAR (50) NULL,
    [BitovieUsloviya]                         NVARCHAR (50) NULL,
    [Inektsii]                                NVARCHAR (1)  NULL,
    [LechenieUStomatologa]                    NVARCHAR (1)  NULL,
    [Operatsii]                               NVARCHAR (1)  NULL,
    [Transfuzii]                              NVARCHAR (1)  NULL,
    [DictCombo8]                              NVARCHAR (50) NULL,
    [Tb]                                      NVARCHAR (1)  NULL,
    [Vich]                                    NVARCHAR (1)  NULL,
    [Malyariya]                               NVARCHAR (1)  NULL,
    [Tif]                                     NVARCHAR (1)  NULL,
    [Paratif]                                 NVARCHAR (1)  NULL,
    [Gepatit]                                 NVARCHAR (1)  NULL,
    [Zpp]                                     NVARCHAR (50) NULL,
    [AOsnovnoy1]                              NVARCHAR (50) NULL,
    [BOslozhnenieOsnovnogo1]                  NVARCHAR (50) NULL,
    [VSoputstvuyushiy1]                       NVARCHAR (50) NULL,
    [DictCombo1]                              NVARCHAR (50) NULL,
    [WardID]                                  INT           NULL,
    [SpecialTreatment]                        NVARCHAR (50) NULL,
    [SicknessResult]                          NVARCHAR (50) NULL,
    [DismissToHospitalName]                   NVARCHAR (50) NULL,
    CONSTRAINT [MeditsinskayaKartaStatsionarnogoBolnogoF003UPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [MeditsinskayaKartaStatsionarnogoBolnogoF003UToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

