CREATE TABLE [dbo].[MedihostOrder] (
    [ID]                 BIGINT         NOT NULL,
    [Status]             INT            NULL,
    [user_id]            INT            NULL,
    [user_name]          NVARCHAR (50)  NULL,
    [order_date]         DATETIME       NULL,
    [MW_Resource_ID]     INT            NULL,
    [Resource_Name]      NVARCHAR (50)  NULL,
    [Resource_ID]        INT            NULL,
    [Reception_Datetime] DATETIME       NULL,
    [Duration]           INT            NULL,
    [Type]               NVARCHAR (50)  NULL,
    [Name1]              NVARCHAR (50)  NULL,
    [Name2]              NVARCHAR (50)  NULL,
    [Name3]              NVARCHAR (50)  NULL,
    [Aim]                NVARCHAR (50)  NULL,
    [Phone]              NVARCHAR (100) NULL,
    [City]               NVARCHAR (50)  NULL,
    [Address]            NVARCHAR (100) NULL,
    [Email]              NVARCHAR (100) NULL,
    [LastChangedOn]      DATETIME       NULL,
    [ImportedOn]         DATETIME       NULL,
    [Changed]            BIT            NULL,
    [Comment]            NTEXT          NULL,
    [PatID]              INT            NULL,
    [ShowInSchedule]     BIT            NULL,
    [Policy_type]        NUMERIC (11)   NULL,
    [Policy_ser]         NVARCHAR (16)  NULL,
    [Policy_num]         NVARCHAR (50)  NULL,
    [BirthDay]           DATETIME       NULL,
    [NapravlenieID]      INT            NULL,
    CONSTRAINT [MedihostOrderPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC)
);

