CREATE TABLE [dbo].[MedZaklyuchenie] (
    [ID]           INT           NOT NULL,
    [PatID]        INT           NULL,
    [NomerZakl]    NVARCHAR (50) NULL,
    [DateZakl]     DATETIME      NULL,
    [ФИО]          NVARCHAR (80) NULL,
    [DR]           DATETIME      NULL,
    [Memo1]        NTEXT         NULL,
    [MestoRozh]    NTEXT         NULL,
    [Pol]          NVARCHAR (50) NULL,
    [Dokument]     NTEXT         NULL,
    [MestoVidachi] NTEXT         NULL,
    [MestoZhi]     NVARCHAR (80) NULL,
    [Subjekt]      NVARCHAR (70) NULL,
    [Raion]        NVARCHAR (50) NULL,
    [Gorod]        NVARCHAR (50) NULL,
    [NaselP]       NVARCHAR (50) NULL,
    [Ulica]        NVARCHAR (50) NULL,
    [Dom]          NVARCHAR (50) NULL,
    [Kvartira]     NVARCHAR (50) NULL,
    [StranaProzh]  NVARCHAR (50) NULL,
    [Period]       NVARCHAR (50) NULL,
    [DiagDict]     NVARCHAR (50) NULL,
    [DiagCode]     NVARCHAR (6)  NULL,
    [Vrach]        INT           NULL,
    [DateOsv]      DATETIME      NULL,
    [Upolnomoch]   NVARCHAR (60) NULL,
    [NalOts]       NVARCHAR (50) NULL,
    CONSTRAINT [MedZaklyucheniePrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [MedZaklyuchenieToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

