CREATE TABLE [dbo].[MInsem] (
    [Id]              INT            NOT NULL,
    [ParentId]        INT            NULL,
    [PatId]           INT            NULL,
    [Descr]           VARCHAR (150)  NULL,
    [ExecDate]        DATETIME       NULL,
    [TryNo]           INT            NULL,
    [DayMC]           INT            NULL,
    [UZOv]            BIT            NULL,
    [DonorNum]        NVARCHAR (20)  NULL,
    [Fresh]           BIT            NULL,
    [GotTime]         DATETIME       NULL,
    [LiqTime]         FLOAT (53)     NULL,
    [Volume]          NVARCHAR (10)  NULL,
    [ClamId]          INT            NULL,
    [a1]              FLOAT (53)     NULL,
    [b1]              FLOAT (53)     NULL,
    [c1]              FLOAT (53)     NULL,
    [ProdMethodId]    INT            NULL,
    [a2]              FLOAT (53)     NULL,
    [b2]              FLOAT (53)     NULL,
    [c2]              FLOAT (53)     NULL,
    [IVolume]         FLOAT (53)     NULL,
    [SpOo]            FLOAT (53)     NULL,
    [CathId]          INT            NULL,
    [Comment]         NTEXT          NULL,
    [EmbrOperId]      INT            NULL,
    [PayNeed]         BIT            NULL,
    [Payed]           BIT            NULL,
    [PaySum]          MONEY          NULL,
    [PayedSum]        MONEY          NULL,
    [PayDate]         DATETIME       NULL,
    [PayComment]      VARCHAR (255)  NULL,
    [OperId]          INT            NULL,
    [OriginalID]      INT            NULL,
    [aa1]             FLOAT (53)     NULL,
    [aa2]             FLOAT (53)     NULL,
    [bb1]             FLOAT (53)     NULL,
    [bb2]             FLOAT (53)     NULL,
    [PartnerFullName] NVARCHAR (100) NULL,
    [Stim]            BIT            NULL,
    CONSTRAINT [PK_MInsem] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_MInsem_PatForm] FOREIGN KEY ([Id]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

