CREATE TABLE [dbo].[MNTK_Diag] (
    [ID]                  INT           NOT NULL,
    [DBFFile]             NVARCHAR (12) NULL,
    [RecNo]               INT           NULL,
    [source]              NVARCHAR (10) NULL,
    [BillServiceID]       INT           NULL,
    [PaymentID]           INT           NULL,
    [PaymentID_MoneyBack] INT           NULL,
    [NOMAMB]              NVARCHAR (8)  NULL,
    [DATUSL]              DATETIME      NULL,
    [PP]                  NVARCHAR (1)  NULL,
    [EYE]                 NVARCHAR (1)  NULL,
    [NXD]                 NVARCHAR (6)  NULL,
    [VZR]                 INT           NULL,
    [POL]                 NVARCHAR (1)  NULL,
    [KODRAZ]              NVARCHAR (2)  NULL,
    [KODUSL]              NVARCHAR (2)  NULL,
    [KODKATU]             NVARCHAR (1)  NULL,
    [KODKATO]             NVARCHAR (2)  NULL,
    [KODVAL]              NVARCHAR (2)  NULL,
    [CENA]                MONEY         NULL,
    [KODPRVOZ]            NVARCHAR (2)  NULL,
    [KODISP]              NVARCHAR (4)  NULL,
    [KODOPER]             NVARCHAR (4)  NULL,
    [KODBRIG]             NVARCHAR (2)  NULL,
    [NUMSCH]              NVARCHAR (6)  NULL,
    [FAM]                 NVARCHAR (20) NULL,
    [KODLG]               NVARCHAR (2)  NULL,
    [DATOTCH]             DATETIME      NULL,
    [NAL]                 MONEY         NULL,
    [DATNAL]              DATETIME      NULL,
    [VOZVRNAL]            MONEY         NULL,
    [DVNAL]               DATETIME      NULL,
    [BEZNAL]              MONEY         NULL,
    [DATBEZN]             DATETIME      NULL,
    [VOZVRBN]             MONEY         NULL,
    [DVBEZN]              DATETIME      NULL,
    [KODKASS]             NVARCHAR (4)  NULL,
    [NUMRAORD]            NVARCHAR (5)  NULL,
    [TIMBEZN]             NVARCHAR (4)  NULL,
    [KODREL]              NVARCHAR (13) NULL,
    [MECR]                NVARCHAR (2)  NULL,
    [MARK]                NVARCHAR (1)  NULL,
    [DATAGENT]            DATETIME      NULL,
    [KODAGENT]            NVARCHAR (4)  NULL,
    [OlkRecNo]            INT           NULL,
    [UpdateTime]          DATETIME      NULL,
    [ExportTime]          DATETIME      NULL,
    CONSTRAINT [PK_MNTK_Diag] PRIMARY KEY CLUSTERED ([ID] ASC)
);

