CREATE TABLE [dbo].[MNTK_RAMB] (
    [ID]            INT            NOT NULL,
    [PatID]         INT            NULL,
    [NOMAMB]        NVARCHAR (8)   NULL,
    [PERV]          INT            NULL,
    [OT]            NVARCHAR (20)  NULL,
    [IM]            NVARCHAR (20)  NULL,
    [FAM]           NVARCHAR (20)  NULL,
    [DATA_ROJD]     DATETIME       NULL,
    [POL]           INT            NULL,
    [GOR_SEL]       INT            NULL,
    [KOD_STR]       INT            NULL,
    [REGION]        INT            NULL,
    [RAION]         INT            NULL,
    [ADR]           NVARCHAR (60)  NULL,
    [TLF]           NVARCHAR (13)  NULL,
    [RABOTA]        NVARCHAR (75)  NULL,
    [SNILS]         NVARCHAR (14)  NULL,
    [VD]            INT            NULL,
    [SD]            NVARCHAR (10)  NULL,
    [ND]            NVARCHAR (20)  NULL,
    [DATVYD]        DATETIME       NULL,
    [KEMVYDAN]      NVARCHAR (75)  NULL,
    [SOCS]          NVARCHAR (2)   NULL,
    [INVALID]       NVARCHAR (2)   NULL,
    [NOMERUD]       NVARCHAR (14)  NULL,
    [LG]            NVARCHAR (2)   NULL,
    [SP]            NVARCHAR (2)   NULL,
    [OBR]           NVARCHAR (1)   NULL,
    [SFERA]         NVARCHAR (2)   NULL,
    [OMS]           NVARCHAR (75)  NULL,
    [OMSS]          NVARCHAR (10)  NULL,
    [OMSN]          NVARCHAR (20)  NULL,
    [DMS]           NVARCHAR (75)  NULL,
    [DMSS]          NVARCHAR (10)  NULL,
    [DMSN]          NVARCHAR (20)  NULL,
    [POISKNOM]      NVARCHAR (9)   NULL,
    [TEL_SL]        NVARCHAR (7)   NULL,
    [TEL_DOM]       NVARCHAR (7)   NULL,
    [SOC_POL]       INT            NULL,
    [DIAG11]        INT            NULL,
    [DIAG12]        INT            NULL,
    [DIAG21]        INT            NULL,
    [DIAG22]        INT            NULL,
    [XOZR]          INT            NULL,
    [LIGOT1]        INT            NULL,
    [LIGOT2]        INT            NULL,
    [VRACH]         INT            NULL,
    [DATA_OBR]      DATETIME       NULL,
    [AdresRegion]   NVARCHAR (50)  NULL,
    [AdresRaion]    NVARCHAR (50)  NULL,
    [AdresGorod]    NVARCHAR (100) NULL,
    [AdresNasPunkt] NVARCHAR (50)  NULL,
    [AdresUlitsa]   NVARCHAR (70)  NULL,
    [AdresDom]      NVARCHAR (10)  NULL,
    [AdresKorpus]   NVARCHAR (10)  NULL,
    [AdresStroenie] NVARCHAR (8)   NULL,
    [AdresKvartira] NVARCHAR (10)  NULL,
    [TLF2]          NVARCHAR (50)  NULL,
    CONSTRAINT [MNTK_RAMBPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [MNTK_RAMBToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

