CREATE TABLE [dbo].[NagruzochnayaProba] (
    [ID]                                    INT           NOT NULL,
    [PatID]                                 INT           NULL,
    [Data]                                  DATETIME      NULL,
    [Vrach]                                 NVARCHAR (50) NULL,
    [PolPatsienta]                          NVARCHAR (50) NULL,
    [Protokol]                              NTEXT         NULL,
    [SubmaksimalnayaChss]                   INT           NULL,
    [IshodnayaChssVMin]                     INT           NULL,
    [IshodnoeAd]                            INT           NULL,
    [IshodnoeAd1]                           INT           NULL,
    [MaksimalnayaChss]                      NVARCHAR (50) NULL,
    [MaksimalnoeAd]                         INT           NULL,
    [MaksimalnoeAd1]                        INT           NULL,
    [MetWt]                                 INT           NULL,
    [G]                                     INT           NULL,
    [VKmCh]                                 INT           NULL,
    [DolzhnayaNagruzkaMetWt]                NVARCHAR (50) NULL,
    [ZhalobiVoVremyaTesta]                  NTEXT         NULL,
    [PrichinaOstanovki]                     NVARCHAR (50) NULL,
    [IzmeneniyaSTT]                         NTEXT         NULL,
    [NarusheniyaRitma]                      NTEXT         NULL,
    [TipReaktsii]                           NVARCHAR (50) NULL,
    [TolerantnostKFizicheskoyNagruzke]      NTEXT         NULL,
    [VosstanovleniePokazateleyGemodinamiki] NTEXT         NULL,
    [Zaklyuchenie]                          NTEXT         NULL,
    [Primechaniya]                          NTEXT         NULL,
    CONSTRAINT [NagruzochnayaProbaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [NagruzochnayaProbaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

