CREATE TABLE [dbo].[NapravlenieNaMedSotsEkspertizu] (
    [ID]                                   INT           NOT NULL,
    [PatID]                                INT           NULL,
    [NaimenUhrejd]                         NVARCHAR (50) NULL,
    [Adres]                                NVARCHAR (50) NULL,
    [DataVidah]                            DATETIME      NULL,
    [UslovRabotZaGod]                      NTEXT         NULL,
    [RezultProvMeropr]                     NTEXT         NULL,
    [OsnovZabolev]                         NVARCHAR (50) NULL,
    [SoputstvuyushieZabolevaniya]          NTEXT         NULL,
    [Oslozhneniya]                         NTEXT         NULL,
    [NarusheniyaOsnovnihFunktsiyOrganizma] NTEXT         NULL,
    [PriznOgrJizned]                       NTEXT         NULL,
    [NalPriznakInvalidn]                   NVARCHAR (1)  NULL,
    [OkonchSrokInvalid]                    NVARCHAR (1)  NULL,
    [Dosrochn]                             NVARCHAR (1)  NULL,
    [Pereosvidetelstv]                     NVARCHAR (1)  NULL,
    [NeobhodProdlBolnList]                 NVARCHAR (1)  NULL,
    [SostBolnogo]                          NTEXT         NULL,
    [Rentgen]                              NTEXT         NULL,
    [LabaratIssled]                        NTEXT         NULL,
    [DopMetIssled]                         NTEXT         NULL,
    [Memo4]                                NTEXT         NULL,
    [DateBox1]                             DATETIME      NULL,
    [DateBox2]                             DATETIME      NULL,
    [Predsedatel]                          NVARCHAR (50) NULL,
    [ChelenKEK1]                           NVARCHAR (50) NULL,
    [ChelenKEK]                            NVARCHAR (50) NULL,
    [ChelenKEK2]                           NVARCHAR (50) NULL,
    CONSTRAINT [NapravlenieNaMedSotsEkspertizuPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [NapravlenieNaMedSotsEkspertizuToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

