CREATE TABLE [dbo].[NapravlenieNaPatologogisticheskoeIssledovanie] (
    [ID]              INT           NOT NULL,
    [PatID]           INT           NULL,
    [Hospital]        NVARCHAR (50) NULL,
    [Nissled1]        INT           NULL,
    [Biopsy]          NVARCHAR (50) NULL,
    [Date]            DATETIME      NULL,
    [OperType]        NVARCHAR (50) NULL,
    [MarkAndObjCount] NTEXT         NULL,
    [ClinicData]      NTEXT         NULL,
    [ClinicDiag]      NTEXT         NULL,
    [TakeCareOf]      NTEXT         NULL,
    [DateMatIn]       DATETIME      NULL,
    [HourMatIn]       INT           NULL,
    [Vrach]           INT           NULL,
    [sign]            NVARCHAR (50) NULL,
    [DateMatGot]      DATETIME      NULL,
    [HourMatGot]      INT           NULL,
    [Nissled]         INT           NULL,
    [Painttype]       NVARCHAR (50) NULL,
    [MakroMicroZakl]  NTEXT         NULL,
    [DatePrepDone]    DATETIME      NULL,
    [HourPrepDone]    INT           NULL,
    [DatePatolIssled] DATETIME      NULL,
    [HourPatolIssled] INT           NULL,
    [Vrach1]          INT           NULL,
    [PatolSign]       NVARCHAR (50) NULL,
    [Otdelenie]       INT           NULL,
    CONSTRAINT [NapravlenieNaPatologogisticheskoeIssledovaniePrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [NapravlenieNaPatologogisticheskoeIssledovanieToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

