CREATE TABLE [dbo].[NaturopaticNutrition] (
    [ID]                           INT          NOT NULL,
    [PatID]                        INT          NULL,
    [HighGlucose]                  NVARCHAR (1) NULL,
    [HighCholesterol]              NVARCHAR (1) NULL,
    [HighTriglycerides]            NVARCHAR (1) NULL,
    [LackOfProtein]                NVARCHAR (1) NULL,
    [LackOfFattyAcids]             NVARCHAR (1) NULL,
    [LackOfVitaminsMinerals]       NVARCHAR (1) NULL,
    [Anemia]                       NVARCHAR (1) NULL,
    [HighBloodPressure]            NVARCHAR (1) NULL,
    [MalfunctionOfLiver]           NVARCHAR (1) NULL,
    [MalfunctionOfKidneys]         NVARCHAR (1) NULL,
    [ThickBloodFlow]               NVARCHAR (1) NULL,
    [Malabsorbption]               NVARCHAR (1) NULL,
    [Hypothyroid]                  NVARCHAR (1) NULL,
    [Hygerthyroid]                 NVARCHAR (1) NULL,
    [Vegetarian]                   NVARCHAR (1) NULL,
    [HormonalImbalance]            NVARCHAR (1) NULL,
    [ImmuneLoad]                   NVARCHAR (1) NULL,
    [Allergies]                    NVARCHAR (1) NULL,
    [Seborthea]                    NVARCHAR (1) NULL,
    [AcidicBlood]                  NVARCHAR (1) NULL,
    [AutoimmuneTyroiditis]         NVARCHAR (1) NULL,
    [WholeGrains]                  NVARCHAR (1) NULL,
    [Legumes]                      NVARCHAR (1) NULL,
    [GrainsLegumes]                NVARCHAR (1) NULL,
    [Cereals]                      NVARCHAR (1) NULL,
    [MeatChickenFish]              NVARCHAR (1) NULL,
    [FishWithOmega3]               NVARCHAR (1) NULL,
    [Eggs]                         NVARCHAR (1) NULL,
    [Vegetables]                   NVARCHAR (1) NULL,
    [Fruits]                       NVARCHAR (1) NULL,
    [NutsAlmonds]                  NVARCHAR (1) NULL,
    [MilkProducts]                 NVARCHAR (1) NULL,
    [OliveOil]                     NVARCHAR (1) NULL,
    [CanolaSunflowerOil]           NVARCHAR (1) NULL,
    [Drinks]                       NVARCHAR (1) NULL,
    [GrainsCoffee]                 NVARCHAR (1) NULL,
    [Sweetening]                   NVARCHAR (1) NULL,
    [Fibers]                       NVARCHAR (1) NULL,
    [CarrotCeleryJuice]            NVARCHAR (1) NULL,
    [Garlic]                       NVARCHAR (1) NULL,
    [Hypothyroid_rf]               NVARCHAR (1) NULL,
    [Hyperthyroid_rf]              NVARCHAR (1) NULL,
    [PomegranateJuice]             NVARCHAR (1) NULL,
    [Iron]                         NVARCHAR (1) NULL,
    [VitaminB12]                   NVARCHAR (1) NULL,
    [FolicAcid]                    NVARCHAR (1) NULL,
    [Zinc]                         NVARCHAR (1) NULL,
    [Calcium]                      NVARCHAR (1) NULL,
    [Magnesium]                    NVARCHAR (1) NULL,
    [Potassium]                    NVARCHAR (1) NULL,
    [Sulphur]                      NVARCHAR (1) NULL,
    [Silica]                       NVARCHAR (1) NULL,
    [Selenium]                     NVARCHAR (1) NULL,
    [ComplexB]                     NVARCHAR (1) NULL,
    [VitaminsACE]                  NVARCHAR (1) NULL,
    [SugarSubstitutesDietProducts] NVARCHAR (1) NULL,
    [FriedFood]                    NVARCHAR (1) NULL,
    [ProcessedFood]                NVARCHAR (1) NULL,
    [Sweets]                       NVARCHAR (1) NULL,
    [ProcessedMeats]               NVARCHAR (1) NULL,
    [FattyMilkProducts]            NVARCHAR (1) NULL,
    [CoffeOrBlackTea]              NVARCHAR (1) NULL,
    [Alcohol]                      NVARCHAR (1) NULL,
    [Salt]                         NVARCHAR (1) NULL,
    [Hypothyroid_lf]               NVARCHAR (1) NULL,
    [Hyperthyroid_lf]              NVARCHAR (1) NULL,
    [DocDate]                      DATETIME     NULL,
    [DocTime]                      DATETIME     NULL,
    [DoctorID]                     INT          NULL,
    CONSTRAINT [NaturopaticNutritionPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [NaturopaticNutritionToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

