CREATE TABLE [dbo].[NaturopaticBloodTest] (
    [ID]                   INT        NOT NULL,
    [PatID]                INT        NULL,
    [Value_12_1]           FLOAT (53) NULL,
    [Value_12_2]           FLOAT (53) NULL,
    [Value_12_3]           FLOAT (53) NULL,
    [Value_12_4]           FLOAT (53) NULL,
    [Value_12_5]           FLOAT (53) NULL,
    [Value_12_6]           FLOAT (53) NULL,
    [Value_12_7]           FLOAT (53) NULL,
    [Value_12_8]           FLOAT (53) NULL,
    [Value_12_9]           FLOAT (53) NULL,
    [Value_12_10]          FLOAT (53) NULL,
    [Value_12_11]          FLOAT (53) NULL,
    [Value_12_12]          FLOAT (53) NULL,
    [Value_12_13]          FLOAT (53) NULL,
    [Value_12_14]          FLOAT (53) NULL,
    [Value_12_15]          FLOAT (53) NULL,
    [Value_12_16]          FLOAT (53) NULL,
    [Value_12_17]          FLOAT (53) NULL,
    [Value_12_18]          FLOAT (53) NULL,
    [AdditionalChemestry1] NTEXT      NULL,
    [Value_13_1]           FLOAT (53) NULL,
    [Value_13_2]           FLOAT (53) NULL,
    [Value_13_3]           FLOAT (53) NULL,
    [Value_13_4]           FLOAT (53) NULL,
    [Value_13_5]           FLOAT (53) NULL,
    [Value_13_6]           FLOAT (53) NULL,
    [Value_13_7]           FLOAT (53) NULL,
    [Value_13_8]           FLOAT (53) NULL,
    [Value_13_9]           FLOAT (53) NULL,
    [Value_13_10]          FLOAT (53) NULL,
    [AdditionalChemestry2] NTEXT      NULL,
    [Value_14_1]           FLOAT (53) NULL,
    [Value_14_2]           FLOAT (53) NULL,
    [Value_14_3]           FLOAT (53) NULL,
    [Value_14_4]           FLOAT (53) NULL,
    [Value_14_5]           FLOAT (53) NULL,
    [Value_14_6]           FLOAT (53) NULL,
    [Value_14_7]           FLOAT (53) NULL,
    [Value_14_8]           FLOAT (53) NULL,
    [Value_14_9]           FLOAT (53) NULL,
    [Value_14_10]          FLOAT (53) NULL,
    [Value_14_11]          FLOAT (53) NULL,
    [Value_14_12]          FLOAT (53) NULL,
    [Value_14_13]          FLOAT (53) NULL,
    [Value_14_14]          FLOAT (53) NULL,
    [Value_14_15]          FLOAT (53) NULL,
    [Value_13_11]          FLOAT (53) NULL,
    [AdditionalCBC]        NTEXT      NULL,
    [Value_15_1]           FLOAT (53) NULL,
    [Value_14_16]          FLOAT (53) NULL,
    [Value_14_17]          FLOAT (53) NULL,
    [Value_15_2]           FLOAT (53) NULL,
    [Value_15_3]           FLOAT (53) NULL,
    [Value_15_4]           FLOAT (53) NULL,
    [Value_15_5]           FLOAT (53) NULL,
    [Value_15_6]           FLOAT (53) NULL,
    [Value_15_7]           FLOAT (53) NULL,
    [Value_15_8]           FLOAT (53) NULL,
    [Value_15_9]           FLOAT (53) NULL,
    [Value_14_18]          FLOAT (53) NULL,
    [Value_14_19]          FLOAT (53) NULL,
    [AdditionalHormones]   NTEXT      NULL,
    [DocDate]              DATETIME   NULL,
    [DocTime]              DATETIME   NULL,
    [DoctorID]             INT        NULL,
    [Notes]                NTEXT      NULL,
    CONSTRAINT [NaturopaticBloodTestPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [NaturopaticBloodTestToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

