CREATE TABLE [dbo].[NevrologicheskoeIssledovanie] (
    [ID]                                      INT            NOT NULL,
    [PatID]                                   INT            NULL,
    [Rech]                                    NVARCHAR (50)  NULL,
    [Chtenie]                                 NVARCHAR (50)  NULL,
    [Praksis]                                 NVARCHAR (50)  NULL,
    [ShemaTela]                               NVARCHAR (50)  NULL,
    [Schet]                                   NVARCHAR (50)  NULL,
    [Pismo]                                   NVARCHAR (50)  NULL,
    [Nasledstvennost]                         NTEXT          NULL,
    [SostoyanieSoznaniya]                     NVARCHAR (50)  NULL,
    [ObshemozgovieSimptomi]                   NTEXT          NULL,
    [ObshemozgovieSimptomi1]                  NTEXT          NULL,
    [Memo1]                                   NTEXT          NULL,
    [Memo2]                                   NTEXT          NULL,
    [Memo3]                                   NTEXT          NULL,
    [Povedenie]                               NVARCHAR (50)  NULL,
    [Pamyat]                                  NVARCHAR (50)  NULL,
    [Depressiya]                              NVARCHAR (1)   NULL,
    [Eyforiya]                                NVARCHAR (1)   NULL,
    [Apatiya]                                 NVARCHAR (1)   NULL,
    [Vyalost]                                 NVARCHAR (1)   NULL,
    [Vnimanie]                                NVARCHAR (50)  NULL,
    [Soznanie]                                NVARCHAR (50)  NULL,
    [PovorotiGoloviIShei]                     NVARCHAR (50)  NULL,
    [DvizheniyaPlech]                         NVARCHAR (50)  NULL,
    [Dizartriya]                              NVARCHAR (1)   NULL,
    [GlotochniyRefleks]                       NVARCHAR (50)  NULL,
    [NBniyRefleks]                            NVARCHAR (50)  NULL,
    [Atrofichen]                              NVARCHAR (1)   NULL,
    [Yazik]                                   NVARCHAR (50)  NULL,
    [Golos]                                   INT            NULL,
    [NBnieZanaveskiIYazichok]                 NVARCHAR (50)  NULL,
    [Glotanie]                                INT            NULL,
    [ProbaRinne]                              NVARCHAR (50)  NULL,
    [Golovokrujenie1]                         INT            NULL,
    [Golovokrujenie]                          NVARCHAR (1)   NULL,
    [SnijenieSluha]                           NVARCHAR (1)   NULL,
    [ShumVUshah]                              NVARCHAR (1)   NULL,
    [Nistagm]                                 NVARCHAR (1)   NULL,
    [OstrotaSluha]                            NVARCHAR (50)  NULL,
    [VPozeRomberga]                           INT            NULL,
    [ProbaVebera]                             NVARCHAR (50)  NULL,
    [Litso]                                   INT            NULL,
    [Parez]                                   INT            NULL,
    [D]                                       NVARCHAR (1)   NULL,
    [C]                                       NVARCHAR (1)   NULL,
    [Lagoftalm]                               NVARCHAR (1)   NULL,
    [DvizheniyaGlaznihYablok]                 NVARCHAR (50)  NULL,
    [Diplopiya2]                              NVARCHAR (1)   NULL,
    [ShodyasheesyaKosoglazie1]                NVARCHAR (1)   NULL,
    [D1]                                      NVARCHAR (1)   NULL,
    [D2]                                      NVARCHAR (1)   NULL,
    [D3]                                      NVARCHAR (1)   NULL,
    [C1]                                      NVARCHAR (1)   NULL,
    [C2]                                      NVARCHAR (1)   NULL,
    [C3]                                      NVARCHAR (1)   NULL,
    [ShodyasheesyaKosoglazie]                 NVARCHAR (1)   NULL,
    [Diplopiya1]                              NVARCHAR (1)   NULL,
    [DvizhenieGlaznihYablok]                  INT            NULL,
    [Kosoglazie]                              NVARCHAR (1)   NULL,
    [Konvergentsiya]                          NVARCHAR (50)  NULL,
    [Ptoz]                                    NVARCHAR (1)   NULL,
    [Diplopiya]                               NVARCHAR (1)   NULL,
    [Ekzoftalm]                               NVARCHAR (1)   NULL,
    [Anizokoriya]                             NVARCHAR (1)   NULL,
    [Akkomodatsiya]                           NVARCHAR (50)  NULL,
    [FotoreaktsiyaNaSvet1]                    INT            NULL,
    [FotoreaktsiyaNaSvet]                     NVARCHAR (50)  NULL,
    [Zrachki]                                 INT            NULL,
    [PolyaZreniya]                            NVARCHAR (50)  NULL,
    [Tsvetooshushenie]                        NVARCHAR (50)  NULL,
    [OS]                                      NVARCHAR (50)  NULL,
    [OD]                                      NVARCHAR (50)  NULL,
    [IPara]                                   NVARCHAR (50)  NULL,
    [ObemAktivnihI]                           NTEXT          NULL,
    [Sila]                                    NTEXT          NULL,
    [Tonus]                                   NTEXT          NULL,
    [Atrofii]                                 NTEXT          NULL,
    [Atrofii1]                                NTEXT          NULL,
    [Atrofii2]                                NTEXT          NULL,
    [Koordinatsiya]                           NTEXT          NULL,
    [ReaktsiyaOpori]                          NVARCHAR (100) NULL,
    [NaVerzhnihKonechnostyahRossolimo]        NTEXT          NULL,
    [SubektivnieRasstroystvaChuvstvitelnosti] NTEXT          NULL,
    [ObektivnieDannie]                        NTEXT          NULL,
    [BolevayaChuvstvitelnost]                 NTEXT          NULL,
    [TaktilnayaChuvstvitelnost]               NTEXT          NULL,
    [TemperaturnayaChuvstvitelnost]           NTEXT          NULL,
    [SustavnoMishechnoeChuvstvo]              NTEXT          NULL,
    [SlozhnieVidiChuvstvitelnosti]            NTEXT          NULL,
    [KoreshkovieSimptomi]                     NTEXT          NULL,
    [Dermografizm]                            NTEXT          NULL,
    [VazomotornieNarusheniya]                 NTEXT          NULL,
    [TroficheskieRasstroystva]                NTEXT          NULL,
    [Potootdelenie]                           NTEXT          NULL,
    [Slyunootdelenie]                         NTEXT          NULL,
    CONSTRAINT [NevrologicheskoeIssledovaniePrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [NevrologicheskoeIssledovanieToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

