CREATE TABLE [dbo].[NevrologicheskoeObsledovanie] (
    [ID]                         INT           NOT NULL,
    [PatID]                      INT           NULL,
    [Data]                       DATETIME      NULL,
    [Vrach]                      INT           NULL,
    [Zhalobi]                    NTEXT         NULL,
    [Soznanie]                   NVARCHAR (50) NULL,
    [RigidnostZatilochnihMishts] NVARCHAR (1)  NULL,
    [Rastormozhennost]           NVARCHAR (1)  NULL,
    [Apraksiya]                  NVARCHAR (1)  NULL,
    [D]                          NVARCHAR (1)  NULL,
    [S]                          NVARCHAR (1)  NULL,
    [S1]                         NVARCHAR (1)  NULL,
    [D1]                         NVARCHAR (1)  NULL,
    [S2]                         NVARCHAR (1)  NULL,
    [D2]                         NVARCHAR (1)  NULL,
    [Astereognoz]                NVARCHAR (1)  NULL,
    [OpticheskayaAtaksiya]       NVARCHAR (1)  NULL,
    [IgnorirovanieProstranstva]  NVARCHAR (1)  NULL,
    [D3]                         NVARCHAR (1)  NULL,
    [S3]                         NVARCHAR (1)  NULL,
    [Dezorientatsiya]            NVARCHAR (50) NULL,
    [Suzhdenie]                  NVARCHAR (50) NULL,
    [Aspontannost]               NVARCHAR (1)  NULL,
    [TsiklSonBodrstvovanie]      NVARCHAR (50) NULL,
    [Amneziya]                   NVARCHAR (50) NULL,
    [Rech]                       NVARCHAR (50) NULL,
    [Agnoziya]                   NVARCHAR (1)  NULL,
    [Akalkuliya]                 NVARCHAR (1)  NULL,
    [Kernig]                     NVARCHAR (1)  NULL,
    CONSTRAINT [NevrologicheskoeObsledovaniePrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [NevrologicheskoeObsledovanieToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

