CREATE TABLE [dbo].[NevrologicheskiyStatus] (
    [ID]                   INT           NOT NULL,
    [PatID]                INT           NULL,
    [Dizartriya]           BIT           NULL,
    [Atrofichen]           BIT           NULL,
    [NebZanIYaz]           NVARCHAR (50) NULL,
    [EditBox4]             NVARCHAR (50) NULL,
    [Glotaniyу]            NVARCHAR (50) NULL,
    [Voice]                NVARCHAR (50) NULL,
    [GlotReflex]           NVARCHAR (50) NULL,
    [NebReflex]            NVARCHAR (50) NULL,
    [ShumVUshah]           BIT           NULL,
    [Nistagm]              BIT           NULL,
    [SnizhenieSluha]       BIT           NULL,
    [Golovokruzhenie]      BIT           NULL,
    [ProbaRinne]           NVARCHAR (50) NULL,
    [EditBox1]             NVARCHAR (50) NULL,
    [EditBox2]             NVARCHAR (50) NULL,
    [EditBox3]             NVARCHAR (50) NULL,
    [S]                    BIT           NULL,
    [D]                    BIT           NULL,
    [Lagoftalm]            BIT           NULL,
    [Face]                 NVARCHAR (50) NULL,
    [Parez]                NVARCHAR (50) NULL,
    [D3]                   BIT           NULL,
    [D2]                   BIT           NULL,
    [D1]                   BIT           NULL,
    [S1]                   BIT           NULL,
    [S3]                   BIT           NULL,
    [Diplopiya2]           BIT           NULL,
    [VIPara]               BIT           NULL,
    [EyeApplemovement1]    NVARCHAR (50) NULL,
    [Ptoz]                 BIT           NULL,
    [kosoglazie]           BIT           NULL,
    [Diplopiya]            BIT           NULL,
    [DvigGlazApple]        NVARCHAR (50) NULL,
    [Zrachki]              NVARCHAR (50) NULL,
    [Konvergentsiya]       NVARCHAR (50) NULL,
    [Accomodation]         NVARCHAR (50) NULL,
    [ColourFotoReaction]   NVARCHAR (50) NULL,
    [PoleZreniya]          NVARCHAR (50) NULL,
    [ColourFeel]           NVARCHAR (50) NULL,
    [OstrotaZreniya]       INT           NULL,
    [OD]                   INT           NULL,
    [toshnota]             BIT           NULL,
    [Golovokruzhenie1]     BIT           NULL,
    [Golovnayabol]         BIT           NULL,
    [SimptomNeri]          NVARCHAR (1)  NULL,
    [Apatiya]              NVARCHAR (1)  NULL,
    [Depressiya]           NVARCHAR (1)  NULL,
    [Eyforiya]             NVARCHAR (1)  NULL,
    [SostMyshz]            NVARCHAR (50) NULL,
    [Soznaniye]            NVARCHAR (50) NULL,
    [AdSist]               INT           NULL,
    [AdDiast]              INT           NULL,
    [Pulse]                INT           NULL,
    [Vnimanie]             NVARCHAR (50) NULL,
    [Pamyat]               NVARCHAR (50) NULL,
    [Поведение]            NVARCHAR (50) NULL,
    [SimptomPosadki]       NVARCHAR (1)  NULL,
    [GipergidrolizLadoney] BIT           NULL,
    [Gipergidrolizstop]    BIT           NULL,
    [Adimamiya]            BIT           NULL,
    [Emotsionalnolabilen]  BIT           NULL,
    [Zagruzhennost]        BIT           NULL,
    [Bradikardiya]         BIT           NULL,
    [SimptomLassega]       NVARCHAR (1)  NULL,
    [SMKerniga]            NVARCHAR (1)  NULL,
    [SMBrudzinskogo]       NVARCHAR (1)  NULL,
    [SkulovoyBehtereva]    NVARCHAR (1)  NULL,
    [Vyalost]              NVARCHAR (1)  NULL,
    [Obemdvig]             NVARCHAR (50) NULL,
    [Mening]               NVARCHAR (50) NULL,
    [CN1P]                 NVARCHAR (50) NULL,
    [Glotaniye]            NVARCHAR (50) NULL,
    [Golovokruzhenie2]     BIT           NULL,
    [C2]                   BIT           NULL,
    [Povedeniye]           NVARCHAR (50) NULL,
    [CheckBox1]            NVARCHAR (1)  NULL,
    [Data]                 DATETIME      NULL,
    [Vrach]                INT           NULL,
    CONSTRAINT [NevrologicheskiyStatusPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [NevrologicheskiyStatusToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

