CREATE TABLE [dbo].[Neyrosonografiya] (
    [ID]                                        INT           NOT NULL,
    [PatID]                                     INT           NULL,
    [Data]                                      DATETIME      NULL,
    [NomerIssledovaniya]                        INT           NULL,
    [DifferentsirovkaVeshestvaMozna]            INT           NULL,
    [StrukturiRaspolozheni]                     INT           NULL,
    [NeSimmetrichni]                            NVARCHAR (1)  NULL,
    [PerednieRogaBokovihZheludochkov]           INT           NULL,
    [TretiyZheludochek]                         INT           NULL,
    [PolostProzrachnoyPeregorodki]              INT           NULL,
    [SosudistieSpleteniyaBokovihZheludochkov]   INT           NULL,
    [EhoGennost]                                INT           NULL,
    [Rasshireni]                                NVARCHAR (1)  NULL,
    [GlibchatogoVida]                           NVARCHAR (1)  NULL,
    [SNerovnimiKonturami]                       NVARCHAR (1)  NULL,
    [OkrugloeAnehogennoeObrazovanieSZhidkostyu] NVARCHAR (1)  NULL,
    [Diametr]                                   INT           NULL,
    [ArteriyVilizievaKruga]                     INT           NULL,
    [PulsatsiyaPerikollozialnoySredneyArterii]  INT           NULL,
    [TsisternaMagna]                            INT           NULL,
    [SilvieviBorozdi]                           INT           NULL,
    [DopolnitelnieDannieUzi]                    NTEXT         NULL,
    [Zaklyuchenie]                              INT           NULL,
    [Vrach]                                     NVARCHAR (50) NULL,
    [Image]                                     IMAGE         NULL,
    [DannieNaPechat]                            NTEXT         NULL,
    [Data2]                                     DATETIME      NULL,
    CONSTRAINT [NeyrosonografiyaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [NeyrosonografiyaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

