CREATE TABLE [dbo].[Number] (
    [ID] INT IDENTITY (0, 1) NOT NULL,
    [YN] BIT CONSTRAINT [DF_Number_YN] DEFAULT (1) NULL,
    CONSTRAINT [PK_Number] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

