CREATE TABLE [dbo].[ObshiyAnalizMochi] (
    [ID]                                                       INT          NOT NULL,
    [PatID]                                                    INT          NULL,
    [OtnostitelnayaPlotnost]                                   FLOAT (53)   NULL,
    [KolVoBelka]                                               INT          NULL,
    [KolVoGlyukozi]                                            FLOAT (53)   NULL,
    [NomerAnaliza]                                             INT          NULL,
    [DataProvedeniyaAnaliza]                                   DATETIME     NULL,
    [Kolichestvo]                                              INT          NULL,
    [Tsvet]                                                    INT          NULL,
    [Prozrachnost]                                             INT          NULL,
    [Reaktsiya]                                                INT          NULL,
    [KetonovieTela]                                            NVARCHAR (1) NULL,
    [Tsilindri]                                                NVARCHAR (1) NULL,
    [Eritrotsiti1]                                             INT          NULL,
    [Leykotsiti]                                               INT          NULL,
    [PloskiyEpiteliy]                                          INT          NULL,
    [EpiteliyPochechnoyLohankiIMochetochnikov]                 INT          NULL,
    [EpiteliotsitiSlizistoyObolochkiMocheispuskatelnogoKanala] INT          NULL,
    [EpiteliyPochek]                                           INT          NULL,
    [Tsilindroidi]                                             INT          NULL,
    [Soli]                                                     NVARCHAR (1) NULL,
    [Gialinovie]                                               INT          NULL,
    [Voskovidnie]                                              INT          NULL,
    [Leykotsitarnie]                                           INT          NULL,
    [Eritrotsitarnie]                                          INT          NULL,
    [Zernistie]                                                INT          NULL,
    [Sliz]                                                     INT          NULL,
    [Bakterii]                                                 INT          NULL,
    [GribiRodaCandidaKandida]                                  INT          NULL,
    [Zhir]                                                     INT          NULL,
    [Urati]                                                    INT          NULL,
    [MochevayaKislota]                                         INT          NULL,
    [Tripelfosfati]                                            INT          NULL,
    [AmorfnieFosfati]                                          INT          NULL,
    [Oksalati]                                                 INT          NULL,
    [NeytralnieFosfati]                                        INT          NULL,
    [MochekisliyAmmoniy]                                       INT          NULL,
    [KaltsiyaKarbonat]                                         INT          NULL,
    [Ksantini]                                                 INT          NULL,
    [Holesterin]                                               INT          NULL,
    [Gemosederin]                                              INT          NULL,
    [Billirubin]                                               INT          NULL,
    [Leytsin]                                                  INT          NULL,
    [Tirazin]                                                  INT          NULL,
    [Tr]                                                       NVARCHAR (1) NULL,
    [Vrach]                                                    INT          NULL,
    [Porfobikinogen]                                           INT          NULL,
    [Kreatin]                                                  FLOAT (53)   NULL,
    [Mochevina]                                                INT          NULL,
    [KlubochkavayFilitratiy]                                   INT          NULL,
    [KanalicevayAbsorbciy]                                     FLOAT (53)   NULL,
    [MochevayKislota]                                          FLOAT (53)   NULL,
    [SrednieMolekuli]                                          FLOAT (53)   NULL,
    [Ioni]                                                     INT          NULL,
    [Natriy]                                                   INT          NULL,
    [Kaliy]                                                    INT          NULL,
    [Kalciy]                                                   FLOAT (53)   NULL,
    [Magniy]                                                   FLOAT (53)   NULL,
    [Hloridi]                                                  FLOAT (53)   NULL,
    [NeorganicheskiyFosfor]                                    FLOAT (53)   NULL,
    [ProbaZemnickigo]                                          INT          NULL,
    [Atseton]                                                  NVARCHAR (1) NULL,
    [UrobilinovieTela]                                         NVARCHAR (1) NULL,
    [Ammiak]                                                   NVARCHAR (1) NULL,
    [KoncentracionniyIndex]                                    FLOAT (53)   NULL,
    [Spermatazoidi]                                            NVARCHAR (1) NULL,
    CONSTRAINT [ObshiyAnalizMochiPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [ObshiyAnalizMochiToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

