CREATE TABLE [dbo].[ObsheeObsledovanie] (
    [ID]                        INT           NOT NULL,
    [PatID]                     INT           NULL,
    [Konstitutsiya]             NVARCHAR (50) NULL,
    [RostStoya]                 INT           NULL,
    [RostSidya]                 INT           NULL,
    [Ves]                       INT           NULL,
    [IndeksMassiTela]           FLOAT (53)    NULL,
    [OkruzhnostGrudnoyKletki]   INT           NULL,
    [NaVdohe]                   INT           NULL,
    [NaVidohe]                  INT           NULL,
    [AnomaliiRazvitiya]         NTEXT         NULL,
    [Chistie]                   NVARCHAR (1)  NULL,
    [NormalnoyOkraski]          NVARCHAR (1)  NULL,
    [KozhniePokrovi]            NTEXT         NULL,
    [VidimieSlizistie]          NVARCHAR (50) NULL,
    [VidimieSlizistie1]         NTEXT         NULL,
    [Nogti]                     NTEXT         NULL,
    [MishtsiRazviti]            NVARCHAR (50) NULL,
    [PriPalpatsii2]             NVARCHAR (50) NULL,
    [PriPalpatsii3]             NVARCHAR (50) NULL,
    [DeformatsiiKostey]         NVARCHAR (1)  NULL,
    [DeformatsiiSustavov]       NVARCHAR (1)  NULL,
    [PriPalpatsii4]             NVARCHAR (50) NULL,
    [ObemDvizheniyVSustavah]    NVARCHAR (50) NULL,
    [ObemDvizheniyVSustavah1]   NVARCHAR (50) NULL,
    [ObemDvizheniyVSustavah2]   NTEXT         NULL,
    [Zhalobi]                   NTEXT         NULL,
    [Puls]                      NTEXT         NULL,
    [Chastota]                  INT           NULL,
    [NaLevoyRuke]               INT           NULL,
    [NaLevoyRuke1]              INT           NULL,
    [MmRtStNaPravoyRuke]        INT           NULL,
    [MmRtStNaPravoyRuke1]       INT           NULL,
    [Ad5]                       INT           NULL,
    [Ad]                        INT           NULL,
    [Ad4]                       INT           NULL,
    [Ad1]                       INT           NULL,
    [Ad3]                       INT           NULL,
    [Ad2]                       INT           NULL,
    [FonovoeChss]               INT           NULL,
    [PosleProbiChss]            INT           NULL,
    [Cherez3MinutiChss]         INT           NULL,
    [NagruzochnayaProba]        NTEXT         NULL,
    [Zhalobi1]                  NTEXT         NULL,
    [Chdd]                      INT           NULL,
    [RitmDihaniya]              NVARCHAR (50) NULL,
    [RitmDihaniya1]             NTEXT         NULL,
    [Zhalobi2]                  NTEXT         NULL,
    [Appetit]                   NVARCHAR (50) NULL,
    [Pitanie]                   NVARCHAR (50) NULL,
    [Zhivot2]                   NVARCHAR (50) NULL,
    [Zhivot]                    NVARCHAR (50) NULL,
    [PriPalpatsiiBoleznennost]  NVARCHAR (1)  NULL,
    [PriPalpatsiiBoleznennost4] NVARCHAR (50) NULL,
    [PriPalpatsiiBoleznennost1] NVARCHAR (50) NULL,
    [Zhivot1]                   NVARCHAR (50) NULL,
    [PriPalpatsiiBoleznennost2] NVARCHAR (50) NULL,
    [PriPalpatsiiBoleznennost3] NVARCHAR (50) NULL,
    [MishechnayaZashita]        NVARCHAR (50) NULL,
    [Pechen]                    NVARCHAR (50) NULL,
    [VistupaetIzPodreberyaNa]   INT           NULL,
    [Kray]                      NVARCHAR (50) NULL,
    [Stul]                      NVARCHAR (50) NULL,
    [OtKi]                      NVARCHAR (50) NULL,
    [OtKi1]                     NVARCHAR (50) NULL,
    [Dopolnitelno]              NTEXT         NULL,
    [ShitovidnayaZheleza]       NVARCHAR (50) NULL,
    [Dopolnitelno1]             NTEXT         NULL,
    CONSTRAINT [ObsheeObsledovaniePrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [ObsheeObsledovanieToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

