CREATE TABLE [dbo].[ObshiyAnalizKroviRetikulotsiti] (
    [ID]                     INT        NOT NULL,
    [PatID]                  INT        NULL,
    [Eritrotsiti]            FLOAT (53) NULL,
    [Gemoglobin]             INT        NULL,
    [TsvPokazatel]           FLOAT (53) NULL,
    [Trombotsiti]            INT        NULL,
    [Leykotsiti]             FLOAT (53) NULL,
    [BazofiliV]              FLOAT (53) NULL,
    [EozinofiliV]            FLOAT (53) NULL,
    [NPalochkoyadernie]      FLOAT (53) NULL,
    [NSegmentoyadernie]      FLOAT (53) NULL,
    [Limfotsiti]             FLOAT (53) NULL,
    [Monotsiti1]             FLOAT (53) NULL,
    [Retikulotsiti]          FLOAT (53) NULL,
    [Soe]                    FLOAT (53) NULL,
    [Gematokrit]             FLOAT (53) NULL,
    [MCV]                    FLOAT (53) NULL,
    [MCHC]                   FLOAT (53) NULL,
    [MCH]                    INT        NULL,
    [OAK]                    NTEXT      NULL,
    [Vrach]                  INT        NULL,
    [Pronomositi]            FLOAT (53) NULL,
    [NBazilofil]             FLOAT (53) NULL,
    [Polihromatofil]         FLOAT (53) NULL,
    [Oksifil]                FLOAT (53) NULL,
    [Eritroid]               FLOAT (53) NULL,
    [Plazmaticheskie kletki] FLOAT (53) NULL,
    [Mielositi]              INT        NULL,
    [Eritloblasti]           FLOAT (53) NULL,
    [Metamielositi]          INT        NULL,
    [Data]                   DATETIME   NULL,
    CONSTRAINT [ObshiyAnalizKroviRetikulotsitiPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [ObshiyAnalizKroviRetikulotsitiToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

