CREATE TABLE [dbo].[ObshiyAnalizMochiRasshir] (
    [ID]                                 INT           NOT NULL,
    [PatID]                              INT           NULL,
    [Data]                               DATETIME      NULL,
    [Laborant]                           NVARCHAR (50) NULL,
    [Tsvet]                              NVARCHAR (50) NULL,
    [OtnositelnayaPlotnost]              NVARCHAR (50) NULL,
    [Reaktsiya]                          FLOAT (53)    NULL,
    [BelokKachestvenniy]                 NVARCHAR (50) NULL,
    [GlyukozaKachestvennaya]             NVARCHAR (50) NULL,
    [KetonovieTelaKachestvenniy]         NVARCHAR (50) NULL,
    [ReaktsiyaNaKrovKachestvenniy]       NVARCHAR (50) NULL,
    [BilirubinKachestvenniy]             NVARCHAR (50) NULL,
    [UrobilinoidiKachestvenniy]          NVARCHAR (50) NULL,
    [ReaktsiyaNaLeykotsitiKachestvenniy] NVARCHAR (50) NULL,
    [NitritiKachestvenniy]               NVARCHAR (50) NULL,
    [LeykotsitiMikroskopiya]             NVARCHAR (50) NULL,
    [EritrotsitiMikroskopiya]            NVARCHAR (50) NULL,
    [EpiteliyPloskiy]                    NVARCHAR (50) NULL,
    [EpiteliyPerehodniy]                 NVARCHAR (50) NULL,
    [Gialinovie]                         NVARCHAR (50) NULL,
    [Zernistie]                          NVARCHAR (50) NULL,
    [Voskovidnie]                        NVARCHAR (50) NULL,
    [Epitelialnie]                       NVARCHAR (50) NULL,
    [Eritrotsitnie]                      NVARCHAR (50) NULL,
    [Pigmentnie]                         NVARCHAR (50) NULL,
    [Leykotsitnie]                       NVARCHAR (50) NULL,
    [Sliz]                               NVARCHAR (50) NULL,
    [Bakterii]                           NVARCHAR (50) NULL,
    [Urati]                              NVARCHAR (50) NULL,
    [MochevieKisloti]                    NVARCHAR (50) NULL,
    [Oksalatov]                          NVARCHAR (50) NULL,
    [Fosfati]                            NVARCHAR (50) NULL,
    CONSTRAINT [ObshiyAnalizMochiRasshirPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [ObshiyAnalizMochiRasshirToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

