CREATE TABLE [dbo].[ObshiyAnamnezBolnogo] (
    [ID]                                  INT            NOT NULL,
    [PatID]                               INT            NULL,
    [ZhenaMuzh]                           NVARCHAR (100) NULL,
    [UslovnoeRazvitiyaBolnogo]            NTEXT          NULL,
    [PerenesennieZabolevaniya]            NTEXT          NULL,
    [ZanyatiyaSportom]                    NTEXT          NULL,
    [Privivki]                            NTEXT          NULL,
    [AllergicheskieZabolevaniyaIReaktsii] NTEXT          NULL,
    [PerenosimostLekarstvennihSredstv]    NTEXT          NULL,
    [ProfessionalnieZabolevaniya]         NTEXT          NULL,
    [VredniePrivichki]                    NTEXT          NULL,
    [Vozrast]                             INT            NULL,
    [Professiya]                          NVARCHAR (40)  NULL,
    [MestoZhitelstva]                     NTEXT          NULL,
    [deti2]                               NTEXT          NULL,
    [Deti]                                NVARCHAR (1)   NULL,
    [Roditeli]                            NVARCHAR (50)  NULL,
    [Roditeli2]                           NTEXT          NULL,
    [SostoyanieZdorovya]                  NTEXT          NULL,
    [ZhilishnieUsloviya]                  NVARCHAR (50)  NULL,
    [HarakterTruda]                       NTEXT          NULL,
    [Sifilis]                             NVARCHAR (1)   NULL,
    [Alkogolizm]                          NVARCHAR (1)   NULL,
    [Gb]                                  NVARCHAR (1)   NULL,
    [SaharniyDiabed]                      NVARCHAR (1)   NULL,
    [Narkomaniya]                         NVARCHAR (1)   NULL,
    [Ibs]                                 NVARCHAR (1)   NULL,
    [PsihicheskieZabolevaniya]            NVARCHAR (1)   NULL,
    [Tuberkulez]                          NVARCHAR (1)   NULL,
    [BolezniObmena]                       NVARCHAR (1)   NULL,
    [OnkologicheskieZabolevaniya]         NVARCHAR (1)   NULL,
    [Nasledstvennost]                     NTEXT          NULL,
    [Data]                                DATETIME       NULL,
    [Vrach]                               NVARCHAR (50)  NULL,
    [SemeynoePolozhenie]                  NVARCHAR (50)  NULL,
    CONSTRAINT [ObshiyAnamnezBolnogoPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [ObshiyAnamnezBolnogoToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

