CREATE TABLE [dbo].[OFate] (
    [Id]               INT           NOT NULL,
    [DocTypeId]        INT           NULL,
    [MasterID]         INT           NULL,
    [ExecDate]         DATETIME      NULL,
    [ONum]             INT           NULL,
    [InsemId]          INT           NULL,
    [ECO]              INT           NULL,
    [PGD]              VARCHAR (255) NULL,
    [OStat1Id]         VARCHAR (15)  NULL,
    [OStat5Id]         VARCHAR (15)  NULL,
    [_0ImgId]          IMAGE         NULL,
    [_0OperId]         INT           NULL,
    [_1Qty]            INT           NULL,
    [_1OStat2Id]       VARCHAR (15)  NULL,
    [_1OStat5Id]       VARCHAR (15)  NULL,
    [_1Die]            BIT           NULL,
    [_1Cryo]           BIT           NULL,
    [_1Trans]          BIT           NULL,
    [_1ImgId]          IMAGE         NULL,
    [_1OperId]         INT           NULL,
    [_2Qty]            INT           NULL,
    [_2OStat3Id]       VARCHAR (15)  NULL,
    [_2OStat4Id]       VARCHAR (15)  NULL,
    [_2OStat5Id]       VARCHAR (15)  NULL,
    [_2Die]            BIT           NULL,
    [_2Cryo]           BIT           NULL,
    [_2Trans]          BIT           NULL,
    [_2ImgId]          IMAGE         NULL,
    [_2OperId]         INT           NULL,
    [_3Qty]            INT           NULL,
    [_3OStat3Id]       VARCHAR (15)  NULL,
    [_3OStat4Id]       VARCHAR (15)  NULL,
    [_3OStat5Id]       VARCHAR (15)  NULL,
    [_3Die]            BIT           NULL,
    [_3Cryo]           BIT           NULL,
    [_3Trans]          BIT           NULL,
    [_3ImgId]          IMAGE         NULL,
    [_3OperId]         INT           NULL,
    [_4Qty]            INT           NULL,
    [_4OStat3Id]       VARCHAR (15)  NULL,
    [_4OStat4Id]       VARCHAR (15)  NULL,
    [_4OStat5Id]       VARCHAR (15)  NULL,
    [_4Die]            BIT           NULL,
    [_4Cryo]           BIT           NULL,
    [_4Trans]          BIT           NULL,
    [_4ImgId]          IMAGE         NULL,
    [_4OperId]         INT           NULL,
    [_5Qty]            INT           NULL,
    [_5OStat3Id]       VARCHAR (15)  NULL,
    [_5OStat4Id]       VARCHAR (15)  NULL,
    [_5OStat5Id]       VARCHAR (15)  NULL,
    [_5Die]            BIT           NULL,
    [_5Cryo]           BIT           NULL,
    [_5Trans]          BIT           NULL,
    [_5ImgId]          IMAGE         NULL,
    [_5OperId]         INT           NULL,
    [_6Qty]            INT           NULL,
    [_6OStat3Id]       VARCHAR (15)  NULL,
    [_6OStat4Id]       VARCHAR (15)  NULL,
    [_6OStat5Id]       VARCHAR (15)  NULL,
    [_6Die]            BIT           NULL,
    [_6Cryo]           BIT           NULL,
    [_6Trans]          BIT           NULL,
    [_6ImgId]          IMAGE         NULL,
    [_6OperId]         INT           NULL,
    [Comment]          VARCHAR (255) NULL,
    [OperId]           INT           NULL,
    [CryoDate]         DATETIME      NULL,
    [CryoTime]         DATETIME      NULL,
    [CryoEB]           BIT           NULL,
    [CryoEQualId]      VARCHAR (15)  NULL,
    [CryoBQual1Id]     VARCHAR (15)  NULL,
    [CryoBQual2Id]     VARCHAR (15)  NULL,
    [CryoComment]      VARCHAR (255) NULL,
    [CryoImgId]        IMAGE         NULL,
    [CryoStorage]      VARCHAR (150) NULL,
    [CryoCulm]         VARCHAR (150) NULL,
    [CryoOperId]       INT           NULL,
    [UCryo]            BIT           NULL,
    [UCryoDate]        DATETIME      NULL,
    [UCryoTime]        DATETIME      NULL,
    [UCryoEQualId]     VARCHAR (15)  NULL,
    [UCryoBUnWrap]     BIT           NULL,
    [UCryoBQual1Id]    VARCHAR (15)  NULL,
    [UCryoBQual2Id]    VARCHAR (15)  NULL,
    [UCryoBQual3Id]    VARCHAR (15)  NULL,
    [UCryoComment]     VARCHAR (255) NULL,
    [UCryoImgId]       IMAGE         NULL,
    [UCryoOperId]      INT           NULL,
    [OriginalID]       INT           NULL,
    [CryoPaidDate]     DATETIME      NULL,
    [ECFTransID]       INT           NULL,
    [StructureVersion] INT           NULL,
    [Duar]             NVARCHAR (50) NULL,
    [Stakan]           NVARCHAR (50) NULL,
    [Goblet]           NVARCHAR (50) NULL,
    [DoPGD]            BIT           NULL,
    [CryoOoc]          BIT           NULL,
    [EmbrQualified]    BIT           NULL,
    [OocQualified]     BIT           NULL,
    CONSTRAINT [PK_OFate] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_OFate_ECFEmbr] FOREIGN KEY ([MasterID]) REFERENCES [dbo].[ECFEmbr] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [OFate_Trans_FK] FOREIGN KEY ([ECFTransID]) REFERENCES [dbo].[ECFTrans] ([Id])
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OFate', @level2type = N'COLUMN', @level2name = N'_3OStat5Id';

