CREATE TABLE [dbo].[OftalmologicheskoeObsledovanie] (
    [ID]                      INT            NOT NULL,
    [PatID]                   INT            NULL,
    [PeredniaKameraVNorme]    NVARCHAR (1)   NULL,
    [BezKorrektsiiR]          FLOAT (53)     NULL,
    [BezKorrektsiiL]          FLOAT (53)     NULL,
    [SKorrektsieyL]           NVARCHAR (50)  NULL,
    [SKorrektsieyR]           NVARCHAR (50)  NULL,
    [Orbita]                  NVARCHAR (50)  NULL,
    [PolozhenieGlaz]          NVARCHAR (50)  NULL,
    [DvigatelniyApparat]      NVARCHAR (50)  NULL,
    [Utolshen]                NVARCHAR (1)   NULL,
    [Cheshuiki]               NVARCHAR (1)   NULL,
    [Iazvochki]               NVARCHAR (1)   NULL,
    [Trihiaz]                 NVARCHAR (1)   NULL,
    [ResnichniyKray]          INT            NULL,
    [KonyuktivaVek]           NVARCHAR (200) NULL,
    [Otdelyaemoe]             INT            NULL,
    [SleznieOrganyVNorme]     NVARCHAR (1)   NULL,
    [Prohodimost]             INT            NULL,
    [Prohodimost1]            NVARCHAR (50)  NULL,
    [SkleraVNorme]            NVARCHAR (1)   NULL,
    [Sklera]                  INT            NULL,
    [Sklera1]                 INT            NULL,
    [Sklera2]                 NVARCHAR (50)  NULL,
    [RogovicaVNorme]          NVARCHAR (1)   NULL,
    [Rogovitsa]               INT            NULL,
    [Rogovitsa1]              INT            NULL,
    [Rogovitsa2]              NVARCHAR (50)  NULL,
    [PerednyayaKamera]        INT            NULL,
    [PerednyayaKamera1]       INT            NULL,
    [Vlaga]                   NVARCHAR (50)  NULL,
    [RaduzhkaVNorme]          NVARCHAR (1)   NULL,
    [Raduzhka]                NVARCHAR (50)  NULL,
    [Zrachok]                 NVARCHAR (50)  NULL,
    [Zrachok1]                INT            NULL,
    [HrustalikVNorme]         NVARCHAR (1)   NULL,
    [Hrustalik]               INT            NULL,
    [Hrustalik1]              INT            NULL,
    [Hrustalik2]              NVARCHAR (50)  NULL,
    [CheckBox7]               NVARCHAR (1)   NULL,
    [SteklovidnoeTelo]        INT            NULL,
    [SteklovidnoeTelo1]       NVARCHAR (50)  NULL,
    [GlaznoeDnoVNorme]        NVARCHAR (1)   NULL,
    [GlaznoeDno]              NVARCHAR (50)  NULL,
    [ZritelniyNerv1]          NTEXT          NULL,
    [Sosudi1]                 NTEXT          NULL,
    [Setchatka1]              NTEXT          NULL,
    [VnutriglaznoeDavlenie1]  NTEXT          NULL,
    [ObektivnayaRefraktsiya1] NTEXT          NULL,
    [Memo9]                   NTEXT          NULL,
    [Zhalobi]                 NTEXT          NULL,
    [Anamnez]                 NTEXT          NULL,
    [ProvodimieManipulyatsii] NVARCHAR (50)  NULL,
    [Data]                    DATETIME       NULL,
    [Vrach]                   NVARCHAR (50)  NULL,
    [Diagnoz]                 NTEXT          NULL,
    CONSTRAINT [OftalmologicheskoeObsledovaniePrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [OftalmologicheskoeObsledovanieToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

