CREATE TABLE [dbo].[Operatsiya] (
    [ID]            INT           NOT NULL,
    [PatID]         INT           NULL,
    [FIO]           NVARCHAR (50) NULL,
    [Data]          DATETIME      NULL,
    [Frk]           NTEXT         NULL,
    [Data2]         DATETIME      NULL,
    [Frk1]          NTEXT         NULL,
    [1]             NVARCHAR (1)  NULL,
    [dva]           NVARCHAR (1)  NULL,
    [tri]           NVARCHAR (1)  NULL,
    [odin]          NVARCHAR (1)  NULL,
    [dva2]          NVARCHAR (1)  NULL,
    [tri3]          NVARCHAR (1)  NULL,
    [Hirurg]        NVARCHAR (50) NULL,
    [Naznacheniya]  NTEXT         NULL,
    [odin2]         NVARCHAR (1)  NULL,
    [dva1]          NVARCHAR (1)  NULL,
    [tri1]          NVARCHAR (1)  NULL,
    [tri4]          NVARCHAR (1)  NULL,
    [dva3]          NVARCHAR (1)  NULL,
    [odin3]         NVARCHAR (1)  NULL,
    [Hirurg1]       NVARCHAR (50) NULL,
    [Naznacheniya1] NTEXT         NULL,
    [Data3]         DATETIME      NULL,
    [protocol]      NTEXT         NULL,
    [Hirurg2]       NVARCHAR (50) NULL,
    [Data4]         DATETIME      NULL,
    [protocol1]     NTEXT         NULL,
    [Hirurg3]       NVARCHAR (50) NULL,
    [Data5]         DATETIME      NULL,
    [protocol2]     NTEXT         NULL,
    [Hirurg4]       NVARCHAR (50) NULL,
    [Data6]         DATETIME      NULL,
    [protocol3]     NTEXT         NULL,
    [Hirurg5]       NVARCHAR (50) NULL,
    CONSTRAINT [OperatsiyaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [OperatsiyaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

