CREATE TABLE [dbo].[OpredelenieElektrochuvstvitelnostiIElektrolabilnostiEchIElSetchatki] (
    [ID]           INT           NOT NULL,
    [PatID]        INT           NULL,
    [PNORD]        INT           NULL,
    [PNORS]        INT           NULL,
    [PNEZD]        INT           NULL,
    [PNEZS]        INT           NULL,
    [PUMED]        INT           NULL,
    [PUMES]        INT           NULL,
    [PZNAD]        INT           NULL,
    [PZNAS]        INT           NULL,
    [PGRUD]        INT           NULL,
    [PGRUS]        INT           NULL,
    [PZAKLUCHENIE] NVARCHAR (18) NULL,
    [LNORD]        INT           NULL,
    [LNORS]        INT           NULL,
    [LNEZD]        INT           NULL,
    [LNEZS]        INT           NULL,
    [LUMED]        INT           NULL,
    [LUMES]        INT           NULL,
    [LZNAD]        INT           NULL,
    [LZNAS]        INT           NULL,
    [LGRUD]        INT           NULL,
    [LGRUS]        INT           NULL,
    [LZAKLUCHENIE] NVARCHAR (18) NULL,
    [RecNo]        INT           NULL,
    [ExportTime]   DATETIME      NULL,
    CONSTRAINT [OpredelenieElektrochuvstvitelnostiIElektrolabilnostiEchIElSetchatkiPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [OpredelenieElektrochuvstvitelnostiIElektrolabilnostiEchIElSetchatkiToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

