CREATE TABLE [dbo].[Organisations] (
    [ID]                  INT             NOT NULL,
    [FullName]            NVARCHAR (200)  NULL,
    [PhysicalAddress]     NVARCHAR (150)  NULL,
    [LegalAddress]        NVARCHAR (150)  NULL,
    [INN]                 NVARCHAR (40)   NULL,
    [KPP]                 NVARCHAR (50)   NULL,
    [Bank]                NVARCHAR (80)   NULL,
    [KS]                  NVARCHAR (40)   NULL,
    [RS]                  NVARCHAR (40)   NULL,
    [Type]                NVARCHAR (20)   NULL,
    [OrgType]             INT             NULL,
    [code]                INT             NULL,
    [BriefName]           NVARCHAR (100)  NULL,
    [MajorDoctor]         NVARCHAR (100)  NULL,
    [Phone]               NVARCHAR (100)  NULL,
    [OwnOrg]              BIT             NULL,
    [Fax]                 NVARCHAR (35)   NULL,
    [EMail]               NVARCHAR (100)  NULL,
    [off]                 INT             NULL,
    [MajorBuhg]           NVARCHAR (100)  NULL,
    [Q]                   NVARCHAR (2)    NULL,
    [C_T]                 INT             NULL,
    [OldQName]            NVARCHAR (100)  NULL,
    [OldQ]                NVARCHAR (2)    NULL,
    [Additional]          NVARCHAR (1000) NULL,
    [MajorDoctorRodPadej] NVARCHAR (100)  NULL,
    [Web]                 NVARCHAR (100)  NULL,
    [Ogrn]                NVARCHAR (15)   NULL,
    [Division]            NVARCHAR (150)  NULL,
    [Okato]               NVARCHAR (15)   NULL,
    [Okpo]                NVARCHAR (15)   NULL,
    CONSTRAINT [organisationsPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC)
);

