CREATE TABLE [dbo].[OsmotrnevropatologaPervichniy] (
    [ID]                                INT           NOT NULL,
    [PatID]                             INT           NULL,
    [RefleksiSVerhniyKonechnostey2]     NVARCHAR (35) NULL,
    [RefleksiSVerhniyKonechnostey1]     NVARCHAR (45) NULL,
    [Ataksia1]                          NVARCHAR (20) NULL,
    [Ataksia2]                          NVARCHAR (1)  NULL,
    [PromahivaniePriPalcenosovoyProbe1] NVARCHAR (1)  NULL,
    [Yazik1]                            INT           NULL,
    [Chuvstvitelnost1]                  INT           NULL,
    [Asteriognoz1]                      NVARCHAR (20) NULL,
    [Paraplegia1]                       NVARCHAR (20) NULL,
    [Monoplegia1]                       NVARCHAR (20) NULL,
    [Paraparez1]                        NVARCHAR (20) NULL,
    [Monoparez1]                        NVARCHAR (20) NULL,
    [Monoparez]                         NVARCHAR (1)  NULL,
    [Paraparez]                         NVARCHAR (1)  NULL,
    [Monoplegia]                        NVARCHAR (1)  NULL,
    [Paraplegia]                        NVARCHAR (1)  NULL,
    [Asteriognoz]                       NVARCHAR (1)  NULL,
    [Apraksia]                          NVARCHAR (1)  NULL,
    [Gemiplegia1]                       NVARCHAR (20) NULL,
    [Tetraplegia1]                      NVARCHAR (20) NULL,
    [Gemiparez1]                        NVARCHAR (20) NULL,
    [Tetraparez1]                       NVARCHAR (20) NULL,
    [Tetraparez]                        NVARCHAR (1)  NULL,
    [Gemiparez]                         NVARCHAR (1)  NULL,
    [Tetraplegia]                       NVARCHAR (1)  NULL,
    [Gemiplegia]                        NVARCHAR (1)  NULL,
    [Afaziya]                           INT           NULL,
    [RasstroystvaDvizheniy]             INT           NULL,
    [Dermografizm]                      INT           NULL,
    [Dermografizm1]                     INT           NULL,
    [Bistroischezaushiy]                NVARCHAR (1)  NULL,
    [Adinamia]                          NVARCHAR (1)  NULL,
    [Vialost]                           NVARCHAR (1)  NULL,
    [SimptomPosadki]                    NVARCHAR (1)  NULL,
    [SimptomNeri]                       NVARCHAR (1)  NULL,
    [Zagrujennost]                      NVARCHAR (1)  NULL,
    [GiperHydrozStop]                   NVARCHAR (1)  NULL,
    [GiperhydrozLadoney]                NVARCHAR (1)  NULL,
    [EmocionalnoLabilen]                NVARCHAR (1)  NULL,
    [SimptomLassega]                    NVARCHAR (1)  NULL,
    [SostoyanieMishtsSpini]             NVARCHAR (20) NULL,
    [ObemDvizheniyPozvonochnika]        INT           NULL,
    [RegidnostZatilochnihMisc]          NVARCHAR (1)  NULL,
    [SMKerniga]                         NVARCHAR (1)  NULL,
    [SMBrudzinskogo]                    NVARCHAR (1)  NULL,
    [SkulovoyBehtereva]                 NVARCHAR (1)  NULL,
    [Soznanie]                          INT           NULL,
    [Pamyat]                            NVARCHAR (50) NULL,
    [Vnimanie]                          NVARCHAR (50) NULL,
    [Povedenie]                         NVARCHAR (50) NULL,
    [Eyforiya]                          NVARCHAR (1)  NULL,
    [Depressiya]                        NVARCHAR (1)  NULL,
    [Apatiya]                           NVARCHAR (1)  NULL,
    [Vyalost]                           NVARCHAR (1)  NULL,
    [GolovnayaBol]                      NVARCHAR (1)  NULL,
    [Golovokruzhenie]                   NVARCHAR (1)  NULL,
    [Bradikardiya]                      NVARCHAR (1)  NULL,
    [Toshnota]                          NVARCHAR (1)  NULL,
    [AdDiast]                           INT           NULL,
    [AdSist]                            INT           NULL,
    [IPara]                             NVARCHAR (50) NULL,
    [PolyaZreniya]                      NVARCHAR (50) NULL,
    [Tsvetooshushenie]                  NVARCHAR (50) NULL,
    [OS]                                NVARCHAR (50) NULL,
    [OD]                                NVARCHAR (50) NULL,
    [Zrachki]                           INT           NULL,
    [FotoreaktsiyaNaSvet1]              INT           NULL,
    [FotoreaktsiyaNaSvet]               NVARCHAR (50) NULL,
    [DvizhenieGlaznihYablok]            INT           NULL,
    [Diplopiya1]                        NVARCHAR (1)  NULL,
    [ShodyasheesyaKosoglazie]           NVARCHAR (1)  NULL,
    [Ekzoftalm]                         NVARCHAR (1)  NULL,
    [Anizokoriya]                       NVARCHAR (1)  NULL,
    [Akkomodatsiya]                     NVARCHAR (50) NULL,
    [Diplopiya]                         NVARCHAR (1)  NULL,
    [Konvergentsiya]                    NVARCHAR (50) NULL,
    [Ptoz]                              NVARCHAR (1)  NULL,
    [Kosoglazie]                        NVARCHAR (1)  NULL,
    [C3]                                NVARCHAR (1)  NULL,
    [C2]                                NVARCHAR (1)  NULL,
    [C1]                                NVARCHAR (1)  NULL,
    [D3]                                NVARCHAR (1)  NULL,
    [D2]                                NVARCHAR (1)  NULL,
    [D1]                                NVARCHAR (1)  NULL,
    [ShodyasheesyaKosoglazie1]          NVARCHAR (1)  NULL,
    [Diplopiya2]                        NVARCHAR (1)  NULL,
    [DvizheniyaGlaznihYablok]           NVARCHAR (50) NULL,
    [Lagoftalm]                         NVARCHAR (1)  NULL,
    [C]                                 NVARCHAR (1)  NULL,
    [D]                                 NVARCHAR (1)  NULL,
    [Parez]                             INT           NULL,
    [Litso]                             INT           NULL,
    [Nistagm]                           NVARCHAR (1)  NULL,
    [OstrotaSluha]                      NVARCHAR (50) NULL,
    [ShumVUshah]                        NVARCHAR (1)  NULL,
    [SnijenieSluha]                     NVARCHAR (1)  NULL,
    [VPozeRomberga]                     INT           NULL,
    [Golovokrujenie]                    NVARCHAR (1)  NULL,
    [Golovokrujenie1]                   INT           NULL,
    [ProbaVebera]                       NVARCHAR (50) NULL,
    [ProbaRinne]                        NVARCHAR (50) NULL,
    [GlotochniyRefleks]                 NVARCHAR (50) NULL,
    [NBniyRefleks]                      NVARCHAR (50) NULL,
    [Dizartriya]                        NVARCHAR (1)  NULL,
    [Atrofichen]                        NVARCHAR (1)  NULL,
    [Yazik]                             NVARCHAR (50) NULL,
    [Golos]                             INT           NULL,
    [NBnieZanaveskiIYazichok]           NVARCHAR (50) NULL,
    [Glotanie]                          INT           NULL,
    [PovorotiGoloviIShei]               NVARCHAR (50) NULL,
    [DvizheniyaPlech]                   NVARCHAR (50) NULL,
    [UdVMin]                            NVARCHAR (50) NULL,
    [Data]                              DATETIME      NULL,
    [Vrach]                             INT           NULL,
    [Zhalobi]                           NTEXT         NULL,
    [Anamnez]                           NTEXT         NULL,
    [ProvodimieManipulyatsii]           NTEXT         NULL,
    [Diagnoz]                           NVARCHAR (50) NULL,
    [BLNomer]                           INT           NULL,
    [Srok]                              DATETIME      NULL,
    [AktivnoePoseshenie]                NVARCHAR (50) NULL,
    [PovtornayaYavka]                   DATETIME      NULL,
    CONSTRAINT [OsmotrnevropatologaPervichniyPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [OsmotrnevropatologaPervichniyToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

