CREATE TABLE [dbo].[OsmotrOtolaringologa] (
    [ID]                INT          NOT NULL,
    [PatID]             INT          NULL,
    [Data]              DATETIME     NULL,
    [Vrach]             INT          NULL,
    [DocTime]           DATETIME     NULL,
    [Zhalobi]           NTEXT        NULL,
    [Operatsii2]        NTEXT        NULL,
    [Operatsii]         NVARCHAR (1) NULL,
    [Transfuzii]        NVARCHAR (1) NULL,
    [Transfuzii2]       NTEXT        NULL,
    [NoAllergy]         NVARCHAR (1) NULL,
    [AnamnezZhizni]     NTEXT        NULL,
    [AnamnezZhizni1]    NTEXT        NULL,
    [AnamnezZhizni2]    NTEXT        NULL,
    [Allergic]          NTEXT        NULL,
    [Allergic2]         NTEXT        NULL,
    [Allergic4]         NTEXT        NULL,
    [PlanObsledovaniya] NTEXT        NULL,
    [PlanLecheniya]     NTEXT        NULL,
    [Recomendacii]      NTEXT        NULL,
    [Nosoglotka]        NTEXT        NULL,
    [Glotka]            NTEXT        NULL,
    [Gortan]            NTEXT        NULL,
    [UshiAS]            NTEXT        NULL,
    [UshiAD]            NTEXT        NULL,
    CONSTRAINT [OsmotrOtolaringologaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [OsmotrOtolaringologaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

