CREATE TABLE [dbo].[OsmotrOtolaringologaPervichniy] (
    [KamertonnoeIssledovanie]          NVARCHAR (45) NULL,
    [RazgovornayaRech]                 INT           NULL,
    [S]                                INT           NULL,
    [ShopotnayaRech1]                  INT           NULL,
    [ShopotnayaRech]                   INT           NULL,
    [BarabannayaPereponkaBezIzmeneniy] NVARCHAR (1)  NULL,
    [BarabannayaPereponka]             NVARCHAR (30) NULL,
    [SluhovoyProhod]                   NVARCHAR (30) NULL,
    [SluhovoyProhodBezIzmeneniy]       NVARCHAR (1)  NULL,
    [NaruzhnoeUhoBezIzmeneniy]         NVARCHAR (1)  NULL,
    [NaruzhnoeUho]                     NVARCHAR (30) NULL,
    [Gortan]                           NVARCHAR (30) NULL,
    [GortanBezIzmeneniy]               NVARCHAR (1)  NULL,
    [GolosovayaFTsiyaBezIzmeneniy]     NVARCHAR (1)  NULL,
    [GolosovayaFTsiya]                 NVARCHAR (30) NULL,
    [LimfaticheskieUzli]               NVARCHAR (30) NULL,
    [LimfaticheskieUzliBezIzmeneniy]   NVARCHAR (1)  NULL,
    [MindaliniDSBezIzmeneniy]          NVARCHAR (1)  NULL,
    [MindaliniDS]                      NVARCHAR (30) NULL,
    [Glotka]                           NVARCHAR (20) NULL,
    [GlotkaBezIzmeneniy]               NVARCHAR (1)  NULL,
    [Slizistaya]                       NVARCHAR (20) NULL,
    [DrugieObrazovaniya]               NVARCHAR (50) NULL,
    [NosoglotkaBezIzmeneniy]           NVARCHAR (1)  NULL,
    [Nosoglotka]                       NVARCHAR (30) NULL,
    [Adenoidi]                         INT           NULL,
    [NosovieRakovini]                  NVARCHAR (25) NULL,
    [NosovayaPeregorodka]              INT           NULL,
    [TsvetSlizistoy]                   NVARCHAR (20) NULL,
    [OtechnostSlizistoy]               NVARCHAR (1)  NULL,
    [Giperemia]                        NVARCHAR (1)  NULL,
    [Atrophia]                         NVARCHAR (1)  NULL,
    [Polipi]                           NVARCHAR (1)  NULL,
    [PolostNosa1]                      NVARCHAR (30) NULL,
    [PolostNosa]                       INT           NULL,
    [NosovoeDihanie]                   NVARCHAR (30) NULL,
    [Zhalobi]                          NTEXT         NULL,
    [Data]                             DATETIME      NULL,
    [Vrach]                            NVARCHAR (50) NULL,
    [Anamnez]                          NTEXT         NULL,
    [VestibulyarnieFunktsii]           NVARCHAR (50) NULL,
    [ProvodimieManipulyatsii]          NVARCHAR (50) NULL,
    [DopolnitelnieDannie]              NTEXT         NULL,
    [Diagnoz]                          NVARCHAR (50) NULL,
    [BLNomer]                          INT           NULL,
    [Srok]                             DATETIME      NULL,
    [AktivnoePoseshenie]               NVARCHAR (50) NULL,
    [YavkaVPolikliniku]                DATETIME      NULL
);

