CREATE TABLE [dbo].[OsmotrEndokrinologaPovt] (
    [ID]                            INT           NOT NULL,
    [PatID]                         INT           NULL,
    [NalichieOslozhneniyTransfuzii] NTEXT         NULL,
    [GruppaKrovi]                   NVARCHAR (50) NULL,
    [Rh]                            NVARCHAR (50) NULL,
    [TransfuziiRanshe]              NVARCHAR (50) NULL,
    [BitovieUsloviya]               NVARCHAR (50) NULL,
    [LichnayaGigiena]               NVARCHAR (50) NULL,
    [UpotreblenieNarkotikov]        NVARCHAR (50) NULL,
    [IstochnikPitevoyVodi]          NVARCHAR (50) NULL,
    [UpotreblenieSiroyVodi]         NVARCHAR (50) NULL,
    [Zhazhda]                       NVARCHAR (1)  NULL,
    [SuhostVoRtu]                   NVARCHAR (1)  NULL,
    [Poliuriya]                     NVARCHAR (1)  NULL,
    [Nikturiya]                     NVARCHAR (1)  NULL,
    [Pohudanie]                     NVARCHAR (1)  NULL,
    [ZyabkostStop]                  NVARCHAR (1)  NULL,
    [ZhzhenieVStopah]               NVARCHAR (1)  NULL,
    [OnemenieVStopah]               NVARCHAR (1)  NULL,
    [PolzanieMurashek]              NVARCHAR (1)  NULL,
    [SudorogiVIkronozhnihMishtsah]  NVARCHAR (1)  NULL,
    [DrozhVTele]                    NVARCHAR (1)  NULL,
    [DrozhVRukah]                   NVARCHAR (1)  NULL,
    [OnemenieKistey]                NVARCHAR (1)  NULL,
    [ZyabkostVerhnihKonechnostey]   NVARCHAR (1)  NULL,
    [TreshiniNaStopah]              NVARCHAR (1)  NULL,
    [TroficheskieIzmeneniyaStop]    NVARCHAR (1)  NULL,
    [Golovokruzhenie]               NVARCHAR (1)  NULL,
    [ShumVGolove]                   NVARCHAR (1)  NULL,
    [GipoglikemicheskoeSostoyanie]  NVARCHAR (1)  NULL,
    [GipoklimSost]                  NVARCHAR (50) NULL,
    [SuhostKozhi]                   NVARCHAR (1)  NULL,
    [Zyabkost]                      NVARCHAR (1)  NULL,
    [Sonliv]                        NVARCHAR (1)  NULL,
    [SaharniyDiabetVTechenie]       NVARCHAR (1)  NULL,
    [Let]                           INT           NULL,
    [NaDUchete]                     NVARCHAR (1)  NULL,
    [ProyavleniyaPolineyropatii]    NVARCHAR (1)  NULL,
    [ProyavleniyaRetinopatii]       NVARCHAR (1)  NULL,
    [ProyavleniyaNefropatii]        NVARCHAR (1)  NULL,
    [Let1]                          INT           NULL,
    [Let2]                          INT           NULL,
    [Let3]                          INT           NULL,
    [Let4]                          INT           NULL,
    [TremorRuk]                     NVARCHAR (1)  NULL,
    [Tremor]                        NVARCHAR (50) NULL,
    [OtekiLitsaIKonechnostey]       NVARCHAR (1)  NULL,
    [OtekKonechn]                   NVARCHAR (50) NULL,
    [NukturiyaRaz]                  NVARCHAR (50) NULL,
    [Nemedikamentoznie]             NVARCHAR (1)  NULL,
    [Combo2]                        NVARCHAR (50) NULL,
    [Medikomentoznie]               NVARCHAR (1)  NULL,
    [DopDann]                       NTEXT         NULL,
    [Teloslozhenie]                 INT           NULL,
    [TonusMuskulaturi]              NVARCHAR (20) NULL,
    [Rost]                          INT           NULL,
    [Ves]                           INT           NULL,
    [VtorichniePolPriznaki]         INT           NULL,
    [Vlajnost]                      NVARCHAR (50) NULL,
    [Pigment]                       NVARCHAR (50) NULL,
    [Oteki]                         NVARCHAR (50) NULL,
    [Ojirenie]                      NVARCHAR (50) NULL,
    [Turgor]                        NVARCHAR (1)  NULL,
    [Okras]                         NVARCHAR (50) NULL,
    [menstrCikl]                    NVARCHAR (50) NULL,
    [Myagkaya]                      NVARCHAR (1)  NULL,
    [Uplotnennaya]                  NVARCHAR (1)  NULL,
    [CheckBox1]                     NVARCHAR (1)  NULL,
    [Left]                          NVARCHAR (50) NULL,
    [Prav]                          NVARCHAR (50) NULL,
    [Combo1]                        NVARCHAR (50) NULL,
    [Uzli2]                         NVARCHAR (50) NULL,
    [UchashenniyDo]                 NVARCHAR (1)  NULL,
    [StulSutki]                     INT           NULL,
    [ZaporiDo]                      NVARCHAR (1)  NULL,
    [EditBox1]                      NVARCHAR (50) NULL,
    [Regulyarniy]                   NVARCHAR (1)  NULL,
    [DihanieVezikulyarnoe]          NVARCHAR (1)  NULL,
    [MnogochislennieHripi]          NVARCHAR (1)  NULL,
    [Legkie]                        NVARCHAR (50) NULL,
    [TonySerdsa]                    NVARCHAR (50) NULL,
    [Ritm]                          NVARCHAR (50) NULL,
    [shum]                          NVARCHAR (50) NULL,
    [AD]                            INT           NULL,
    [AD1]                           INT           NULL,
    [AD2]                           INT           NULL,
    [Puls]                          NVARCHAR (50) NULL,
    [Puls2]                         NVARCHAR (50) NULL,
    [VtorPolPrizn]                  NVARCHAR (50) NULL,
    [Myagkiy]                       NVARCHAR (1)  NULL,
    [TvRdiy]                        NVARCHAR (1)  NULL,
    [Boleznenniy]                   NVARCHAR (1)  NULL,
    [Bezboleznenniy]                NVARCHAR (1)  NULL,
    [Vzdut]                         NVARCHAR (1)  NULL,
    [Jivot]                         NVARCHAR (50) NULL,
    [Pechen]                        NVARCHAR (50) NULL,
    [Selezenka]                     NVARCHAR (50) NULL,
    [NervnoPsihStat]                NVARCHAR (50) NULL,
    [PichevarSistema]               NVARCHAR (50) NULL,
    [Hripi]                         NVARCHAR (1)  NULL,
    [EditBox2]                      INT           NULL,
    [DateBox1]                      DATETIME      NULL,
    [AktPosechen]                   NVARCHAR (50) NULL,
    [DateBox2]                      DATETIME      NULL,
    [EditBox3]                      NVARCHAR (50) NULL,
    [Data]                          DATETIME      NULL,
    [Vrach]                         NVARCHAR (50) NULL,
    [ZyabkostKistey]                NVARCHAR (1)  NULL,
    [OtekiLitsa]                    NVARCHAR (1)  NULL,
    [EditBox4]                      NVARCHAR (50) NULL,
    [EditBox5]                      NVARCHAR (50) NULL,
    [EditBox6]                      NVARCHAR (50) NULL,
    [OtekiKonechnostey]             NVARCHAR (1)  NULL,
    [EditBox7]                      NVARCHAR (50) NULL,
    [Combo8]                        NVARCHAR (50) NULL,
    [Combo9]                        NVARCHAR (50) NULL,
    [Combo10]                       NVARCHAR (50) NULL,
    [Combo11]                       NVARCHAR (50) NULL,
    [Combo12]                       NVARCHAR (50) NULL,
    [Combo13]                       NVARCHAR (50) NULL,
    [Combo14]                       NVARCHAR (50) NULL,
    [Combo15]                       NVARCHAR (50) NULL,
    [Combo16]                       NVARCHAR (50) NULL,
    [Combo17]                       NVARCHAR (50) NULL,
    [Combo18]                       NVARCHAR (50) NULL,
    [Combo19]                       NVARCHAR (50) NULL,
    [Combo20]                       NVARCHAR (50) NULL,
    [Combo21]                       NVARCHAR (50) NULL,
    [Combo22]                       NVARCHAR (50) NULL,
    [Combo23]                       NVARCHAR (50) NULL,
    [Combo24]                       NVARCHAR (50) NULL,
    [Combo25]                       NVARCHAR (50) NULL,
    [Combo26]                       NVARCHAR (50) NULL,
    [Combo27]                       NVARCHAR (50) NULL,
    [Combo28]                       NVARCHAR (50) NULL,
    [Combo29]                       NVARCHAR (50) NULL,
    [Combo30]                       NVARCHAR (50) NULL,
    [Combo31]                       NVARCHAR (50) NULL,
    [Combo32]                       NVARCHAR (50) NULL,
    [IMT]                           FLOAT (53)    NULL,
    [Combo3]                        NVARCHAR (50) NULL,
    [EditBox8]                      NVARCHAR (50) NULL,
    [Combo4]                        NVARCHAR (50) NULL,
    [Combo5]                        NVARCHAR (50) NULL,
    [Combo6]                        NVARCHAR (50) NULL,
    [EditBox9]                      NVARCHAR (50) NULL,
    [Combo7]                        NVARCHAR (50) NULL,
    [EditBox10]                     NVARCHAR (50) NULL,
    [EditBox11]                     NVARCHAR (50) NULL,
    [DiagnozPoMkb10]                NVARCHAR (80) NULL,
    [Memo1]                         NTEXT         NULL,
    CONSTRAINT [OsmotrEndokrinologaPovtPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [OsmotrEndokrinologaPovtToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

