CREATE TABLE [dbo].[OsmotrNarkologa] (
    [ID]                               INT            NOT NULL,
    [PatID]                            INT            NULL,
    [Data]                             DATETIME       NULL,
    [Vrach]                            INT            NULL,
    [PrichinaOsmotra]                  NVARCHAR (50)  NULL,
    [PrichinaNapravleniya]             NVARCHAR (20)  NULL,
    [EditBox3]                         NVARCHAR (20)  NULL,
    [ToniSerdca]                       NVARCHAR (50)  NULL,
    [Vozrast]                          NVARCHAR (50)  NULL,
    [Teloslozhenie]                    NVARCHAR (50)  NULL,
    [Turgor]                           NVARCHAR (20)  NULL,
    [Teloslozhenie2]                   NVARCHAR (20)  NULL,
    [Suhost]                           NVARCHAR (50)  NULL,
    [Okraska]                          NVARCHAR (20)  NULL,
    [Pigment]                          NVARCHAR (50)  NULL,
    [Pigment2]                         NVARCHAR (20)  NULL,
    [Visipaniya]                       NVARCHAR (20)  NULL,
    [Povrezhdeniya]                    NVARCHAR (20)  NULL,
    [BleskGlaz]                        NVARCHAR (1)   NULL,
    [Giperemiya]                       NVARCHAR (1)   NULL,
    [Slezotechenie]                    NVARCHAR (1)   NULL,
    [SostoyanieKonyunktivi]            NVARCHAR (20)  NULL,
    [SostoyanieSlizistihObolochek]     NVARCHAR (20)  NULL,
    [NalichieNaleta]                   NVARCHAR (1)   NULL,
    [SuhostSO]                         NVARCHAR (50)  NULL,
    [ZubiCondition]                    NVARCHAR (20)  NULL,
    [AD1]                              INT            NULL,
    [AD2]                              INT            NULL,
    [Puls]                             INT            NULL,
    [Ritm]                             NVARCHAR (50)  NULL,
    [AktsentTonaNa]                    NVARCHAR (50)  NULL,
    [Hripi]                            NVARCHAR (50)  NULL,
    [Nasmork]                          NVARCHAR (1)   NULL,
    [Kashel]                           NVARCHAR (1)   NULL,
    [Chihanie]                         NVARCHAR (1)   NULL,
    [Odishka]                          INT            NULL,
    [Hripi2]                           NVARCHAR (20)  NULL,
    [Toshnota]                         NVARCHAR (1)   NULL,
    [Rvota]                            NVARCHAR (1)   NULL,
    [Anoreksiya]                       NVARCHAR (1)   NULL,
    [Ponosi]                           NVARCHAR (1)   NULL,
    [Zapori]                           NVARCHAR (1)   NULL,
    [EditBox2]                         NVARCHAR (20)  NULL,
    [Combo1]                           NVARCHAR (50)  NULL,
    [SelezPalp]                        NVARCHAR (50)  NULL,
    [Pollakiuriya]                     NVARCHAR (1)   NULL,
    [Poliuriya]                        NVARCHAR (1)   NULL,
    [Anuriya]                          NVARCHAR (1)   NULL,
    [DizuricheskieRasstroystva]        NVARCHAR (1)   NULL,
    [SMPasternatskogo]                 NVARCHAR (50)  NULL,
    [ChuvstvitelnostNeNarushena]       NVARCHAR (1)   NULL,
    [Chuvstvitelnost]                  NVARCHAR (50)  NULL,
    [Chuvstvitelnost2]                 NVARCHAR (20)  NULL,
    [DSNeNarushena]                    NVARCHAR (1)   NULL,
    [DS]                               NVARCHAR (50)  NULL,
    [DS2]                              NVARCHAR (20)  NULL,
    [ZrachkiVNorme]                    NVARCHAR (1)   NULL,
    [Mioz]                             NVARCHAR (1)   NULL,
    [Midriaz]                          NVARCHAR (1)   NULL,
    [ReakciyaNaSvet]                   NVARCHAR (50)  NULL,
    [Nistagm]                          NVARCHAR (20)  NULL,
    [TremorVek]                        NVARCHAR (1)   NULL,
    [TremorPaltsevRuk]                 NVARCHAR (1)   NULL,
    [PodergivaniyaLitsevoyMuskulaturi] NVARCHAR (1)   NULL,
    [Sudorogi]                         NVARCHAR (1)   NULL,
    [PodergivaniyaMishtsKonechnostey]  NVARCHAR (1)   NULL,
    [PodergivaniyaTulovisha]           NVARCHAR (1)   NULL,
    [GTR]                              NVARCHAR (50)  NULL,
    [EditBox1]                         NVARCHAR (20)  NULL,
    [PaltseNosovoy]                    NVARCHAR (1)   NULL,
    [PyatochnoKolennoy]                NVARCHAR (1)   NULL,
    [Ukazatelnoy]                      NVARCHAR (1)   NULL,
    [NeustoychivostVPozeRomberga]      NVARCHAR (1)   NULL,
    [SmazannostRechi]                  NVARCHAR (1)   NULL,
    [Zaikanie]                         NVARCHAR (1)   NULL,
    [RasstroystvoPocherka]             NVARCHAR (1)   NULL,
    [Dermografizm]                     NVARCHAR (50)  NULL,
    [SNN]                              NVARCHAR (20)  NULL,
    [SNN2]                             NVARCHAR (20)  NULL,
    [Anamnez1]                         NTEXT          NULL,
    [Zaklyuchenie]                     NVARCHAR (50)  NULL,
    [Kommentrariy]                     NTEXT          NULL,
    [Diagn]                            NTEXT          NULL,
    [DiagnozPoMkb10]                   NVARCHAR (255) NULL,
    CONSTRAINT [OsmotrNarkologaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [OsmotrNarkologaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

