CREATE TABLE [dbo].[OsmotrPsihiatra] (
    [ID]                                               INT            NOT NULL,
    [PatID]                                            INT            NULL,
    [RosIRazvivalsyaVSootvetstviiSVozrastom]           NVARCHAR (1)   NULL,
    [ProhodSrochnSluzhbVAfganistS]                     NVARCHAR (1)   NULL,
    [SluzhilVAfganistaneS]                             NVARCHAR (1)   NULL,
    [OfitserZapasaS]                                   NVARCHAR (1)   NULL,
    [DateBox5]                                         DATETIME       NULL,
    [DateBox6]                                         DATETIME       NULL,
    [NahodVKomandVChechneVMvdS]                        NVARCHAR (1)   NULL,
    [DateBox7]                                         DATETIME       NULL,
    [DateBox8]                                         DATETIME       NULL,
    [SluzhilPoKontraktuVChechneS]                      NVARCHAR (1)   NULL,
    [DateBox9]                                         DATETIME       NULL,
    [DateBox10]                                        DATETIME       NULL,
    [NeposredstUchastVBoevDeystNePrinim]               NVARCHAR (1)   NULL,
    [PrinimalUchastieVBoevihDeystviyah]                NVARCHAR (1)   NULL,
    [PrinimUchastVBoevDeystSVisStepenRisk]             NVARCHAR (1)   NULL,
    [PoluchilRanenieVoVremyaSluzhbi]                   NVARCHAR (1)   NULL,
    [PerenesKontuziyu]                                 NVARCHAR (1)   NULL,
    [PerenesUshibMozga]                                NVARCHAR (1)   NULL,
    [PerenesSotryasenieMozga]                          NVARCHAR (1)   NULL,
    [TravmIRaneniyNeBilo]                              NVARCHAR (1)   NULL,
    [PerenesInfZab]                                    NVARCHAR (50)  NULL,
    [OshushenieNerealnostiOkruzhayusheyObstanovki]     NVARCHAR (1)   NULL,
    [Trevoga]                                          NVARCHAR (1)   NULL,
    [OshushNeyasnUgroziIzVne]                          NVARCHAR (1)   NULL,
    [ChuvstvoVnutrenneyPustoti]                        NVARCHAR (1)   NULL,
    [ChuvstOdnovremenPrisutsDvuhRealnVoyniIMira]       NVARCHAR (1)   NULL,
    [VnezapChuvstChtoKakoeToSobitieVoennogoVrem]       NVARCHAR (1)   NULL,
    [NavyazcVospominanVoennihSobitiy]                  NVARCHAR (1)   NULL,
    [Snovideniya]                                      NVARCHAR (1)   NULL,
    [NostalgiyaToskaPoAfganistanu]                     NVARCHAR (1)   NULL,
    [PerehodeKMirnoyZhizni]                            NVARCHAR (1)   NULL,
    [Simptomatika]                                     NVARCHAR (50)  NULL,
    [Jalobi]                                           NVARCHAR (50)  NULL,
    [ZhalobiSohranyayutsya]                            NVARCHAR (1)   NULL,
    [TravmGolov]                                       NVARCHAR (1)   NULL,
    [NastVrem]                                         NVARCHAR (50)  NULL,
    [SchitaetSebyaZdorovim]                            NVARCHAR (1)   NULL,
    [ImeetGruppuInvalidnosti]                          NVARCHAR (1)   NULL,
    [Stradaet]                                         NVARCHAR (50)  NULL,
    [SeychasSovsemNePet]                               NVARCHAR (1)   NULL,
    [ZloupotrebAlkogNapit]                             NVARCHAR (1)   NULL,
    [BivayutZapoiPoNeskolkoDney]                       NVARCHAR (1)   NULL,
    [TyazheloPerenositPohmele]                         NVARCHAR (1)   NULL,
    [InogdZabivToChtoDelalVSostOpyan]                  NVARCHAR (1)   NULL,
    [ProhodilProtivoalkogolnoeLechenie]                NVARCHAR (1)   NULL,
    [DateBox12]                                        DATETIME       NULL,
    [NikogdaNeProhodProtivoalkogLechen]                NVARCHAR (1)   NULL,
    [NarSna]                                           NVARCHAR (50)  NULL,
    [BistrayaUtomlyaemost]                             NVARCHAR (1)   NULL,
    [NarushenieSna]                                    NVARCHAR (1)   NULL,
    [Rabotospos]                                       NVARCHAR (50)  NULL,
    [OtmechaetRazdrazhit]                              NVARCHAR (1)   NULL,
    [Razdraj]                                          NVARCHAR (50)  NULL,
    [ProyavlAgressivnost]                              NVARCHAR (1)   NULL,
    [NastroenieSnizheno]                               NVARCHAR (1)   NULL,
    [BespokoitTrevogaStrahNeuverennostVZavtrashnemDne] NVARCHAR (1)   NULL,
    [NedoverKOkruzhayush]                              NVARCHAR (1)   NULL,
    [OtmechaetSnizheniePamyati]                        NVARCHAR (1)   NULL,
    [SnijPamyati]                                      NVARCHAR (50)  NULL,
    [NostalgiyaPoAfganistanu]                          NVARCHAR (1)   NULL,
    [Orientirovan]                                     NVARCHAR (1)   NULL,
    [KontaktuDostupen]                                 NVARCHAR (1)   NULL,
    [VBesedeNeZainteresovan]                           NVARCHAR (1)   NULL,
    [Nastroen]                                         NVARCHAR (50)  NULL,
    [Pamyat]                                           NVARCHAR (50)  NULL,
    [Intelekt]                                         NVARCHAR (50)  NULL,
    [Combo2]                                           NVARCHAR (50)  NULL,
    [Combo3]                                           NVARCHAR (50)  NULL,
    [Rasstroystva]                                     NVARCHAR (50)  NULL,
    [Bred]                                             NVARCHAR (1)   NULL,
    [Gallyutsinatsii]                                  NVARCHAR (1)   NULL,
    [SuitsidalnieMisli]                                NVARCHAR (1)   NULL,
    [Kritika]                                          NVARCHAR (50)  NULL,
    [Data]                                             DATETIME       NULL,
    [Vrach]                                            INT            NULL,
    [BLNomer]                                          INT            NULL,
    [Srok]                                             DATETIME       NULL,
    [AktivnoePoseshenie]                               NVARCHAR (50)  NULL,
    [PovtornayaYavka]                                  DATETIME       NULL,
    [DistsirkulEntsefalop]                             NVARCHAR (1)   NULL,
    [Stepen]                                           NVARCHAR (50)  NULL,
    [DiscEncef]                                        NVARCHAR (50)  NULL,
    [SindromKognNarush]                                NVARCHAR (1)   NULL,
    [VestibulyarniySindrom]                            NVARCHAR (1)   NULL,
    [NevrostenSindrom]                                 NVARCHAR (1)   NULL,
    [SudorozhniySindrom]                               NVARCHAR (1)   NULL,
    [AstenSubdepres]                                   NVARCHAR (1)   NULL,
    [Dementsiya]                                       NVARCHAR (1)   NULL,
    [OrganichBredRasstr]                               NVARCHAR (1)   NULL,
    [OrganicheskiyGallyutsinoz]                        NVARCHAR (1)   NULL,
    [Deliriy]                                          NVARCHAR (1)   NULL,
    [Diagn]                                            NTEXT          NULL,
    [GruppaInvalidnosti]                               NVARCHAR (1)   NULL,
    [GruppaInvalidn]                                   NVARCHAR (50)  NULL,
    [Neyroleptikami]                                   NVARCHAR (1)   NULL,
    [Nootropami]                                       NVARCHAR (1)   NULL,
    [Antikonvulsantami]                                NVARCHAR (1)   NULL,
    [Trankvilizatorami]                                NVARCHAR (1)   NULL,
    [SosudistimiPreparatami]                           NVARCHAR (1)   NULL,
    [DegidrotatTerap]                                  NVARCHAR (1)   NULL,
    [PsihicheskiyAnamnezNeOtyagoshen]                  NVARCHAR (1)   NULL,
    [PsihiatramNeObrashalsya]                          NVARCHAR (1)   NULL,
    [NahodPodNablyudenPsih]                            NVARCHAR (1)   NULL,
    [PoluchaetLechenie]                                NVARCHAR (1)   NULL,
    [PoluchLech]                                       NVARCHAR (50)  NULL,
    [LechenVPsihBoln]                                  NVARCHAR (1)   NULL,
    [God]                                              INT            NULL,
    [ZatrudnenZasip]                                   NVARCHAR (1)   NULL,
    [OtsutstvChuvstvaSna]                              NVARCHAR (1)   NULL,
    [NarushenieFormuliSna]                             NVARCHAR (1)   NULL,
    [RannieProbuzhdeniya]                              NVARCHAR (1)   NULL,
    [PrerivistiySon]                                   NVARCHAR (1)   NULL,
    [Dostupen]                                         NVARCHAR (1)   NULL,
    [Zatrudnen]                                        NVARCHAR (1)   NULL,
    [Maloproduktiven]                                  NVARCHAR (1)   NULL,
    [Nastroenie]                                       NVARCHAR (50)  NULL,
    [Intellekt]                                        NVARCHAR (50)  NULL,
    [Vnimanie]                                         NVARCHAR (50)  NULL,
    [Obstoyatelnoe]                                    NVARCHAR (1)   NULL,
    [Vyazkoe]                                          NVARCHAR (1)   NULL,
    [Mishlenie1]                                       NVARCHAR (50)  NULL,
    [Logichnoe]                                        NVARCHAR (1)   NULL,
    [Rigidnoe]                                         NVARCHAR (1)   NULL,
    [Neproduktivnoe]                                   NVARCHAR (1)   NULL,
    [Mishlen2]                                         NVARCHAR (50)  NULL,
    [Razdrazhitelnost]                                 NVARCHAR (1)   NULL,
    [SnizhennoeNastroenie]                             NVARCHAR (1)   NULL,
    [Slezlivost]                                       NVARCHAR (1)   NULL,
    [Slabodushie]                                      NVARCHAR (1)   NULL,
    [NeobosnovanniyStrah]                              NVARCHAR (1)   NULL,
    [Napryazhennost]                                   NVARCHAR (1)   NULL,
    [SnijeniePamyati]                                  NVARCHAR (50)  NULL,
    [Golovokrujenie]                                   NVARCHAR (50)  NULL,
    [ShumVGolove]                                      NVARCHAR (50)  NULL,
    [Padenie]                                          NVARCHAR (50)  NULL,
    [GolovnieBoli]                                     NVARCHAR (50)  NULL,
    [Rabotosposobnost]                                 NVARCHAR (50)  NULL,
    [Projivaet]                                        NVARCHAR (50)  NULL,
    [Projiv]                                           NVARCHAR (100) NULL,
    [SamSebyaObsluzhivaet]                             NVARCHAR (1)   NULL,
    [NuzhdVPostoronUhod]                               NVARCHAR (1)   NULL,
    [SoblyudPravilaGigien]                             NVARCHAR (1)   NULL,
    [ZaSoboyNeSledit]                                  NVARCHAR (1)   NULL,
    [IzDomaNeVihodit]                                  NVARCHAR (1)   NULL,
    [ZritelnieGallyutsinatsii]                         NVARCHAR (1)   NULL,
    [VerbalnieGallyutsinatsii]                         NVARCHAR (1)   NULL,
    [ObonyatelnieGallyutsinatsii]                      NVARCHAR (1)   NULL,
    [IstinnieGallyutsinatsii]                          NVARCHAR (1)   NULL,
    [Psevdogallyutsinatsii]                            NVARCHAR (1)   NULL,
    [FIO]                                              NVARCHAR (50)  NULL,
    [BirthDate]                                        DATETIME       NULL,
    [MestoOsmotra]                                     NVARCHAR (50)  NULL,
    [AdresRegistracii]                                 NVARCHAR (50)  NULL,
    [Zaklyuchenie]                                     NVARCHAR (50)  NULL,
    [Kommentrariy]                                     NTEXT          NULL,
    [DiagnozPoMkb10]                                   NVARCHAR (255) NULL,
    [PsihAnamnezNeOtyagosh]                            NVARCHAR (1)   NULL,
    [DateBox1]                                         DATETIME       NULL,
    [DateBox2]                                         DATETIME       NULL,
    [DateBox3]                                         DATETIME       NULL,
    [DateBox4]                                         DATETIME       NULL,
    [Combo1]                                           NVARCHAR (50)  NULL,
    [DateBox11]                                        DATETIME       NULL,
    CONSTRAINT [OsmotrPsihiatraPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [OsmotrPsihiatraToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

