CREATE TABLE [dbo].[OsmotrPsihiatraDlyaUchastnikovVov] (
    [ID]                              INT            NOT NULL,
    [PatID]                           INT            NULL,
    [PsihicheskiyAnamnezNeOtyagoshen] NVARCHAR (1)   NULL,
    [Data]                            DATETIME       NULL,
    [Vrach]                           INT            NULL,
    [PsihiatramNeObrashalsya]         NVARCHAR (1)   NULL,
    [NahodPodNablyudenPsih]           NVARCHAR (1)   NULL,
    [PoluchaetLechenie]               NVARCHAR (1)   NULL,
    [PoluchLech]                      NVARCHAR (50)  NULL,
    [LechenVPsihBoln]                 NVARCHAR (1)   NULL,
    [Neyroleptikami]                  NVARCHAR (1)   NULL,
    [Trankvilizatorami]               NVARCHAR (1)   NULL,
    [Antikonvulsantami]               NVARCHAR (1)   NULL,
    [Nootropami]                      NVARCHAR (1)   NULL,
    [SosudistimiPreparatami]          NVARCHAR (1)   NULL,
    [DegidrotatTerap]                 NVARCHAR (1)   NULL,
    [TravmaGoloviV]                   NVARCHAR (1)   NULL,
    [PerenOperats]                    NVARCHAR (1)   NULL,
    [Operats]                         NVARCHAR (100) NULL,
    [KontuzGolovMozga]                NVARCHAR (1)   NULL,
    [InsultV]                         NVARCHAR (1)   NULL,
    [God]                             INT            NULL,
    [God1]                            INT            NULL,
    [God2]                            INT            NULL,
    [God3]                            INT            NULL,
    [God4]                            INT            NULL,
    [InfarktMiokardaV]                NVARCHAR (1)   NULL,
    [God6]                            INT            NULL,
    [SaharniyDiabet]                  NVARCHAR (1)   NULL,
    [SaharnDiabet]                    NVARCHAR (50)  NULL,
    [GipertonicheskieKrizisi]         NVARCHAR (1)   NULL,
    [SudorozhniePristupi]             NVARCHAR (1)   NULL,
    [SudorPrist]                      NVARCHAR (50)  NULL,
    [KolichestvoVMesyac]              INT            NULL,
    [KolichestvoVMesyac1]             INT            NULL,
    [God7]                            INT            NULL,
    [Data1]                           DATETIME       NULL,
    [GruppaInvalidnosti]              NVARCHAR (1)   NULL,
    [GruppaInvalidn]                  NVARCHAR (50)  NULL,
    [Projivaet]                       NVARCHAR (50)  NULL,
    [Projiv]                          NVARCHAR (100) NULL,
    [SamSebyaObsluzhivaet]            NVARCHAR (1)   NULL,
    [NuzhdVPostoronUhod]              NVARCHAR (1)   NULL,
    [SoblyudPravilaGigien]            NVARCHAR (1)   NULL,
    [ZaSoboyNeSledit]                 NVARCHAR (1)   NULL,
    [IzDomaNeVihodit]                 NVARCHAR (1)   NULL,
    [God8]                            INT            NULL,
    [God9]                            INT            NULL,
    [God10]                           INT            NULL,
    [God11]                           INT            NULL,
    [SnijeniePamyati]                 NVARCHAR (50)  NULL,
    [Golovokrujenie]                  NVARCHAR (50)  NULL,
    [ShumVGolove]                     NVARCHAR (50)  NULL,
    [Padenie]                         NVARCHAR (50)  NULL,
    [GolovnieBoli]                    NVARCHAR (50)  NULL,
    [Rabotosposobnost]                NVARCHAR (50)  NULL,
    [ZatrudnenZasip]                  NVARCHAR (1)   NULL,
    [OtsutstvChuvstvaSna]             NVARCHAR (1)   NULL,
    [NarushenieFormuliSna]            NVARCHAR (1)   NULL,
    [RannieProbuzhdeniya]             NVARCHAR (1)   NULL,
    [PrerivistiySon]                  NVARCHAR (1)   NULL,
    [Razdraj]                         NVARCHAR (50)  NULL,
    [Razdrazhitelnost]                NVARCHAR (1)   NULL,
    [SnizhennoeNastroenie]            NVARCHAR (1)   NULL,
    [Slezlivost]                      NVARCHAR (1)   NULL,
    [Slabodushie]                     NVARCHAR (1)   NULL,
    [Trevoga]                         NVARCHAR (1)   NULL,
    [NeobosnovanniyStrah]             NVARCHAR (1)   NULL,
    [Napryazhennost]                  NVARCHAR (1)   NULL,
    [Memo1]                           NTEXT          NULL,
    [Gallyutsinatsii]                 NVARCHAR (1)   NULL,
    [Gallyucinacii]                   NVARCHAR (50)  NULL,
    [Memo2]                           NTEXT          NULL,
    [Orientirovan]                    NVARCHAR (50)  NULL,
    [Dostupen]                        NVARCHAR (1)   NULL,
    [Zatrudnen]                       NVARCHAR (1)   NULL,
    [Maloproduktiven]                 NVARCHAR (1)   NULL,
    [VBesedeNeZainteresovan]          NVARCHAR (1)   NULL,
    [Nastroenie]                      NVARCHAR (50)  NULL,
    [Pamyat]                          NVARCHAR (50)  NULL,
    [Intellekt]                       NVARCHAR (50)  NULL,
    [Vnimanie]                        NVARCHAR (50)  NULL,
    [Obstoyatelnoe]                   NVARCHAR (1)   NULL,
    [Vyazkoe]                         NVARCHAR (1)   NULL,
    [Mishlenie1]                      NVARCHAR (50)  NULL,
    [Logichnoe]                       NVARCHAR (1)   NULL,
    [Rigidnoe]                        NVARCHAR (1)   NULL,
    [Neproduktivnoe]                  NVARCHAR (1)   NULL,
    [Mishlen2]                        NVARCHAR (50)  NULL,
    [ZritelnieGallyutsinatsii]        NVARCHAR (1)   NULL,
    [VerbalnieGallyutsinatsii]        NVARCHAR (1)   NULL,
    [ObonyatelnieGallyutsinatsii]     NVARCHAR (1)   NULL,
    [IstinnieGallyutsinatsii]         NVARCHAR (1)   NULL,
    [Psevdogallyutsinatsii]           NVARCHAR (1)   NULL,
    [Bred]                            NVARCHAR (1)   NULL,
    [SuitsidalnieMisli]               NVARCHAR (1)   NULL,
    [Kritika]                         NVARCHAR (50)  NULL,
    [BLNomer]                         INT            NULL,
    [Srok]                            DATETIME       NULL,
    [AktivnoePoseshenie]              NVARCHAR (50)  NULL,
    [PovtornayaYavka]                 DATETIME       NULL,
    [DistsirkulEntsefalop]            NVARCHAR (1)   NULL,
    [Stepen]                          NVARCHAR (50)  NULL,
    [DiscEncef]                       NVARCHAR (50)  NULL,
    [SindromKognNarush]               NVARCHAR (1)   NULL,
    [VestibulyarniySindrom]           NVARCHAR (1)   NULL,
    [NevrostenSindrom]                NVARCHAR (1)   NULL,
    [SudorozhniySindrom]              NVARCHAR (1)   NULL,
    [AstenSubdepres]                  NVARCHAR (1)   NULL,
    [Dementsiya]                      NVARCHAR (1)   NULL,
    [OrganichBredRasstr]              NVARCHAR (1)   NULL,
    [OrganicheskiyGallyutsinoz]       NVARCHAR (1)   NULL,
    [Deliriy]                         NVARCHAR (1)   NULL,
    [Diagn]                           NTEXT          NULL,
    CONSTRAINT [OsmotrPsihiatraDlyaUchastnikovVovPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [OsmotrPsihiatraDlyaUchastnikovVovToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

