CREATE TABLE [dbo].[OsmotrPediatra] (
    [ID]                               INT            NOT NULL,
    [PatID]                            INT            NULL,
    [Data]                             DATETIME       NULL,
    [DocTime]                          DATETIME       NULL,
    [Zhalobi]                          NTEXT          NULL,
    [AnamnezZhizni]                    NTEXT          NULL,
    [AnamnezZhizni1]                   NTEXT          NULL,
    [AnamnezZhizni2]                   NTEXT          NULL,
    [GrudVskarml]                      INT            NULL,
    [RozhdVes]                         INT            NULL,
    [RozhdRost]                        INT            NULL,
    [Allergic]                         NTEXT          NULL,
    [Allergic2]                        NTEXT          NULL,
    [Allergic4]                        NTEXT          NULL,
    [EpidAnamnes]                      NTEXT          NULL,
    [Operatsii]                        NVARCHAR (1)   NULL,
    [Operatsii2]                       NTEXT          NULL,
    [Transfuzii]                       NVARCHAR (1)   NULL,
    [Transfuzii2]                      NTEXT          NULL,
    [Inektsii]                         NVARCHAR (1)   NULL,
    [Inektsii2]                        NTEXT          NULL,
    [LechenieUStomatologa]             NVARCHAR (1)   NULL,
    [LechenieUStomatologa2]            NTEXT          NULL,
    [NoAllergy]                        NVARCHAR (1)   NULL,
    [PlanObsledovaniya]                NTEXT          NULL,
    [PlanLecheniya]                    NTEXT          NULL,
    [Recomendacii]                     NTEXT          NULL,
    [T]                                FLOAT (53)     NULL,
    [ChSS]                             FLOAT (53)     NULL,
    [ChD]                              FLOAT (53)     NULL,
    [OkruzhnostGolovy]                 FLOAT (53)     NULL,
    [OkruzhnostGrudi]                  FLOAT (53)     NULL,
    [BolRodnichok]                     FLOAT (53)     NULL,
    [SostoyanieZubov]                  NVARCHAR (250) NULL,
    [IndexPolovogoRazv]                NVARCHAR (250) NULL,
    [ObshiyOsmotr]                     NTEXT          NULL,
    [Nevrolog]                         NTEXT          NULL,
    [Lor]                              NTEXT          NULL,
    [Ortoped]                          NTEXT          NULL,
    [Vrach]                            NVARCHAR (50)  NULL,
    [Sostoyznie]                       NVARCHAR (50)  NULL,
    [Reakciya]                         NVARCHAR (250) NULL,
    [Teloslojenie]                     NVARCHAR (250) NULL,
    [Pitanie]                          NVARCHAR (250) NULL,
    [Koja]                             NVARCHAR (250) NULL,
    [Zev]                              NVARCHAR (250) NULL,
    [Mindalini]                        NVARCHAR (250) NULL,
    [Sostoyznie1]                      NVARCHAR (250) NULL,
    [Tonzillyarnie]                    NVARCHAR (16)  NULL,
    [BokovieSheynie]                   NVARCHAR (20)  NULL,
    [Zatilochnie]                      NVARCHAR (19)  NULL,
    [Pahovie]                          NVARCHAR (19)  NULL,
    [Podmishechnie]                    NVARCHAR (20)  NULL,
    [UvelicheniUzliDr]                 NVARCHAR (50)  NULL,
    [limfouzliklichestvo]              NVARCHAR (250) NULL,
    [limfouzlivelichina]               NVARCHAR (250) NULL,
    [BoleznenniePriPalpatsii]          NVARCHAR (40)  NULL,
    [Podvijnie]                        NVARCHAR (40)  NULL,
    [LuzliDr]                          NVARCHAR (50)  NULL,
    [PerkutorniyZvuk]                  NVARCHAR (250) NULL,
    [Yasnie]                           NVARCHAR (10)  NULL,
    [Ritmichnie]                       NVARCHAR (15)  NULL,
    [DrugoeToni]                       NVARCHAR (250) NULL,
    [Vezikulyarnoe]                    NVARCHAR (40)  NULL,
    [RavnomernoProvoditsyaVoVseOtdeli] NVARCHAR (40)  NULL,
    [HripovNet]                        NVARCHAR (40)  NULL,
    [DrugoeDih]                        NVARCHAR (250) NULL,
    [Myagkiy]                          NVARCHAR (15)  NULL,
    [Bezboleznenniy]                   NVARCHAR (40)  NULL,
    [UKrayaRebernoyDugi]               NVARCHAR (25)  NULL,
    [NePalpiruetsya]                   NVARCHAR (15)  NULL,
    [DrugoJiv]                         NVARCHAR (250) NULL,
    [DrugoePechen]                     NVARCHAR (250) NULL,
    [DrugoeSelezenka]                  NVARCHAR (250) NULL,
    [Stul2]                            NVARCHAR (250) NULL,
    [Svob]                             NVARCHAR (15)  NULL,
    [Bezboleznenniy1]                  NVARCHAR (40)  NULL,
    [DrugoeMocheispuckanie]            NVARCHAR (250) NULL,
    [NPO2]                             NVARCHAR (250) NULL,
    [Otsutstvuyut]                     NVARCHAR (15)  NULL,
    [mening]                           NVARCHAR (250) NULL,
    [RefleksiNovorojdennih]            NVARCHAR (250) NULL,
    [bolshoyrodnichok]                 NVARCHAR (250) NULL,
    [Tonusmishc]                       NVARCHAR (250) NULL,
    [BezPatologii]                     NVARCHAR (50)  NULL,
    [kostnayasistdr]                   NVARCHAR (50)  NULL,
    [Skolkodneyrebenku]                FLOAT (53)     NULL,
    CONSTRAINT [OsmotrPediatraPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [OsmotrPediatraToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

