CREATE TABLE [dbo].[OsmotrKardiologa] (
    [ID]                          INT            NOT NULL,
    [PatID]                       INT            NULL,
    [Zhalobi]                     NTEXT          NULL,
    [AnamnezZabolevaniya]         NTEXT          NULL,
    [Diagnoz]                     NTEXT          NULL,
    [NaznachennoeIssledovanie]    NVARCHAR (50)  NULL,
    [OkraskaKozhnihPokrovov]      NVARCHAR (30)  NULL,
    [Vlazhnost]                   NVARCHAR (30)  NULL,
    [Oteki]                       INT            NULL,
    [Oteki1]                      NVARCHAR (30)  NULL,
    [LimfaticheskieUzli1]         NVARCHAR (30)  NULL,
    [LimfaticheskieUzli]          INT            NULL,
    [Sustavi]                     NVARCHAR (30)  NULL,
    [Boleznennost]                NVARCHAR (30)  NULL,
    [Konfiguratsiya1]             NVARCHAR (30)  NULL,
    [Konfiguratsiya]              INT            NULL,
    [Kontraktura]                 NVARCHAR (1)   NULL,
    [Ankiloz]                     NVARCHAR (1)   NULL,
    [Zev]                         NTEXT          NULL,
    [Mindalini]                   NTEXT          NULL,
    [Hripi]                       INT            NULL,
    [Hripi1]                      NVARCHAR (15)  NULL,
    [Dihanie]                     NVARCHAR (30)  NULL,
    [GranitsiSerdtsa]             NVARCHAR (30)  NULL,
    [Puls]                        INT            NULL,
    [Napolnenie]                  NVARCHAR (30)  NULL,
    [Napryazhenie]                NVARCHAR (30)  NULL,
    [ToniSerdtsa]                 NVARCHAR (30)  NULL,
    [VerhushechniyTolchok]        NVARCHAR (30)  NULL,
    [ShumiSerdtsa]                NTEXT          NULL,
    [NadSosudami]                 NTEXT          NULL,
    [AdNaLevoyRuke]               INT            NULL,
    [AdNaLevoyRuke1]              INT            NULL,
    [AdNaPravoyRuke]              INT            NULL,
    [AdNaPravoyRuke1]             INT            NULL,
    [RazmeriPecheniPoKurlovu]     FLOAT (53)     NULL,
    [Harakteristika]              NTEXT          NULL,
    [Selezenka]                   NTEXT          NULL,
    [Dopolnitelno]                NTEXT          NULL,
    [DihaniePrimechanie]          NTEXT          NULL,
    [AktsentVtorogoTonaNadAortoy] NVARCHAR (30)  NULL,
    [NadLegochnoyArteriey]        NVARCHAR (30)  NULL,
    [RazmeriPecheniPoKurlovu1]    FLOAT (53)     NULL,
    [RazmeriPecheniPoKurlovu2]    FLOAT (53)     NULL,
    [Defitsit]                    INT            NULL,
    [Mocheispuskanie]             NVARCHAR (30)  NULL,
    [Vrach]                       NVARCHAR (50)  NULL,
    [Data]                        DATETIME       NULL,
    [KodPoMkb10]                  NVARCHAR (10)  NULL,
    [DiagnozPoMkb10]              NVARCHAR (80)  NULL,
    [Zaklyuchenie]                NVARCHAR (50)  NULL,
    [Kommentrariy]                NTEXT          NULL,
    [RazmeriPecheniPoKurlovu3]    FLOAT (53)     NULL,
    [RazmeriPecheniPoKurlovu4]    FLOAT (53)     NULL,
    [AdNaPravoyRuke2]             INT            NULL,
    [Hripi2]                      NVARCHAR (15)  NULL,
    [Konfiguratsiya2]             NTEXT          NULL,
    [AdNaLevoyRuke2]              INT            NULL,
    [LimfaticheskieUzli2]         NTEXT          NULL,
    [Oteki2]                      NTEXT          NULL,
    [DocTime]                     DATETIME       NULL,
    [PlanLech2]                   NVARCHAR (255) NULL,
    [planlech1]                   NVARCHAR (50)  NULL,
    [Planobsl]                    NVARCHAR (50)  NULL,
    [PlanObsledovaniya]           NTEXT          NULL,
    [PlanLecheniya]               NTEXT          NULL,
    [Recomendacii]                NTEXT          NULL,
    [zakl]                        NTEXT          NULL,
    CONSTRAINT [OsmotrKardiologaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [OsmotrKardiologaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

