CREATE TABLE [dbo].[OsmotrHirurgaPervichniy] (
    [ID]                                                                           INT            NOT NULL,
    [PatID]                                                                        INT            NULL,
    [Data]                                                                         DATETIME       NULL,
    [Vrach]                                                                        INT            NULL,
    [Zhalobi]                                                                      NTEXT          NULL,
    [Anamnez]                                                                      NTEXT          NULL,
    [VerhnieKonechnosti]                                                           NVARCHAR (50)  NULL,
    [NizhnieKonechnosti]                                                           NVARCHAR (50)  NULL,
    [Sustavi]                                                                      NVARCHAR (50)  NULL,
    [Yazik]                                                                        NVARCHAR (50)  NULL,
    [Yazik1]                                                                       NVARCHAR (50)  NULL,
    [Yazik2]                                                                       NVARCHAR (50)  NULL,
    [Stul]                                                                         NVARCHAR (50)  NULL,
    [Stul1]                                                                        NVARCHAR (50)  NULL,
    [PryamayaKishka]                                                               NVARCHAR (50)  NULL,
    [DopolnitelnieDannie]                                                          NTEXT          NULL,
    [ProvodimieManipulyatsii]                                                      NTEXT          NULL,
    [Diagnoz]                                                                      NVARCHAR (50)  NULL,
    [BLNomer]                                                                      INT            NULL,
    [Srok]                                                                         DATETIME       NULL,
    [AktivnoePoseshenie]                                                           NVARCHAR (50)  NULL,
    [YavkaVPolikliniku]                                                            DATETIME       NULL,
    [Kozja]                                                                        NTEXT          NULL,
    [LimfUzli]                                                                     NTEXT          NULL,
    [Jivot]                                                                        NVARCHAR (50)  NULL,
    [Combo1]                                                                       NVARCHAR (50)  NULL,
    [Jiv]                                                                          NVARCHAR (100) NULL,
    [MishZash]                                                                     NVARCHAR (100) NULL,
    [Pechen]                                                                       NVARCHAR (50)  NULL,
    [Pechen1]                                                                      NVARCHAR (100) NULL,
    [Naznach]                                                                      NTEXT          NULL,
    [Obsled]                                                                       NTEXT          NULL,
    [Combo9]                                                                       NVARCHAR (50)  NULL,
    [BoliVSustavah]                                                                NVARCHAR (1)   NULL,
    [BoliVIkronozhnihMishtsahPriHodbe]                                             NVARCHAR (1)   NULL,
    [BoliVNogahVPokoe]                                                             NVARCHAR (1)   NULL,
    [ZyabkostStop]                                                                 NVARCHAR (1)   NULL,
    [SudorogiVMishtsahNogPreimushestvennoVPokoe]                                   NVARCHAR (1)   NULL,
    [OtekiNogUsilivayushiesyaKVecheru]                                             NVARCHAR (1)   NULL,
    [BoliVZhivote]                                                                 NVARCHAR (1)   NULL,
    [Combo3]                                                                       NVARCHAR (50)  NULL,
    [Toshnota]                                                                     NVARCHAR (1)   NULL,
    [RvotaZhelchyu]                                                                NVARCHAR (1)   NULL,
    [RvotaSedennoyPishey]                                                          NVARCHAR (1)   NULL,
    [RvotaKofeynoyGushey]                                                          NVARCHAR (1)   NULL,
    [Combo4]                                                                       NVARCHAR (50)  NULL,
    [Combo5]                                                                       NVARCHAR (50)  NULL,
    [Combo6]                                                                       NVARCHAR (50)  NULL,
    [Kozha]                                                                        NVARCHAR (50)  NULL,
    [Kozha1]                                                                       NVARCHAR (50)  NULL,
    [Kozha2]                                                                       NVARCHAR (50)  NULL,
    [Kozha3]                                                                       NVARCHAR (50)  NULL,
    [Kozha4]                                                                       NVARCHAR (50)  NULL,
    [LU]                                                                           NVARCHAR (50)  NULL,
    [LU2]                                                                          NVARCHAR (50)  NULL,
    [Sustavi1]                                                                     NVARCHAR (50)  NULL,
    [Combo7]                                                                       NVARCHAR (50)  NULL,
    [PulsatsiyaArteriyMagistralnihIPerifericheskihOtchetlivayaVStandartnihTochkah] NVARCHAR (1)   NULL,
    [Combo8]                                                                       NVARCHAR (50)  NULL,
    [FlebektaziyaVOblastiNizhnihKonechnostey]                                      NVARCHAR (1)   NULL,
    [Oteki]                                                                        NVARCHAR (1)   NULL,
    [Combo10]                                                                      NVARCHAR (50)  NULL,
    [Myagkiy]                                                                      NVARCHAR (1)   NULL,
    [Vzdut]                                                                        NVARCHAR (1)   NULL,
    [Boleznenniy]                                                                  NVARCHAR (1)   NULL,
    [Combo11]                                                                      NVARCHAR (50)  NULL,
    [VEpigastrii]                                                                  NVARCHAR (1)   NULL,
    [VPravoyPodvzdoshnoyOblasti]                                                   NVARCHAR (1)   NULL,
    [Razlitaya]                                                                    NVARCHAR (1)   NULL,
    [PalpiruetsyaUKrayaRebernoyDugi]                                               NVARCHAR (1)   NULL,
    [Uvelichena]                                                                   NVARCHAR (1)   NULL,
    [CheckBox1]                                                                    NVARCHAR (1)   NULL,
    [ShetkinaBlyumberga]                                                           NVARCHAR (1)   NULL,
    [Razdolskogo]                                                                  NVARCHAR (1)   NULL,
    [Pokolachivaniya]                                                              NVARCHAR (1)   NULL,
    [VPravomPodrebere1]                                                            NVARCHAR (1)   NULL,
    [OpoyasivayushayaVVerhnihOtdelahZhivota1]                                      NVARCHAR (1)   NULL,
    [MyussiGeorgievskogo1]                                                         NVARCHAR (1)   NULL,
    [Kera1]                                                                        NVARCHAR (1)   NULL,
    [GrekovaOrtnera1]                                                              NVARCHAR (1)   NULL,
    [Rovzinga1]                                                                    NVARCHAR (1)   NULL,
    [Obraztsova1]                                                                  NVARCHAR (1)   NULL,
    [Sitkovskogo1]                                                                 NVARCHAR (1)   NULL,
    [Mozesa]                                                                       NVARCHAR (1)   NULL,
    [Homansa]                                                                      NVARCHAR (1)   NULL,
    [Yazik3]                                                                       NVARCHAR (50)  NULL,
    [Yazik4]                                                                       NVARCHAR (50)  NULL,
    [Yazik5]                                                                       NVARCHAR (50)  NULL,
    [Stul2]                                                                        NVARCHAR (50)  NULL,
    [Stul3]                                                                        NVARCHAR (50)  NULL,
    [MocheispuskanieNeNarusheno]                                                   NVARCHAR (1)   NULL,
    [Combo2]                                                                       NVARCHAR (50)  NULL,
    [EditBox1]                                                                     NVARCHAR (50)  NULL,
    [ObrabotkaKozhiRastvoromSpirta70]                                              NVARCHAR (1)   NULL,
    [ObrabotkaRaniRastvoromPerekisiVodoroda3]                                      NVARCHAR (1)   NULL,
    [ProizvedenoVskritieGnoynika]                                                  NVARCHAR (1)   NULL,
    [VipolnenaPunktsiya]                                                           NVARCHAR (1)   NULL,
    [UstanovlenDrenazh]                                                            NVARCHAR (1)   NULL,
    [VipolnenaReviziyaRani]                                                        NVARCHAR (1)   NULL,
    [SvishevoyHodPromitRastvoramiAntiseptikovRRN2o23RRFuratsilina002]              NVARCHAR (1)   NULL,
    [Memo1]                                                                        NTEXT          NULL,
    [MestnayaAnesteziyaSolNovocaini2]                                              NVARCHAR (1)   NULL,
    [MestnayaAnesteziyaSolNovocaini05]                                             NVARCHAR (1)   NULL,
    [MestnayaAnesteziyaSolLidocaini2]                                              NVARCHAR (1)   NULL,
    [Memo2]                                                                        NTEXT          NULL,
    [Memo3]                                                                        NTEXT          NULL,
    [Naznachen]                                                                    NTEXT          NULL,
    [Obsledovan]                                                                   NTEXT          NULL,
    [Ds]                                                                           NVARCHAR (100) NULL,
    CONSTRAINT [OsmotrHirurgaPervichniyPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [OsmotrHirurgaPervichniyToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

