CREATE TABLE [dbo].[OsmotrEndokrinologaPerv] (
    [ID]                            INT           NOT NULL,
    [PatID]                         INT           NULL,
    [NalichieOslozhneniyTransfuzii] NTEXT         NULL,
    [GruppaKrovi]                   NVARCHAR (50) NULL,
    [Rh]                            NVARCHAR (50) NULL,
    [TransfuziiRanshe]              NVARCHAR (50) NULL,
    [BitovieUsloviya]               NVARCHAR (50) NULL,
    [LichnayaGigiena]               NVARCHAR (50) NULL,
    [UpotreblenieNarkotikov]        NVARCHAR (50) NULL,
    [IstochnikPitevoyVodi]          NVARCHAR (50) NULL,
    [UpotreblenieSiroyVodi]         NVARCHAR (50) NULL,
    [Zhazhda]                       NVARCHAR (1)  NULL,
    [SuhostVoRtu]                   NVARCHAR (1)  NULL,
    [Poliuriya]                     NVARCHAR (1)  NULL,
    [Nikturiya]                     NVARCHAR (1)  NULL,
    [Pohudanie]                     NVARCHAR (1)  NULL,
    [ZyabkostStop]                  NVARCHAR (1)  NULL,
    [ZhzhenieVStopah]               NVARCHAR (1)  NULL,
    [OnemenieVStopah]               NVARCHAR (1)  NULL,
    [PolzanieMurashek]              NVARCHAR (1)  NULL,
    [SudorogiVIkronozhnihMishtsah]  NVARCHAR (1)  NULL,
    [DrozhVTele]                    NVARCHAR (1)  NULL,
    [DrozhVRukah]                   NVARCHAR (1)  NULL,
    [OnemenieKistey]                NVARCHAR (1)  NULL,
    [ZyabkostVerhnihKonechnostey]   NVARCHAR (1)  NULL,
    [TreshiniNaStopah]              NVARCHAR (1)  NULL,
    [TroficheskieIzmeneniyaStop]    NVARCHAR (1)  NULL,
    [Golovokruzhenie]               NVARCHAR (1)  NULL,
    [ShumVGolove]                   NVARCHAR (1)  NULL,
    [GipoglikemicheskoeSostoyanie]  NVARCHAR (1)  NULL,
    [GipoklimSost]                  NVARCHAR (50) NULL,
    [SuhostKozhi]                   NVARCHAR (1)  NULL,
    [Zyabkost]                      NVARCHAR (1)  NULL,
    [Sonliv]                        NVARCHAR (1)  NULL,
    [SaharniyDiabetVTechenie]       NVARCHAR (1)  NULL,
    [Let]                           INT           NULL,
    [NaDUchete]                     NVARCHAR (1)  NULL,
    [ProyavleniyaPolineyropatii]    NVARCHAR (1)  NULL,
    [ProyavleniyaRetinopatii]       NVARCHAR (1)  NULL,
    [ProyavleniyaNefropatii]        NVARCHAR (1)  NULL,
    [Let1]                          INT           NULL,
    [Let2]                          INT           NULL,
    [Let3]                          INT           NULL,
    [Let4]                          INT           NULL,
    [TremorRuk]                     NVARCHAR (1)  NULL,
    [Tremor]                        NVARCHAR (50) NULL,
    [OtekiLitsaIKonechnostey]       NVARCHAR (1)  NULL,
    [OtekKonechn]                   NVARCHAR (50) NULL,
    [NukturiyaRaz]                  NVARCHAR (50) NULL,
    [DopDann]                       NTEXT         NULL,
    [Teloslozhenie]                 INT           NULL,
    [TonusMuskulaturi]              NVARCHAR (20) NULL,
    [Rost]                          INT           NULL,
    [Ves]                           INT           NULL,
    [VtorichniePolPriznaki]         INT           NULL,
    [Vlajnost]                      NVARCHAR (50) NULL,
    [Pigment]                       NVARCHAR (50) NULL,
    [Oteki]                         NVARCHAR (50) NULL,
    [Ojirenie]                      NVARCHAR (50) NULL,
    [Turgor]                        NVARCHAR (1)  NULL,
    [Okras]                         NVARCHAR (50) NULL,
    [menstrCikl]                    NVARCHAR (50) NULL,
    [Myagkaya]                      NVARCHAR (1)  NULL,
    [Uplotnennaya]                  NVARCHAR (1)  NULL,
    [CheckBox1]                     NVARCHAR (1)  NULL,
    [Left]                          NVARCHAR (50) NULL,
    [Prav]                          NVARCHAR (50) NULL,
    [Combo1]                        NVARCHAR (50) NULL,
    [Uzli2]                         NVARCHAR (50) NULL,
    [UchashenniyDo]                 NVARCHAR (1)  NULL,
    [StulSutki]                     INT           NULL,
    [ZaporiDo]                      NVARCHAR (1)  NULL,
    [EditBox1]                      NVARCHAR (50) NULL,
    [Regulyarniy]                   NVARCHAR (1)  NULL,
    [DihanieVezikulyarnoe]          NVARCHAR (1)  NULL,
    [MnogochislennieHripi]          NVARCHAR (1)  NULL,
    [Legkie]                        NVARCHAR (50) NULL,
    [TonySerdsa]                    NVARCHAR (50) NULL,
    [Ritm]                          NVARCHAR (50) NULL,
    [shum]                          NVARCHAR (50) NULL,
    [AD]                            INT           NULL,
    [AD1]                           INT           NULL,
    [AD2]                           INT           NULL,
    [Puls]                          NVARCHAR (50) NULL,
    [Puls2]                         NVARCHAR (50) NULL,
    [VtorPolPrizn]                  NVARCHAR (50) NULL,
    [Myagkiy]                       NVARCHAR (1)  NULL,
    [TvRdiy]                        NVARCHAR (1)  NULL,
    [Boleznenniy]                   NVARCHAR (1)  NULL,
    [Bezboleznenniy]                NVARCHAR (1)  NULL,
    [Vzdut]                         NVARCHAR (1)  NULL,
    [Jivot]                         NVARCHAR (50) NULL,
    [Pechen]                        NVARCHAR (50) NULL,
    [Selezenka]                     NVARCHAR (50) NULL,
    [NervnoPsihStat]                NVARCHAR (50) NULL,
    [PichevarSistema]               NVARCHAR (50) NULL,
    [Hripi]                         NVARCHAR (50) NULL,
    [EditBox2]                      INT           NULL,
    [DateBox1]                      DATETIME      NULL,
    [AktPosechen]                   NVARCHAR (50) NULL,
    [DateBox2]                      DATETIME      NULL,
    [EditBox3]                      NVARCHAR (50) NULL,
    [IMT]                           FLOAT (53)    NULL,
    [Data]                          DATETIME      NULL,
    [Vrach]                         NVARCHAR (50) NULL,
    [OtekiLitsa]                    NVARCHAR (1)  NULL,
    [Nemedikamentoznie]             NVARCHAR (1)  NULL,
    [Combo2]                        NVARCHAR (50) NULL,
    [Medikomentoznie]               NVARCHAR (1)  NULL,
    [OtekiKonechnostey]             NVARCHAR (1)  NULL,
    [OtekKonechn1]                  NVARCHAR (50) NULL,
    [Teloslozhenie1]                INT           NULL,
    [Rost1]                         INT           NULL,
    [Ves1]                          INT           NULL,
    [Ojirenie1]                     NVARCHAR (50) NULL,
    [TonusMuskulaturi1]             NVARCHAR (20) NULL,
    [Pigment1]                      NVARCHAR (50) NULL,
    [Okras1]                        NVARCHAR (50) NULL,
    [Vlajnost1]                     NVARCHAR (50) NULL,
    [EditBox10]                     NVARCHAR (50) NULL,
    [Oteki1]                        NVARCHAR (50) NULL,
    [VtorichniePolPriznaki1]        INT           NULL,
    [VtorPolPrizn1]                 NVARCHAR (50) NULL,
    [menstrCikl1]                   NVARCHAR (50) NULL,
    [Myagkaya1]                     NVARCHAR (1)  NULL,
    [Uplotnennaya1]                 NVARCHAR (1)  NULL,
    [CheckBox2]                     NVARCHAR (1)  NULL,
    [Uzli3]                         NVARCHAR (50) NULL,
    [Combo3]                        NVARCHAR (50) NULL,
    [Combo4]                        NVARCHAR (50) NULL,
    [Prav1]                         NVARCHAR (50) NULL,
    [Left1]                         NVARCHAR (50) NULL,
    [Regulyarniy1]                  NVARCHAR (1)  NULL,
    [UchashenniyDo1]                NVARCHAR (1)  NULL,
    [ZaporiDo1]                     NVARCHAR (1)  NULL,
    [EditBox4]                      NVARCHAR (50) NULL,
    [StulSutki1]                    INT           NULL,
    [Combo5]                        NVARCHAR (50) NULL,
    [Hripi1]                        NVARCHAR (50) NULL,
    [MnogochislennieHripi1]         NVARCHAR (1)  NULL,
    [Legkie1]                       NVARCHAR (50) NULL,
    [TonySerdsa1]                   NVARCHAR (50) NULL,
    [Ritm1]                         NVARCHAR (50) NULL,
    [AD3]                           INT           NULL,
    [AD4]                           INT           NULL,
    [EditBox8]                      NVARCHAR (50) NULL,
    [Puls1]                         NVARCHAR (50) NULL,
    [AD5]                           INT           NULL,
    [shum1]                         NVARCHAR (50) NULL,
    [Myagkiy1]                      NVARCHAR (1)  NULL,
    [TvRdiy1]                       NVARCHAR (1)  NULL,
    [Vzdut1]                        NVARCHAR (1)  NULL,
    [Boleznenniy1]                  NVARCHAR (1)  NULL,
    [Bezboleznenniy1]               NVARCHAR (1)  NULL,
    [Jivot1]                        NVARCHAR (50) NULL,
    [Selezenka1]                    NVARCHAR (50) NULL,
    [Pechen1]                       NVARCHAR (50) NULL,
    [EditBox11]                     NVARCHAR (50) NULL,
    [NervnoPsihStat1]               NVARCHAR (50) NULL,
    [PichevarSistema1]              NVARCHAR (50) NULL,
    [Combo6]                        NVARCHAR (50) NULL,
    [Combo7]                        NVARCHAR (50) NULL,
    [Combo8]                        NVARCHAR (50) NULL,
    [EditBox9]                      NVARCHAR (50) NULL,
    [Combo9]                        NVARCHAR (50) NULL,
    [Memo1]                         NTEXT         NULL,
    [DiagnozPoMkb10]                NVARCHAR (80) NULL,
    [EditBox5]                      NVARCHAR (50) NULL,
    [EditBox6]                      INT           NULL,
    [DateBox3]                      DATETIME      NULL,
    [DateBox4]                      DATETIME      NULL,
    [Turgor1]                       NVARCHAR (1)  NULL,
    [EditBox7]                      NVARCHAR (50) NULL,
    CONSTRAINT [OsmotrEndokrinologaPervPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [OsmotrEndokrinologaPervToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

