CREATE TABLE [dbo].[OsmotrGinekolog] (
    [ID]                          INT            NOT NULL,
    [PatID]                       INT            NULL,
    [Data]                        DATETIME       NULL,
    [Vrach]                       INT            NULL,
    [Zhalobi]                     NTEXT          NULL,
    [Pm]                          NVARCHAR (50)  NULL,
    [MetodPredoxraneniy]          NVARCHAR (50)  NULL,
    [Rekomendacii]                NTEXT          NULL,
    [Operatsii]                   NVARCHAR (1)   NULL,
    [SheikaMatki]                 NVARCHAR (50)  NULL,
    [Videleniy]                   NVARCHAR (50)  NULL,
    [Videleniy2]                  NVARCHAR (50)  NULL,
    [SlizistayVlagaliha]          NVARCHAR (50)  NULL,
    [SlizistayVlagaliha2]         NVARCHAR (50)  NULL,
    [SlizistayVlagaliha3]         NVARCHAR (50)  NULL,
    [Videleniy3]                  NVARCHAR (50)  NULL,
    [SheikaMatki3]                NVARCHAR (50)  NULL,
    [Matka]                       NVARCHAR (50)  NULL,
    [Matka2]                      NVARCHAR (50)  NULL,
    [Matka3]                      NVARCHAR (50)  NULL,
    [Konturi]                     NVARCHAR (1)   NULL,
    [Yvelicenado]                 INT            NULL,
    [Pridatki]                    NVARCHAR (50)  NULL,
    [Pridatki1]                   INT            NULL,
    [Svodi]                       NVARCHAR (50)  NULL,
    [DopObrazovaniyVmalomTazu]    NVARCHAR (100) NULL,
    [SomatAnamnez]                NVARCHAR (50)  NULL,
    [Rodov]                       INT            NULL,
    [MedAbortov]                  INT            NULL,
    [Vikidishey]                  INT            NULL,
    [Beremennostey]               INT            NULL,
    [Chislorodov]                 NVARCHAR (50)  NULL,
    [Chisloabortov]               NVARCHAR (50)  NULL,
    [Chislovikidishey]            NVARCHAR (50)  NULL,
    [Operatsii1]                  NTEXT          NULL,
    [GinekologiceskieZabolevaniy] NTEXT          NULL,
    CONSTRAINT [OsmotrGinekologPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [OsmotrGinekologToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

