CREATE TABLE [dbo].[OsmotrUrologaPervichniy] (
    [ID]                                                       INT            NOT NULL,
    [PatID]                                                    INT            NULL,
    [Data]                                                     DATETIME       NULL,
    [Vrach]                                                    INT            NULL,
    [Zhalobi]                                                  NTEXT          NULL,
    [Anamnez]                                                  NTEXT          NULL,
    [Yazik]                                                    NVARCHAR (50)  NULL,
    [Zhivot]                                                   NVARCHAR (50)  NULL,
    [Pochki]                                                   NVARCHAR (50)  NULL,
    [MochevoyPuzir]                                            NVARCHAR (50)  NULL,
    [NaruzhniePolovieOrgani]                                   NVARCHAR (50)  NULL,
    [Videleniya]                                               NVARCHAR (50)  NULL,
    [Mocha]                                                    NVARCHAR (50)  NULL,
    [Prostata]                                                 NVARCHAR (50)  NULL,
    [AnalizMochi]                                              NVARCHAR (50)  NULL,
    [AnalizKrovi]                                              NVARCHAR (50)  NULL,
    [InstrumentalnoeObsledovanie]                              NVARCHAR (50)  NULL,
    [Diagnoz]                                                  NVARCHAR (50)  NULL,
    [BLNomer]                                                  INT            NULL,
    [Srok]                                                     DATETIME       NULL,
    [DictCombo1]                                               NVARCHAR (50)  NULL,
    [DictCombo3]                                               NVARCHAR (50)  NULL,
    [EditBox3]                                                 INT            NULL,
    [Combo2]                                                   NVARCHAR (50)  NULL,
    [Combo1]                                                   NVARCHAR (50)  NULL,
    [Combo3]                                                   NVARCHAR (50)  NULL,
    [Combo4]                                                   NVARCHAR (50)  NULL,
    [VNachale]                                                 NVARCHAR (1)   NULL,
    [VKontse]                                                  NVARCHAR (1)   NULL,
    [Ostrie]                                                   NVARCHAR (1)   NULL,
    [Zhguchie]                                                 NVARCHAR (1)   NULL,
    [Combo5]                                                   NVARCHAR (50)  NULL,
    [NalichieSgustkovKroviVMoche]                              NVARCHAR (1)   NULL,
    [VPoyasnichnoyOblasti]                                     NVARCHAR (1)   NULL,
    [VPodreberyahSIhVOblastMochevogoPuzirya]                   NVARCHAR (1)   NULL,
    [PolovihOrganov]                                           NVARCHAR (1)   NULL,
    [SnizheniePolovogoVlecheniya]                              NVARCHAR (1)   NULL,
    [SnizhenieErektivnoySposobnosti]                           NVARCHAR (1)   NULL,
    [BistrayaEyakulyatsiya]                                    NVARCHAR (1)   NULL,
    [Gemospermiya]                                             NVARCHAR (1)   NULL,
    [BolVoVremyaEyakulyatsii]                                  NVARCHAR (1)   NULL,
    [OtsutstvieBeremennosteyPriDlitelnomPeriodeSemeynoyZhizni] NVARCHAR (1)   NULL,
    [Combo6]                                                   NVARCHAR (50)  NULL,
    [Memo1]                                                    NTEXT          NULL,
    [EditBox1]                                                 INT            NULL,
    [DictCombo2]                                               NVARCHAR (50)  NULL,
    [DictCombo4]                                               NVARCHAR (50)  NULL,
    [DictCombo5]                                               NVARCHAR (50)  NULL,
    [Combo7]                                                   NVARCHAR (50)  NULL,
    [Combo8]                                                   NVARCHAR (50)  NULL,
    [Combo9]                                                   NVARCHAR (50)  NULL,
    [EditBox2]                                                 NVARCHAR (20)  NULL,
    [DictCombo6]                                               NVARCHAR (50)  NULL,
    [UvelichenieYaichka]                                       NVARCHAR (1)   NULL,
    [PokrasnenieKozhiMoshonki]                                 NVARCHAR (1)   NULL,
    [Combo11]                                                  NVARCHAR (50)  NULL,
    [Combo12]                                                  NVARCHAR (50)  NULL,
    [Combo13]                                                  NVARCHAR (50)  NULL,
    [DictCombo7]                                               NVARCHAR (50)  NULL,
    [EditBox4]                                                 INT            NULL,
    [DictCombo8]                                               NVARCHAR (50)  NULL,
    [Combo10]                                                  NVARCHAR (50)  NULL,
    [Combo14]                                                  NVARCHAR (50)  NULL,
    [Combo15]                                                  NVARCHAR (50)  NULL,
    [Combo16]                                                  NVARCHAR (50)  NULL,
    [Combo17]                                                  NVARCHAR (50)  NULL,
    [Combo18]                                                  NVARCHAR (50)  NULL,
    [Combo19]                                                  NVARCHAR (50)  NULL,
    [Combo20]                                                  NVARCHAR (50)  NULL,
    [Combo21]                                                  NVARCHAR (50)  NULL,
    [Combo22]                                                  NVARCHAR (50)  NULL,
    [Combo23]                                                  NVARCHAR (50)  NULL,
    [Combo24]                                                  NVARCHAR (50)  NULL,
    [EditBox5]                                                 INT            NULL,
    [GranitsiProstatiNedostizhimiPaltsem]                      NVARCHAR (1)   NULL,
    [Memo2]                                                    NTEXT          NULL,
    [Memo3]                                                    NTEXT          NULL,
    [Ds]                                                       NVARCHAR (100) NULL,
    CONSTRAINT [OsmotrUrologaPervichniyPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [OsmotrUrologaPervichniyToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

