CREATE TABLE [dbo].[OsmotrTerapevtaPovtorniy] (
    [ID]                                                            INT           NOT NULL,
    [PatID]                                                         INT           NULL,
    [Zhalobi]                                                       NTEXT         NULL,
    [PerenesennieZabolevaniya]                                      NTEXT         NULL,
    [Allergoanamnez]                                                NTEXT         NULL,
    [Nasledstvennost]                                               NTEXT         NULL,
    [ObektivnieDannie]                                              NTEXT         NULL,
    [Gemotransfuzii]                                                NTEXT         NULL,
    [IstoriyaBolezni]                                               NTEXT         NULL,
    [PredvaritelniyDiagnoz]                                         NTEXT         NULL,
    [Dieta]                                                         NTEXT         NULL,
    [MedikamentoznayaTerapiya]                                      NTEXT         NULL,
    [DopolnitelnieNaznacheniya]                                     NTEXT         NULL,
    [BolnichniyListNomer]                                           NVARCHAR (50) NULL,
    [S]                                                             DATETIME      NULL,
    [Po]                                                            DATETIME      NULL,
    [PovtornayaYavka]                                               DATETIME      NULL,
    [Vremya]                                                        NVARCHAR (50) NULL,
    [KTrudu]                                                        DATETIME      NULL,
    [Primechaniya]                                                  NTEXT         NULL,
    [DataOsmotra]                                                   DATETIME      NULL,
    [Kurenie]                                                       NVARCHAR (1)  NULL,
    [Alkogol]                                                       NVARCHAR (1)  NULL,
    [Narkotiki]                                                     NVARCHAR (1)  NULL,
    [Rezhim]                                                        NVARCHAR (50) NULL,
    [DictCombo1]                                                    NVARCHAR (50) NULL,
    [Memo1]                                                         NTEXT         NULL,
    [Data]                                                          DATETIME      NULL,
    [Vrach]                                                         INT           NULL,
    [Anamnez]                                                       NTEXT         NULL,
    [Kozha]                                                         NVARCHAR (50) NULL,
    [Kozha1]                                                        NVARCHAR (50) NULL,
    [LU]                                                            NVARCHAR (50) NULL,
    [Sustavi]                                                       NVARCHAR (50) NULL,
    [Sustavi1]                                                      NVARCHAR (50) NULL,
    [Zev]                                                           NVARCHAR (50) NULL,
    [Mindalini]                                                     NVARCHAR (50) NULL,
    [Chdd]                                                          INT           NULL,
    [Dihanie]                                                       NVARCHAR (50) NULL,
    [Hripi]                                                         NVARCHAR (50) NULL,
    [PritupleniePerkutornogoZvukaVOblasti]                          NVARCHAR (50) NULL,
    [ToniSerdtsa]                                                   NVARCHAR (50) NULL,
    [ToniSerdtsa1]                                                  NVARCHAR (50) NULL,
    [AktsentIITonaNaAorte]                                          NVARCHAR (1)  NULL,
    [ShumSistolicheskiyNaVerhushkeVoIIMezhrebereSprava]             NVARCHAR (1)  NULL,
    [shumsist]                                                      NVARCHAR (50) NULL,
    [DiastolicheskiyNaVerhushkeVTochkeBotkinaIIIIIVToniNaVerhushke] NVARCHAR (1)  NULL,
    [AdSidya]                                                       INT           NULL,
    [AdSidya1]                                                      INT           NULL,
    [AdLZha]                                                        INT           NULL,
    [AdLZha1]                                                       INT           NULL,
    [Puls]                                                          NVARCHAR (50) NULL,
    [Napolneniya]                                                   NVARCHAR (50) NULL,
    [Napolneniya1]                                                  NVARCHAR (50) NULL,
    [Yazik1]                                                        NVARCHAR (50) NULL,
    [Yazik]                                                         NVARCHAR (50) NULL,
    [Yazik2]                                                        NVARCHAR (50) NULL,
    [Zhivot]                                                        NVARCHAR (50) NULL,
    [Zhivot1]                                                       NVARCHAR (50) NULL,
    [PriPalpatsiiBoleznennost3]                                     NVARCHAR (50) NULL,
    [PriPalpatsiiBoleznennost]                                      NVARCHAR (1)  NULL,
    [PriPalpatsiiBoleznennost1]                                     NVARCHAR (50) NULL,
    [PriPalpatsiiBoleznennost2]                                     NVARCHAR (50) NULL,
    [PriPalpatsiiBoleznennost4]                                     NVARCHAR (50) NULL,
    [PriPalpatsiiBoleznennost5]                                     NVARCHAR (1)  NULL,
    [MishechnayaZashita]                                            NVARCHAR (50) NULL,
    [Pechen]                                                        NVARCHAR (50) NULL,
    [VistupaetIzPodreberyaNa]                                       INT           NULL,
    [Kray]                                                          NVARCHAR (50) NULL,
    [Kray1]                                                         NVARCHAR (50) NULL,
    [Stul]                                                          NVARCHAR (50) NULL,
    [Mocheispuskanie]                                               NVARCHAR (50) NULL,
    [Mocheispuskanie1]                                              NVARCHAR (50) NULL,
    [OtKi]                                                          NVARCHAR (50) NULL,
    [OtKi1]                                                         NVARCHAR (50) NULL,
    [DopolnitelnieDannie]                                           NTEXT         NULL,
    [Diagnoz]                                                       NVARCHAR (50) NULL,
    [GruppaDNablyudeniyaD1D2D3]                                     NVARCHAR (50) NULL,
    [BLNomer]                                                       INT           NULL,
    [Srok]                                                          DATETIME      NULL,
    [AktivnoePoseshenie]                                            NVARCHAR (50) NULL,
    [Mindal]                                                        NVARCHAR (50) NULL,
    [Naznachen]                                                     NTEXT         NULL,
    [Obsledovan]                                                    NTEXT         NULL,
    [shum sist]                                                     NVARCHAR (50) NULL,
    CONSTRAINT [OsmotrTerapevtaPovtorniyPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [OsmotrTerapevtaPovtorniyToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

