CREATE TABLE [dbo].[OsmotrDietologa] (
    [ID]        INT      NOT NULL,
    [PatID]     INT      NULL,
    [Image1]    IMAGE    NULL,
    [Comment1]  NTEXT    NULL,
    [DateImg1]  DATETIME NULL,
    [Image11]   IMAGE    NULL,
    [Comment11] NTEXT    NULL,
    [DateImg11] DATETIME NULL,
    [Image12]   IMAGE    NULL,
    [Comment12] NTEXT    NULL,
    [DateImg12] DATETIME NULL,
    [Image13]   IMAGE    NULL,
    [Comment13] NTEXT    NULL,
    [DateImg13] DATETIME NULL,
    [Image14]   IMAGE    NULL,
    [Comment14] NTEXT    NULL,
    [DateImg14] DATETIME NULL,
    [Image15]   IMAGE    NULL,
    [Comment15] NTEXT    NULL,
    [DateImg15] DATETIME NULL,
    [Image16]   IMAGE    NULL,
    [Comment16] NTEXT    NULL,
    [DateImg16] DATETIME NULL,
    [Image17]   IMAGE    NULL,
    [Comment17] NTEXT    NULL,
    [DateImg17] DATETIME NULL,
    [Image18]   IMAGE    NULL,
    [Comment18] NTEXT    NULL,
    [DateImg18] DATETIME NULL,
    [Data1]     DATETIME NULL,
    [DocTime]   DATETIME NULL,
    [Vrach2]    INT      NULL,
    CONSTRAINT [OsmotrDietologaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [OsmotrDietologaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

