CREATE TABLE [dbo].[OsmotrOnkologaPovtorniy] (
    [ID]                                                            INT           NOT NULL,
    [PatID]                                                         INT           NULL,
    [Data]                                                          DATETIME      NULL,
    [Vrach]                                                         NVARCHAR (50) NULL,
    [Zhalobi]                                                       NTEXT         NULL,
    [Anamnez]                                                       NTEXT         NULL,
    [Kozha]                                                         NVARCHAR (50) NULL,
    [Kozha1]                                                        NVARCHAR (50) NULL,
    [LU]                                                            NVARCHAR (50) NULL,
    [Sustavi]                                                       NVARCHAR (50) NULL,
    [Sustavi1]                                                      NVARCHAR (50) NULL,
    [Zev]                                                           NVARCHAR (50) NULL,
    [Mindalini]                                                     NVARCHAR (50) NULL,
    [Chdd]                                                          INT           NULL,
    [Dihanie]                                                       NVARCHAR (50) NULL,
    [Hripi]                                                         NVARCHAR (50) NULL,
    [PritupleniePerkutornogoZvukaVOblasti]                          NVARCHAR (50) NULL,
    [ToniSerdtsa]                                                   NVARCHAR (50) NULL,
    [ToniSerdtsa1]                                                  NVARCHAR (50) NULL,
    [AktsentIITonaNaAorte]                                          NVARCHAR (1)  NULL,
    [ShumSistolicheskiyNaVerhushkeVoIIMezhrebereSprava]             NVARCHAR (1)  NULL,
    [shum sist]                                                     NVARCHAR (50) NULL,
    [DiastolicheskiyNaVerhushkeVTochkeBotkinaIIIIIVToniNaVerhushke] NVARCHAR (1)  NULL,
    [AdSidya]                                                       INT           NULL,
    [AdSidya1]                                                      INT           NULL,
    [AdLZha]                                                        INT           NULL,
    [AdLZha1]                                                       INT           NULL,
    [Puls]                                                          NVARCHAR (50) NULL,
    [Napolneniya]                                                   NVARCHAR (50) NULL,
    [Napolneniya1]                                                  NVARCHAR (50) NULL,
    [Yazik1]                                                        NVARCHAR (50) NULL,
    [Yazik]                                                         NVARCHAR (50) NULL,
    [Yazik2]                                                        NVARCHAR (50) NULL,
    [Zhivot]                                                        NVARCHAR (50) NULL,
    [Zhivot1]                                                       NVARCHAR (50) NULL,
    [PriPalpatsiiBoleznennost3]                                     NVARCHAR (50) NULL,
    [PriPalpatsiiBoleznennost]                                      NVARCHAR (1)  NULL,
    [PriPalpatsiiBoleznennost1]                                     NVARCHAR (50) NULL,
    [PriPalpatsiiBoleznennost2]                                     NVARCHAR (50) NULL,
    [PriPalpatsiiBoleznennost4]                                     NVARCHAR (50) NULL,
    [DictCombo1]                                                    NVARCHAR (50) NULL,
    [PriPalpatsiiBoleznennost5]                                     NVARCHAR (1)  NULL,
    [MishechnayaZashita]                                            NVARCHAR (50) NULL,
    [Pechen]                                                        NVARCHAR (50) NULL,
    [VistupaetIzPodreberyaNa]                                       INT           NULL,
    [Kray]                                                          NVARCHAR (50) NULL,
    [Kray1]                                                         NVARCHAR (50) NULL,
    [Stul]                                                          NVARCHAR (50) NULL,
    [Mocheispuskanie]                                               NVARCHAR (50) NULL,
    [Mocheispuskanie1]                                              NVARCHAR (50) NULL,
    [OtKi]                                                          NVARCHAR (50) NULL,
    [OtKi1]                                                         NVARCHAR (50) NULL,
    [DopolnitelnieDannie]                                           NTEXT         NULL,
    [Diagnoz]                                                       NVARCHAR (50) NULL,
    [GruppaDNablyudeniyaD1D2D3]                                     NVARCHAR (50) NULL,
    [BLNomer]                                                       INT           NULL,
    [Srok]                                                          DATETIME      NULL,
    [AktivnoePoseshenie]                                            NVARCHAR (50) NULL,
    [PovtornayaYavka]                                               DATETIME      NULL,
    CONSTRAINT [OsmotrOnkologaPovtorniyPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [OsmotrOnkologaPovtorniyToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

