CREATE TABLE [dbo].[OsmotrGinekologa] (
    [ID]                                           INT            NOT NULL,
    [PatID]                                        INT            NULL,
    [Zhalobi]                                      NTEXT          NULL,
    [GinekologicheskieZabolevaniya]                NTEXT          NULL,
    [NaruzhniyZev]                                 NVARCHAR (50)  NULL,
    [MenarheS]                                     INT            NULL,
    [RegulyarniyCherez]                            INT            NULL,
    [NachaloPolovoyZhizniS]                        INT            NULL,
    [VBrake]                                       NVARCHAR (1)   NULL,
    [Rodov]                                        INT            NULL,
    [MedAbortov]                                   INT            NULL,
    [Vikidishey]                                   INT            NULL,
    [Oslozhnenie]                                  NVARCHAR (1)   NULL,
    [NachaloZabolevaniya]                          NTEXT          NULL,
    [MetodiLecheniya]                              NTEXT          NULL,
    [LechilasRanee]                                NVARCHAR (1)   NULL,
    [Effekt]                                       NVARCHAR (25)  NULL,
    [Retsidivi]                                    NVARCHAR (25)  NULL,
    [ObshiyOsmotr]                                 NTEXT          NULL,
    [OsmotrSheykiMatkiVZerkalah]                   NVARCHAR (50)  NULL,
    [Kp]                                           NVARCHAR (50)  NULL,
    [Konsistentsiya]                               NVARCHAR (50)  NULL,
    [OgranichenaVPodvizhnosti]                     NVARCHAR (50)  NULL,
    [Uvelichena]                                   NVARCHAR (50)  NULL,
    [SpaechniyProtsess]                            NVARCHAR (50)  NULL,
    [Sprava]                                       NVARCHAR (50)  NULL,
    [Sleva]                                        NVARCHAR (50)  NULL,
    [Npo]                                          NTEXT          NULL,
    [Pokrita]                                      NVARCHAR (50)  NULL,
    [RaspolozhenniyUchastkamiVokrugNaruzhnogoZeva] NVARCHAR (25)  NULL,
    [ZonaTransformatsii]                           NVARCHAR (50)  NULL,
    [Poblednenie]                                  NVARCHAR (1)   NULL,
    [AtsetoBeliyEpiteliy]                          NVARCHAR (1)   NULL,
    [GranitsaEpiteliya]                            NVARCHAR (50)  NULL,
    [Zhelezi]                                      NVARCHAR (50)  NULL,
    [Sosudi]                                       NVARCHAR (50)  NULL,
    [ProbaShillera]                                NTEXT          NULL,
    [Drugoe5]                                      NVARCHAR (25)  NULL,
    [Data]                                         DATETIME       NULL,
    [Vrach]                                        NVARCHAR (50)  NULL,
    [Kontracepciya]                                NTEXT          NULL,
    [RodovOslozhneniya]                            NTEXT          NULL,
    [MedAbortovOslozhneniya]                       NTEXT          NULL,
    [VikidisheyOslozhneniya]                       NTEXT          NULL,
    [VydeleniyaMatki]                              NTEXT          NULL,
    [PridatkiSlevaPrimechanie]                     NTEXT          NULL,
    [PridatkiSpravaPrimechanie]                    NTEXT          NULL,
    [RektalnoeObsledovanie]                        NTEXT          NULL,
    [RaspolozhenieMatki]                           NVARCHAR (20)  NULL,
    [MenarheUstan]                                 NVARCHAR (5)   NULL,
    [Menstr]                                       NVARCHAR (50)  NULL,
    [MenstrCherez]                                 NVARCHAR (50)  NULL,
    [umeren]                                       NVARCHAR (50)  NULL,
    [bezbolez]                                     NVARCHAR (50)  NULL,
    [regul]                                        NVARCHAR (50)  NULL,
    [Beremennostey1]                               INT            NULL,
    [Drugoe6]                                      NVARCHAR (25)  NULL,
    [cbKontracepciya]                              NVARCHAR (1)   NULL,
    [OslozhneniyaPriRodah]                         NVARCHAR (1)   NULL,
    [OslozhneniyaPriAbortah]                       NVARCHAR (1)   NULL,
    [OslozhneniyaPriVikidishah]                    NVARCHAR (1)   NULL,
    [DocTime]                                      DATETIME       NULL,
    [PlanLech2]                                    NVARCHAR (255) NULL,
    [planlech1]                                    NVARCHAR (50)  NULL,
    [Planobsl]                                     NVARCHAR (50)  NULL,
    [PlanObsledovaniya]                            NTEXT          NULL,
    [PlanLecheniya]                                NTEXT          NULL,
    [Recomendacii]                                 NTEXT          NULL,
    [AnamnezZhizni2]                               NTEXT          NULL,
    [AnamnezZhizni1]                               NTEXT          NULL,
    [AnamnezZhizni]                                NTEXT          NULL,
    [Allergic6]                                    NVARCHAR (255) NULL,
    [Allergic1]                                    NVARCHAR (255) NULL,
    [Allergic]                                     NTEXT          NULL,
    [Allergic3]                                    NVARCHAR (255) NULL,
    [Allergic2]                                    NTEXT          NULL,
    [Allergic5]                                    NVARCHAR (255) NULL,
    [Allergic4]                                    NTEXT          NULL,
    [EpidAnamnes1]                                 NVARCHAR (50)  NULL,
    [EpidAnamnes]                                  NTEXT          NULL,
    [Operatsii]                                    NVARCHAR (1)   NULL,
    [Operatsii2]                                   NTEXT          NULL,
    [Transfuzii]                                   NVARCHAR (1)   NULL,
    [Transfuzii2]                                  NTEXT          NULL,
    [VSrokah]                                      NVARCHAR (30)  NULL,
    [Regularnaya]                                  NVARCHAR (50)  NULL,
    [VneBraka]                                     NVARCHAR (1)   NULL,
    [VneBrakaComment]                              NVARCHAR (50)  NULL,
    [SheikaMatki]                                  NTEXT          NULL,
    [LiniyaStyka]                                  NTEXT          NULL,
    [DrugieIzmeneniya]                             NTEXT          NULL,
    [NoAllergy]                                    NVARCHAR (1)   NULL,
    CONSTRAINT [OsmotrGinekologaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [OsmotrGinekologaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

