CREATE TABLE [dbo].[OsmotrEndokrinologaPervichniy] (
    [Teloslozhenie]            INT           NULL,
    [Rost]                     INT           NULL,
    [Ves]                      INT           NULL,
    [NervnoPsihicheskiyStatus] NVARCHAR (20) NULL,
    [OtekiLica]                NVARCHAR (1)  NULL,
    [Zabkost]                  NVARCHAR (1)  NULL,
    [SuhostKogi]               NVARCHAR (1)  NULL,
    [Zapori]                   NVARCHAR (1)  NULL,
    [sonlivost]                NVARCHAR (1)  NULL,
    [Libido]                   NVARCHAR (20) NULL,
    [VtorichniePolPriznaki]    INT           NULL,
    [Razmer]                   INT           NULL,
    [Konsistentsiya]           NVARCHAR (20) NULL,
    [Uzli]                     NVARCHAR (20) NULL,
    [Boleznennost]             NTEXT         NULL,
    [Tahicardia]               NVARCHAR (1)  NULL,
    [DrojanieRuk]              NVARCHAR (1)  NULL,
    [Ekzoftalm]                NVARCHAR (1)  NULL,
    [Grefe]                    NVARCHAR (1)  NULL,
    [DopolnitelnieDannie]      NTEXT         NULL,
    [Razmer1]                  INT           NULL,
    [Razmer2]                  INT           NULL,
    [Diagnoz]                  NVARCHAR (50) NULL,
    [ObsheeSostoyanie]         NVARCHAR (50) NULL,
    [Data]                     DATETIME      NULL,
    [Vrach]                    INT           NULL,
    [Vlazhnost]                NVARCHAR (50) NULL,
    [Oteki]                    NVARCHAR (50) NULL,
    [Okraska]                  NVARCHAR (50) NULL,
    [Turgor]                   NVARCHAR (50) NULL,
    [VirazhPZhKletchatki]      NVARCHAR (50) NULL,
    [TonusMuskulaturi]         NVARCHAR (50) NULL,
    [MenstrTsikl]              NVARCHAR (50) NULL,
    [OtekiLitsaIKonechnostey]  NVARCHAR (50) NULL,
    [SuhostKozhi]              NVARCHAR (50) NULL,
    [Zyabkost]                 NVARCHAR (50) NULL,
    [Sonlivost1]               NVARCHAR (50) NULL,
    [Zapori2]                  NVARCHAR (50) NULL,
    [Dihanie]                  NVARCHAR (50) NULL,
    [Dihanie1]                 NVARCHAR (20) NULL,
    [Hripi]                    NVARCHAR (50) NULL,
    [Hripi1]                   NVARCHAR (50) NULL,
    [Hripi2]                   NVARCHAR (20) NULL,
    [ToniSerdtsa]              NVARCHAR (50) NULL,
    [ToniSerdtsa1]             NVARCHAR (20) NULL,
    [Shum]                     NVARCHAR (20) NULL,
    [AD]                       INT           NULL,
    [AD1]                      INT           NULL,
    [Puls]                     INT           NULL,
    [Puls1]                    NVARCHAR (50) NULL,
    [Zhivot]                   NVARCHAR (50) NULL,
    [Zhivot1]                  NVARCHAR (50) NULL,
    [Pechen]                   NVARCHAR (50) NULL,
    [Pechen1]                  NVARCHAR (20) NULL,
    [Selezenka]                NVARCHAR (20) NULL,
    [BLNomer]                  INT           NULL,
    [Srok]                     DATETIME      NULL,
    [AktivnoePoseshenie]       NVARCHAR (20) NULL,
    [PovtornayaYavka]          DATETIME      NULL,
    [ID]                       INT           NULL,
    [PatID]                    INT           NULL,
    CONSTRAINT [OsmotrEndokrinologaPervichniyToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

