CREATE TABLE [dbo].[OsmotrTravmatologaPervichniy] (
    [ID]                      INT           NOT NULL,
    [PatID]                   INT           NULL,
    [Zhalobi]                 NTEXT         NULL,
    [Anamnez]                 NTEXT         NULL,
    [VerhnieKonechnosti]      NVARCHAR (50) NULL,
    [NizhnieKonechnosti]      NVARCHAR (50) NULL,
    [Sustavi]                 NVARCHAR (50) NULL,
    [Yazik]                   NVARCHAR (50) NULL,
    [Yazik1]                  NVARCHAR (50) NULL,
    [Yazik2]                  NVARCHAR (50) NULL,
    [Stul]                    NVARCHAR (50) NULL,
    [Stul1]                   NVARCHAR (50) NULL,
    [PryamayaKishka]          NVARCHAR (50) NULL,
    [DopolnitelnieDannie]     NTEXT         NULL,
    [ProvodimieManipulyatsii] NTEXT         NULL,
    [Diagnoz]                 NVARCHAR (50) NULL,
    [BLNomer]                 INT           NULL,
    [Srok]                    DATETIME      NULL,
    [AktivnoePoseshenie]      NVARCHAR (50) NULL,
    [YavkaVPolikliniku]       DATETIME      NULL,
    [Data]                    DATETIME      NULL,
    [Vrach]                   NVARCHAR (50) NULL,
    [Kozja]                   NTEXT         NULL,
    [LimfUzli]                NTEXT         NULL,
    [Sustav]                  NVARCHAR (50) NULL,
    [Jivot]                   NVARCHAR (50) NULL,
    [Combo1]                  NVARCHAR (50) NULL,
    [Jiv]                     NVARCHAR (50) NULL,
    [MishZash]                NVARCHAR (50) NULL,
    [Pechen]                  NVARCHAR (50) NULL,
    [Pechen1]                 NVARCHAR (50) NULL,
    [Naznach]                 NTEXT         NULL,
    [Obsled]                  NTEXT         NULL,
    CONSTRAINT [OsmotrTravmatologaPervichniyPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [OsmotrTravmatologaPervichniyToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

