CREATE TABLE [dbo].[OtorinolaringologicheskoeObsledovanie] (
    [ID]                               INT            NOT NULL,
    [PatID]                            INT            NULL,
    [KamertonnoeIssledovanie]          NVARCHAR (100) NULL,
    [RazgovornayaRech]                 INT            NULL,
    [S]                                INT            NULL,
    [ShopotnayaRech1]                  INT            NULL,
    [ShopotnayaRech]                   INT            NULL,
    [BarabannayaPereponkaBezIzmeneniy] NVARCHAR (1)   NULL,
    [BarabannayaPereponka]             NVARCHAR (100) NULL,
    [SluhovoyProhod]                   NVARCHAR (100) NULL,
    [SluhovoyProhodBezIzmeneniy]       NVARCHAR (1)   NULL,
    [NaruzhnoeUhoBezIzmeneniy]         NVARCHAR (1)   NULL,
    [NaruzhnoeUho]                     NVARCHAR (100) NULL,
    [Gortan]                           NVARCHAR (100) NULL,
    [GortanBezIzmeneniy]               NVARCHAR (1)   NULL,
    [GolosovayaFTsiyaBezIzmeneniy]     NVARCHAR (1)   NULL,
    [GolosovayaFTsiya]                 NVARCHAR (100) NULL,
    [LimfaticheskieUzli]               NVARCHAR (100) NULL,
    [LimfaticheskieUzliBezIzmeneniy]   NVARCHAR (1)   NULL,
    [MindaliniDSBezIzmeneniy]          NVARCHAR (1)   NULL,
    [MindaliniDS]                      NVARCHAR (100) NULL,
    [Glotka]                           NVARCHAR (100) NULL,
    [GlotkaBezIzmeneniy]               NVARCHAR (1)   NULL,
    [Slizistaya]                       NVARCHAR (20)  NULL,
    [DrugieObrazovaniya]               NVARCHAR (50)  NULL,
    [NosoglotkaBezIzmeneniy]           NVARCHAR (1)   NULL,
    [Nosoglotka]                       NVARCHAR (30)  NULL,
    [Adenoidi]                         INT            NULL,
    [NosovieRakovini]                  NVARCHAR (25)  NULL,
    [NosovayaPeregorodka]              INT            NULL,
    [TsvetSlizistoy]                   NVARCHAR (20)  NULL,
    [OtechnostSlizistoy]               NVARCHAR (1)   NULL,
    [Giperemia]                        NVARCHAR (1)   NULL,
    [Atrophia]                         NVARCHAR (1)   NULL,
    [Polipi]                           NVARCHAR (1)   NULL,
    [PolostNosa1]                      NVARCHAR (30)  NULL,
    [PolostNosa]                       NVARCHAR (30)  NULL,
    [NosovoeDihanie]                   NVARCHAR (30)  NULL,
    [Zhalobi]                          NTEXT          NULL,
    [Anamnez]                          NTEXT          NULL,
    [VestibulyarnieFunktsii]           NVARCHAR (100) NULL,
    [ProvodimieManipulyatsii]          NVARCHAR (100) NULL,
    [DopolnitelnieDannie]              NTEXT          NULL,
    [Data1]                            DATETIME       NULL,
    [Vrach]                            INT            NULL,
    [Memo1]                            NTEXT          NULL,
    CONSTRAINT [OtorinolaringologicheskoeObsledovaniePrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [OtorinolaringologicheskoeObsledovanieToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

