CREATE TABLE [dbo].[PatRef] (
    [Id]                  INT           NOT NULL,
    [patid]               INT           NULL,
    [CardNum]             INT           NULL,
    [CardTypeId]          INT           NULL,
    [CardDate]            DATETIME      NULL,
    [LastName]            VARCHAR (255) NULL,
    [FullName]            VARCHAR (255) NULL,
    [GenderId]            INT           NULL,
    [FullNameP]           VARCHAR (255) NULL,
    [BirthDate]           DATETIME      NULL,
    [BirthDateP]          DATETIME      NULL,
    [AgeP]                INT           NULL,
    [InfSrcId]            INT           NULL,
    [InfSourceId]         INT           NULL,
    [Address]             VARCHAR (255) NULL,
    [Phone]               VARCHAR (255) NULL,
    [PhoneW]              VARCHAR (255) NULL,
    [Occupation]          VARCHAR (255) NULL,
    [OccupationP]         VARCHAR (255) NULL,
    [ServHere]            VARCHAR (255) NULL,
    [ServIn]              VARCHAR (255) NULL,
    [BGId]                INT           NULL,
    [RFId]                INT           NULL,
    [PBGId]               INT           NULL,
    [PRFId]               INT           NULL,
    [OperId]              INT           NULL,
    [PhotoId]             INT           NULL,
    [Donor]               BIT           NULL,
    [DonorNum]            NVARCHAR (20) NULL,
    [AttOperId]           INT           NULL,
    [Preg]                INT           NULL,
    [OriginalID]          INT           NULL,
    [BrakZaregistrirovan] BIT           NULL,
    CONSTRAINT [PK_PatRef] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_PatRef_PatForm] FOREIGN KEY ([Id]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

