CREATE TABLE [dbo].[PervichniyPriMTravmatologaOrtopeda] (
    [ID]                                            INT           NOT NULL,
    [PatID]                                         INT           NULL,
    [Zhalobi]                                       NTEXT         NULL,
    [AnamnezZabolevaniya]                           NTEXT         NULL,
    [Inektsii]                                      NVARCHAR (1)  NULL,
    [LechenieUStomatologa]                          NVARCHAR (1)  NULL,
    [Operatsii]                                     NVARCHAR (1)  NULL,
    [Transfuzii]                                    NVARCHAR (1)  NULL,
    [Tb]                                            NVARCHAR (1)  NULL,
    [Vich]                                          NVARCHAR (1)  NULL,
    [Malyariya]                                     NVARCHAR (1)  NULL,
    [Tif]                                           NVARCHAR (1)  NULL,
    [Paratif]                                       NVARCHAR (1)  NULL,
    [Gepatit]                                       NVARCHAR (1)  NULL,
    [DopolnitelnieDannie]                           NTEXT         NULL,
    [Teloslozhenie]                                 INT           NULL,
    [Ves]                                           INT           NULL,
    [TemperaturaTela]                               FLOAT (53)    NULL,
    [Kozha1]                                        INT           NULL,
    [Sustavi]                                       INT           NULL,
    [Boleznennost]                                  INT           NULL,
    [Konfiguratsiya]                                INT           NULL,
    [Ankiloz]                                       NVARCHAR (1)  NULL,
    [Kontraktura]                                   NVARCHAR (1)  NULL,
    [Gematomi]                                      NVARCHAR (50) NULL,
    [Ssadini]                                       NVARCHAR (1)  NULL,
    [Rani]                                          NVARCHAR (1)  NULL,
    [Predvariteljnyj diagnoz]                       NTEXT         NULL,
    [AnamnezZhizni]                                 NTEXT         NULL,
    [AnamnezZhizni1]                                NTEXT         NULL,
    [AnamnezZhizni2]                                NTEXT         NULL,
    [AnamnezZhizni3]                                NTEXT         NULL,
    [Medikamentov]                                  NTEXT         NULL,
    [Produktov]                                     NTEXT         NULL,
    [NalichieOslozhneniyTransfuzii]                 NTEXT         NULL,
    [GruppaKrovi]                                   NVARCHAR (50) NULL,
    [Rh]                                            NVARCHAR (50) NULL,
    [TransfuziiRanshe]                              NVARCHAR (50) NULL,
    [BitovieUsloviya]                               NVARCHAR (50) NULL,
    [LichnayaGigiena]                               NVARCHAR (50) NULL,
    [UpotreblenieNarkotikov]                        NVARCHAR (50) NULL,
    [IstochnikPitevoyVodi]                          NVARCHAR (50) NULL,
    [UpotreblenieSiroyVodi]                         NVARCHAR (50) NULL,
    [NalichieTbVichMalyariiTifaParatifaGepatitaZpp] NVARCHAR (50) NULL,
    [Zpp]                                           NVARCHAR (50) NULL,
    [Konfiguratsiya1]                               NVARCHAR (45) NULL,
    [PolozhenieBolnogo]                             NVARCHAR (50) NULL,
    [PolozhenieBolnogo1]                            NTEXT         NULL,
    [Gematomi2]                                     NVARCHAR (1)  NULL,
    [Rani2]                                         NVARCHAR (50) NULL,
    [Ssadini2]                                      NVARCHAR (50) NULL,
    [DeformatsiyaOsiKonechnosti]                    NTEXT         NULL,
    [PovrezhdennayaKonechnost]                      NTEXT         NULL,
    [AmplitudaDvizheniy]                            NTEXT         NULL,
    [Dlina]                                         NVARCHAR (50) NULL,
    [Okruzhnost]                                    NVARCHAR (50) NULL,
    [MishechnayaSila]                               NVARCHAR (50) NULL,
    [Kozha]                                         NVARCHAR (50) NULL,
    [Kozha2]                                        NVARCHAR (50) NULL,
    [Data]                                          DATETIME      NULL,
    [Vrach]                                         NVARCHAR (50) NULL,
    CONSTRAINT [PervichniyPriMTravmatologaOrtopedaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PervichniyPriMTravmatologaOrtopedaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

