CREATE TABLE [dbo].[PervichniyPriMNefrologa] (
    [ID]                                            INT           NOT NULL,
    [PatID]                                         INT           NULL,
    [Zhalobi]                                       NTEXT         NULL,
    [AnamnezZabolevaniya]                           NTEXT         NULL,
    [Inektsii]                                      NVARCHAR (1)  NULL,
    [LechenieUStomatologa]                          NVARCHAR (1)  NULL,
    [Operatsii]                                     NVARCHAR (1)  NULL,
    [Transfuzii]                                    NVARCHAR (1)  NULL,
    [Tb]                                            NVARCHAR (1)  NULL,
    [Vich]                                          NVARCHAR (1)  NULL,
    [Malyariya]                                     NVARCHAR (1)  NULL,
    [Tif]                                           NVARCHAR (1)  NULL,
    [Paratif]                                       NVARCHAR (1)  NULL,
    [Gepatit]                                       NVARCHAR (1)  NULL,
    [ObektivniyStatus]                              NTEXT         NULL,
    [ObsheeSostoyanie]                              INT           NULL,
    [Teloslozhenie]                                 INT           NULL,
    [Ves]                                           INT           NULL,
    [TemperaturaTela]                               FLOAT (53)    NULL,
    [Kozha1]                                        INT           NULL,
    [PigmentatsiyaIDepigmentatsiya]                 NVARCHAR (35) NULL,
    [Krovoizliyaniya]                               NVARCHAR (35) NULL,
    [Rubtsi]                                        NVARCHAR (35) NULL,
    [FormaIHarakterVisipaniy]                       NVARCHAR (35) NULL,
    [SosudistieIzmeneniya]                          NVARCHAR (35) NULL,
    [TroficheskieIzmeneniya]                        NVARCHAR (35) NULL,
    [Nogti4]                                        INT           NULL,
    [Nogti11]                                       INT           NULL,
    [Nogti21]                                       INT           NULL,
    [Nogti31]                                       INT           NULL,
    [LimfaticheskieUzli1]                           NTEXT         NULL,
    [Mishtsi1]                                      INT           NULL,
    [MishciBoleznennost1]                           NVARCHAR (1)  NULL,
    [Kosti1]                                        NTEXT         NULL,
    [KostiBoleznennost1]                            NVARCHAR (1)  NULL,
    [Sustavi1]                                      NTEXT         NULL,
    [SustaviBoleznnenost1]                          NVARCHAR (1)  NULL,
    [SustaviDeformacii1]                            NVARCHAR (1)  NULL,
    [sustaviDefiguracii1]                           NVARCHAR (1)  NULL,
    [Pochki1]                                       NTEXT         NULL,
    [SMPasternatskogo1]                             INT           NULL,
    [Mocheispuskanie1]                              INT           NULL,
    [PoseshenieNaDomu1]                             NVARCHAR (1)  NULL,
    [KompleksniyOsmotr1]                            NVARCHAR (1)  NULL,
    [NeobhodimaFlyuorografiya1]                     NVARCHAR (1)  NULL,
    [NuzhdaetsyaVStatsionarnomLechenii1]            NVARCHAR (1)  NULL,
    [PredvaritelniyDiagnoz]                         NTEXT         NULL,
    [AnamnezZhizni]                                 NTEXT         NULL,
    [AnamnezZhizni1]                                NTEXT         NULL,
    [AnamnezZhizni2]                                NTEXT         NULL,
    [AnamnezZhizni3]                                NTEXT         NULL,
    [Medikamentov]                                  NTEXT         NULL,
    [Produktov]                                     NTEXT         NULL,
    [NalichieOslozhneniyTransfuzii]                 NTEXT         NULL,
    [GruppaKrovi]                                   NVARCHAR (50) NULL,
    [Rh]                                            NVARCHAR (50) NULL,
    [TransfuziiRanshe]                              NVARCHAR (50) NULL,
    [BitovieUsloviya]                               NVARCHAR (50) NULL,
    [LichnayaGigiena]                               NVARCHAR (50) NULL,
    [UpotreblenieNarkotikov]                        NVARCHAR (50) NULL,
    [IstochnikPitevoyVodi]                          NVARCHAR (50) NULL,
    [UpotreblenieSiroyVodi]                         NVARCHAR (50) NULL,
    [NalichieTbVichMalyariiTifaParatifaGepatitaZpp] NVARCHAR (50) NULL,
    [Zpp]                                           NVARCHAR (50) NULL,
    [Data]                                          DATETIME      NULL,
    [Vrach]                                         NVARCHAR (50) NULL,
    CONSTRAINT [PervichniyPriMNefrologaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PervichniyPriMNefrologaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

