CREATE TABLE [dbo].[PervichniyPriMGastroenterologa] (
    [ID]                                            INT           NOT NULL,
    [PatID]                                         INT           NULL,
    [Zhalobi]                                       NTEXT         NULL,
    [Memo1]                                         NTEXT         NULL,
    [Memo2]                                         NTEXT         NULL,
    [Memo4]                                         NTEXT         NULL,
    [Memo3]                                         NTEXT         NULL,
    [AnamnezZabolevaniya]                           NTEXT         NULL,
    [Memo5]                                         NTEXT         NULL,
    [Memo6]                                         NTEXT         NULL,
    [Memo7]                                         NTEXT         NULL,
    [Inektsii]                                      NVARCHAR (1)  NULL,
    [LechenieUStomatologa]                          NVARCHAR (1)  NULL,
    [Operatsii]                                     NVARCHAR (1)  NULL,
    [Transfuzii]                                    NVARCHAR (1)  NULL,
    [DictCombo2]                                    NVARCHAR (50) NULL,
    [DictCombo3]                                    NVARCHAR (50) NULL,
    [DictCombo4]                                    NVARCHAR (50) NULL,
    [DictCombo5]                                    NVARCHAR (50) NULL,
    [DictCombo6]                                    NVARCHAR (50) NULL,
    [DictCombo7]                                    NVARCHAR (50) NULL,
    [DictCombo9]                                    NVARCHAR (50) NULL,
    [DictCombo10]                                   NVARCHAR (50) NULL,
    [DictCombo8]                                    NVARCHAR (50) NULL,
    [Tb]                                            NVARCHAR (1)  NULL,
    [Vich]                                          NVARCHAR (1)  NULL,
    [Malyariya]                                     NVARCHAR (1)  NULL,
    [Tif]                                           NVARCHAR (1)  NULL,
    [Paratif]                                       NVARCHAR (1)  NULL,
    [Gepatit]                                       NVARCHAR (1)  NULL,
    [DictCombo11]                                   NVARCHAR (50) NULL,
    [ObektivniyStatus1]                             NTEXT         NULL,
    [SosudiVerhnihKonechnostey1]                    NTEXT         NULL,
    [SosudiNizhnihKonechnostey1]                    NTEXT         NULL,
    [Date]                                          DATETIME      NULL,
    [Doctor]                                        NVARCHAR (50) NULL,
    [AnamnezZhizni]                                 NTEXT         NULL,
    [AnamnezZhizni1]                                NTEXT         NULL,
    [AnamnezZhizni2]                                NTEXT         NULL,
    [AnamnezZhizni3]                                NTEXT         NULL,
    [Medikamentov]                                  NTEXT         NULL,
    [Produktov]                                     NTEXT         NULL,
    [NalichieOslozhneniyTransfuzii]                 NTEXT         NULL,
    [GruppaKrovi]                                   NVARCHAR (50) NULL,
    [Rh]                                            NVARCHAR (50) NULL,
    [TransfuziiRanshe]                              NVARCHAR (50) NULL,
    [BitovieUsloviya]                               NVARCHAR (50) NULL,
    [LichnayaGigiena]                               NVARCHAR (50) NULL,
    [UpotreblenieNarkotikov]                        NVARCHAR (50) NULL,
    [IstochnikPitevoyVodi]                          NVARCHAR (50) NULL,
    [UpotreblenieSiroyVodi]                         NVARCHAR (50) NULL,
    [NalichieTbVichMalyariiTifaParatifaGepatitaZpp] NVARCHAR (50) NULL,
    [Zpp]                                           NVARCHAR (50) NULL,
    CONSTRAINT [PervichniyPriMGastroenterologaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PervichniyPriMGastroenterologaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

