CREATE TABLE [dbo].[PervichniyPriMOtorinolaringologa] (
    [ID]                                            INT           NOT NULL,
    [PatID]                                         INT           NULL,
    [Zhalobi]                                       NTEXT         NULL,
    [AnamnezZabolevaniya]                           NTEXT         NULL,
    [Inektsii]                                      NVARCHAR (1)  NULL,
    [LechenieUStomatologa]                          NVARCHAR (1)  NULL,
    [Operatsii]                                     NVARCHAR (1)  NULL,
    [Transfuzii]                                    NVARCHAR (1)  NULL,
    [Tb]                                            NVARCHAR (1)  NULL,
    [Vich]                                          NVARCHAR (1)  NULL,
    [Malyariya]                                     NVARCHAR (1)  NULL,
    [Tif]                                           NVARCHAR (1)  NULL,
    [Paratif]                                       NVARCHAR (1)  NULL,
    [Gepatit]                                       NVARCHAR (1)  NULL,
    [DopolnitelnieDannie]                           NVARCHAR (45) NULL,
    [KamertonnoeIssledovanie]                       NVARCHAR (45) NULL,
    [RazgovornayaRech]                              INT           NULL,
    [S]                                             INT           NULL,
    [ShopotnayaRech1]                               INT           NULL,
    [ShopotnayaRech]                                INT           NULL,
    [BarabannayaPereponkaBezIzmeneniy]              NVARCHAR (1)  NULL,
    [BarabannayaPereponka]                          NVARCHAR (30) NULL,
    [SluhovoyProhod]                                NVARCHAR (30) NULL,
    [SluhovoyProhodBezIzmeneniy]                    NVARCHAR (1)  NULL,
    [NaruzhnoeUhoBezIzmeneniy]                      NVARCHAR (1)  NULL,
    [NaruzhnoeUho]                                  NVARCHAR (30) NULL,
    [Gortan]                                        NVARCHAR (30) NULL,
    [GortanBezIzmeneniy]                            NVARCHAR (1)  NULL,
    [GolosovayaFTsiyaBezIzmeneniy]                  NVARCHAR (1)  NULL,
    [GolosovayaFTsiya]                              NVARCHAR (30) NULL,
    [LimfaticheskieUzli]                            NVARCHAR (30) NULL,
    [LimfaticheskieUzliBezIzmeneniy]                NVARCHAR (1)  NULL,
    [MindaliniDSBezIzmeneniy]                       NVARCHAR (1)  NULL,
    [MindaliniDS]                                   NVARCHAR (30) NULL,
    [Glotka]                                        NVARCHAR (20) NULL,
    [GlotkaBezIzmeneniy]                            NVARCHAR (1)  NULL,
    [Slizistaya]                                    NVARCHAR (20) NULL,
    [DrugieObrazovaniya]                            NVARCHAR (50) NULL,
    [NosoglotkaBezIzmeneniy]                        NVARCHAR (1)  NULL,
    [Nosoglotka]                                    NVARCHAR (30) NULL,
    [Adenoidi]                                      INT           NULL,
    [NosovieRakovini]                               NVARCHAR (25) NULL,
    [NosovayaPeregorodka]                           INT           NULL,
    [TsvetSlizistoy]                                NVARCHAR (20) NULL,
    [OtechnostSlizistoy]                            NVARCHAR (1)  NULL,
    [Giperemia]                                     NVARCHAR (1)  NULL,
    [Atrophia]                                      NVARCHAR (1)  NULL,
    [Polipi]                                        NVARCHAR (1)  NULL,
    [NosovoeDihanie]                                NVARCHAR (30) NULL,
    [Zhalobi1]                                      NTEXT         NULL,
    [AnamnezZhizni]                                 NTEXT         NULL,
    [AnamnezZhizni1]                                NTEXT         NULL,
    [AnamnezZhizni2]                                NTEXT         NULL,
    [AnamnezZhizni3]                                NTEXT         NULL,
    [Medikamentov]                                  NTEXT         NULL,
    [Produktov]                                     NTEXT         NULL,
    [NalichieOslozhneniyTransfuzii]                 NTEXT         NULL,
    [GruppaKrovi]                                   NVARCHAR (50) NULL,
    [Rh]                                            NVARCHAR (50) NULL,
    [TransfuziiRanshe]                              NVARCHAR (50) NULL,
    [BitovieUsloviya]                               NVARCHAR (50) NULL,
    [LichnayaGigiena]                               NVARCHAR (50) NULL,
    [UpotreblenieNarkotikov]                        NVARCHAR (50) NULL,
    [IstochnikPitevoyVodi]                          NVARCHAR (50) NULL,
    [UpotreblenieSiroyVodi]                         NVARCHAR (50) NULL,
    [NalichieTbVichMalyariiTifaParatifaGepatitaZpp] NVARCHAR (50) NULL,
    [Zpp]                                           NVARCHAR (50) NULL,
    [Data]                                          DATETIME      NULL,
    [Vrach]                                         INT           NULL,
    [PolostNosa]                                    NVARCHAR (30) NULL,
    [Zaklyuchenie]                                  NVARCHAR (50) NULL,
    [Kommentrariy]                                  NTEXT         NULL,
    CONSTRAINT [PervichniyPriMOtorinolaringologaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PervichniyPriMOtorinolaringologaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

