CREATE TABLE [dbo].[PervichniyPriMGematologaVPoliklinike] (
    [ID]                              INT           NOT NULL,
    [PatID]                           INT           NULL,
    [Zhalobi]                         NTEXT         NULL,
    [Memo1]                           NTEXT         NULL,
    [Memo4]                           NTEXT         NULL,
    [Memo3]                           NTEXT         NULL,
    [Memo2]                           NTEXT         NULL,
    [AnamnezZabolevaniya]             NTEXT         NULL,
    [Memo5]                           NTEXT         NULL,
    [Memo6]                           NTEXT         NULL,
    [Memo7]                           NTEXT         NULL,
    [Inektsii]                        NVARCHAR (1)  NULL,
    [LechenieUStomatologa]            NVARCHAR (1)  NULL,
    [Operatsii]                       NVARCHAR (1)  NULL,
    [Transfuzii]                      NVARCHAR (1)  NULL,
    [DictCombo2]                      NVARCHAR (50) NULL,
    [DictCombo3]                      NVARCHAR (50) NULL,
    [DictCombo4]                      NVARCHAR (50) NULL,
    [DictCombo5]                      NVARCHAR (50) NULL,
    [DictCombo6]                      NVARCHAR (50) NULL,
    [DictCombo7]                      NVARCHAR (50) NULL,
    [DictCombo9]                      NVARCHAR (50) NULL,
    [DictCombo10]                     NVARCHAR (50) NULL,
    [DictCombo8]                      NVARCHAR (50) NULL,
    [Tb]                              NVARCHAR (1)  NULL,
    [Vich]                            NVARCHAR (1)  NULL,
    [Malyariya]                       NVARCHAR (1)  NULL,
    [Tif]                             NVARCHAR (1)  NULL,
    [Paratif]                         NVARCHAR (1)  NULL,
    [Gepatit]                         NVARCHAR (1)  NULL,
    [DictCombo11]                     NVARCHAR (50) NULL,
    [ObektivniyStatus1]               NTEXT         NULL,
    [SosudiVerhnihKonechnostey1]      NTEXT         NULL,
    [SosudiNizhnihKonechnostey1]      NTEXT         NULL,
    [PulsNaLevoySonnoyArterii2]       INT           NULL,
    [PulsNaLevoySonnoyArterii11]      INT           NULL,
    [AdNaPravoyVerhneyKonechnosti11]  INT           NULL,
    [AdNaPravoyVerhneyKonechnosti2]   INT           NULL,
    [AdNaLevoyVerhneyKonechnosti11]   INT           NULL,
    [AdNaLevoyVerhneyKonechnosti2]    INT           NULL,
    [AdNaLevoyNizhneyKonechnosti2]    INT           NULL,
    [AdNaLevoyNizhneyKonechnosti11]   INT           NULL,
    [AdNaPravoyNizhneyKonechnosti2]   INT           NULL,
    [AdNaPravoyNizhneyKonechnosti11]  INT           NULL,
    [PulsatsiyaBryushnoyChastiAorti1] NVARCHAR (1)  NULL,
    [KozhniePokrovi1]                 NVARCHAR (60) NULL,
    [DopolnitelnieDannie1]            NVARCHAR (50) NULL,
    [Kozha]                           INT           NULL,
    [PigmentatsiyaIDepigmentatsiya]   NVARCHAR (35) NULL,
    [Krovoizliyaniya]                 NVARCHAR (35) NULL,
    [Rubtsi]                          NVARCHAR (35) NULL,
    [TroficheskieIzmeneniya]          NVARCHAR (35) NULL,
    [SosudistieIzmeneniya]            NVARCHAR (35) NULL,
    [FormaIHarakterVisipaniy]         NVARCHAR (35) NULL,
    [Nogti]                           INT           NULL,
    [Nogti1]                          INT           NULL,
    [Nogti2]                          INT           NULL,
    [Nogti3]                          INT           NULL,
    [VidimieSlizistie]                INT           NULL,
    [VidimieSlizistie1]               INT           NULL,
    [LimfaticheskieUzli]              NTEXT         NULL,
    [Mishtsi]                         INT           NULL,
    [Mishtsi1]                        INT           NULL,
    [MishciBoleznennost]              NVARCHAR (1)  NULL,
    [DopolnitelnieDannie]             NTEXT         NULL,
    [Kozha1]                          INT           NULL,
    [PigmentatsiyaIDepigmentatsiya1]  NVARCHAR (35) NULL,
    [Krovoizliyaniya1]                NVARCHAR (35) NULL,
    [Rubtsi1]                         NVARCHAR (35) NULL,
    [TroficheskieIzmeneniya1]         NVARCHAR (35) NULL,
    [SosudistieIzmeneniya1]           NVARCHAR (35) NULL,
    [FormaIHarakterVisipaniy1]        NVARCHAR (35) NULL,
    [Nogti4]                          INT           NULL,
    [Nogti11]                         INT           NULL,
    [Nogti21]                         INT           NULL,
    [Nogti31]                         INT           NULL,
    [VidimieSlizistie2]               INT           NULL,
    [VidimieSlizistie11]              INT           NULL,
    [LimfaticheskieUzli1]             NTEXT         NULL,
    [Mishtsi2]                        INT           NULL,
    [Mishtsi11]                       INT           NULL,
    [MishciBoleznennost1]             NVARCHAR (1)  NULL,
    [DopolnitelnieDannie2]            NTEXT         NULL,
    [Kozha2]                          INT           NULL,
    [PigmentatsiyaIDepigmentatsiya2]  NVARCHAR (35) NULL,
    [Krovoizliyaniya2]                NVARCHAR (35) NULL,
    [Rubtsi2]                         NVARCHAR (35) NULL,
    [TroficheskieIzmeneniya2]         NVARCHAR (35) NULL,
    [SosudistieIzmeneniya2]           NVARCHAR (35) NULL,
    [FormaIHarakterVisipaniy2]        NVARCHAR (35) NULL,
    [Nogti5]                          INT           NULL,
    [Nogti12]                         INT           NULL,
    [Nogti22]                         INT           NULL,
    [Nogti32]                         INT           NULL,
    [VidimieSlizistie3]               INT           NULL,
    [VidimieSlizistie12]              INT           NULL,
    [LimfaticheskieUzli2]             NTEXT         NULL,
    [Mishtsi3]                        INT           NULL,
    [Mishtsi12]                       INT           NULL,
    [MishciBoleznennost2]             NVARCHAR (1)  NULL,
    [DopolnitelnieDannie3]            NTEXT         NULL,
    [Kozha3]                          INT           NULL,
    [PigmentatsiyaIDepigmentatsiya3]  NVARCHAR (35) NULL,
    [Krovoizliyaniya3]                NVARCHAR (35) NULL,
    [Rubtsi3]                         NVARCHAR (35) NULL,
    [TroficheskieIzmeneniya3]         NVARCHAR (35) NULL,
    [SosudistieIzmeneniya3]           NVARCHAR (35) NULL,
    [FormaIHarakterVisipaniy3]        NVARCHAR (35) NULL,
    [Nogti6]                          INT           NULL,
    [Nogti13]                         INT           NULL,
    [Nogti23]                         INT           NULL,
    [Nogti33]                         INT           NULL,
    [VidimieSlizistie4]               INT           NULL,
    [VidimieSlizistie13]              INT           NULL,
    [LimfaticheskieUzli3]             NTEXT         NULL,
    [Mishtsi4]                        INT           NULL,
    [Mishtsi13]                       INT           NULL,
    [MishciBoleznennost3]             NVARCHAR (1)  NULL,
    [DopolnitelnieDannie4]            NTEXT         NULL,
    [DateBox1]                        DATETIME      NULL,
    [DictCombo1]                      NVARCHAR (50) NULL,
    [Memo8]                           NTEXT         NULL,
    CONSTRAINT [PervichniyPriMGematologaVPoliklinikePrimKey] PRIMARY KEY CLUSTERED ([ID] ASC)
);

