CREATE TABLE [dbo].[PerviyVizitBeremennoy] (
    [ID]                       INT            NOT NULL,
    [PatID]                    INT            NULL,
    [DiagVProshlom]            NVARCHAR (250) NULL,
    [CommonIll]                NTEXT          NULL,
    [DiagVProshlom1]           NVARCHAR (250) NULL,
    [GynecologicIll]           NTEXT          NULL,
    [Surgery]                  NTEXT          NULL,
    [HusbandHealth]            NTEXT          NULL,
    [MenarheS]                 INT            NULL,
    [MenarheUstan]             NVARCHAR (15)  NULL,
    [RegulyarniyCherez]        NVARCHAR (80)  NULL,
    [regul]                    NVARCHAR (50)  NULL,
    [NachaloPolovoyZhizniS]    INT            NULL,
    [Features]                 NVARCHAR (250) NULL,
    [LastMenstrStart]          DATETIME       NULL,
    [LastMenstrFinish]         DATETIME       NULL,
    [FetusMoveStart]           DATETIME       NULL,
    [Weight]                   FLOAT (53)     NULL,
    [sistR]                    INT            NULL,
    [diastR]                   INT            NULL,
    [sistL]                    INT            NULL,
    [diastL]                   INT            NULL,
    [OkruzhnostZhivotaSm]      NVARCHAR (250) NULL,
    [VisotaDnaMatkiSm]         NVARCHAR (250) NULL,
    [PolozheniePloda]          NVARCHAR (250) NULL,
    [FetusPresentation]        NVARCHAR (250) NULL,
    [NaruzhPolOrgany]          NVARCHAR (250) NULL,
    [Videleniya]               NVARCHAR (250) NULL,
    [SheikaMatki]              NVARCHAR (250) NULL,
    [TeloMatki]                NVARCHAR (250) NULL,
    [Pridatki]                 NVARCHAR (250) NULL,
    [Osobennosti]              NVARCHAR (250) NULL,
    [PregDuration]             INT            NULL,
    [DeliveryEstimate]         DATETIME       NULL,
    [VaginaResearchProvodilos] BIT            NULL,
    [Height]                   FLOAT (53)     NULL,
    [BreastState]              NTEXT          NULL,
    [CirculatorySystemState]   NTEXT          NULL,
    [OtherOrgans]              NTEXT          NULL,
    [physiqueFeatures]         NTEXT          NULL,
    [DSp]                      NVARCHAR (250) NULL,
    [DCr]                      NVARCHAR (250) NULL,
    [Dtroch]                   NVARCHAR (250) NULL,
    [Cext]                     NVARCHAR (250) NULL,
    [Cdiag]                    NVARCHAR (250) NULL,
    [OkruzhnostZhivotaSm6]     FLOAT (53)     NULL,
    [Vid]                      NVARCHAR (250) NULL,
    [Pozitsiya]                NVARCHAR (250) NULL,
    [FetusPulse]               INT            NULL,
    [DocDate]                  DATETIME       NULL,
    [MenstRegul]               NVARCHAR (1)   NULL,
    [Vrach]                    INT            NULL,
    [Cvera]                    NVARCHAR (250) NULL,
    [MKBName]                  NVARCHAR (255) NULL,
    [MKBCode]                  NVARCHAR (250) NULL,
    [Height1]                  FLOAT (53)     NULL,
    [Assignments]              NTEXT          NULL,
    [OslozhnenieBeremenosti]   NVARCHAR (300) NULL,
    [ZabolevanieDiagnoz]       NVARCHAR (300) NULL,
    [RezysFaktorMyzha]         NVARCHAR (50)  NULL,
    [ReakciyBasData1]          DATETIME       NULL,
    [ReakciyBasData2]          DATETIME       NULL,
    [RezIslGonokokki]          NVARCHAR (50)  NULL,
    [RSK]                      NVARCHAR (50)  NULL,
    [KozhnayProba]             NVARCHAR (50)  NULL,
    [Rkc]                      NVARCHAR (50)  NULL,
    [DiagnozBeremenosti]       NTEXT          NULL,
    [DataVzatiyNaYchet]        DATETIME       NULL,
    [Obrazovanie]              NVARCHAR (10)  NULL,
    [YsloviyTruda]             NVARCHAR (50)  NULL,
    [MestoRabotiM]             NVARCHAR (50)  NULL,
    [FamiliyM]                 NVARCHAR (50)  NULL,
    [TelefonM]                 NVARCHAR (50)  NULL,
    CONSTRAINT [PerviyVizitBeremennoyPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PerviyVizitBeremennoyToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

