CREATE TABLE [dbo].[PervichniyPriemTerapevtaNoviy] (
    [ID]                        INT           NOT NULL,
    [PatID]                     INT           NULL,
    [Memo1]                     NTEXT         NULL,
    [Memo2]                     NTEXT         NULL,
    [Memo3]                     NTEXT         NULL,
    [Memo4]                     NTEXT         NULL,
    [Memo5]                     NTEXT         NULL,
    [Memo7]                     NTEXT         NULL,
    [Memo8]                     NTEXT         NULL,
    [Memo10]                    NTEXT         NULL,
    [Memo12]                    NTEXT         NULL,
    [Memo13]                    NTEXT         NULL,
    [Memo14]                    NTEXT         NULL,
    [EditBox1]                  NVARCHAR (50) NULL,
    [DateBox1]                  DATETIME      NULL,
    [DateBox2]                  DATETIME      NULL,
    [DateBox3]                  DATETIME      NULL,
    [EditBox2]                  NVARCHAR (50) NULL,
    [DateBox4]                  DATETIME      NULL,
    [Memo15]                    NTEXT         NULL,
    [DateBox5]                  DATETIME      NULL,
    [Kurenie]                   NVARCHAR (1)  NULL,
    [Alkogol]                   NVARCHAR (1)  NULL,
    [Narkotiki]                 NVARCHAR (1)  NULL,
    [Combo1]                    NVARCHAR (50) NULL,
    [Zhalobi]                   NTEXT         NULL,
    [PerenesennieZabolevaniya]  NTEXT         NULL,
    [Allergoanamnez]            NTEXT         NULL,
    [Nasledstvennost]           NTEXT         NULL,
    [ObektivnieDannie]          NTEXT         NULL,
    [Gemotransfuzii]            NTEXT         NULL,
    [IstoriyaBolezni]           NTEXT         NULL,
    [PredvaritelniyDiagnoz]     NTEXT         NULL,
    [Dieta]                     NTEXT         NULL,
    [MedikamentoznayaTerapiya]  NTEXT         NULL,
    [DopolnitelnieNaznacheniya] NTEXT         NULL,
    [BolnichniyListNomer]       NVARCHAR (50) NULL,
    [S]                         DATETIME      NULL,
    [Po]                        DATETIME      NULL,
    [PovtornayaYavka]           DATETIME      NULL,
    [Vremya]                    NVARCHAR (50) NULL,
    [KTrudu]                    DATETIME      NULL,
    [Primechaniya]              NTEXT         NULL,
    [DataOsmotra]               DATETIME      NULL,
    [Rezhim]                    NVARCHAR (50) NULL,
    CONSTRAINT [PervichniyPriemTerapevtaNoviyPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PervichniyPriemTerapevtaNoviyToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

