CREATE TABLE [dbo].[PervichniyPriMGematologa] (
    [ID]                                            INT           NOT NULL,
    [PatID]                                         INT           NULL,
    [Zhalobi]                                       NTEXT         NULL,
    [AnamnezZabolevaniya]                           NTEXT         NULL,
    [Inektsii]                                      NVARCHAR (1)  NULL,
    [LechenieUStomatologa]                          NVARCHAR (1)  NULL,
    [Operatsii]                                     NVARCHAR (1)  NULL,
    [Transfuzii]                                    NVARCHAR (1)  NULL,
    [Tb]                                            NVARCHAR (1)  NULL,
    [Vich]                                          NVARCHAR (1)  NULL,
    [Malyariya]                                     NVARCHAR (1)  NULL,
    [Tif]                                           NVARCHAR (1)  NULL,
    [Paratif]                                       NVARCHAR (1)  NULL,
    [Gepatit]                                       NVARCHAR (1)  NULL,
    [Kozha]                                         INT           NULL,
    [PigmentatsiyaIDepigmentatsiya]                 NVARCHAR (35) NULL,
    [Krovoizliyaniya]                               NVARCHAR (35) NULL,
    [Rubtsi]                                        NVARCHAR (35) NULL,
    [TroficheskieIzmeneniya]                        NVARCHAR (35) NULL,
    [SosudistieIzmeneniya]                          NVARCHAR (35) NULL,
    [FormaIHarakterVisipaniy]                       NVARCHAR (35) NULL,
    [Nogti]                                         INT           NULL,
    [Nogti1]                                        INT           NULL,
    [Nogti2]                                        INT           NULL,
    [Nogti3]                                        INT           NULL,
    [VidimieSlizistie]                              INT           NULL,
    [VidimieSlizistie1]                             INT           NULL,
    [LimfaticheskieUzli]                            NTEXT         NULL,
    [Mishtsi]                                       INT           NULL,
    [Mishtsi1]                                      INT           NULL,
    [MishciBoleznennost]                            NVARCHAR (1)  NULL,
    [DopolnitelnieDannie]                           NTEXT         NULL,
    [DictCombo1]                                    NVARCHAR (50) NULL,
    [PredvaritelniyDiagnoz]                         NTEXT         NULL,
    [LichnayaJizny]                                 NTEXT         NULL,
    [PerenesennieZabolevania]                       NTEXT         NULL,
    [SemeyniyAnamnez]                               NTEXT         NULL,
    [VredniePrivichki]                              NTEXT         NULL,
    [Medikamentov]                                  NTEXT         NULL,
    [Produktov]                                     NTEXT         NULL,
    [NalichieOslozhneniyTransfuzii]                 NTEXT         NULL,
    [GruppaKrovi]                                   NVARCHAR (50) NULL,
    [Rh]                                            NVARCHAR (50) NULL,
    [TransfuziiRanshe]                              NVARCHAR (50) NULL,
    [BitovieUsloviya]                               NVARCHAR (50) NULL,
    [LichnayaGigiena]                               NVARCHAR (50) NULL,
    [UpotreblenieNarkotikov]                        NVARCHAR (50) NULL,
    [IstochnikPitevoyVodi]                          NVARCHAR (50) NULL,
    [UpotreblenieSiroyVodi]                         NVARCHAR (50) NULL,
    [NalichieTbVichMalyariiTifaParatifaGepatitaZpp] NVARCHAR (50) NULL,
    [Zpp]                                           NVARCHAR (50) NULL,
    [Data]                                          DATETIME      NULL,
    [AnamnezZhizni]                                 NTEXT         NULL,
    [AnamnezZhizni1]                                NTEXT         NULL,
    [AnamnezZhizni2]                                NTEXT         NULL,
    [AnamnezZhizni3]                                NTEXT         NULL,
    [Doctor]                                        NVARCHAR (50) NULL,
    CONSTRAINT [PervichniyPriMGematologaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PervichniyPriMGematologaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

