CREATE TABLE [dbo].[PervichniyPriemAngiohirurgaVPoliklinike] (
    [ID]                              INT           NOT NULL,
    [PatID]                           INT           NULL,
    [Zhalobi]                         NTEXT         NULL,
    [Anamnez]                         NTEXT         NULL,
    [PerenesennieZabolevaniya]        NTEXT         NULL,
    [AllergologicheskiyAnamnez]       NTEXT         NULL,
    [ObektivniyStatus]                NTEXT         NULL,
    [SosudiVerhnihKonechnostey]       NTEXT         NULL,
    [SosudiNizhnihKonechnostey]       NTEXT         NULL,
    [PulsNaLevoySonnoyArterii]        INT           NULL,
    [PulsNaLevoySonnoyArterii1]       INT           NULL,
    [AdNaPravoyVerhneyKonechnosti1]   INT           NULL,
    [AdNaPravoyVerhneyKonechnosti]    INT           NULL,
    [AdNaLevoyVerhneyKonechnosti1]    INT           NULL,
    [AdNaLevoyVerhneyKonechnosti]     INT           NULL,
    [AdNaLevoyNizhneyKonechnosti]     INT           NULL,
    [AdNaLevoyNizhneyKonechnosti1]    INT           NULL,
    [AdNaPravoyNizhneyKonechnosti]    INT           NULL,
    [AdNaPravoyNizhneyKonechnosti1]   INT           NULL,
    [PulsatsiyaBryushnoyChastiAorti]  NVARCHAR (1)  NULL,
    [KozhniePokrovi]                  NVARCHAR (60) NULL,
    [DopolnitelnieDannie]             NVARCHAR (50) NULL,
    [Memo1]                           NTEXT         NULL,
    [Memo4]                           NTEXT         NULL,
    [Memo3]                           NTEXT         NULL,
    [Memo2]                           NTEXT         NULL,
    [AnamnezZabolevaniya]             NTEXT         NULL,
    [Memo5]                           NTEXT         NULL,
    [Memo6]                           NTEXT         NULL,
    [Memo7]                           NTEXT         NULL,
    [Inektsii]                        NVARCHAR (1)  NULL,
    [LechenieUStomatologa]            NVARCHAR (1)  NULL,
    [Operatsii]                       NVARCHAR (1)  NULL,
    [Transfuzii]                      NVARCHAR (1)  NULL,
    [DictCombo2]                      NVARCHAR (50) NULL,
    [DictCombo3]                      NVARCHAR (50) NULL,
    [DictCombo4]                      NVARCHAR (50) NULL,
    [DictCombo5]                      NVARCHAR (50) NULL,
    [DictCombo6]                      NVARCHAR (50) NULL,
    [DictCombo7]                      NVARCHAR (50) NULL,
    [DictCombo9]                      NVARCHAR (50) NULL,
    [DictCombo10]                     NVARCHAR (50) NULL,
    [DictCombo8]                      NVARCHAR (50) NULL,
    [Tb]                              NVARCHAR (1)  NULL,
    [Vich]                            NVARCHAR (1)  NULL,
    [Malyariya]                       NVARCHAR (1)  NULL,
    [Tif]                             NVARCHAR (1)  NULL,
    [Paratif]                         NVARCHAR (1)  NULL,
    [Gepatit]                         NVARCHAR (1)  NULL,
    [DictCombo11]                     NVARCHAR (50) NULL,
    [ObektivniyStatus1]               NTEXT         NULL,
    [SosudiVerhnihKonechnostey1]      NTEXT         NULL,
    [SosudiNizhnihKonechnostey1]      NTEXT         NULL,
    [PulsNaLevoySonnoyArterii2]       INT           NULL,
    [PulsNaLevoySonnoyArterii11]      INT           NULL,
    [AdNaPravoyVerhneyKonechnosti11]  INT           NULL,
    [AdNaPravoyVerhneyKonechnosti2]   INT           NULL,
    [AdNaLevoyVerhneyKonechnosti11]   INT           NULL,
    [AdNaLevoyVerhneyKonechnosti2]    INT           NULL,
    [AdNaLevoyNizhneyKonechnosti2]    INT           NULL,
    [AdNaLevoyNizhneyKonechnosti11]   INT           NULL,
    [AdNaPravoyNizhneyKonechnosti2]   INT           NULL,
    [AdNaPravoyNizhneyKonechnosti11]  INT           NULL,
    [PulsatsiyaBryushnoyChastiAorti1] NVARCHAR (1)  NULL,
    [KozhniePokrovi1]                 NVARCHAR (60) NULL,
    [DopolnitelnieDannie1]            NVARCHAR (50) NULL,
    [DictCombo1]                      NVARCHAR (50) NULL,
    [DateBox1]                        DATETIME      NULL,
    [Memo8]                           NTEXT         NULL,
    CONSTRAINT [PervichniyPriemAngiohirurgaVPoliklinikePrimKey] PRIMARY KEY CLUSTERED ([ID] ASC)
);

