CREATE TABLE [dbo].[PervichniyPriemGinekologaVPoliklinike] (
    [ID]                                        INT           NOT NULL,
    [PatID]                                     INT           NULL,
    [Zhalobi]                                   NTEXT         NULL,
    [Memo1]                                     NTEXT         NULL,
    [Memo4]                                     NTEXT         NULL,
    [Memo3]                                     NTEXT         NULL,
    [Memo2]                                     NTEXT         NULL,
    [AnamnezZabolevaniya]                       NTEXT         NULL,
    [Memo5]                                     NTEXT         NULL,
    [Memo6]                                     NTEXT         NULL,
    [Memo7]                                     NTEXT         NULL,
    [Inektsii]                                  NVARCHAR (1)  NULL,
    [LechenieUStomatologa]                      NVARCHAR (1)  NULL,
    [Operatsii]                                 NVARCHAR (1)  NULL,
    [Transfuzii]                                NVARCHAR (1)  NULL,
    [DictCombo2]                                NVARCHAR (50) NULL,
    [DictCombo3]                                NVARCHAR (50) NULL,
    [DictCombo4]                                NVARCHAR (50) NULL,
    [DictCombo5]                                NVARCHAR (50) NULL,
    [DictCombo6]                                NVARCHAR (50) NULL,
    [DictCombo7]                                NVARCHAR (50) NULL,
    [DictCombo9]                                NVARCHAR (50) NULL,
    [DictCombo10]                               NVARCHAR (50) NULL,
    [DictCombo8]                                NVARCHAR (50) NULL,
    [Tb]                                        NVARCHAR (1)  NULL,
    [Vich]                                      NVARCHAR (1)  NULL,
    [Malyariya]                                 NVARCHAR (1)  NULL,
    [Tif]                                       NVARCHAR (1)  NULL,
    [Paratif]                                   NVARCHAR (1)  NULL,
    [Gepatit]                                   NVARCHAR (1)  NULL,
    [DictCombo11]                               NVARCHAR (50) NULL,
    [PridatkiSpravaBoleznennie]                 NVARCHAR (1)  NULL,
    [Tyazhistie]                                NVARCHAR (1)  NULL,
    [PridatkiSpravaUvelicheni]                  NVARCHAR (1)  NULL,
    [MatkaUvelichena]                           NVARCHAR (1)  NULL,
    [DoKakihRazmerov]                           FLOAT (53)    NULL,
    [Konsistentsiya]                            INT           NULL,
    [Forma]                                     INT           NULL,
    [Raspolozhenie]                             INT           NULL,
    [SvodiSlevaBoleznennie]                     NVARCHAR (1)  NULL,
    [SvodiSlevaGlubokie]                        NVARCHAR (1)  NULL,
    [SvodiSpravaBoleznennie]                    NVARCHAR (1)  NULL,
    [SvodiSpravaGlubokie]                       NVARCHAR (1)  NULL,
    [BezOsobennostey]                           NVARCHAR (1)  NULL,
    [ParametriyOsobennosti]                     NVARCHAR (50) NULL,
    [PridatkiSpravaKonglomerat]                 NVARCHAR (50) NULL,
    [PridatkiSpravaDrugoe]                      NVARCHAR (50) NULL,
    [PridatkiSlevaBoleznennie]                  NVARCHAR (1)  NULL,
    [PridatkiSlevaTyazhistie]                   NVARCHAR (1)  NULL,
    [PridatkiSlevaUvelicheni]                   NVARCHAR (1)  NULL,
    [PridatkiSlevaKonglomerat]                  NVARCHAR (50) NULL,
    [PridatkiSlevaDrugoe]                       NVARCHAR (50) NULL,
    [PervieSimptomiNachaloZabolevaniya]         NVARCHAR (50) NULL,
    [NachaloZabolevaniyaDrugoe]                 NVARCHAR (50) NULL,
    [Abort]                                     NVARCHAR (1)  NULL,
    [Travma]                                    NVARCHAR (1)  NULL,
    [Pereohlazhdenie]                           NVARCHAR (1)  NULL,
    [PolovoeSnoshenie]                          NVARCHAR (1)  NULL,
    [Rodi]                                      NVARCHAR (1)  NULL,
    [GdeIKogdaLechilas]                         NVARCHAR (50) NULL,
    [MetogdiLecheniya]                          NVARCHAR (50) NULL,
    [EffektOtLecheniya]                         NVARCHAR (1)  NULL,
    [Retsidivi]                                 NVARCHAR (1)  NULL,
    [OtyagoshennayaNasledstvennost]             NVARCHAR (1)  NULL,
    [ProdolzhitelnostMenstrualnogoTsikla]       INT           NULL,
    [Nachalo]                                   DATETIME      NULL,
    [Konets]                                    DATETIME      NULL,
    [GinekologicheskiyAnamnezBol]               NVARCHAR (1)  NULL,
    [Zaderzhki1]                                NVARCHAR (1)  NULL,
    [Kontratseptsiya]                           NVARCHAR (1)  NULL,
    [Brak]                                      NVARCHAR (1)  NULL,
    [Medaborti]                                 INT           NULL,
    [ObsheeChisloBeremennosteyRodi]             INT           NULL,
    [ObsheeChisloBeremennostey]                 INT           NULL,
    [VKakomVozrasteNachalaPolovuyuZhizn]        INT           NULL,
    [VideleniyaPriMenstruatsii]                 INT           NULL,
    [SamoproizvolnieVikidishi]                  INT           NULL,
    [PrezhdevremennieRodi]                      INT           NULL,
    [Mertvorozhdeniya]                          NVARCHAR (50) NULL,
    [Oslozhneniya]                              NVARCHAR (50) NULL,
    [Menarhe]                                   DATETIME      NULL,
    [Pravilnie]                                 NVARCHAR (1)  NULL,
    [VlagalisheRozhavshey]                      NVARCHAR (1)  NULL,
    [VlagalisheNerozhavshey]                    NVARCHAR (1)  NULL,
    [SheykaMatkiForma]                          INT           NULL,
    [DisplaziyaEpiteliya]                       NVARCHAR (1)  NULL,
    [Ektropion]                                 NVARCHAR (1)  NULL,
    [SheykaMatkiVideleniya]                     NVARCHAR (1)  NULL,
    [Kondilomi]                                 NVARCHAR (1)  NULL,
    [Polipi]                                    NVARCHAR (1)  NULL,
    [Eroziya]                                   NVARCHAR (1)  NULL,
    [IssledovanieCharezPryamuyuKishku]          NVARCHAR (50) NULL,
    [Zaklyuchenie]                              NTEXT         NULL,
    [MazkiNaFloru]                              NVARCHAR (1)  NULL,
    [UziOrganovMalogoTaza]                      NVARCHAR (1)  NULL,
    [Zakluchenie]                               NTEXT         NULL,
    [Zhalobi1]                                  NTEXT         NULL,
    [Bol]                                       NVARCHAR (1)  NULL,
    [Harakter]                                  NVARCHAR (50) NULL,
    [Lokalizatsiya]                             NVARCHAR (50) NULL,
    [BolDrugoe]                                 NVARCHAR (50) NULL,
    [NarushenieMenstrualnoyFunktsii]            NVARCHAR (1)  NULL,
    [IzmenenieDlitelnosti]                      NVARCHAR (1)  NULL,
    [AtsiklichnostKrovotecheniy]                NVARCHAR (1)  NULL,
    [OtsutstvieKrovotecheniy]                   NVARCHAR (1)  NULL,
    [IzmenenieIntensivnosti]                    NVARCHAR (1)  NULL,
    [Zaderzhki]                                 NVARCHAR (1)  NULL,
    [KrovotecheniePoslePolovogoAkta]            NVARCHAR (1)  NULL,
    [NarushenieMenstrualnoyFunktsiiDrugoe]      NVARCHAR (50) NULL,
    [Tsvet]                                     NVARCHAR (50) NULL,
    [Kolichestvo]                               INT           NULL,
    [Videleniya]                                NVARCHAR (1)  NULL,
    [UsloviyaPoyavleniya]                       NVARCHAR (50) NULL,
    [VideleniyaHarakter]                        NVARCHAR (50) NULL,
    [Drugoe]                                    NVARCHAR (50) NULL,
    [DrugieRasstroystvaPolovoyFunktsii]         NVARCHAR (1)  NULL,
    [Zud]                                       NVARCHAR (1)  NULL,
    [Visipaniya]                                NVARCHAR (1)  NULL,
    [Besplodie]                                 NVARCHAR (1)  NULL,
    [OshushenieMatki]                           NVARCHAR (1)  NULL,
    [DrugieRasstroystvaPolovoyFunktsiiDrugoe]   NVARCHAR (50) NULL,
    [RasstroystvaFuntsiySmezhnihOrganov]        NVARCHAR (1)  NULL,
    [BolPriDefekatsii]                          NVARCHAR (1)  NULL,
    [BolPriMocheispuskanii]                     NVARCHAR (1)  NULL,
    [Ponos]                                     NVARCHAR (1)  NULL,
    [Zapor]                                     NVARCHAR (1)  NULL,
    [NederzhanieMochi]                          NVARCHAR (1)  NULL,
    [RasstroystvaFuntsiySmezhnihOrganovDrugoe]  NVARCHAR (50) NULL,
    [ObshieRastroystva]                         NVARCHAR (1)  NULL,
    [PlohoeSamochuvstvie]                       NVARCHAR (1)  NULL,
    [Serdtsebienie]                             NVARCHAR (1)  NULL,
    [ObshieRastroystvaDrugoe]                   NVARCHAR (50) NULL,
    [Bessonnitsa]                               NVARCHAR (1)  NULL,
    [ObmorochnoeSostoyanie]                     NVARCHAR (1)  NULL,
    [Ozhirenie]                                 NVARCHAR (1)  NULL,
    [Pohudenie]                                 NVARCHAR (1)  NULL,
    [Zhalobi11]                                 NTEXT         NULL,
    [Bol1]                                      NVARCHAR (1)  NULL,
    [Harakter1]                                 NVARCHAR (50) NULL,
    [Lokalizatsiya1]                            NVARCHAR (50) NULL,
    [BolDrugoe1]                                NVARCHAR (50) NULL,
    [NarushenieMenstrualnoyFunktsii1]           NVARCHAR (1)  NULL,
    [IzmenenieDlitelnosti1]                     NVARCHAR (1)  NULL,
    [AtsiklichnostKrovotecheniy1]               NVARCHAR (1)  NULL,
    [OtsutstvieKrovotecheniy1]                  NVARCHAR (1)  NULL,
    [IzmenenieIntensivnosti1]                   NVARCHAR (1)  NULL,
    [Zaderzhki2]                                NVARCHAR (1)  NULL,
    [KrovotecheniePoslePolovogoAkta1]           NVARCHAR (1)  NULL,
    [NarushenieMenstrualnoyFunktsiiDrugoe1]     NVARCHAR (50) NULL,
    [Tsvet1]                                    NVARCHAR (50) NULL,
    [Kolichestvo1]                              INT           NULL,
    [Videleniya1]                               NVARCHAR (1)  NULL,
    [UsloviyaPoyavleniya1]                      NVARCHAR (50) NULL,
    [VideleniyaHarakter1]                       NVARCHAR (50) NULL,
    [Drugoe1]                                   NVARCHAR (50) NULL,
    [DrugieRasstroystvaPolovoyFunktsii1]        NVARCHAR (1)  NULL,
    [Zud1]                                      NVARCHAR (1)  NULL,
    [Visipaniya1]                               NVARCHAR (1)  NULL,
    [Besplodie1]                                NVARCHAR (1)  NULL,
    [OshushenieMatki1]                          NVARCHAR (1)  NULL,
    [DrugieRasstroystvaPolovoyFunktsiiDrugoe1]  NVARCHAR (50) NULL,
    [RasstroystvaFuntsiySmezhnihOrganov1]       NVARCHAR (1)  NULL,
    [BolPriDefekatsii1]                         NVARCHAR (1)  NULL,
    [BolPriMocheispuskanii1]                    NVARCHAR (1)  NULL,
    [Ponos1]                                    NVARCHAR (1)  NULL,
    [Zapor1]                                    NVARCHAR (1)  NULL,
    [NederzhanieMochi1]                         NVARCHAR (1)  NULL,
    [RasstroystvaFuntsiySmezhnihOrganovDrugoe1] NVARCHAR (50) NULL,
    [ObshieRastroystva1]                        NVARCHAR (1)  NULL,
    [PlohoeSamochuvstvie1]                      NVARCHAR (1)  NULL,
    [Serdtsebienie1]                            NVARCHAR (1)  NULL,
    [ObshieRastroystvaDrugoe1]                  NVARCHAR (50) NULL,
    [Bessonnitsa1]                              NVARCHAR (1)  NULL,
    [ObmorochnoeSostoyanie1]                    NVARCHAR (1)  NULL,
    [Ozhirenie1]                                NVARCHAR (1)  NULL,
    [Pohudenie1]                                NVARCHAR (1)  NULL,
    [DateBox1]                                  DATETIME      NULL,
    [DictCombo1]                                NVARCHAR (50) NULL,
    [Memo8]                                     NTEXT         NULL,
    CONSTRAINT [PervichniyPriemGinekologaVPoliklinikePrimKey] PRIMARY KEY CLUSTERED ([ID] ASC)
);

