CREATE TABLE [dbo].[PervichniyPriemAngiohirurga] (
    [ID]                                            INT           NOT NULL,
    [PatID]                                         INT           NULL,
    [Zhalobi]                                       NTEXT         NULL,
    [AnamnezZabolevaniya]                           NTEXT         NULL,
    [Inektsii]                                      NVARCHAR (1)  NULL,
    [LechenieUStomatologa]                          NVARCHAR (1)  NULL,
    [Operatsii]                                     NVARCHAR (1)  NULL,
    [Transfuzii]                                    NVARCHAR (1)  NULL,
    [DictCombo8]                                    NVARCHAR (50) NULL,
    [Tb]                                            NVARCHAR (1)  NULL,
    [Vich]                                          NVARCHAR (1)  NULL,
    [Malyariya]                                     NVARCHAR (1)  NULL,
    [Tif]                                           NVARCHAR (1)  NULL,
    [Paratif]                                       NVARCHAR (1)  NULL,
    [Gepatit]                                       NVARCHAR (1)  NULL,
    [ObektivniyStatus1]                             NTEXT         NULL,
    [SosudiVerhnihKonechnostey1]                    NTEXT         NULL,
    [SosudiNizhnihKonechnostey1]                    NTEXT         NULL,
    [PulsNaLevoySonnoyArterii2]                     INT           NULL,
    [PulsNaLevoySonnoyArterii11]                    INT           NULL,
    [AdNaPravoyVerhneyKonechnosti11]                INT           NULL,
    [AdNaPravoyVerhneyKonechnosti2]                 INT           NULL,
    [AdNaLevoyVerhneyKonechnosti11]                 INT           NULL,
    [AdNaLevoyVerhneyKonechnosti2]                  INT           NULL,
    [AdNaLevoyNizhneyKonechnosti2]                  INT           NULL,
    [AdNaLevoyNizhneyKonechnosti11]                 INT           NULL,
    [AdNaPravoyNizhneyKonechnosti2]                 INT           NULL,
    [AdNaPravoyNizhneyKonechnosti11]                INT           NULL,
    [PulsatsiyaBryushnoyChastiAorti1]               NVARCHAR (1)  NULL,
    [KozhniePokrovi1]                               NVARCHAR (60) NULL,
    [DopolnitelnieDannie1]                          NVARCHAR (50) NULL,
    [PredvaritelniyDiagnoz]                         NTEXT         NULL,
    [LichnayaJizny]                                 NTEXT         NULL,
    [PerenesennieZabolevaniya]                      NTEXT         NULL,
    [CemeyniyAnamnez]                               NTEXT         NULL,
    [VredniePrivichki]                              NTEXT         NULL,
    [Medikamentov]                                  NTEXT         NULL,
    [Produktov]                                     NTEXT         NULL,
    [NalichieOslozhneniyTransfuzii]                 NTEXT         NULL,
    [GruppaKrovi]                                   NVARCHAR (50) NULL,
    [Rh]                                            NVARCHAR (50) NULL,
    [TransfuziiRanshe]                              NVARCHAR (50) NULL,
    [BitovieUsloviya]                               NVARCHAR (50) NULL,
    [LichnayaGigiena]                               NVARCHAR (50) NULL,
    [UpotreblenieNarkotikov]                        NVARCHAR (50) NULL,
    [IstochnikPitevoyVodi]                          NVARCHAR (50) NULL,
    [UpotreblenieSiroyVodi]                         NVARCHAR (50) NULL,
    [Zpp]                                           NVARCHAR (50) NULL,
    [Vrach]                                         NVARCHAR (50) NULL,
    [Data]                                          DATETIME      NULL,
    [AnamnezZhizni]                                 NTEXT         NULL,
    [AnamnezZhizni1]                                NTEXT         NULL,
    [AnamnezZhizni2]                                NTEXT         NULL,
    [AnamnezZhizni3]                                NTEXT         NULL,
    [NalichieTbVichMalyariiTifaParatifaGepatitaZpp] NVARCHAR (50) NULL,
    CONSTRAINT [PervichniyPriemAngiohirurgaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PervichniyPriemAngiohirurgaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

