CREATE TABLE [dbo].[PervichniyPriMEndokrinologa] (
    [ID]                                            INT           NOT NULL,
    [PatID]                                         INT           NULL,
    [Zhalobi]                                       NTEXT         NULL,
    [AnamnezZabolevaniya]                           NTEXT         NULL,
    [Inektsii]                                      NVARCHAR (1)  NULL,
    [LechenieUStomatologa]                          NVARCHAR (1)  NULL,
    [Operatsii]                                     NVARCHAR (1)  NULL,
    [Transfuzii]                                    NVARCHAR (1)  NULL,
    [Tb]                                            NVARCHAR (1)  NULL,
    [Vich]                                          NVARCHAR (1)  NULL,
    [Malyariya]                                     NVARCHAR (1)  NULL,
    [Tif]                                           NVARCHAR (1)  NULL,
    [Paratif]                                       NVARCHAR (1)  NULL,
    [Gepatit]                                       NVARCHAR (1)  NULL,
    [Teloslozhenie]                                 INT           NULL,
    [TonusMuskulaturi]                              NVARCHAR (20) NULL,
    [Rost]                                          INT           NULL,
    [Ves]                                           INT           NULL,
    [VirazhPZhKletchatki]                           NVARCHAR (20) NULL,
    [Vlazhnost]                                     NVARCHAR (20) NULL,
    [Oteki]                                         NVARCHAR (20) NULL,
    [Turgor]                                        NVARCHAR (20) NULL,
    [Pigmentatsiya]                                 NVARCHAR (20) NULL,
    [NervnoPsihicheskiyStatus]                      NVARCHAR (20) NULL,
    [OtekiLica]                                     NVARCHAR (1)  NULL,
    [Zabkost]                                       NVARCHAR (1)  NULL,
    [SuhostKogi]                                    NVARCHAR (1)  NULL,
    [Zapori]                                        NVARCHAR (1)  NULL,
    [sonlivost]                                     NVARCHAR (1)  NULL,
    [Libido]                                        NVARCHAR (20) NULL,
    [VtorichniePolPriznaki]                         INT           NULL,
    [Razmer]                                        INT           NULL,
    [Konsistentsiya]                                NVARCHAR (20) NULL,
    [Uzli]                                          NVARCHAR (20) NULL,
    [Boleznennost]                                  NTEXT         NULL,
    [Tahicardia]                                    NVARCHAR (1)  NULL,
    [DrojanieRuk]                                   NVARCHAR (1)  NULL,
    [Ekzoftalm]                                     NVARCHAR (1)  NULL,
    [Grefe]                                         NVARCHAR (1)  NULL,
    [DopolnitelnieDannie]                           NTEXT         NULL,
    [Razmer1]                                       INT           NULL,
    [Razmer2]                                       INT           NULL,
    [PredvaritelniyDiagnoz]                         NTEXT         NULL,
    [AnamnezZhizni]                                 NTEXT         NULL,
    [AnamnezZhizni1]                                NTEXT         NULL,
    [AnamnezZhizni2]                                NTEXT         NULL,
    [AnamnezZhizni3]                                NTEXT         NULL,
    [Medikamentov]                                  NTEXT         NULL,
    [Produktov]                                     NTEXT         NULL,
    [NalichieOslozhneniyTransfuzii]                 NTEXT         NULL,
    [GruppaKrovi]                                   NVARCHAR (50) NULL,
    [Rh]                                            NVARCHAR (50) NULL,
    [TransfuziiRanshe]                              NVARCHAR (50) NULL,
    [BitovieUsloviya]                               NVARCHAR (50) NULL,
    [LichnayaGigiena]                               NVARCHAR (50) NULL,
    [UpotreblenieNarkotikov]                        NVARCHAR (50) NULL,
    [IstochnikPitevoyVodi]                          NVARCHAR (50) NULL,
    [UpotreblenieSiroyVodi]                         NVARCHAR (50) NULL,
    [NalichieTbVichMalyariiTifaParatifaGepatitaZpp] NVARCHAR (50) NULL,
    [Zpp]                                           NVARCHAR (50) NULL,
    [ObsheeSostoyanie]                              NTEXT         NULL,
    [Data]                                          DATETIME      NULL,
    [Vrach]                                         NVARCHAR (50) NULL,
    CONSTRAINT [PervichniyPriMEndokrinologaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PervichniyPriMEndokrinologaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

