CREATE TABLE [dbo].[PovtorniyPriemVenerologa] (
    [ID]                        INT            NOT NULL,
    [PatID]                     INT            NULL,
    [PolovZhizn]                NVARCHAR (20)  NULL,
    [pppFIO]                    NVARCHAR (200) NULL,
    [pppGodRozh]                NVARCHAR (50)  NULL,
    [pppAdres]                  NVARCHAR (200) NULL,
    [pppDataPoslSvyazi]         NVARCHAR (50)  NULL,
    [SemPol]                    NVARCHAR (100) NULL,
    [PPP]                       NVARCHAR (37)  NULL,
    [DrugPolKont]               NVARCHAR (50)  NULL,
    [DrugPolKontEst]            NTEXT          NULL,
    [BitKontFIO1]               NVARCHAR (200) NULL,
    [BitKontVozrast1]           NVARCHAR (50)  NULL,
    [BitKontOtnosh1]            NVARCHAR (200) NULL,
    [BitKontDataObsl1]          NVARCHAR (50)  NULL,
    [BitKontRezObsl1]           NVARCHAR (50)  NULL,
    [BitKontFIO2]               NVARCHAR (200) NULL,
    [BitKontVozrast2]           NVARCHAR (50)  NULL,
    [BitKontOtnosh2]            NVARCHAR (200) NULL,
    [BitKontDataObsl2]          NVARCHAR (50)  NULL,
    [BitKontRezObsl2]           NVARCHAR (50)  NULL,
    [BitKontFIO3]               NVARCHAR (200) NULL,
    [BitKontVozrast3]           NVARCHAR (50)  NULL,
    [BitKontOtnosh3]            NVARCHAR (200) NULL,
    [BitKontDataObsl3]          NVARCHAR (50)  NULL,
    [BitKontRezObsl3]           NVARCHAR (50)  NULL,
    [BitKontFIO4]               NVARCHAR (200) NULL,
    [BitKontVozrast4]           NVARCHAR (50)  NULL,
    [BitKontOtnosh4]            NVARCHAR (200) NULL,
    [BitKontDataObsl4]          NVARCHAR (50)  NULL,
    [BitKontRezObsl4]           NVARCHAR (50)  NULL,
    [BitKontFIO5]               NVARCHAR (200) NULL,
    [BitKontVozrast5]           NVARCHAR (50)  NULL,
    [BitKontOtnosh5]            NVARCHAR (200) NULL,
    [BitKontDataObsl5]          NVARCHAR (50)  NULL,
    [BitKontRezObsl5]           NVARCHAR (50)  NULL,
    [OtekiText]                 NVARCHAR (200) NULL,
    [Oteki]                     NVARCHAR (10)  NULL,
    [Temp]                      NVARCHAR (10)  NULL,
    [Polozhenie]                NVARCHAR (50)  NULL,
    [Soznanie]                  NVARCHAR (50)  NULL,
    [Sost]                      NVARCHAR (20)  NULL,
    [LimfouzliText]             NTEXT          NULL,
    [Limfouzli]                 NVARCHAR (20)  NULL,
    [PatVipadVolos]             NVARCHAR (50)  NULL,
    [PatVipadVolosNabl]         NTEXT          NULL,
    [KozhPokrVisip]             NVARCHAR (50)  NULL,
    [KozhPokrVisipNalich]       NTEXT          NULL,
    [PolGubVisip]               NVARCHAR (50)  NULL,
    [PolGubVisipEst]            NTEXT          NULL,
    [GubUretrZhen]              NVARCHAR (50)  NULL,
    [GubUretrZhenIzmen]         NTEXT          NULL,
    [ZerkVisip]                 NVARCHAR (50)  NULL,
    [ZerkVisipEst]              NVARCHAR (200) NULL,
    [ZerkVidel]                 NVARCHAR (50)  NULL,
    [ZerkVidelEst]              NVARCHAR (200) NULL,
    [BlednoRozovaya]            NVARCHAR (14)  NULL,
    [Giperemirovana]            NVARCHAR (14)  NULL,
    [Otechna]                   NVARCHAR (6)   NULL,
    [VidelenZhen]               NVARCHAR (50)  NULL,
    [VidelenZhenEst]            NTEXT          NULL,
    [BartolinZhel]              NVARCHAR (50)  NULL,
    [BartolinZhelIzmen]         NTEXT          NULL,
    [PolChlenVisip]             NVARCHAR (50)  NULL,
    [PolChlenVisipEst]          NTEXT          NULL,
    [GubUret]                   NVARCHAR (200) NULL,
    [Videleniya]                NVARCHAR (200) NULL,
    [NeMochilsya]               NVARCHAR (100) NULL,
    [MochaPerv]                 NVARCHAR (200) NULL,
    [MochaVtor]                 NVARCHAR (50)  NULL,
    [OrgMosh]                   NVARCHAR (50)  NULL,
    [OrhMoshIzm]                NTEXT          NULL,
    [A5xObosnov]                NTEXT          NULL,
    [L40process]                NVARCHAR (50)  NULL,
    [L40Forma]                  NVARCHAR (50)  NULL,
    [L40stadiya]                NVARCHAR (50)  NULL,
    [L40tip]                    NVARCHAR (50)  NULL,
    [DiagDict]                  NVARCHAR (50)  NULL,
    [DiagCode]                  NVARCHAR (6)   NULL,
    [SopDiag]                   NVARCHAR (50)  NULL,
    [DiagDop]                   NTEXT          NULL,
    [Oslozhneniya]              NVARCHAR (200) NULL,
    [Eds]                       NVARCHAR (3)   NULL,
    [KlinicheskiyAnalizKrovi]   NVARCHAR (24)  NULL,
    [ObshiyAnalizMochi]         NVARCHAR (17)  NULL,
    [KalNaYaGlist]              NVARCHAR (14)  NULL,
    [PosevNaGribi]              NVARCHAR (14)  NULL,
    [IFAlyamb]                  NVARCHAR (18)  NULL,
    [IFApylori]                 NVARCHAR (13)  NULL,
    [IFAHbSAg]                  NVARCHAR (13)  NULL,
    [LipidniyProfil]            NVARCHAR (16)  NULL,
    [BiohimProbiPecheni]        NVARCHAR (20)  NULL,
    [SoskobNogti]               NVARCHAR (34)  NULL,
    [SoskobMezhPalc]            NVARCHAR (38)  NULL,
    [soskobStopi]               NVARCHAR (30)  NULL,
    [SoskobVolosist]            NVARCHAR (41)  NULL,
    [SoskobGladkoyKozhi]        NVARCHAR (30)  NULL,
    [SoskobNaKlesha]            NVARCHAR (31)  NULL,
    [KrovNaSahar]               NVARCHAR (14)  NULL,
    [Revmoprobi]                NVARCHAR (10)  NULL,
    [MazkiOtpechatki]           NVARCHAR (15)  NULL,
    [KroviNaVolchan]            NVARCHAR (27)  NULL,
    [AnalizMochiPoNechiporenko] NVARCHAR (26)  NULL,
    [Rif]                       NVARCHAR (3)   NULL,
    [IfaATKParazitam]           NVARCHAR (19)  NULL,
    [Antibiotikogramma]         NVARCHAR (17)  NULL,
    [DemodLico]                 NVARCHAR (30)  NULL,
    [DemodUshi]                 NVARCHAR (32)  NULL,
    [DemodResnic]               NVARCHAR (27)  NULL,
    [SoskobNaLepru]             NVARCHAR (15)  NULL,
    [SoskobNaBlTreponemu]       NVARCHAR (27)  NULL,
    [Mazok]                     NVARCHAR (6)   NULL,
    [BakPosevNaFloruSMazkom]    NVARCHAR (27)  NULL,
    [BakPosevNaFloru]           NVARCHAR (18)  NULL,
    [IfaSumAntitela]            NVARCHAR (22)  NULL,
    [IfaIgM]                    NVARCHAR (7)   NULL,
    [IfaIgG]                    NVARCHAR (7)   NULL,
    [Mrp]                       NVARCHAR (3)   NULL,
    [Rpga]                      NVARCHAR (4)   NULL,
    [IfaAntiHlamidiya]          NVARCHAR (17)  NULL,
    [IfaAntiVpg12]              NVARCHAR (16)  NULL,
    [Vich]                      NVARCHAR (3)   NULL,
    [Pcr]                       NVARCHAR (3)   NULL,
    [Naznacheniya]              NTEXT          NULL,
    [Rezhim]                    NVARCHAR (30)  NULL,
    [SledYavka]                 DATETIME       NULL,
    [PlanObs]                   NTEXT          NULL,
    [Dieta]                     NVARCHAR (100) NULL,
    [NahodilsyaNaPrieme]        NVARCHAR (19)  NULL,
    [NeSostoitNaUchete]         NVARCHAR (19)  NULL,
    [NahodilsyaNaLechenii]      NVARCHAR (20)  NULL,
    [PoNeobhodimosti]           NVARCHAR (16)  NULL,
    [Revmatolog]                NVARCHAR (10)  NULL,
    [Nevrolog]                  NVARCHAR (8)   NULL,
    [Pediatr]                   NVARCHAR (7)   NULL,
    [AllergologImmunolog]       NVARCHAR (20)  NULL,
    [Urolog]                    NVARCHAR (6)   NULL,
    [Ginekolog]                 NVARCHAR (9)   NULL,
    [Endokrinolog]              NVARCHAR (12)  NULL,
    [Gastroenterolog]           NVARCHAR (15)  NULL,
    [Terapevt]                  NVARCHAR (8)   NULL,
    [Lor]                       NVARCHAR (3)   NULL,
    [Stomatolog]                NVARCHAR (10)  NULL,
    [Onkolog]                   NVARCHAR (7)   NULL,
    [Okulist]                   NVARCHAR (7)   NULL,
    [Zhalobi]                   NTEXT          NULL,
    [lokaliz1]                  NVARCHAR (7)   NULL,
    [lokaliz2]                  NVARCHAR (22)  NULL,
    [NaKozhe1]                  NVARCHAR (25)  NULL,
    [NaKozhe2]                  NVARCHAR (4)   NULL,
    [NaKozhe3]                  NVARCHAR (3)   NULL,
    [NaKozhe4]                  NVARCHAR (5)   NULL,
    [NaKozhe5]                  NVARCHAR (6)   NULL,
    [NaKozhe6]                  NVARCHAR (5)   NULL,
    [NaKozhe7]                  NVARCHAR (7)   NULL,
    [NaKozhe8]                  NVARCHAR (6)   NULL,
    [NaKozhe9]                  NVARCHAR (25)  NULL,
    [NaKozhe10]                 NVARCHAR (6)   NULL,
    [NaKozhe11]                 NVARCHAR (5)   NULL,
    [NaKozhe12]                 NVARCHAR (7)   NULL,
    [NaKozhe13]                 NVARCHAR (5)   NULL,
    [NaKozhe14]                 NVARCHAR (7)   NULL,
    [NaKozhe15]                 NVARCHAR (6)   NULL,
    [NaKozhe16]                 NVARCHAR (15)  NULL,
    [NaKozhe17]                 NVARCHAR (7)   NULL,
    [NaKozhe18]                 NVARCHAR (3)   NULL,
    [Sliz1]                     NVARCHAR (11)  NULL,
    [Sliz2]                     NVARCHAR (15)  NULL,
    [Zhalobi1]                  NVARCHAR (15)  NULL,
    [Zhalobi2]                  NVARCHAR (22)  NULL,
    [Zhalobi4]                  NVARCHAR (14)  NULL,
    [Zhalobi5]                  NVARCHAR (31)  NULL,
    [Zhalobi6]                  NVARCHAR (34)  NULL,
    [Zhalobi7]                  NVARCHAR (32)  NULL,
    [Zhalobi9]                  NVARCHAR (21)  NULL,
    [Zhalobi10]                 NVARCHAR (16)  NULL,
    [Zhalobi8]                  NVARCHAR (32)  NULL,
    [Zhalobi11]                 NVARCHAR (35)  NULL,
    [Zhalobi12]                 NVARCHAR (26)  NULL,
    [Zhalobi13]                 NVARCHAR (16)  NULL,
    [Zhalobi3]                  NVARCHAR (23)  NULL,
    [VideleniyaHarakter]        NVARCHAR (100) NULL,
    [VideleniyaZapah]           NVARCHAR (100) NULL,
    [skladok1]                  NVARCHAR (19)  NULL,
    [skladok2]                  NVARCHAR (22)  NULL,
    [skladok3]                  NVARCHAR (20)  NULL,
    [skladok4]                  NVARCHAR (39)  NULL,
    [skladok5]                  NVARCHAR (16)  NULL,
    [skladok6]                  NVARCHAR (25)  NULL,
    [skladok7]                  NVARCHAR (16)  NULL,
    [skladok8]                  NVARCHAR (20)  NULL,
    [Data]                      DATETIME       NULL,
    [Vrach]                     INT            NULL,
    [MestoObrasheniya]          NVARCHAR (50)  NULL,
    [OtekiTEMP]                 NVARCHAR (50)  NULL,
    [F20TEMP]                   NVARCHAR (50)  NULL,
    [LimfouzliTEMP]             NVARCHAR (50)  NULL,
    [process1TEMP]              NVARCHAR (50)  NULL,
    [process2TEMP]              NVARCHAR (50)  NULL,
    [process4TEMP]              NVARCHAR (50)  NULL,
    [process3TEMP]              NVARCHAR (50)  NULL,
    [LechilsyaTEMP]             NVARCHAR (50)  NULL,
    [LNvidavalsyaTEMP]          NVARCHAR (50)  NULL,
    [LNestTEMP]                 NVARCHAR (50)  NULL,
    [FluorografTEMP]            NVARCHAR (50)  NULL,
    [DonorTEMP]                 NVARCHAR (50)  NULL,
    [tuberkulezTEMP]            NVARCHAR (20)  NULL,
    [TubUchetTEMP]              NVARCHAR (20)  NULL,
    [GepatitTEMP]               NVARCHAR (20)  NULL,
    [GepUchetTEMP]              NVARCHAR (20)  NULL,
    [VenTEMP]                   NVARCHAR (20)  NULL,
    [VenUchetTEMP]              NVARCHAR (20)  NULL,
    [NasledAnamnezTEMP]         NVARCHAR (20)  NULL,
    [EditBox1]                  NVARCHAR (50)  NULL,
    [EditBox2]                  NVARCHAR (50)  NULL,
    [EditBox3]                  NVARCHAR (50)  NULL,
    [KakNaprTEMP]               NVARCHAR (50)  NULL,
    [DinamikaZabolev]           NVARCHAR (50)  NULL,
    [RezAnaliz]                 NTEXT          NULL,
    [NomGospit]                 NVARCHAR (50)  NULL,
    [Zhalobi14]                 NVARCHAR (38)  NULL,
    [Kosmetolog]                NVARCHAR (20)  NULL,
    [Infektsionist]             NVARCHAR (20)  NULL,
    [Zhalobi15]                 NVARCHAR (35)  NULL,
    [VremyaSledYavki]           NVARCHAR (50)  NULL,
    [ZerkVidel1]                NVARCHAR (50)  NULL,
    [ZerkVidel2]                NVARCHAR (50)  NULL,
    [ZerkVisipSheika]           NVARCHAR (50)  NULL,
    [SheikaGiperemirovana]      NVARCHAR (14)  NULL,
    [sheikaOtechna]             NVARCHAR (6)   NULL,
    [SheikaVisipEroz]           NVARCHAR (65)  NULL,
    [SheikaVisipNet]            NVARCHAR (13)  NULL,
    [SheikaVidelSliz]           NVARCHAR (9)   NULL,
    [SheikaVidelGnoi]           NVARCHAR (7)   NULL,
    [NaruzhPolOrgRazvZhen]      NVARCHAR (50)  NULL,
    [NaruzhPolOrgRazvNeprZhen]  NTEXT          NULL,
    [NaruzhPolOrgRazv]          NVARCHAR (50)  NULL,
    [NaruzhPolOrgRazvNeprav]    NTEXT          NULL,
    [UretrSpok]                 NVARCHAR (9)   NULL,
    [UretrGiper]                NVARCHAR (14)  NULL,
    [UretrOtech]                NVARCHAR (6)   NULL,
    [UretrVidel1]               NVARCHAR (50)  NULL,
    [UretrVidel2]               NVARCHAR (50)  NULL,
    [UretrVidel]                NVARCHAR (50)  NULL,
    [GolovkaSpok]               NVARCHAR (10)  NULL,
    [GolovkaGiper]              NVARCHAR (15)  NULL,
    [GolovkaOtechna]            NVARCHAR (10)  NULL,
    [GolovkaMatserir]           NVARCHAR (15)  NULL,
    [NaletNaGolovke]            NVARCHAR (50)  NULL,
    [SledYavkaKab]              NVARCHAR (50)  NULL,
    [Fizioterapevt]             NVARCHAR (15)  NULL,
    [IsslSoka]                  NVARCHAR (25)  NULL,
    [SopDiagDict]               NVARCHAR (50)  NULL,
    [SopDiagCode]               NVARCHAR (6)   NULL,
    [Hirurg]                    NVARCHAR (10)  NULL,
    [VrachUzd]                  NVARCHAR (10)  NULL,
    [OtkazOtGosp]               NVARCHAR (30)  NULL,
    [PreparatRecept]            NTEXT          NULL,
    [Gonadotropin]              NVARCHAR (15)  NULL,
    [Kortizol]                  NVARCHAR (10)  NULL,
    [TiroksinT4]                NVARCHAR (15)  NULL,
    [DgeaS]                     NVARCHAR (10)  NULL,
    [Ssg]                       NVARCHAR (5)   NULL,
    [Ttg]                       NVARCHAR (5)   NULL,
    [Follikulostim]             NVARCHAR (20)  NULL,
    [Lyuteiniziruyush]          NVARCHAR (20)  NULL,
    [Prolaktin]                 NVARCHAR (10)  NULL,
    [Testosteron]               NVARCHAR (15)  NULL,
    [ObshiyBelok]               NVARCHAR (15)  NULL,
    [SReaktivniyBelok]          NVARCHAR (30)  NULL,
    [RevmotoidniyFaktor]        NVARCHAR (25)  NULL,
    [Mochevina]                 NVARCHAR (15)  NULL,
    [Kreatenin]                 NVARCHAR (15)  NULL,
    [MochevayaKislota]          NVARCHAR (20)  NULL,
    [BilirubinObshiy]           NVARCHAR (40)  NULL,
    [AstAlt]                    NVARCHAR (10)  NULL,
    [ShelochnayaFosfataza]      NVARCHAR (25)  NULL,
    [Ggpt]                      NVARCHAR (5)   NULL,
    [Holesterin]                NVARCHAR (15)  NULL,
    [Triglitseridi]             NVARCHAR (15)  NULL,
    [LpvpLpnp]                  NVARCHAR (15)  NULL,
    [Koprogramma]               NVARCHAR (15)  NULL,
    [IgEObshiy]                 NVARCHAR (15)  NULL,
    [LNnomer]                   NVARCHAR (50)  NULL,
    [LNdateS]                   DATETIME       NULL,
    [LNdatePo]                  DATETIME       NULL,
    [LgotRecept]                NTEXT          NULL,
    [SledYavkaKab1]             NVARCHAR (50)  NULL,
    [LNprodlenS]                DATETIME       NULL,
    [ReaktsiyaGregersena]       NVARCHAR (22)  NULL,
    [SoskobNaEnterobioz]        NVARCHAR (30)  NULL,
    [AnalizMochiNaPorfirini]    NVARCHAR (25)  NULL,
    [KrovNaSpid]                NVARCHAR (15)  NULL,
    [ImmunoblotSifilis]         NVARCHAR (30)  NULL,
    [CAC]                       NVARCHAR (1)   NULL,
    [F20]                       NVARCHAR (10)  NULL,
    CONSTRAINT [PovtorniyPriemVenerologaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PovtorniyPriemVenerologaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

