CREATE TABLE [dbo].[PovtorniyPriMEndokrinologa] (
    [ID]                       INT           NOT NULL,
    [PatID]                    INT           NULL,
    [PredvaritelniyDiagnoz]    NTEXT         NULL,
    [Data]                     DATETIME      NULL,
    [Vrach]                    NVARCHAR (50) NULL,
    [Teloslozhenie]            INT           NULL,
    [TonusMuskulaturi]         NVARCHAR (20) NULL,
    [Rost]                     INT           NULL,
    [Ves]                      INT           NULL,
    [VirazhPZhKletchatki]      NVARCHAR (20) NULL,
    [Vlazhnost]                NVARCHAR (20) NULL,
    [Oteki]                    NVARCHAR (20) NULL,
    [Turgor]                   NVARCHAR (20) NULL,
    [Pigmentatsiya]            NVARCHAR (20) NULL,
    [NervnoPsihicheskiyStatus] NVARCHAR (20) NULL,
    [OtekiLica]                NVARCHAR (1)  NULL,
    [Zabkost]                  NVARCHAR (1)  NULL,
    [SuhostKogi]               NVARCHAR (1)  NULL,
    [Zapori]                   NVARCHAR (1)  NULL,
    [sonlivost]                NVARCHAR (1)  NULL,
    [Libido]                   NVARCHAR (20) NULL,
    [VtorichniePolPriznaki]    INT           NULL,
    [Razmer]                   INT           NULL,
    [Konsistentsiya]           NVARCHAR (20) NULL,
    [Uzli]                     NVARCHAR (20) NULL,
    [Boleznennost]             NTEXT         NULL,
    [Tahicardia]               NVARCHAR (1)  NULL,
    [DrojanieRuk]              NVARCHAR (1)  NULL,
    [Ekzoftalm]                NVARCHAR (1)  NULL,
    [Grefe]                    NVARCHAR (1)  NULL,
    [DopolnitelnieDannie]      NTEXT         NULL,
    [Razmer1]                  INT           NULL,
    [Razmer2]                  INT           NULL,
    [ObsheeSostoyanie]         NTEXT         NULL,
    CONSTRAINT [PovtorniyPriMEndokrinologaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PovtorniyPriMEndokrinologaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

