CREATE TABLE [dbo].[PovtorniyPriMTerapevta] (
    [ID]                                           INT           NOT NULL,
    [PatID]                                        INT           NULL,
    [Rost]                                         INT           NULL,
    [Ves]                                          INT           NULL,
    [SostoyaniePatsienta]                          NVARCHAR (50) NULL,
    [Soznanie]                                     NVARCHAR (50) NULL,
    [Polozhenie]                                   NVARCHAR (50) NULL,
    [Emotsii]                                      NVARCHAR (50) NULL,
    [Osanka]                                       NVARCHAR (50) NULL,
    [Konstitutsiya]                                NVARCHAR (50) NULL,
    [VirazhenieLitsa]                              NVARCHAR (50) NULL,
    [Povedenie]                                    NVARCHAR (50) NULL,
    [Kozha]                                        NVARCHAR (50) NULL,
    [Kozha1]                                       NVARCHAR (50) NULL,
    [Kozha2]                                       NVARCHAR (50) NULL,
    [Kozha3]                                       NVARCHAR (50) NULL,
    [Kozha4]                                       NVARCHAR (50) NULL,
    [Nogti]                                        NVARCHAR (50) NULL,
    [Nogti1]                                       NVARCHAR (50) NULL,
    [Nogti2]                                       NVARCHAR (50) NULL,
    [Nogti3]                                       NVARCHAR (50) NULL,
    [VidimieSlizistie]                             NVARCHAR (50) NULL,
    [VidimieSlizistie1]                            NVARCHAR (50) NULL,
    [VidimieSlizistie2]                            NVARCHAR (50) NULL,
    [PzhkRazvita]                                  NVARCHAR (50) NULL,
    [Oteki]                                        NVARCHAR (50) NULL,
    [PreimushestvennoVOblasti]                     NTEXT         NULL,
    [VOblasti]                                     NTEXT         NULL,
    [VidimieSlizistie3]                            NTEXT         NULL,
    [UchastkiDepigmentatsii]                       NVARCHAR (50) NULL,
    [Rubtsi]                                       NVARCHAR (50) NULL,
    [Krovoizliyaniya]                              NVARCHAR (50) NULL,
    [SosudistieZvezdochki]                         NVARCHAR (50) NULL,
    [TroficheskieIzmeneniya]                       NVARCHAR (50) NULL,
    [Mindalini2]                                   NVARCHAR (35) NULL,
    [Dihanie2]                                     INT           NULL,
    [DihaniePrimechanie2]                          NTEXT         NULL,
    [Hripi3]                                       INT           NULL,
    [Hripi5]                                       INT           NULL,
    [Chdd]                                         NVARCHAR (50) NULL,
    [DihanieCherezNos]                             NVARCHAR (50) NULL,
    [RitmDihaniya]                                 NVARCHAR (50) NULL,
    [Kashel1]                                      NVARCHAR (1)  NULL,
    [Odishka1]                                     NVARCHAR (1)  NULL,
    [PatologicheskieIzmeneniya]                    NVARCHAR (50) NULL,
    [GrudnayaKletka]                               NVARCHAR (50) NULL,
    [PriPalpatsii]                                 NVARCHAR (50) NULL,
    [PriPalpatsii1]                                NVARCHAR (50) NULL,
    [HodReber]                                     NVARCHAR (50) NULL,
    [MezhreberniePromezhutki]                      NVARCHAR (50) NULL,
    [NadIPodklyuchichnieYamkiVirazheni]            NVARCHAR (50) NULL,
    [EpigastralniyUgolGrad]                        NVARCHAR (50) NULL,
    [GolosovoeDrozhanie]                           NVARCHAR (50) NULL,
    [GolosovoeDrozhanie1]                          NVARCHAR (50) NULL,
    [NadVseyPoverhnostyuLegkihSlishen]             NVARCHAR (50) NULL,
    [LegochniyZvuk]                                NVARCHAR (50) NULL,
    [OkologrudinnayaLiniya]                        NVARCHAR (50) NULL,
    [OkologrudinnayaLiniya1]                       NVARCHAR (50) NULL,
    [SredneklyuchichnayaLiniya]                    NVARCHAR (50) NULL,
    [PerednyayaPodmishechnayaLiniya]               NVARCHAR (50) NULL,
    [SrednyayaPodmishechnayaLiniya]                NVARCHAR (50) NULL,
    [ZadnyayaPodmishechnayaLiniya]                 NVARCHAR (50) NULL,
    [LopatochnayaLiniya]                           NVARCHAR (50) NULL,
    [OkolopozvonochnayaLiniya]                     NVARCHAR (50) NULL,
    [SredneklyuchichnayaLiniya1]                   NVARCHAR (50) NULL,
    [PerednyayaPodmishechnayaLiniya1]              NVARCHAR (50) NULL,
    [SrednyayaPodmishechnayaLiniya1]               NVARCHAR (50) NULL,
    [ZadnyayaPodmishechnayaLiniya1]                NVARCHAR (50) NULL,
    [LopatochnayaLiniya1]                          NVARCHAR (50) NULL,
    [OkolopozvonochnayaLiniya1]                    NVARCHAR (50) NULL,
    [Mindalini]                                    NVARCHAR (35) NULL,
    [Dihanie]                                      INT           NULL,
    [Hripi]                                        INT           NULL,
    [Hripi1]                                       INT           NULL,
    [DihaniePrimechanie]                           NTEXT         NULL,
    [Zev1]                                         NVARCHAR (33) NULL,
    [DopolnitelnieDannieDihanie]                   NTEXT         NULL,
    [Puls]                                         INT           NULL,
    [Defitsit]                                     INT           NULL,
    [Napryazhenie]                                 INT           NULL,
    [ToniSerdtsa]                                  INT           NULL,
    [GranitsiSerdtsa]                              INT           NULL,
    [VerhushechniyTolchok]                         INT           NULL,
    [Napolnenie]                                   INT           NULL,
    [NadSosudami]                                  NVARCHAR (35) NULL,
    [AktsentVtorogoTonaNadAortoy]                  INT           NULL,
    [NadLegochnoyArteriey]                         INT           NULL,
    [AdNaPravoyRuke]                               INT           NULL,
    [AdNaPravoyRuke1]                              INT           NULL,
    [Harakteristika]                               NVARCHAR (60) NULL,
    [ShumiSerdtsa]                                 NVARCHAR (33) NULL,
    [AdNaLevoyRuke]                                INT           NULL,
    [AdNaLevoyRuke1]                               INT           NULL,
    [DopolnitelnieDannieCCC]                       NTEXT         NULL,
    [PoseshenieNaDomu]                             INT           NULL,
    [KompleksniyOsmotr]                            NVARCHAR (1)  NULL,
    [NuzhdaetsyaVStatsionarnomLechenii]            NVARCHAR (1)  NULL,
    [NeobhodimaFlyuorografiya]                     NVARCHAR (1)  NULL,
    [Mindalini1]                                   NVARCHAR (35) NULL,
    [Dihanie1]                                     INT           NULL,
    [Hripi2]                                       INT           NULL,
    [Hripi11]                                      INT           NULL,
    [DihaniePrimechanie1]                          NTEXT         NULL,
    [Zev11]                                        NVARCHAR (33) NULL,
    [DopolnitelnieDannieDihanie1]                  NTEXT         NULL,
    [Puls1]                                        INT           NULL,
    [Defitsit1]                                    INT           NULL,
    [Napryazhenie1]                                INT           NULL,
    [ToniSerdtsa1]                                 INT           NULL,
    [GranitsiSerdtsa1]                             INT           NULL,
    [VerhushechniyTolchok1]                        INT           NULL,
    [Napolnenie1]                                  INT           NULL,
    [NadSosudami1]                                 NVARCHAR (35) NULL,
    [AktsentVtorogoTonaNadAortoy1]                 INT           NULL,
    [NadLegochnoyArteriey1]                        INT           NULL,
    [AdNaPravoyRuke2]                              INT           NULL,
    [AdNaPravoyRuke11]                             INT           NULL,
    [Harakteristika1]                              NVARCHAR (60) NULL,
    [ShumiSerdtsa1]                                NVARCHAR (33) NULL,
    [AdNaLevoyRuke2]                               INT           NULL,
    [AdNaLevoyRuke11]                              INT           NULL,
    [DopolnitelnieDannieCCC1]                      NTEXT         NULL,
    [PoseshenieNaDomu1]                            INT           NULL,
    [KompleksniyOsmotr1]                           NVARCHAR (1)  NULL,
    [NuzhdaetsyaVStatsionarnomLechenii1]           NVARCHAR (1)  NULL,
    [NeobhodimaFlyuorografiya1]                    NVARCHAR (1)  NULL,
    [Puls3]                                        INT           NULL,
    [Defitsit3]                                    INT           NULL,
    [Napryazhenie3]                                INT           NULL,
    [GranitsiSerdtsa3]                             INT           NULL,
    [ToniSerdtsa3]                                 INT           NULL,
    [VerhushechniyTolchok3]                        INT           NULL,
    [Napolnenie3]                                  INT           NULL,
    [AktsentVtorogoTonaNadAortoy3]                 INT           NULL,
    [NadSosudami3]                                 NVARCHAR (35) NULL,
    [NadLegochnoyArteriey3]                        INT           NULL,
    [ShumiSerdtsa2]                                NVARCHAR (50) NULL,
    [AdNaPravoyRuke4]                              INT           NULL,
    [NadLegochnoyArteriey21]                       INT           NULL,
    [AdNaPravoyRuke31]                             INT           NULL,
    [AdNaPravoyRuke121]                            INT           NULL,
    [Harakteristika21]                             NVARCHAR (60) NULL,
    [ShumiSerdtsa21]                               NVARCHAR (33) NULL,
    [AdNaLevoyRuke31]                              INT           NULL,
    [AdNaLevoyRuke121]                             INT           NULL,
    [DopolnitelnieDannieCCC21]                     NTEXT         NULL,
    [PoseshenieNaDomu21]                           INT           NULL,
    [KompleksniyOsmotr21]                          NVARCHAR (1)  NULL,
    [NuzhdaetsyaVStatsionarnomLechenii21]          NVARCHAR (1)  NULL,
    [NeobhodimaFlyuorografiya21]                   NVARCHAR (1)  NULL,
    [AdNaPravoyRuke13]                             INT           NULL,
    [AdNaLevoyRuke4]                               INT           NULL,
    [AdNaLevoyRuke13]                              INT           NULL,
    [Harakteristika3]                              NVARCHAR (60) NULL,
    [DopolnitelnieDannie]                          NTEXT         NULL,
    [Mindalini3]                                   NVARCHAR (35) NULL,
    [Zev13]                                        NVARCHAR (33) NULL,
    [Dihanie3]                                     INT           NULL,
    [DihaniePrimechanie3]                          NTEXT         NULL,
    [Hripi4]                                       INT           NULL,
    [Hripi13]                                      INT           NULL,
    [EditBox7]                                     NVARCHAR (50) NULL,
    [DictCombo52]                                  NVARCHAR (50) NULL,
    [DictCombo62]                                  NVARCHAR (50) NULL,
    [Kashel]                                       NVARCHAR (1)  NULL,
    [Odishka]                                      NVARCHAR (1)  NULL,
    [EditBox8]                                     NVARCHAR (50) NULL,
    [DictCombo72]                                  NVARCHAR (50) NULL,
    [DictCombo82]                                  NVARCHAR (50) NULL,
    [DictCombo92]                                  NVARCHAR (50) NULL,
    [DictCombo102]                                 NVARCHAR (50) NULL,
    [DictCombo112]                                 NVARCHAR (50) NULL,
    [DictCombo21]                                  NVARCHAR (50) NULL,
    [EditBox9]                                     NVARCHAR (50) NULL,
    [DictCombo31]                                  NVARCHAR (50) NULL,
    [DictCombo34]                                  NVARCHAR (50) NULL,
    [EditBox12]                                    NVARCHAR (50) NULL,
    [EditBox13]                                    NVARCHAR (50) NULL,
    [EditBox14]                                    NVARCHAR (50) NULL,
    [EditBox15]                                    NVARCHAR (50) NULL,
    [EditBox16]                                    NVARCHAR (50) NULL,
    [EditBox17]                                    NVARCHAR (50) NULL,
    [EditBox18]                                    NVARCHAR (50) NULL,
    [EditBox19]                                    NVARCHAR (50) NULL,
    [EditBox20]                                    NVARCHAR (50) NULL,
    [EditBox21]                                    NVARCHAR (50) NULL,
    [EditBox22]                                    NVARCHAR (50) NULL,
    [EditBox23]                                    NVARCHAR (50) NULL,
    [EditBox24]                                    NVARCHAR (50) NULL,
    [EditBox25]                                    NVARCHAR (50) NULL,
    [Zhivot]                                       NVARCHAR (50) NULL,
    [Zhivot1]                                      NVARCHAR (50) NULL,
    [Simmetrichen]                                 NVARCHAR (1)  NULL,
    [GrizhevieVipyachivaniya]                      NVARCHAR (1)  NULL,
    [PosleoperatsionnieRubtsi]                     NVARCHAR (1)  NULL,
    [Zhivot2]                                      NVARCHAR (50) NULL,
    [Zhivot3]                                      NVARCHAR (50) NULL,
    [PodkozhnayaVenoznayaSet]                      NVARCHAR (1)  NULL,
    [VidimayaPeristaltikaKishechnika]              NVARCHAR (1)  NULL,
    [Meteorizm]                                    NVARCHAR (1)  NULL,
    [PoverhnostnayaPalpatsiya]                     NVARCHAR (50) NULL,
    [PoverhnostnayaPalpatsiya1]                    NVARCHAR (50) NULL,
    [CheckBox1]                                    NVARCHAR (1)  NULL,
    [GrizhevieVipyachivaniya1]                     NVARCHAR (1)  NULL,
    [PoverhnostnayaPalpatsiya2]                    NVARCHAR (50) NULL,
    [SigmovidnayaKishka]                           NTEXT         NULL,
    [SlepayaKishka]                                NTEXT         NULL,
    [VoshodyashayaINishodyashayaObodochnayaKishka] NTEXT         NULL,
    [PoperechnoObodochnayaKishka]                  NTEXT         NULL,
    [PerkutornoNizhnyayaGranitsaNahoditsyaNa]      NVARCHAR (50) NULL,
    [Auskultativno]                                NVARCHAR (50) NULL,
    [ShumPleska]                                   NVARCHAR (1)  NULL,
    [ZonaShoffara]                                 NVARCHAR (50) NULL,
    [ZonaGubergritsa]                              NVARCHAR (50) NULL,
    [TochkaMeyoRobsona]                            NVARCHAR (50) NULL,
    [GranitsiPecheniPoKurlovu]                     NVARCHAR (50) NULL,
    [GranitsiPecheniPoKurlovu1]                    NVARCHAR (50) NULL,
    [GranitsiPecheniPoKurlovu2]                    NVARCHAR (50) NULL,
    [KrayPecheni]                                  NVARCHAR (50) NULL,
    [KrayPecheni1]                                 NVARCHAR (50) NULL,
    [SMKera]                                       NVARCHAR (1)  NULL,
    [SMMerfi]                                      NVARCHAR (1)  NULL,
    [SMPekarskogo]                                 NVARCHAR (1)  NULL,
    [FrenikusSimptom]                              NVARCHAR (1)  NULL,
    [Poperechnik]                                  NVARCHAR (50) NULL,
    [Dlinnik]                                      NVARCHAR (50) NULL,
    [Palpiruetsya]                                 NVARCHAR (1)  NULL,
    [SMKurvuaze]                                   NVARCHAR (1)  NULL,
    [IssledovanieSelezenki]                        NVARCHAR (50) NULL,
    [Mocheispuskanie]                              INT           NULL,
    [SMPasternatskogo]                             INT           NULL,
    [OblastPochekVneshne]                          NVARCHAR (50) NULL,
    [OblastPochekVneshne1]                         NVARCHAR (50) NULL,
    [Pochki]                                       NVARCHAR (50) NULL,
    [Pochki1]                                      NVARCHAR (50) NULL,
    [Mocheispuskanie1]                             NVARCHAR (50) NULL,
    [SMPokolachivaniya]                            NVARCHAR (50) NULL,
    [SMPokolachivaniya1]                           NVARCHAR (50) NULL,
    [SMPasternatskogo1]                            NVARCHAR (50) NULL,
    [BoliVnizuZhivota]                             NVARCHAR (50) NULL,
    [BoliVnizuZhivota1]                            NVARCHAR (50) NULL,
    [Videleniya]                                   NVARCHAR (50) NULL,
    [Videleniya1]                                  NVARCHAR (50) NULL,
    [MassaTelaZaPosledniyMesyats]                  NVARCHAR (50) NULL,
    [Kg]                                           NVARCHAR (50) NULL,
    [VipadenieVolos]                               NVARCHAR (1)  NULL,
    [LomkostNogtey]                                NVARCHAR (1)  NULL,
    [Potlivost]                                    NVARCHAR (50) NULL,
    [Potlivost1]                                   NVARCHAR (50) NULL,
    [Slabost]                                      NVARCHAR (50) NULL,
    [UsilivaetsyaPri]                              NVARCHAR (1)  NULL,
    [ProhoditPosle]                                NVARCHAR (1)  NULL,
    [Slabost2]                                     NVARCHAR (50) NULL,
    [NarusheniyaSna]                               NVARCHAR (1)  NULL,
    [Slabost3]                                     NVARCHAR (50) NULL,
    [GolovnieBoli]                                 NVARCHAR (50) NULL,
    [GolovnieBoli1]                                NVARCHAR (50) NULL,
    [ShumVUshah]                                   NVARCHAR (1)  NULL,
    [NarusheniyaZreniya]                           NVARCHAR (50) NULL,
    [NarusheniyaZreniya1]                          NTEXT         NULL,
    [DopolnitelnieDannie1]                         NTEXT         NULL,
    [Slabost1]                                     NVARCHAR (50) NULL,
    [MishtsiRazviti]                               NVARCHAR (50) NULL,
    [PriPalpatsii2]                                NVARCHAR (50) NULL,
    [DeformatsiiKostey]                            NVARCHAR (1)  NULL,
    [PriPalpatsii3]                                NVARCHAR (50) NULL,
    [DeformatsiiSustavov]                          NVARCHAR (1)  NULL,
    [ObemDvizheniyVSustavah]                       NVARCHAR (50) NULL,
    [ObemDvizheniyVSustavah1]                      NVARCHAR (50) NULL,
    [PriPalpatsii4]                                NVARCHAR (50) NULL,
    [Data]                                         DATETIME      NULL,
    [Vrach]                                        NVARCHAR (50) NULL,
    [PredvaritelniyDiagnoz]                        NTEXT         NULL,
    [PoseshenieNaDomu3]                            INT           NULL,
    [KompleksniyOsmotr3]                           NVARCHAR (1)  NULL,
    [NeobhodimaFlyuorografiya3]                    NVARCHAR (1)  NULL,
    [NuzhdaetsyaVStatsionarnomLechenii3]           NVARCHAR (1)  NULL,
    CONSTRAINT [PovtorniyPriMTerapevtaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PovtorniyPriMTerapevtaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

