CREATE TABLE [dbo].[PovtorniyPriMTravmatologaOrtopeda] (
    [ID]                         INT           NOT NULL,
    [PatID]                      INT           NULL,
    [Data]                       DATETIME      NULL,
    [Vrach]                      NVARCHAR (50) NULL,
    [Predvariteljnyj diagnoz]    NTEXT         NULL,
    [Teloslozhenie]              INT           NULL,
    [Ves]                        INT           NULL,
    [TemperaturaTela]            FLOAT (53)    NULL,
    [Kozha1]                     INT           NULL,
    [Sustavi]                    INT           NULL,
    [Boleznennost]               INT           NULL,
    [Konfiguratsiya]             INT           NULL,
    [Konfiguratsiya1]            NVARCHAR (45) NULL,
    [Ankiloz]                    NVARCHAR (1)  NULL,
    [Kontraktura]                NVARCHAR (1)  NULL,
    [DopolnitelnieDannie]        NTEXT         NULL,
    [PolozhenieBolnogo]          NVARCHAR (50) NULL,
    [PolozhenieBolnogo1]         NTEXT         NULL,
    [Gematomi2]                  NVARCHAR (1)  NULL,
    [Ssadini]                    NVARCHAR (1)  NULL,
    [Rani]                       NVARCHAR (1)  NULL,
    [Rani2]                      NVARCHAR (50) NULL,
    [EditBox1]                   NVARCHAR (50) NULL,
    [Ssadini2]                   NVARCHAR (50) NULL,
    [DeformatsiyaOsiKonechnosti] NTEXT         NULL,
    [PovrezhdennayaKonechnost]   NTEXT         NULL,
    [AmplitudaDvizheniy]         NTEXT         NULL,
    [Dlina]                      NVARCHAR (50) NULL,
    [Okruzhnost]                 NVARCHAR (50) NULL,
    [MishechnayaSila]            NVARCHAR (50) NULL,
    [Kozha]                      NVARCHAR (50) NULL,
    [Kozha2]                     NVARCHAR (50) NULL,
    CONSTRAINT [PovtorniyPriMTravmatologaOrtopedaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PovtorniyPriMTravmatologaOrtopedaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

