CREATE TABLE [dbo].[PovtorniyPriMKardiologa] (
    [ID]                          INT           NOT NULL,
    [PatID]                       INT           NULL,
    [Data]                        DATETIME      NULL,
    [Vrach]                       NVARCHAR (50) NULL,
    [PredvaritelniyDiagnoz]       NTEXT         NULL,
    [OkraskaKozhnihPokrovov]      INT           NULL,
    [Vlazhnost]                   INT           NULL,
    [Oteki]                       INT           NULL,
    [Oteki1]                      NVARCHAR (45) NULL,
    [LimfaticheskieUzli1]         NVARCHAR (45) NULL,
    [LimfaticheskieUzli]          INT           NULL,
    [Sustavi]                     INT           NULL,
    [Boleznennost]                INT           NULL,
    [Konfiguratsiya1]             NVARCHAR (45) NULL,
    [Konfiguratsiya]              INT           NULL,
    [Kontraktura]                 NVARCHAR (1)  NULL,
    [Ankiloz]                     NVARCHAR (1)  NULL,
    [Zev]                         NVARCHAR (33) NULL,
    [Mindalini]                   NVARCHAR (35) NULL,
    [Hripi]                       INT           NULL,
    [Hripi1]                      INT           NULL,
    [Dihanie]                     INT           NULL,
    [GranitsiSerdtsa]             INT           NULL,
    [Puls]                        INT           NULL,
    [Napolnenie]                  INT           NULL,
    [Napryazhenie]                INT           NULL,
    [ToniSerdtsa]                 INT           NULL,
    [VerhushechniyTolchok]        INT           NULL,
    [ShumiSerdtsa]                NVARCHAR (33) NULL,
    [NadSosudami]                 NVARCHAR (35) NULL,
    [AdNaLevoyRuke]               INT           NULL,
    [AdNaLevoyRuke1]              INT           NULL,
    [AdNaPravoyRuke]              INT           NULL,
    [AdNaPravoyRuke1]             INT           NULL,
    [RazmeriPecheniPoKurlovu]     FLOAT (53)    NULL,
    [Harakteristika]              NVARCHAR (60) NULL,
    [Selezenka]                   NVARCHAR (33) NULL,
    [Dopolnitelno]                NTEXT         NULL,
    [DihaniePrimechanie]          NTEXT         NULL,
    [AktsentVtorogoTonaNadAortoy] INT           NULL,
    [NadLegochnoyArteriey]        INT           NULL,
    [RazmeriPecheniPoKurlovu1]    FLOAT (53)    NULL,
    [RazmeriPecheniPoKurlovu2]    FLOAT (53)    NULL,
    [Defitsit]                    INT           NULL,
    [Mocheispuskanie]             INT           NULL,
    CONSTRAINT [PovtorniyPriMKardiologaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PovtorniyPriMKardiologaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

