CREATE TABLE [dbo].[PovtorniyPriMStomatologa] (
    [ID]                  INT           NOT NULL,
    [PatID]               INT           NULL,
    [Data]                DATETIME      NULL,
    [Vrach]               NVARCHAR (50) NULL,
    [VneshniyOsmor]       NTEXT         NULL,
    [VidimieSlizistie]    NVARCHAR (50) NULL,
    [Prikus]              NVARCHAR (20) NULL,
    [VerhiyRadR28]        NVARCHAR (3)  NULL,
    [VerhiyRadR27]        NVARCHAR (3)  NULL,
    [VerhiyRadR26]        NVARCHAR (3)  NULL,
    [VerhiyRadR25]        NVARCHAR (3)  NULL,
    [VerhiyRadR24]        NVARCHAR (3)  NULL,
    [VerhiyRadR23]        NVARCHAR (3)  NULL,
    [VerhiyRadR22]        NVARCHAR (3)  NULL,
    [VerhiyRadR21]        NVARCHAR (3)  NULL,
    [VerhiyRadL21]        NVARCHAR (3)  NULL,
    [VerhiyRadL22]        NVARCHAR (3)  NULL,
    [VerhiyRadL23]        NVARCHAR (3)  NULL,
    [VerhiyRadL24]        NVARCHAR (3)  NULL,
    [VerhiyRadL25]        NVARCHAR (3)  NULL,
    [VerhiyRadL26]        NVARCHAR (3)  NULL,
    [VerhiyRadL27]        NVARCHAR (3)  NULL,
    [VerhiyRadL28]        NVARCHAR (3)  NULL,
    [VerhiyRadL18]        NVARCHAR (3)  NULL,
    [VerhiyRadL17]        NVARCHAR (3)  NULL,
    [VerhiyRadL16]        NVARCHAR (3)  NULL,
    [VerhiyRadL15]        NVARCHAR (3)  NULL,
    [VerhiyRadL14]        NVARCHAR (3)  NULL,
    [VerhiyRadL13]        NVARCHAR (3)  NULL,
    [VerhiyRadL12]        NVARCHAR (3)  NULL,
    [VerhiyRadL11]        NVARCHAR (3)  NULL,
    [VerhiyRadR11]        NVARCHAR (3)  NULL,
    [VerhiyRadR12]        NVARCHAR (3)  NULL,
    [VerhiyRadR13]        NVARCHAR (3)  NULL,
    [VerhiyRadR14]        NVARCHAR (3)  NULL,
    [VerhiyRadR15]        NVARCHAR (3)  NULL,
    [VerhiyRadR16]        NVARCHAR (3)  NULL,
    [VerhiyRadR17]        NVARCHAR (3)  NULL,
    [VerhiyRadR18]        NVARCHAR (3)  NULL,
    [NijniyRadR18]        NVARCHAR (3)  NULL,
    [NijniyRadR28]        NVARCHAR (3)  NULL,
    [NijniyRadR17]        NVARCHAR (3)  NULL,
    [NijniyRadR27]        NVARCHAR (3)  NULL,
    [NijniyRadR16]        NVARCHAR (3)  NULL,
    [NijniyRadR26]        NVARCHAR (3)  NULL,
    [NijniyRadR15]        NVARCHAR (3)  NULL,
    [NijniyRadR25]        NVARCHAR (3)  NULL,
    [NijniyRadR14]        NVARCHAR (3)  NULL,
    [NijniyRadR24]        NVARCHAR (3)  NULL,
    [NijniyRadR13]        NVARCHAR (3)  NULL,
    [NijniyRadR23]        NVARCHAR (3)  NULL,
    [NijniyRadR12]        NVARCHAR (3)  NULL,
    [NijniyRadR22]        NVARCHAR (3)  NULL,
    [NijniyRadR11]        NVARCHAR (3)  NULL,
    [NijniyRadR21]        NVARCHAR (3)  NULL,
    [NijniyRadL11]        NVARCHAR (3)  NULL,
    [NijniyRadL12]        NVARCHAR (3)  NULL,
    [NijniyRadL21]        NVARCHAR (3)  NULL,
    [NijniyRadL22]        NVARCHAR (3)  NULL,
    [NijniyRadL24]        NVARCHAR (3)  NULL,
    [NijniyRadL23]        NVARCHAR (3)  NULL,
    [NijniyRadL13]        NVARCHAR (3)  NULL,
    [NijniyRadL14]        NVARCHAR (3)  NULL,
    [NijniyRadL15]        NVARCHAR (3)  NULL,
    [NijniyRadL25]        NVARCHAR (3)  NULL,
    [NijniyRadL16]        NVARCHAR (3)  NULL,
    [NijniyRadL26]        NVARCHAR (3)  NULL,
    [NijniyRadL17]        NVARCHAR (3)  NULL,
    [NijniyRadL27]        NVARCHAR (3)  NULL,
    [NijniyRadL18]        NVARCHAR (3)  NULL,
    [NijniyRadL28]        NVARCHAR (3)  NULL,
    [Rentgen]             NTEXT         NULL,
    [SanatsiyaPolostiRta] NVARCHAR (1)  NULL,
    [DiagDictCombo]       NVARCHAR (50) NULL,
    [DiagCode]            NVARCHAR (6)  NULL,
    [Recommendations]     NTEXT         NULL,
    [Zhalobi]             NTEXT         NULL,
    [Lechenie]            NTEXT         NULL,
    [TypeFormOsmotr]      NVARCHAR (50) NULL,
    CONSTRAINT [PovtorniyPriMStomatologaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PovtorniyPriMStomatologaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

