CREATE TABLE [dbo].[PovtorniyPriMOtorinolaringologa] (
    [ID]                               INT           NOT NULL,
    [PatID]                            INT           NULL,
    [Data]                             DATETIME      NULL,
    [Vrach]                            INT           NULL,
    [DopolnitelnieDannie]              NVARCHAR (45) NULL,
    [KamertonnoeIssledovanie]          NVARCHAR (45) NULL,
    [RazgovornayaRech]                 INT           NULL,
    [S]                                INT           NULL,
    [ShopotnayaRech1]                  INT           NULL,
    [ShopotnayaRech]                   INT           NULL,
    [BarabannayaPereponkaBezIzmeneniy] NVARCHAR (1)  NULL,
    [BarabannayaPereponka]             NVARCHAR (30) NULL,
    [SluhovoyProhod]                   NVARCHAR (30) NULL,
    [SluhovoyProhodBezIzmeneniy]       NVARCHAR (1)  NULL,
    [NaruzhnoeUhoBezIzmeneniy]         NVARCHAR (1)  NULL,
    [NaruzhnoeUho]                     NVARCHAR (30) NULL,
    [Gortan]                           NVARCHAR (30) NULL,
    [GortanBezIzmeneniy]               NVARCHAR (1)  NULL,
    [GolosovayaFTsiyaBezIzmeneniy]     NVARCHAR (1)  NULL,
    [GolosovayaFTsiya]                 NVARCHAR (30) NULL,
    [LimfaticheskieUzli]               NVARCHAR (30) NULL,
    [LimfaticheskieUzliBezIzmeneniy]   NVARCHAR (1)  NULL,
    [MindaliniDSBezIzmeneniy]          NVARCHAR (1)  NULL,
    [MindaliniDS]                      NVARCHAR (30) NULL,
    [Glotka]                           NVARCHAR (20) NULL,
    [GlotkaBezIzmeneniy]               NVARCHAR (1)  NULL,
    [Slizistaya]                       NVARCHAR (20) NULL,
    [DrugieObrazovaniya]               NVARCHAR (50) NULL,
    [NosoglotkaBezIzmeneniy]           NVARCHAR (1)  NULL,
    [Nosoglotka]                       NVARCHAR (30) NULL,
    [Adenoidi]                         INT           NULL,
    [NosovieRakovini]                  NVARCHAR (25) NULL,
    [NosovayaPeregorodka]              INT           NULL,
    [TsvetSlizistoy]                   NVARCHAR (20) NULL,
    [OtechnostSlizistoy]               NVARCHAR (1)  NULL,
    [Giperemia]                        NVARCHAR (1)  NULL,
    [Atrophia]                         NVARCHAR (1)  NULL,
    [Polipi]                           NVARCHAR (1)  NULL,
    [PolostNosa1]                      NVARCHAR (30) NULL,
    [PolostNosa]                       NVARCHAR (30) NULL,
    [NosovoeDihanie]                   NVARCHAR (30) NULL,
    [Zhalobi1]                         NTEXT         NULL,
    CONSTRAINT [PovtorniyPriMOtorinolaringologaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PovtorniyPriMOtorinolaringologaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

