CREATE TABLE [dbo].[PregnancyFlow] (
    [ID]                       INT            NOT NULL,
    [PatID]                    INT            NULL,
    [PatLastName]              NVARCHAR (250) NULL,
    [PatFirstName]             NVARCHAR (250) NULL,
    [PatSecondName]            NVARCHAR (250) NULL,
    [DocDate]                  DATETIME       NULL,
    [Weight]                   FLOAT (53)     NULL,
    [WeightDelta]              FLOAT (53)     NULL,
    [Complains]                NTEXT          NULL,
    [PresentState]             NTEXT          NULL,
    [Assignments]              NTEXT          NULL,
    [sist1]                    INT            NULL,
    [diast1]                   INT            NULL,
    [sist2]                    INT            NULL,
    [diast2]                   INT            NULL,
    [DSp]                      INT            NULL,
    [DCr]                      INT            NULL,
    [DTr]                      INT            NULL,
    [TazCExt]                  INT            NULL,
    [CDiag]                    INT            NULL,
    [TVera]                    INT            NULL,
    [OkruzhnostZhivotaSm]      FLOAT (53)     NULL,
    [VisotaDnaMatkiSm]         FLOAT (53)     NULL,
    [PolozheniePloda]          NVARCHAR (250) NULL,
    [SerdtsebieniePlodaMesto]  NVARCHAR (250) NULL,
    [Pozitsiya]                NVARCHAR (250) NULL,
    [ChisloUdarov]             INT            NULL,
    [PredlezhashayaChast]      NVARCHAR (250) NULL,
    [GdeNahoditsya]            NVARCHAR (250) NULL,
    [PolozheniePloda1]         NVARCHAR (50)  NULL,
    [WombTonus]                BIT            NULL,
    [Comment]                  NTEXT          NULL,
    [Doctor]                   INT            NULL,
    [Puls]                     INT            NULL,
    [PregnancyWeek]            INT            NULL,
    [FetusMove]                NVARCHAR (250) NULL,
    [DocNum]                   INT            NULL,
    [OtekiP]                   NVARCHAR (250) NULL,
    [WeightChange]             NVARCHAR (15)  NULL,
    [WombTonusTxt]             NVARCHAR (100) NULL,
    [Oteki]                    BIT            NULL,
    [NaruzhPolOrgany]          NVARCHAR (250) NULL,
    [Videleniya]               NVARCHAR (250) NULL,
    [SheikaMatki]              NVARCHAR (250) NULL,
    [TeloMatki]                NVARCHAR (250) NULL,
    [Pridatki]                 NVARCHAR (250) NULL,
    [Osobennosti]              NVARCHAR (250) NULL,
    [VaginaResearchProvodilos] BIT            NULL,
    [vidanS]                   DATETIME       NULL,
    [ProdlenS]                 DATETIME       NULL,
    [ZakritS]                  DATETIME       NULL,
    [VidanPo]                  DATETIME       NULL,
    [ProdlenPo]                DATETIME       NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PregnancyFlowToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

