CREATE TABLE [dbo].[PreparatiGR] (
    [№]        FLOAT (53)     NULL,
    [CFARG]    FLOAT (53)     NULL,
    [FNAMEFRG] NVARCHAR (255) NULL,
    [CMNN]     FLOAT (53)     NULL,
    [NAMEMNNR] NVARCHAR (255) NULL,
    [NOMKLS]   FLOAT (53)     NULL,
    [NAMEMED]  NVARCHAR (255) NULL,
    [DATEB]    NVARCHAR (255) NULL,
    [PRREG]    FLOAT (53)     NULL,
    [DATEBP]   NVARCHAR (255) NULL,
    [MSGTEXT]  NVARCHAR (255) NULL
);

