CREATE TABLE [dbo].[PriemTerapevtaNEW] (
    [ID]                        INT           NOT NULL,
    [PatID]                     INT           NULL,
    [Zhalobi]                   NTEXT         NULL,
    [PerenesennieZabolevaniya]  NTEXT         NULL,
    [Allergoanamnez]            NTEXT         NULL,
    [Nasledstvennost]           NTEXT         NULL,
    [ObektivnieDannie]          NTEXT         NULL,
    [Gemotransfuzii]            NTEXT         NULL,
    [IstoriyaBolezni]           NTEXT         NULL,
    [PredvaritelniyDiagnoz]     NTEXT         NULL,
    [Dieta]                     NTEXT         NULL,
    [MedikamentoznayaTerapiya]  NTEXT         NULL,
    [DopolnitelnieNaznacheniya] NTEXT         NULL,
    [BolnichniyListNomer]       NVARCHAR (50) NULL,
    [S]                         DATETIME      NULL,
    [Po]                        DATETIME      NULL,
    [PovtornayaYavka]           DATETIME      NULL,
    [Vremya]                    NVARCHAR (50) NULL,
    [KTrudu]                    DATETIME      NULL,
    [Primechaniya]              NTEXT         NULL,
    [DataOsmotra]               DATETIME      NULL,
    [Kurenie]                   NVARCHAR (1)  NULL,
    [Alkogol]                   NVARCHAR (1)  NULL,
    [Narkotiki]                 NVARCHAR (1)  NULL,
    [Rezhim]                    NVARCHAR (50) NULL,
    [DictCombo1]                NVARCHAR (50) NULL,
    CONSTRAINT [PriemTerapevtaNEWPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PriemTerapevtaNEWToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

