CREATE TABLE [dbo].[PriemVracha_Oftalmolog_instrumental_methods] (
    [ID]                       INT           NOT NULL,
    [PatID]                    INT           NULL,
    [MasterID]                 INT           NULL,
    [AnamnezZhizni1]           NTEXT         NULL,
    [AnamnezZhizni2]           NTEXT         NULL,
    [AnamnezZhizn]             NVARCHAR (50) NULL,
    [MKBName]                  NVARCHAR (50) NULL,
    [MKBCode]                  NVARCHAR (50) NULL,
    [travmimemo]               NTEXT         NULL,
    [Operatsii2]               NTEXT         NULL,
    [AnamnezZhizni]            NTEXT         NULL,
    [Image1]                   IMAGE         NULL,
    [spisok_rimsk3]            NVARCHAR (3)  NULL,
    [spisok_arabsk4]           NVARCHAR (1)  NULL,
    [spisok_arabsk5]           NVARCHAR (1)  NULL,
    [spisok_rimsk6]            NVARCHAR (3)  NULL,
    [spisok_arabsk7]           NVARCHAR (1)  NULL,
    [spisok_rimsk8]            NVARCHAR (3)  NULL,
    [spisok_rimsk9]            NVARCHAR (3)  NULL,
    [spisok_arabsk10]          NVARCHAR (1)  NULL,
    [Primechanie1]             NTEXT         NULL,
    [Image2]                   IMAGE         NULL,
    [spisok_rimsk4]            NVARCHAR (3)  NULL,
    [spisok_arabsk6]           NVARCHAR (1)  NULL,
    [spisok_rimsk7]            NVARCHAR (3)  NULL,
    [spisok_arabsk8]           NVARCHAR (1)  NULL,
    [spisok_rimsk10]           NVARCHAR (3)  NULL,
    [spisok_arabsk9]           NVARCHAR (1)  NULL,
    [spisok_rimsk11]           NVARCHAR (3)  NULL,
    [spisok_arabsk11]          NVARCHAR (1)  NULL,
    [Image3]                   IMAGE         NULL,
    [Primechanie2]             NTEXT         NULL,
    [Image4]                   IMAGE         NULL,
    [NizkayOstrotaZreniaOD1]   NVARCHAR (50) NULL,
    [NizkayOstrotaZreniaOS1]   NVARCHAR (50) NULL,
    [Primech1]                 NTEXT         NULL,
    [VisusSph_OD]              NVARCHAR (50) NULL,
    [PlusminusVisusOD1]        NVARCHAR (1)  NULL,
    [Visus_sph1]               NVARCHAR (50) NULL,
    [PlusminusVisusOD]         NVARCHAR (1)  NULL,
    [VisusCyl_OD]              NVARCHAR (50) NULL,
    [VisusAx_OD]               INT           NULL,
    [Gradus]                   NVARCHAR (50) NULL,
    [VisusSph_OS]              NVARCHAR (50) NULL,
    [PlusminusVisusOD2]        NVARCHAR (1)  NULL,
    [Visus_sph2]               NVARCHAR (50) NULL,
    [PlusminusVisusOS]         NVARCHAR (1)  NULL,
    [VisusCyl_OS]              NVARCHAR (50) NULL,
    [Visusax_OS]               INT           NULL,
    [Gradus1]                  NVARCHAR (50) NULL,
    [DK2D]                     FLOAT (53)    NULL,
    [AX2D]                     INT           NULL,
    [AX1D]                     INT           NULL,
    [DK1D]                     FLOAT (53)    NULL,
    [AX1S]                     INT           NULL,
    [DK1S]                     FLOAT (53)    NULL,
    [DK2S]                     FLOAT (53)    NULL,
    [AX2S]                     INT           NULL,
    [Primechanie]              NTEXT         NULL,
    [AutorefSph_OD11]          FLOAT (53)    NULL,
    [AutorefCyl_OD1]           FLOAT (53)    NULL,
    [AutorefAx_OD1]            NVARCHAR (50) NULL,
    [AutorefAx_OD2]            NVARCHAR (50) NULL,
    [AutorefCyl_OD2]           FLOAT (53)    NULL,
    [AutorefSph_OD12]          FLOAT (53)    NULL,
    [plusminusuzkizrachokOD]   NVARCHAR (50) NULL,
    [plusminuscycloplegeyaOD]  NVARCHAR (50) NULL,
    [plusminusuzkizrachokOD1]  NVARCHAR (50) NULL,
    [plusminusuzkizrachokOD2]  NVARCHAR (50) NULL,
    [AutorefAx_OD3]            NVARCHAR (50) NULL,
    [AutorefAx_OD4]            NVARCHAR (50) NULL,
    [AutorefCyl_OD3]           FLOAT (53)    NULL,
    [AutorefCyl_OD4]           FLOAT (53)    NULL,
    [plusminuscycloplegeyaOD1] NVARCHAR (50) NULL,
    [plusminusuzkizrachokOD3]  NVARCHAR (50) NULL,
    [AutorefSph_OD13]          FLOAT (53)    NULL,
    [AutorefSph_OD14]          FLOAT (53)    NULL,
    [plusminusuzkizrachokOD4]  NVARCHAR (50) NULL,
    [plusminusuzkizrachokOD5]  NVARCHAR (50) NULL,
    [Lab_Inst_obsl_memo]       NTEXT         NULL,
    [Rezim]                    NVARCHAR (50) NULL,
    [DataSledYavky]            DATETIME      NULL,
    [Dieta_Text]               NVARCHAR (80) NULL,
    [Vrach2]                   INT           NULL,
    [vidanS]                   DATETIME      NULL,
    [ProdlenS]                 DATETIME      NULL,
    [ZakritS]                  DATETIME      NULL,
    [VidanPo]                  DATETIME      NULL,
    [ProdlenPo]                DATETIME      NULL,
    [Zakluchenie_dlya_vipiski] NTEXT         NULL,
    CONSTRAINT [PriemVracha_Oftalmolog_instrumental_methodsPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PriemVracha_Oftalmolog_instrumental_methodsToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

