CREATE TABLE [dbo].[PriemVracha_Terapevt_Osmotr] (
    [ID]                     INT           NOT NULL,
    [PatID]                  INT           NULL,
    [ObemBDerITalii]         NVARCHAR (1)  NULL,
    [Konstitutsiya]          NVARCHAR (50) NULL,
    [Soznanie]               NVARCHAR (50) NULL,
    [obshsost]               NVARCHAR (50) NULL,
    [Rost]                   INT           NULL,
    [Ves]                    INT           NULL,
    [temperatura]            FLOAT (53)    NULL,
    [talia]                  INT           NULL,
    [bedra]                  INT           NULL,
    [Odnorodnost]            NVARCHAR (50) NULL,
    [Razmeri]                NVARCHAR (50) NULL,
    [Konsistentsiya]         NVARCHAR (50) NULL,
    [Boleznennost]           NVARCHAR (50) NULL,
    [ShitovidnayaZheleza]    BIT           NULL,
    [kozhnyepokrovy]         NVARCHAR (50) NULL,
    [strii]                  NVARCHAR (50) NULL,
    [striimemo]              NTEXT         NULL,
    [okraska]                NVARCHAR (50) NULL,
    [kozhnyepokrovymemo]     NTEXT         NULL,
    [turgor]                 NVARCHAR (50) NULL,
    [vlaznost]               NVARCHAR (50) NULL,
    [Pzhkletchatka]          NVARCHAR (50) NULL,
    [KozhniePokrovi]         NVARCHAR (1)  NULL,
    [LimfaticheskieUzli]     NVARCHAR (1)  NULL,
    [LimfaticheskieUzliMemo] NTEXT         NULL,
    CONSTRAINT [PriemVracha_Terapevt_OsmotrPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PriemVracha_Terapevt_OsmotrToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

