CREATE TABLE [dbo].[PriemVracha_Otolaringolog_Gortan] (
    [ID]                             INT           NOT NULL,
    [PatID]                          INT           NULL,
    [Golos]                          NVARCHAR (50) NULL,
    [SostoyanieSlizistoyObolochki]   NVARCHAR (50) NULL,
    [SmikaniePriFrontatsii]          NVARCHAR (50) NULL,
    [PodvizhnostPriDihanii]          NVARCHAR (50) NULL,
    [TonusGolosovihSkladok]          NVARCHAR (50) NULL,
    [SlizistayaObolochkaGortan]      NVARCHAR (50) NULL,
    [DihanieMemo]                    NTEXT         NULL,
    [GolosCvetcombo]                 NVARCHAR (50) NULL,
    [GolosMemo]                      NTEXT         NULL,
    [PredverieMemo]                  NTEXT         NULL,
    [GolosovieSkladkiMemo]           NTEXT         NULL,
    [SostoyanieSlizistoyMemo]        NTEXT         NULL,
    [SmikanieMemo]                   NTEXT         NULL,
    [TonusGolosovihSkladokMemo]      NTEXT         NULL,
    [SlizistayaobolochkaGortanMemo]  NTEXT         NULL,
    [OtdelyaemoeGortanMemo]          NTEXT         NULL,
    [PodskladochnoeprostranstvoMemo] NTEXT         NULL,
    [PodvizhnostpridihaniiMemo]      NTEXT         NULL,
    [Dihanie]                        NVARCHAR (50) NULL,
    [PodskladochnoeProstranstvo]     NVARCHAR (50) NULL,
    [OtdelyaemoeGortan]              NVARCHAR (50) NULL,
    [OtdelyaemoeGortancombo]         NVARCHAR (50) NULL,
    CONSTRAINT [PriemVracha_Otolaringolog_GortanPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PriemVracha_Otolaringolog_GortanToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

