CREATE TABLE [dbo].[PriemVracha_Newropatolog_CherepnieNervi] (
    [ID]                                                             INT           NOT NULL,
    [PatID]                                                          INT           NULL,
    [pervaja para]                                                   NVARCHAR (50) NULL,
    [zrenie]                                                         NVARCHAR (50) NULL,
    [gemianopsija]                                                   NVARCHAR (50) NULL,
    [vid_gemi]                                                       NTEXT         NULL,
    [Geteronimnaja]                                                  NVARCHAR (50) NULL,
    [ZritelnieGallyutsinatsii]                                       NVARCHAR (1)  NULL,
    [Cvet]                                                           NVARCHAR (50) NULL,
    [ProizvolnieDvizheniyaGlazVPolnomObeme]                          NVARCHAR (1)  NULL,
    [ParezVzora]                                                     NVARCHAR (1)  NULL,
    [Glaza]                                                          NVARCHAR (50) NULL,
    [Strabizm]                                                       NVARCHAR (50) NULL,
    [OkulotsefalicheskiyRefleks]                                     NVARCHAR (1)  NULL,
    [Ptoz]                                                           NVARCHAR (1)  NULL,
    [ZrachkiForma]                                                   NVARCHAR (50) NULL,
    [ZrachkiShirina]                                                 NVARCHAR (50) NULL,
    [soxr]                                                           NVARCHAR (50) NULL,
    [sprava_sleva]                                                   NTEXT         NULL,
    [foro_pr]                                                        NVARCHAR (50) NULL,
    [jivie]                                                          NVARCHAR (50) NULL,
    [sprava_sleva1]                                                  NTEXT         NULL,
    [LichoChustv]                                                    NVARCHAR (50) NULL,
    [I]                                                              NVARCHAR (1)  NULL,
    [II]                                                             NVARCHAR (1)  NULL,
    [III]                                                            NVARCHAR (1)  NULL,
    [vetvi]                                                          NVARCHAR (50) NULL,
    [zelder]                                                         NVARCHAR (50) NULL,
    [skobki_Z]                                                       NTEXT         NULL,
    [Jvatel_p]                                                       NVARCHAR (50) NULL,
    [Jvatel]                                                         NTEXT         NULL,
    [lico_ass]                                                       NVARCHAR (50) NULL,
    [lico_assim]                                                     NTEXT         NULL,
    [parys]                                                          NVARCHAR (50) NULL,
    [parez]                                                          NVARCHAR (50) NULL,
    [mim_s_s]                                                        NTEXT         NULL,
    [Lakrimacia]                                                     NVARCHAR (50) NULL,
    [NarushenieVkusaNaPerednih23Yazika]                              NVARCHAR (1)  NULL,
    [Giperakuziya]                                                   NVARCHAR (1)  NULL,
    [slux_1]                                                         NVARCHAR (50) NULL,
    [slux]                                                           NTEXT         NULL,
    [VestibulSindrom]                                                NVARCHAR (50) NULL,
    [PorezNeba]                                                      NVARCHAR (50) NULL,
    [GlotochniiRefleks]                                              NVARCHAR (50) NULL,
    [UvulaPoSredneyLiniiOtklonena]                                   NVARCHAR (1)  NULL,
    [Glotanie]                                                       NVARCHAR (50) NULL,
    [PolozenieGolovi]                                                NVARCHAR (50) NULL,
    [ProizvolnieDvizheniyaGoloviIMishtsPlechevogoPoyasaOgranichenni] NVARCHAR (1)  NULL,
    [Jazik]                                                          NVARCHAR (50) NULL,
    CONSTRAINT [PriemVracha_Newropatolog_CherepnieNerviPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PriemVracha_Newropatolog_CherepnieNerviToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

