CREATE TABLE [dbo].[PriemVracha_Otolaringolog_Nos] (
    [ID]                            INT           NOT NULL,
    [PatID]                         INT           NULL,
    [UstyaSluhovihTrubCombo]        NVARCHAR (50) NULL,
    [Obonyanie]                     NVARCHAR (50) NULL,
    [NosovoeDihanie]                NVARCHAR (50) NULL,
    [PreddverieNosa]                NVARCHAR (50) NULL,
    [nosaperegorodka]               NVARCHAR (50) NULL,
    [osovierakovini]                NVARCHAR (50) NULL,
    [nosoviehodicheck]              NVARCHAR (1)  NULL,
    [Slizistaya]                    NVARCHAR (50) NULL,
    [Otdelaemoe]                    NVARCHAR (50) NULL,
    [SvodNosoglotki]                NVARCHAR (50) NULL,
    [UtolsheniZadnieKontsi]         NVARCHAR (1)  NULL,
    [UtolsheniTubarnieValiki]       NVARCHAR (1)  NULL,
    [NosovieRakovini]               NTEXT         NULL,
    [PeregorodkaNosa]               NTEXT         NULL,
    [PreddverieNosaMemo]            NTEXT         NULL,
    [NaruzhniyNosMemo]              NTEXT         NULL,
    [NosovoeDihanieMemo]            NTEXT         NULL,
    [Obonyaniememo]                 NTEXT         NULL,
    [Otdelyaemoe]                   NTEXT         NULL,
    [SlizistayaObolochka]           NTEXT         NULL,
    [UstyaSluhovihTrub]             NTEXT         NULL,
    [NosoglodkaZadnyayaRinoskopiya] NTEXT         NULL,
    [NosovieHodi]                   NTEXT         NULL,
    [NaruzhniyNos]                  NVARCHAR (1)  NULL,
    [SformirovanPravilno]           NVARCHAR (1)  NULL,
    CONSTRAINT [PriemVracha_Otolaringolog_NosPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PriemVracha_Otolaringolog_NosToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

