CREATE TABLE [dbo].[PriemVracha_Otolaringolog_SluhovoyPassport] (
    [ID]                INT            NOT NULL,
    [PatID]             INT            NULL,
    [Shum]              NVARCHAR (200) NULL,
    [Shum1]             NVARCHAR (200) NULL,
    [ShepotnayaRech1]   NVARCHAR (200) NULL,
    [RazgovornayaRech1] NVARCHAR (200) NULL,
    [GromkayaRech1]     NVARCHAR (200) NULL,
    [GromkayaRech]      NVARCHAR (200) NULL,
    [RazgovornayaRech]  NVARCHAR (200) NULL,
    [ShepotnayaRech]    NVARCHAR (200) NULL,
    [OpitVeberaW]       NVARCHAR (50)  NULL,
    [OpitVeberaW1]      NVARCHAR (50)  NULL,
    [OpitRinneR1]       NVARCHAR (50)  NULL,
    [OpitRinneR]        NVARCHAR (50)  NULL,
    [OpitFedericheF]    NVARCHAR (50)  NULL,
    [OpitZheleG]        NVARCHAR (50)  NULL,
    [OpitZheleG1]       NVARCHAR (50)  NULL,
    [OpitFedericheF1]   NVARCHAR (50)  NULL,
    [Vozdushnaya3]      NVARCHAR (50)  NULL,
    [Vozdushnaya2]      NVARCHAR (50)  NULL,
    [Kostnaya2]         NVARCHAR (50)  NULL,
    [EditBox7]          NVARCHAR (50)  NULL,
    [Kostnaya1]         NVARCHAR (50)  NULL,
    [Vozdushnaya1]      NVARCHAR (50)  NULL,
    [Kostnaya]          NVARCHAR (50)  NULL,
    [Vozdushnaya]       NVARCHAR (50)  NULL,
    CONSTRAINT [PriemVracha_Otolaringolog_SluhovoyPassportPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PriemVracha_Otolaringolog_SluhovoyPassportToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

