CREATE TABLE [dbo].[PriemVracha_AkusheraGinekologa_GinekologAnamnes] (
    [ID]                      INT           NOT NULL,
    [PatID]                   INT           NULL,
    [MenarheS]                INT           NULL,
    [MenarheUstan]            NVARCHAR (5)  NULL,
    [RegulyarniyCherez]       NVARCHAR (80) NULL,
    [bezbolez]                NVARCHAR (50) NULL,
    [regul]                   NVARCHAR (50) NULL,
    [umeren]                  NVARCHAR (50) NULL,
    [MenstrCherez]            NVARCHAR (50) NULL,
    [Menstr]                  NVARCHAR (50) NULL,
    [NachaloPolovoyZhizniS]   INT           NULL,
    [Rodov]                   INT           NULL,
    [Beremennostey1]          INT           NULL,
    [Vikidishey]              INT           NULL,
    [MedAbortov]              INT           NULL,
    [Kontracepciya]           NTEXT         NULL,
    [cbKontracepciya]         NVARCHAR (1)  NULL,
    [RodovOslozhneniya]       NTEXT         NULL,
    [MedAbortovOslozhneniya]  NTEXT         NULL,
    [VikidisheyOslozhneniya]  NTEXT         NULL,
    [Regularnaya]             NVARCHAR (50) NULL,
    [VBrake]                  NVARCHAR (1)  NULL,
    [VneBraka]                NVARCHAR (1)  NULL,
    [VneBrakaComment]         NVARCHAR (50) NULL,
    [NastoyashayaBeremennost] NVARCHAR (1)  NULL,
    [chislorodov]             NVARCHAR (50) NULL,
    [Chisloabortov]           NVARCHAR (50) NULL,
    [Chislovikidishey]        NVARCHAR (50) NULL,
    [LastMenstrStart]         DATETIME      NULL,
    [LastMenstrFinish]        DATETIME      NULL,
    CONSTRAINT [PriemVracha_AkusheraGinekologa_GinekologAnamnesPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PriemVracha_AkusheraGinekologa_GinekologAnamnesToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

