CREATE TABLE [dbo].[PriemVracha_Newropatolog_ObshemozgovieSimptomi] (
    [ID]                                     INT           NOT NULL,
    [PatID]                                  INT           NULL,
    [pamat]                                  NVARCHAR (50) NULL,
    [Povedenie]                              NVARCHAR (50) NULL,
    [Vnimanie]                               NVARCHAR (50) NULL,
    [Soznanie]                               NVARCHAR (50) NULL,
    [OrientatsiyaVMeste]                     NVARCHAR (1)  NULL,
    [GolovnayaBol]                           NVARCHAR (1)  NULL,
    [localizachija]                          NTEXT         NULL,
    [harakter]                               NTEXT         NULL,
    [periodichnost]                          NTEXT         NULL,
    [vremasytok]                             NTEXT         NULL,
    [Simtomi]                                NTEXT         NULL,
    [NesistemnoeGolovokruzhenie]             NVARCHAR (1)  NULL,
    [Toshnota]                               NVARCHAR (1)  NULL,
    [Rvota]                                  NVARCHAR (1)  NULL,
    [ObshesudorozhniePripadki]               NVARCHAR (1)  NULL,
    [simpBrudzinskogo]                       NVARCHAR (50) NULL,
    [RegidnostMishzShei]                     NVARCHAR (50) NULL,
    [SimpKerniga]                            NVARCHAR (50) NULL,
    [SkylSimpMondonezi]                      NVARCHAR (50) NULL,
    [Fotofobiya]                             NVARCHAR (1)  NULL,
    [GiperesteziyaKozhnihPokrovovISlizistih] NVARCHAR (1)  NULL,
    [OrientatsiyaVoVremeni]                  NVARCHAR (1)  NULL,
    [OrientatsiyaSobstvennoyLichnosti]       NVARCHAR (1)  NULL,
    [DostupnostKRechevomuKontaktu]           NVARCHAR (1)  NULL,
    [Fonofobiya]                             NVARCHAR (1)  NULL,
    CONSTRAINT [PriemVracha_Newropatolog_ObshemozgovieSimptomiPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PriemVracha_Newropatolog_ObshemozgovieSimptomiToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

