CREATE TABLE [dbo].[PriemVracha_Otolaringolog_Ushi] (
    [ID]                                          INT           NOT NULL,
    [PatID]                                       INT           NULL,
    [ADNaruzhniySluhovoyProhodcombo]              NVARCHAR (50) NULL,
    [ADKozhacombo]                                NVARCHAR (50) NULL,
    [ADOtdelyaemoecombo]                          NVARCHAR (50) NULL,
    [ADTsvetVidcombo]                             NVARCHAR (50) NULL,
    [ADPalpatsiyaPerkussiyaSostsevidnogoOtrostka] NTEXT         NULL,
    [ADPalpatsiyaKozelka]                         NTEXT         NULL,
    [ADUshnayaRakovinamemo]                       NTEXT         NULL,
    [ADNaruzhniySluhovoyProhodmemo]               NTEXT         NULL,
    [ADKozhamemo]                                 NTEXT         NULL,
    [ADOtdelyaemoememo]                           NTEXT         NULL,
    [ADBarabannayaPereponkamemo]                  NTEXT         NULL,
    [ADTsvetVidmemo]                              NTEXT         NULL,
    [ADOpoznavatelnieZnakimemo]                   NTEXT         NULL,
    [ADTselostnostmemo]                           NTEXT         NULL,
    [ASNaruzhniySluhovoyProhodcombo]              NVARCHAR (50) NULL,
    [ASKozhacombo]                                NVARCHAR (50) NULL,
    [ASOtdelyaemoecombo]                          NVARCHAR (50) NULL,
    [ASTsvetVidcombo]                             NVARCHAR (50) NULL,
    [ASPalpatsiyaPerkussiyaSostsevidnogoOtrostka] NTEXT         NULL,
    [ASPalpatsiyaKozelka]                         NTEXT         NULL,
    [ASUshnayaRakovinamemo]                       NTEXT         NULL,
    [ASNaruzhniySluhovoyProhodmemo]               NTEXT         NULL,
    [ASKozhamemo]                                 NTEXT         NULL,
    [ASOtdelyaemoememo]                           NTEXT         NULL,
    [ASBarabannayaPereponkamemo]                  NTEXT         NULL,
    [ASTsvetVidmemo]                              NTEXT         NULL,
    [ASOpoznavatelnieZnakimemo]                   NTEXT         NULL,
    [ASTselostnostmemo]                           NTEXT         NULL,
    CONSTRAINT [PriemVracha_Otolaringolog_UshiPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PriemVracha_Otolaringolog_UshiToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

