CREATE TABLE [dbo].[PriemVracha_SosudistiyHirurg] (
    [ID]                      INT           NOT NULL,
    [PatID]                   INT           NULL,
    [Jaloby]                  NTEXT         NULL,
    [AnamnezZab]              NTEXT         NULL,
    [AnamnezOb]               NTEXT         NULL,
    [AnamnezAller]            NTEXT         NULL,
    [Alcogol]                 NVARCHAR (50) NULL,
    [Kurenie]                 NVARCHAR (50) NULL,
    [UpotreblenieNarkotikov]  NVARCHAR (50) NULL,
    [SmokeYears]              INT           NULL,
    [SmokePerDay]             INT           NULL,
    [Sostoyanie]              NVARCHAR (50) NULL,
    [Okraska]                 NVARCHAR (50) NULL,
    [Soznanie]                NVARCHAR (50) NULL,
    [GrubOchNevrologSimptom]  NVARCHAR (50) NULL,
    [Pitanie]                 NVARCHAR (50) NULL,
    [Teloslozhenie]           NVARCHAR (50) NULL,
    [Pravilnoe]               NVARCHAR (1)  NULL,
    [FizRazvitie]             NVARCHAR (50) NULL,
    [UvelicheniUzli]          NVARCHAR (1)  NULL,
    [UvelicheniJeleza]        NVARCHAR (1)  NULL,
    [LimfaticheskieUzly]      NVARCHAR (50) NULL,
    [LimfUzPriPalpacii]       NVARCHAR (50) NULL,
    [ShitovidnayaJeleza]      NVARCHAR (50) NULL,
    [ShitJelPriPalpacii]      NVARCHAR (50) NULL,
    [Akrotsianoz]             NVARCHAR (1)  NULL,
    [KostnoMyshSystem]        NTEXT         NULL,
    [DvizheniyVSustavahDop]   NVARCHAR (50) NULL,
    [DvijenyVPozvonoch]       NVARCHAR (50) NULL,
    [DvijeniyVSustavah]       NVARCHAR (50) NULL,
    [DvijenyVPozvonochDop]    NVARCHAR (50) NULL,
    [DihanieCherezNos]        NVARCHAR (50) NULL,
    [FormaGrudKletki]         NVARCHAR (50) NULL,
    [GrudKletkiVakteDihaniya] NVARCHAR (50) NULL,
    [CHDD]                    INT           NULL,
    [PerkutornZvuk]           NVARCHAR (50) NULL,
    [AuskultaciyaDihaniya]    NVARCHAR (50) NULL,
    [ToniSerdtsa1]            NVARCHAR (50) NULL,
    [Puls1]                   INT           NULL,
    [AdNaLevoyRuke2]          INT           NULL,
    [AdNaLevoyRuke3]          INT           NULL,
    [AdNaPravoyRuke2]         INT           NULL,
    [AdNaPravoyRuke3]         INT           NULL,
    [OblastSerdcaIshei]       NVARCHAR (50) NULL,
    [NadSosudami]             NVARCHAR (50) NULL,
    [Appetit]                 NVARCHAR (50) NULL,
    [Yazik2]                  NVARCHAR (50) NULL,
    [Yazik1]                  NVARCHAR (50) NULL,
    [Stul]                    NVARCHAR (50) NULL,
    [StulDop]                 NTEXT         NULL,
    [Jivot]                   NVARCHAR (50) NULL,
    [JivotPriPalpacii]        NVARCHAR (50) NULL,
    [Boleznenno]              NVARCHAR (1)  NULL,
    [Glotanie]                NVARCHAR (50) NULL,
    [CheckBox2]               NVARCHAR (1)  NULL,
    [CheckBox3]               NVARCHAR (1)  NULL,
    [CheckBox4]               NVARCHAR (1)  NULL,
    [CheckBox5]               NVARCHAR (1)  NULL,
    [CheckBox6]               NVARCHAR (1)  NULL,
    [CheckBox7]               NVARCHAR (1)  NULL,
    [CheckBox8]               NVARCHAR (1)  NULL,
    [CheckBox9]               NVARCHAR (1)  NULL,
    [CheckBox10]              NVARCHAR (1)  NULL,
    [CheckBox11]              NVARCHAR (1)  NULL,
    [CheckBox12]              NVARCHAR (1)  NULL,
    [CheckBox13]              NVARCHAR (1)  NULL,
    [CheckBox14]              NVARCHAR (1)  NULL,
    [CheckBox1]               NVARCHAR (1)  NULL,
    [CheckBox15]              NVARCHAR (1)  NULL,
    [CheckBox16]              NVARCHAR (1)  NULL,
    [CheckBox17]              NVARCHAR (1)  NULL,
    [CheckBox18]              NVARCHAR (1)  NULL,
    [CheckBox19]              NVARCHAR (1)  NULL,
    [CheckBox20]              NVARCHAR (1)  NULL,
    [CheckBox21]              NVARCHAR (1)  NULL,
    [CheckBox22]              NVARCHAR (1)  NULL,
    [CheckBox23]              NVARCHAR (1)  NULL,
    [CheckBox24]              NVARCHAR (1)  NULL,
    [CheckBox25]              NVARCHAR (1)  NULL,
    [CheckBox26]              NVARCHAR (1)  NULL,
    [CheckBox27]              NVARCHAR (1)  NULL,
    [CheckBox28]              NVARCHAR (1)  NULL,
    [KojnayaTamperatura]      NTEXT         NULL,
    [CvetKojnihPokrovov]      NTEXT         NULL,
    [TroficheskieIzmeneniya]  NTEXT         NULL,
    [OtyokiNog]               NTEXT         NULL,
    [PlanObsledovaniya]       NTEXT         NULL,
    [Vrach2]                  INT           NULL,
    [Data]                    DATETIME      NULL,
    [DocTime]                 DATETIME      NULL,
    [PokolachPoPoyasOblasti]  NVARCHAR (50) NULL,
    [MochitsyaSamostoyatelno] NVARCHAR (1)  NULL,
    [Rekomendovano]           NTEXT         NULL,
    [LekarstTerapiya]         NTEXT         NULL,
    [Image1]                  IMAGE         NULL,
    CONSTRAINT [PriemVracha_SosudistiyHirurgPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PriemVracha_SosudistiyHirurgToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

