CREATE TABLE [dbo].[ProfosmotrGinekolog] (
    [ID]                                                      INT            NOT NULL,
    [PatID]                                                   INT            NULL,
    [Zaklyuchenie]                                            NVARCHAR (100) NULL,
    [Kommentrariy]                                            NTEXT          NULL,
    [Data]                                                    DATETIME       NULL,
    [Vrach]                                                   INT            NULL,
    [Zhalobi1]                                                NTEXT          NULL,
    [Pm]                                                      NVARCHAR (50)  NULL,
    [MetodPredoxraneniy]                                      NVARCHAR (50)  NULL,
    [MetodPredoxraneniy2]                                     NVARCHAR (50)  NULL,
    [GinekologiceskieZabolevaniy]                             NVARCHAR (50)  NULL,
    [Zhivot]                                                  NVARCHAR (50)  NULL,
    [Zhivot2]                                                 NVARCHAR (50)  NULL,
    [DopDanie]                                                NVARCHAR (50)  NULL,
    [MolocnieZhelezi]                                         NVARCHAR (50)  NULL,
    [NaruzhniePolovieOrganiRazvitiPravilno]                   NVARCHAR (1)   NULL,
    [NaruzhniePolovieOrganiRazvitiPravilno2]                  NVARCHAR (50)  NULL,
    [SheikaMatki]                                             NVARCHAR (50)  NULL,
    [SheikaMatki2]                                            NVARCHAR (50)  NULL,
    [VideleniyIzkanala]                                       NVARCHAR (50)  NULL,
    [VideleniyIzkanala2]                                      NVARCHAR (50)  NULL,
    [VideleniyIzkanala3]                                      NVARCHAR (50)  NULL,
    [SlizistayaSheykaMatkiBezNarusheniyaEpitelialnogoPokrova] NVARCHAR (1)   NULL,
    [SlizistayaSheykaMatkiBezNarusheniya2]                    NVARCHAR (50)  NULL,
    [SlizistayVlagaliha]                                      NVARCHAR (50)  NULL,
    [SlizistayVlagaliha2]                                     NVARCHAR (50)  NULL,
    [SlizistayVlagaliha3]                                     NVARCHAR (50)  NULL,
    [Vlagalishe]                                              NVARCHAR (50)  NULL,
    [Matka]                                                   NVARCHAR (50)  NULL,
    [Matka2]                                                  NVARCHAR (50)  NULL,
    [Matka3]                                                  NVARCHAR (50)  NULL,
    [Matka4]                                                  NVARCHAR (50)  NULL,
    [Konturi]                                                 NVARCHAR (50)  NULL,
    [KonturiNormalnihRazmerov]                                NVARCHAR (1)   NULL,
    [Yvelicenado]                                             INT            NULL,
    [PridatkiSpravo]                                          NVARCHAR (50)  NULL,
    [PridatkiSpravo2]                                         NVARCHAR (50)  NULL,
    [PridatkiSpravo3]                                         NVARCHAR (50)  NULL,
    [PridatkiSpravo4]                                         INT            NULL,
    [PridatkiSlevo]                                           NVARCHAR (50)  NULL,
    [PridatkiSlevo2]                                          NVARCHAR (50)  NULL,
    [PridatkiSlevo3]                                          NVARCHAR (50)  NULL,
    [PridatkiSlevo4]                                          INT            NULL,
    [Svodi]                                                   NVARCHAR (50)  NULL,
    [Svodi2]                                                  NVARCHAR (50)  NULL,
    [DopObrazovaniyVmalomTazu]                                NVARCHAR (100) NULL,
    [GruppaD]                                                 NVARCHAR (2)   NULL,
    [Vievleno]                                                NVARCHAR (10)  NULL,
    [DiagnozPoMkb10]                                          NVARCHAR (80)  NULL,
    [KodPoMkb10]                                              NVARCHAR (10)  NULL,
    [Recommendation]                                          NTEXT          NULL,
    CONSTRAINT [ProfosmotrGinekologPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [ProfosmotrGinekologToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

