CREATE TABLE [dbo].[ProfosmotrTerapevt] (
    [ID]                   INT            NOT NULL,
    [PatID]                INT            NULL,
    [Zaklyuchenie]         NVARCHAR (100) NULL,
    [Kommentrariy]         NTEXT          NULL,
    [Data]                 DATETIME       NULL,
    [Vrach]                INT            NULL,
    [Zhalobi2]             NTEXT          NULL,
    [AnamnezZabolevaniya1] NTEXT          NULL,
    [KozhniePocrovi]       NVARCHAR (50)  NULL,
    [KozhniePocrovi2]      NVARCHAR (50)  NULL,
    [Sustavi]              NVARCHAR (50)  NULL,
    [Sustavi2]             NVARCHAR (50)  NULL,
    [Zev]                  NVARCHAR (50)  NULL,
    [Mindalini4]           NVARCHAR (50)  NULL,
    [Dixanie]              NVARCHAR (50)  NULL,
    [Xripi]                NVARCHAR (50)  NULL,
    [PretuplenieZvuka]     NVARCHAR (50)  NULL,
    [ToniSerdca]           NVARCHAR (50)  NULL,
    [Akcent2]              NVARCHAR (50)  NULL,
    [Shum]                 NVARCHAR (50)  NULL,
    [Puls2]                INT            NULL,
    [Puls4]                NVARCHAR (50)  NULL,
    [Yzik]                 NVARCHAR (50)  NULL,
    [ZhivotPriPalpaci3]    NVARCHAR (51)  NULL,
    [ZhivotPriPalpacii4]   NVARCHAR (50)  NULL,
    [NePalpiruetsya]       NVARCHAR (1)   NULL,
    [PechenVistupaet]      FLOAT (53)     NULL,
    [krai]                 NVARCHAR (50)  NULL,
    [Stul]                 NVARCHAR (50)  NULL,
    [Moceispuskanie]       NVARCHAR (50)  NULL,
    [DopDanie]             NTEXT          NULL,
    [GruppaD]              NVARCHAR (2)   NULL,
    [Vievleno]             NVARCHAR (10)  NULL,
    [LimfoticeskieUzli]    NVARCHAR (50)  NULL,
    [Akcent]               NVARCHAR (50)  NULL,
    [ZhivotPriPalpaci]     NVARCHAR (50)  NULL,
    [AdSist1]              INT            NULL,
    [AdDiast1]             INT            NULL,
    [DiagnozPoMkb10]       NVARCHAR (80)  NULL,
    [KodPoMkb10]           NVARCHAR (10)  NULL,
    [Recommendation]       NTEXT          NULL,
    CONSTRAINT [ProfosmotrTerapevtPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [ProfosmotrTerapevtToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

