CREATE TABLE [dbo].[ProfosmotrHirurg] (
    [ID]                      INT            NOT NULL,
    [PatID]                   INT            NULL,
    [Data]                    DATETIME       NULL,
    [Vrach]                   INT            NULL,
    [Zaklyuchenie]            NVARCHAR (100) NULL,
    [Kommentrariy]            NTEXT          NULL,
    [Zhalobi1]                NTEXT          NULL,
    [AnamnezZabolevaniya1]    NTEXT          NULL,
    [VerxnieKonecnosti]       NVARCHAR (100) NULL,
    [Kozha]                   NVARCHAR (50)  NULL,
    [kozha1]                  NVARCHAR (100) NULL,
    [PulsaziyNadArteriei]     NVARCHAR (100) NULL,
    [NaStope]                 NVARCHAR (100) NULL,
    [Arterii]                 NVARCHAR (100) NULL,
    [veni]                    NVARCHAR (100) NULL,
    [Tazobedrenie]            NVARCHAR (50)  NULL,
    [Tazobedrenie1]           NVARCHAR (50)  NULL,
    [Kolennie1]               NVARCHAR (50)  NULL,
    [Kolennie]                NVARCHAR (50)  NULL,
    [Stopi1]                  NVARCHAR (50)  NULL,
    [Stopi]                   NVARCHAR (50)  NULL,
    [PalzevNog1]              NVARCHAR (50)  NULL,
    [PalzevNog]               NVARCHAR (50)  NULL,
    [Plechevie1]              NVARCHAR (50)  NULL,
    [Plechevie]               NVARCHAR (50)  NULL,
    [Loktevie1]               NVARCHAR (50)  NULL,
    [Loktevie]                NVARCHAR (50)  NULL,
    [Lucezapasnie1]           NVARCHAR (50)  NULL,
    [Lucezapasnie]            NVARCHAR (50)  NULL,
    [Kisti1]                  NVARCHAR (50)  NULL,
    [Kisti]                   NVARCHAR (50)  NULL,
    [PalciRuk1]               NVARCHAR (50)  NULL,
    [PalciRuk]                NVARCHAR (50)  NULL,
    [ZhivotPriPalpacii]       NVARCHAR (50)  NULL,
    [ZhivotPriPalpacii1]      NVARCHAR (50)  NULL,
    [PrymayKishka]            NVARCHAR (50)  NULL,
    [PramayKishka1]           NVARCHAR (100) NULL,
    [DopDanie]                NTEXT          NULL,
    [Vievleno]                NVARCHAR (50)  NULL,
    [XirurgiceskoiPatalogii]  NVARCHAR (50)  NULL,
    [XirurgiceskoiPatalogii1] NVARCHAR (50)  NULL,
    [DiagnozPoMkb10]          NVARCHAR (80)  NULL,
    [KodPoMkb10]              NVARCHAR (10)  NULL,
    [GruppaD]                 NVARCHAR (2)   NULL,
    [Recommendation]          NTEXT          NULL,
    CONSTRAINT [ProfosmotrHirurgPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [ProfosmotrHirurgToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

