CREATE TABLE [dbo].[ProfosmotrNevropatolog] (
    [ID]                             INT            NOT NULL,
    [PatID]                          INT            NULL,
    [Data]                           DATETIME       NULL,
    [Vrach]                          INT            NULL,
    [Zhalobi1]                       NTEXT          NULL,
    [AnamnezZabolevaniya1]           NTEXT          NULL,
    [AdSist1]                        INT            NULL,
    [AdDiast1]                       INT            NULL,
    [Puls1]                          INT            NULL,
    [Diplopiya3]                     NVARCHAR (1)   NULL,
    [BoleznenostVTockax]             NVARCHAR (50)  NULL,
    [DvizhenievSustavax]             NVARCHAR (50)  NULL,
    [MihechniTonys]                  NVARCHAR (50)  NULL,
    [silavrykax]                     INT            NULL,
    [silavnogax]                     INT            NULL,
    [VsheinomOtd]                    NVARCHAR (50)  NULL,
    [VgrudnomOtd]                    NVARCHAR (50)  NULL,
    [VpoisnichnomOtd]                NVARCHAR (50)  NULL,
    [ChmnBezPatologii]               NVARCHAR (1)   NULL,
    [Skolioz]                        NVARCHAR (50)  NULL,
    [SuxozhilnieRefleksiRuk]         NVARCHAR (50)  NULL,
    [PatologicheskieRefleksi]        NVARCHAR (50)  NULL,
    [Poxotka]                        NVARCHAR (50)  NULL,
    [KoordinatornieProbi]            NVARCHAR (50)  NULL,
    [Potootdelenie]                  NVARCHAR (50)  NULL,
    [DopInfo]                        NTEXT          NULL,
    [DvizhenieGlaznihYablok1]        NVARCHAR (50)  NULL,
    [Zrachki1]                       NVARCHAR (50)  NULL,
    [FotoreaktsiyaNaSvet2]           NVARCHAR (50)  NULL,
    [BoleznenostVTochkahVihoda]      NVARCHAR (1)   NULL,
    [Glotanie1]                      NVARCHAR (50)  NULL,
    [Yazik2]                         NVARCHAR (50)  NULL,
    [Litso1]                         NVARCHAR (50)  NULL,
    [SheiniOTDELBolPriDvizhenii]     NVARCHAR (1)   NULL,
    [GrudnomOTDELBolPriDvizhenii]    NVARCHAR (1)   NULL,
    [PoysnicnomOTDELBolPriDvizhenii] NVARCHAR (1)   NULL,
    [SkoliozPozvonochnika]           NVARCHAR (1)   NULL,
    [VPozeRomberga1]                 NVARCHAR (50)  NULL,
    [Chuvstvitelnost2]               NVARCHAR (50)  NULL,
    [SuxozhilnieRefleksiNog]         NVARCHAR (50)  NULL,
    [Dermografizm2]                  NVARCHAR (50)  NULL,
    [GruppaD]                        NVARCHAR (2)   NULL,
    [Vievleno]                       NVARCHAR (10)  NULL,
    [MyshcySpyny]                    NVARCHAR (50)  NULL,
    [Chuvstvitelnost]                NVARCHAR (50)  NULL,
    [MihechniTonys2]                 NVARCHAR (50)  NULL,
    [DiagnozPoMkb10]                 NVARCHAR (80)  NULL,
    [KodPoMkb10]                     NVARCHAR (10)  NULL,
    [Zaklyuchenie]                   NVARCHAR (100) NULL,
    [Kommentrariy]                   NTEXT          NULL,
    [Recommendation]                 NTEXT          NULL,
    CONSTRAINT [ProfosmotrNevropatologPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [ProfosmotrNevropatologToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

