CREATE TABLE [dbo].[REESTR_temp] (
    [NUM_S]      NVARCHAR (5)   NULL,
    [DATA_S]     DATETIME2 (7)  NULL,
    [NUSL]       INT            NULL,
    [CARD]       INT            NULL,
    [FAM]        NVARCHAR (60)  NULL,
    [IMYA]       NVARCHAR (40)  NULL,
    [OTCH]       NVARCHAR (40)  NULL,
    [POL]        NVARCHAR (1)   NULL,
    [DATE_BIRTH] DATETIME2 (7)  NULL,
    [KATEG]      INT            NULL,
    [IST_FIN]    INT            NULL,
    [C_INSUR]    INT            NULL,
    [P_SER]      NVARCHAR (10)  NULL,
    [P_NUM]      NVARCHAR (16)  NULL,
    [REGION]     INT            NULL,
    [FROM_FIRM]  INT            NULL,
    [PURP]       INT            NULL,
    [URGENT]     INT            NULL,
    [DATE_IN]    DATETIME2 (7)  NULL,
    [DATE_OUT]   DATETIME2 (7)  NULL,
    [Q_U]        INT            NULL,
    [RESULT_ILL] INT            NULL,
    [CODE_MES]   NVARCHAR (7)   NULL,
    [RESULT_TRE] INT            NULL,
    [DS_CLIN]    NVARCHAR (9)   NULL,
    [CHAR_MAIN]  INT            NULL,
    [VISIT_POL]  INT            NULL,
    [VISIT_HOM]  INT            NULL,
    [VISIT_DS]   INT            NULL,
    [VISIT_HS]   INT            NULL,
    [MOVE_LPU]   INT            NULL,
    [NSNDHOSP]   NVARCHAR (10)  NULL,
    [TYPE_HOSP]  INT            NULL,
    [SPECFIC]    INT            NULL,
    [DOCFIC]     INT            NULL,
    [TYPE_PAY]   INT            NULL,
    [TARIF]      FLOAT (53)     NULL,
    [SUM_PAY]    FLOAT (53)     NULL,
    [I_TYPE]     INT            NULL,
    [D_TYPE]     NVARCHAR (3)   NULL,
    [K_PR]       INT            NULL,
    [VISIT_PR]   FLOAT (53)     NULL,
    [ST_ZAN]     INT            NULL,
    [SN_DOC]     NVARCHAR (16)  NULL,
    [C_DOC]      INT            NULL,
    [DS_S]       NVARCHAR (7)   NULL,
    [SMO]        NVARCHAR (5)   NULL,
    [NPR_MO]     NVARCHAR (6)   NULL,
    [PRVS]       NVARCHAR (9)   NULL,
    [IDDOKT]     NVARCHAR (16)  NULL,
    [VPOLIS]     INT            NULL,
    [NOVOR]      NVARCHAR (9)   NULL,
    [OS_SLUCH]   INT            NULL,
    [PROFIL]     INT            NULL,
    [DET]        INT            NULL,
    [VIDPOM]     INT            NULL,
    [USL_OK]     INT            NULL,
    [ISHOD]      INT            NULL,
    [RSLT]       INT            NULL,
    [DOCTYPE]    INT            NULL,
    [DOCSER]     NVARCHAR (10)  NULL,
    [DOCNUM]     NVARCHAR (20)  NULL,
    [SNILS]      NVARCHAR (14)  NULL,
    [UR_MO]      NVARCHAR (6)   NULL,
    [OKATO_OMS]  NVARCHAR (5)   NULL,
    [VNOV_D]     INT            NULL,
    [FOR_POM]    INT            NULL,
    [DS2]        NVARCHAR (10)  NULL,
    [DS3]        NVARCHAR (10)  NULL,
    [VNOV_M]     INT            NULL,
    [CODE_MES2]  NVARCHAR (7)   NULL,
    [DOST]       INT            NULL,
    [FAM_P]      NVARCHAR (40)  NULL,
    [IM_P]       NVARCHAR (40)  NULL,
    [OT_P]       NVARCHAR (40)  NULL,
    [W_P]        INT            NULL,
    [DR_P]       DATETIME2 (7)  NULL,
    [DOST_P]     INT            NULL,
    [MR]         NVARCHAR (100) NULL,
    [KSG]        INT            NULL,
    [PR_NOV]     INT            NULL,
    [SUMV]       FLOAT (53)     NULL,
    [NAPRLECH]   NVARCHAR (10)  NULL,
    [NUSL_ORG]   INT            NULL,
    [STAGE]      INT            NULL,
    [IDKARTA]    INT            NULL,
    [IDMONTH]    INT            NULL,
    [IDLPU]      INT            NULL,
    [KOD_F]      INT            NULL,
    [N_INSUR]    NVARCHAR (50)  NULL,
    [DOCUMENT]   NVARCHAR (20)  NULL,
    [ADDRESS]    NVARCHAR (120) NULL,
    [MCOD]       NVARCHAR (8)   NULL,
    [IDBOL]      INT            NULL,
    [IDVRACH]    INT            NULL,
    [STATUS]     INT            NULL,
    [IDSTRAX]    INT            NULL,
    [JOB]        INT            NULL,
    [IDPOLIS]    INT            NULL,
    [VISIT_P]    INT            NULL,
    [VISIT_H]    INT            NULL,
    [VISIT]      INT            NULL,
    [K_P1]       FLOAT (53)     NULL,
    [K_H1]       FLOAT (53)     NULL,
    [K_P2]       FLOAT (53)     NULL,
    [K_H2]       FLOAT (53)     NULL,
    [V_P1]       FLOAT (53)     NULL,
    [V_H1]       FLOAT (53)     NULL,
    [V_P2]       FLOAT (53)     NULL,
    [V_H2]       FLOAT (53)     NULL,
    [IDDPT]      INT            NULL,
    [UET]        FLOAT (53)     NULL,
    [IDRES1]     INT            NULL,
    [NREC]       INT            NULL,
    [NPARA]      INT            NULL,
    [UNITS]      INT            NULL,
    [NRC]        INT            NULL,
    [UET_PARA]   FLOAT (53)     NULL,
    [OKVED]      NVARCHAR (10)  NULL,
    [VORG_POL]   INT            NULL,
    [VORG_HOM]   INT            NULL,
    [VORG_DS]    INT            NULL,
    [VORG_HS]    INT            NULL,
    [IDPURP_ORG] INT            NULL,
    [OGRN]       NVARCHAR (16)  NULL
);

