CREATE TABLE [dbo].[Rektoskopiya] (
    [ID]                                     INT          NOT NULL,
    [PatID]                                  INT          NULL,
    [NomerIssledovaniya]                     INT          NULL,
    [DataIssledovanie]                       DATETIME     NULL,
    [Vrach]                                  INT          NULL,
    [TubusFibroskopaVveden]                  INT          NULL,
    [ProsvetR]                               INT          NULL,
    [ProsvetR1]                              INT          NULL,
    [VProsvetePryamoyKishki]                 INT          NULL,
    [VidiSkladokR]                           INT          NULL,
    [SosudistiyRisunokR]                     INT          NULL,
    [SlizistayaR]                            INT          NULL,
    [PoverhnostR]                            INT          NULL,
    [OtekSlizistoyR]                         INT          NULL,
    [MelkotochechnieKrovoizliyaniyaR]        NVARCHAR (1) NULL,
    [YazviR]                                 NVARCHAR (1) NULL,
    [KolichestvoR]                           INT          NULL,
    [LokalizatsiyaYazvR]                     INT          NULL,
    [LokalizatsiyaYazvR1]                    INT          NULL,
    [FormaYazvR]                             INT          NULL,
    [FormaRostaDlyaOpuholiR]                 INT          NULL,
    [RazmeramiYaR]                           INT          NULL,
    [LokalizatsiyaKrovoizliyaniyR]           INT          NULL,
    [MelkotochenieKrovoizR]                  INT          NULL,
    [LokalizatsiyaKrovoizliyaniyR1]          INT          NULL,
    [PolipiR]                                NVARCHAR (1) NULL,
    [PolipiComboR]                           INT          NULL,
    [KartsinomaR]                            NVARCHAR (1) NULL,
    [KarcinomaComboR]                        INT          NULL,
    [ImeetsyaR]                              INT          NULL,
    [SfinkterOBernaPirogovaMyute]            INT          NULL,
    [LokalizatsiyaPolipovR]                  INT          NULL,
    [FormaPolipovR]                          INT          NULL,
    [LokalizatsiyaPolipovR1]                 INT          NULL,
    [RazmerPolipovR]                         INT          NULL,
    [LokalizatsiyaKartsinomiR]               INT          NULL,
    [FormaKartsinomiR]                       INT          NULL,
    [FormaKartsinomiR1]                      INT          NULL,
    [LokalizatsiyaKartsinomiR1]              INT          NULL,
    [RazmerKarcinomiR]                       INT          NULL,
    [LokalizatsiyaR]                         INT          NULL,
    [LokalizatsiyaR1]                        INT          NULL,
    [FormaR1]                                INT          NULL,
    [FormaR]                                 INT          NULL,
    [RazmerPatologicheskokogoObrazovaniyaR]  INT          NULL,
    [TsitologicheskoeIssledovanieSigmKishki] NVARCHAR (1) NULL,
    [GistologicheskoeIssledovanieSigmKishki] NVARCHAR (1) NULL,
    [TsitologicheskoeIssledovaniePrKishki]   NVARCHAR (1) NULL,
    [GistologicheskoeIssledovaniePrKishki]   NVARCHAR (1) NULL,
    [VpervieViyavlenniyBolnoy]               NVARCHAR (1) NULL,
    [ErozivniySfinkterit]                    NVARCHAR (1) NULL,
    [AnalnoSosochkoviyPolip]                 NVARCHAR (1) NULL,
    [PolipPryamoyKishki]                     NVARCHAR (1) NULL,
    [AnalnoSosochkoviePolipi]                NVARCHAR (1) NULL,
    [CRPryamoyKishki]                        NVARCHAR (1) NULL,
    [NovoobrazovaniePryamoyKishki]           NVARCHAR (1) NULL,
    [PolipiPryamoyKishki]                    NVARCHAR (1) NULL,
    [HronicheskiyGemorroy]                   INT          NULL,
    [HronicheskiyGemorroy1]                  INT          NULL,
    [HronicheskiyGemorroy2]                  INT          NULL,
    [Image]                                  IMAGE        NULL,
    [DannieVivodimoeNaPechat]                NTEXT        NULL,
    [Zaklyuchenie]                           NTEXT        NULL,
    CONSTRAINT [RektoskopiyaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [RektoskopiyaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

