CREATE TABLE [dbo].[ReoEntsefalografiya] (
    [ID]                                        INT        NOT NULL,
    [PatID]                                     INT        NULL,
    [NomerIssledovaniya]                        INT        NULL,
    [DataIssledovanie]                          DATETIME   NULL,
    [Rid]                                       FLOAT (53) NULL,
    [Ris]                                       FLOAT (53) NULL,
    [Kas]                                       FLOAT (53) NULL,
    [PulsovoeKrovenapolnenieSprava]             INT        NULL,
    [TonusArteriySprava]                        INT        NULL,
    [TonusArteriySprava1]                       INT        NULL,
    [VenozniyOttokSprava]                       INT        NULL,
    [PulsovoeKrovenapolnenieSleva]              INT        NULL,
    [TonusArteriySleva]                         INT        NULL,
    [TonusArteriySleva1]                        INT        NULL,
    [VenozniyOttokSleva]                        INT        NULL,
    [VenozniyOttokSleva1]                       INT        NULL,
    [PriznakiMezhpolusharnoyAsimmetrii]         INT        NULL,
    [TonusArteriySprava2]                       INT        NULL,
    [TonusArteriySleva2]                        INT        NULL,
    [VenozniyOttokSprava1]                      INT        NULL,
    [Rid1]                                      FLOAT (53) NULL,
    [Ris1]                                      FLOAT (53) NULL,
    [Kas1]                                      FLOAT (53) NULL,
    [PulsovoeKrovenapolnenieSprava1]            INT        NULL,
    [TonusArteriySprava3]                       INT        NULL,
    [TonusArteriySprava4]                       INT        NULL,
    [TonusArteriySprava5]                       INT        NULL,
    [VenozniyOttokSprava2]                      INT        NULL,
    [VenozniyOttokSprava3]                      INT        NULL,
    [PulsovoeKrovenapolnenieSleva1]             INT        NULL,
    [TonusArteriySleva3]                        INT        NULL,
    [TonusArteriySleva4]                        INT        NULL,
    [TonusArteriySleva5]                        INT        NULL,
    [VenozniyOttokSleva2]                       INT        NULL,
    [VenozniyOttokSleva3]                       INT        NULL,
    [PriznakiMezhpolusharnoyAsimmetrii1]        INT        NULL,
    [ProbaSPovorotomGoloviVpravoVlevoVverhVniz] NTEXT      NULL,
    [Vrach]                                     INT        NULL,
    [Zaklyuchenie]                              NTEXT      NULL,
    CONSTRAINT [ReoEntsefalografiyaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [ReoEntsefalografiyaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

