CREATE TABLE [dbo].[Reovazografiya] (
    [ID]                 INT           NOT NULL,
    [PatID]              INT           NULL,
    [NomerIssledovaniya] INT           NULL,
    [DataIssledovanie]   DATETIME      NULL,
    [PlechoRidUR]        FLOAT (53)    NULL,
    [PlechoRidUR1]       INT           NULL,
    [PPrRidUR]           FLOAT (53)    NULL,
    [PPrRidUR1]          INT           NULL,
    [KistRidUR]          FLOAT (53)    NULL,
    [PaletsRidUR]        FLOAT (53)    NULL,
    [PaletsRidUR1]       INT           NULL,
    [PlechoRidUL]        FLOAT (53)    NULL,
    [PlechoRidUL1]       INT           NULL,
    [PPrRidUL]           FLOAT (53)    NULL,
    [PPrRidUL1]          INT           NULL,
    [KistRidUL]          FLOAT (53)    NULL,
    [KistRidUL1]         INT           NULL,
    [PaletsRidUL]        FLOAT (53)    NULL,
    [PlechoRidDR]        FLOAT (53)    NULL,
    [PlechoRidDR1]       INT           NULL,
    [PPrRidDR]           FLOAT (53)    NULL,
    [PPrRidDR1]          INT           NULL,
    [KistRidDR]          FLOAT (53)    NULL,
    [KistRidDR1]         INT           NULL,
    [PaletsRidDR]        FLOAT (53)    NULL,
    [PaletsRidDR1]       INT           NULL,
    [PlechoRidDL]        FLOAT (53)    NULL,
    [PlechoRidDL1]       INT           NULL,
    [PPrRidDL]           FLOAT (53)    NULL,
    [PPrRidDL1]          INT           NULL,
    [KistRidDL1]         INT           NULL,
    [KistRidDL]          FLOAT (53)    NULL,
    [PaletsRidDL]        FLOAT (53)    NULL,
    [PaletsRidDL1]       INT           NULL,
    [KistRidUR1]         INT           NULL,
    [PaletsRidUL1]       INT           NULL,
    [TonusArteriy]       INT           NULL,
    [IzmenenenieTonusa]  INT           NULL,
    [StepenIzmeneniya]   INT           NULL,
    [Lokalizatsiya]      INT           NULL,
    [Storona]            NVARCHAR (50) NULL,
    [VenozniyOttok]      INT           NULL,
    [Lokalizatsiya1]     INT           NULL,
    [Storona1]           NVARCHAR (50) NULL,
    [Vrach]              INT           NULL,
    [Zaklyuchenie]       NTEXT         NULL,
    CONSTRAINT [ReovazografiyaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [ReovazografiyaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

