CREATE TABLE [dbo].[FOMSRequests] (
    [ID]                        INT           NOT NULL,
    [IsNew]                     BIT           CONSTRAINT [DF_FOMSRequests_IsNew] DEFAULT ((0)) NULL,
    [PatID]                     INT           NULL,
    [DoctorId]                  INT           NULL,
    [IsHospitalization]         BIT           CONSTRAINT [DF_FOMSRequests_IsHospitalization] DEFAULT ((0)) NULL,
    [HealingStartDate]          DATETIME      CONSTRAINT [DF_FOMSRequests_HealingStart] DEFAULT (getdate()) NULL,
    [HealingEndDate]            DATETIME      NULL,
    [TreatmentPlaceTypeId]      INT           NULL,
    [IsFirstResolt]             BIT           NULL,
    [ResoltResultId]            INT           NULL,
    [MedicalHelpTypeId]         INT           NULL,
    [TargetResoltId]            INT           NULL,
    [TemporaryDirectorDate]     DATETIME      NULL,
    [DispensedDate]             DATETIME      NULL,
    [ProtractionDate]           DATETIME      NULL,
    [VisitationId]              NVARCHAR (50) NULL,
    [DiseaseId]                 INT           NULL,
    [DispensaryObservationId]   INT           NULL,
    [TraumaId]                  INT           NULL,
    [TemporaryDirectorId]       INT           NULL,
    [IsResoltComplate]          BIT           NULL,
    [InsertStamp]               DATETIME      CONSTRAINT [DF_FOMSRequests_InsertStamp] DEFAULT (getdate()) NULL,
    [TalonNumber]               INT           NULL,
    [TemporaryDirectorReasonId] INT           NULL,
    [ReportId]                  INT           NULL,
    [MedicalHelpId]             INT           NULL,
    [RefferalId]                INT           NULL,
    [HospitalizationId]         INT           NULL,
    [ProfileHelpId]             INT           NULL,
    [FinalMESId]                INT           NULL,
    [BonusMESId]                INT           NULL,
    [DiseaseOutcomeId]          INT           NULL,
    [PreviewSickDictId]         INT           NULL,
    [FinalSickDictId]           INT           NULL,
    [BonusSickDictId]           INT           NULL,
    [ObslugId]                  INT           NULL,
    [TypPrebId]                 INT           NULL,
    [CharMainId]                INT           NULL,
    [VisitCount]                INT           NULL,
    [VisitPolCount]             INT           NULL,
    [VisitHomCount]             INT           NULL,
    [VisitDsCount]              INT           NULL,
    [VisitHSCount]              INT           NULL,
    [NSNDHOSP]                  INT           NULL,
    [TypePayId]                 INT           NULL,
    [KPRId]                     INT           NULL,
    [ReportDate]                DATETIME      NULL,
    [IsActive]                  BIT           CONSTRAINT [DF_FOMSRequests_IsActive] DEFAULT ((0)) NOT NULL,
    [FinanceSourceId]           INT           NULL,
    CONSTRAINT [PK_FOMSRequests] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FOMSRequests_FOMSReports] FOREIGN KEY ([ReportId]) REFERENCES [dbo].[FOMSReports] ([ID]),
    CONSTRAINT [fomsrequestsToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

