CREATE TABLE dbo.FOMS_H_SL
(
    Id int NOT NULL IDENTITY(1, 1) PRIMARY KEY,
    ZapId int NOT NULL REFERENCES dbo.FOMS_H_ZAP(Id),
    SL_ID varchar(36) NULL,
    LPU_1 varchar(8) NULL,
    PODR int NULL,
    PROFIL int NULL,
    PROFIL_K int NULL,
    DET int NULL,
    P_CEL varchar(20) NULL,
    NHISTORY varchar(50) NULL,
    P_PER int NULL,
    DATE_1 date NULL,
    DATE_2 date NULL,
    KD varchar(20) NULL,
    DS0 varchar(10) NULL,
    DS1 varchar(10) NULL,
    DS2 varchar(10) NULL,
    DS3 varchar(10) NULL,
    DN varchar(20) NULL,
    CODE_MES1 varchar(20) NULL,
    CODE_MES2 varchar(20) NULL,
    REAB varchar(20) NULL,
    PRVS int NULL,
    VERS_SPEC varchar(4) NULL,
    IDDOKT varchar(25) NULL,
    ED_COL decimal NULL,
    TARIF decimal NULL,
    SUM_M decimal NULL,
    COMENTSL varchar(250) NULL
)