CREATE TABLE [dbo].[Service] (
    [ID]                         INT             NOT NULL,
    [FullName]                   NVARCHAR (1024) NULL,
    [KeyWord]                    NVARCHAR (255)  NULL,
    [Primechanie]                NTEXT           NULL,
    [Code]                       NVARCHAR (12)   NULL,
    [Price]                      MONEY           NULL,
    [CurrencyPrice]              MONEY           NULL,
    [Measure]                    NVARCHAR (50)   NULL,
    [Duration]                   INT             NULL,
    [StavkaNDS]                  INT             NULL,
    [isOms]                      BIT             NULL,
    [UET]                        FLOAT (53)      NULL,
    [AutoRefresh]                BIT             NULL,
    [UETsister]                  FLOAT (53)      NULL,
    [cbAutoCalc_UETsister]       NVARCHAR (1)    NULL,
    [cbAutoCalc_UETdoctor]       NVARCHAR (1)    NULL,
    [DictComboMKB]               NVARCHAR (50)   NULL,
    [DictComboFaza]              NVARCHAR (50)   NULL,
    [DictComboStadiya]           NVARCHAR (50)   NULL,
    [DictComboOslozhneniya]      NVARCHAR (50)   NULL,
    [DictComboUsloviyaOkazaniya] NVARCHAR (50)   NULL,
    [WordDocument]               TEXT            NULL,
    [Conditions]                 NTEXT           NULL,
    CONSTRAINT [ServicePrimKey] PRIMARY KEY CLUSTERED ([ID] ASC)
);

