CREATE TABLE [dbo].[VizovNaDom] (
    [ID]         INT            NOT NULL,
    [MasterID]   INT            NULL,
    [Cardnum]    NVARCHAR (50)  NULL,
    [Povod]      NVARCHAR (50)  NULL,
    [CallType]   NVARCHAR (50)  NULL,
    [MakeDate]   DATETIME       NULL,
    [CallHour]   NVARCHAR (10)  NULL,
    [Diagnoz]    NVARCHAR (100) NULL,
    [RunDoctor]  INT            NULL,
    [DoneHelp]   NVARCHAR (50)  NULL,
    [RunHour]    INT            NULL,
    [Дата]       DATETIME       NULL,
    [Age]        NVARCHAR (15)  NULL,
    [Автор]      INT            NULL,
    [PatAddress] NVARCHAR (100) NULL,
    [PatId]      NVARCHAR (10)  NULL,
    [PatPhone]   NVARCHAR (50)  NULL,
    [LastName]   NVARCHAR (50)  NULL,
    [FirstName]  NVARCHAR (50)  NULL,
    [SecondName] NVARCHAR (50)  NULL,
    [IdNapr]     INT            NULL,
    CONSTRAINT [VizovNaDomPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC)
);

