CREATE PROCEDURE dbo.FOMSReportHClear
AS
BEGIN
    DELETE FROM dbo.FOMS_H_KSG_KPG
    DELETE FROM dbo.FOMS_H_USL
    DELETE FROM dbo.FOMS_H_SANK
    DELETE FROM dbo.FOMS_H_SL
    DELETE FROM dbo.FOMS_H_Z_SL
    DELETE FROM dbo.FOMS_H_PACIENT
    DELETE FROM dbo.FOMS_H_ZAP
    DELETE FROM dbo.FOMS_H_SCHET
    DELETE FROM dbo.FOMS_H_ZL_LIST
END
