
CREATE FUNCTION  [dbo].[CyrToLat_char]
(@string nvarchar(1))
RETURNS nvarchar(2)
AS
BEGIN
return	case UNICODE(@string)
		when UNICODE('а') then 'a'
		when UNICODE('б') then 'b'
		when UNICODE('в') then 'v'
		when UNICODE('г') then 'g'
		when UNICODE('д') then 'd'
		when UNICODE('е') then 'e'
		when UNICODE('ё') then 'yo'
		when UNICODE('ж') then 'zh'
		when UNICODE('з') then 'z'
		when UNICODE('и') then 'i'
		when UNICODE('й') then 'y'
		when UNICODE('к') then 'k'
		when UNICODE('л') then 'l'
		when UNICODE('м') then 'm'
		when UNICODE('н') then 'n'
		when UNICODE('о') then 'o'
		when UNICODE('п') then 'p'
		when UNICODE('р') then 'r'
		when UNICODE('с') then 's'
		when UNICODE('т') then 't'
		when UNICODE('у') then 'u'
		when UNICODE('ф') then 'f'
		when UNICODE('х') then 'h'
		when UNICODE('ц') then 'ts'
		when UNICODE('ч') then 'ch'
		when UNICODE('ш') then 'sh'
		when UNICODE('щ') then 'sh'
		when UNICODE('ъ') then ''
		when UNICODE('ы') then 'i'
		when UNICODE('ь') then ''
		when UNICODE('э') then 'e'
		when UNICODE('ю') then 'yu'
		when UNICODE('я') then 'ya'

		when UNICODE('А') then 'A'
		when UNICODE('Б') then 'B'
		when UNICODE('В') then 'V'
		when UNICODE('Г') then 'G'
		when UNICODE('Д') then 'D'
		when UNICODE('Е') then 'E'
		when UNICODE('Ё') then 'Yo'
		when UNICODE('Ж') then 'Zh'
		when UNICODE('З') then 'Z'
		when UNICODE('И') then 'I'
		when UNICODE('Й') then 'Y'
		when UNICODE('К') then 'K'
		when UNICODE('Л') then 'L'
		when UNICODE('М') then 'M'
		when UNICODE('Н') then 'N'
		when UNICODE('О') then 'O'
		when UNICODE('П') then 'P'
		when UNICODE('Р') then 'R'
		when UNICODE('С') then 'S'
		when UNICODE('Т') then 'T'
		when UNICODE('У') then 'U'
		when UNICODE('Ф') then 'F'
		when UNICODE('Х') then 'H'
		when UNICODE('Ц') then 'Ts'
		when UNICODE('Ч') then 'Ch'
		when UNICODE('Ш') then 'Sh'
		when UNICODE('Щ') then 'Sh'
		when UNICODE('Ъ') then ''
		when UNICODE('Ы') then 'I'
		when UNICODE('Ь') then ''
		when UNICODE('Э') then 'E'
		when UNICODE('Ю') then 'Yu'
		when UNICODE('Я') then 'Ya'
		else @string
	end

END
