
CREATE FUNCTION fnHMS(@Value DATETIME)
RETURNS DATETIME
BEGIN
  DECLARE @H INT
  DECLARE @M INT
  DECLARE @S INT
  DECLARE @V DATETIME

  SET @H=DATEPART(hh,@Value)
  SET @M=DATEPART(mi,@Value)
  SET @S=DATEPART(ss,@Value)

  SELECT @V = DATEADD(ss,@S,DATEADD(mi,@M,DATEADD(hh,@H,'00:00:00')))
  RETURN @V
END
