CREATE TABLE [dbo].[SG] (
    [Id]             INT           NOT NULL,
    [PatId]          INT           NULL,
    [ExecDate]       DATETIME      NULL,
    [ChasDays]       INT           NULL,
    [Volume]         FLOAT (53)    NULL,
    [Color]          VARCHAR (150) NULL,
    [Clam]           VARCHAR (150) NULL,
    [LiqTime]        VARCHAR (150) NULL,
    [Conc]           VARCHAR (150) NULL,
    [Qty]            VARCHAR (150) NULL,
    [Quick]          VARCHAR (150) NULL,
    [Slow]           VARCHAR (150) NULL,
    [QS]             VARCHAR (150) NULL,
    [Fluc]           VARCHAR (150) NULL,
    [Fixed]          VARCHAR (150) NULL,
    [Norm]           VARCHAR (150) NULL,
    [NormKru]        VARCHAR (150) NULL,
    [Rounded]        VARCHAR (150) NULL,
    [Erit]           VARCHAR (150) NULL,
    [Epit]           VARCHAR (150) NULL,
    [Aglut]          VARCHAR (150) NULL,
    [Mucus]          VARCHAR (150) NULL,
    [PayNeed]        BIT           NULL,
    [Payed]          BIT           NULL,
    [PaySum]         MONEY         NULL,
    [PayedSum]       MONEY         NULL,
    [PayDate]        DATETIME      NULL,
    [PayComment]     VARCHAR (255) NULL,
    [OperId]         INT           NULL,
    [OriginalID]     INT           NULL,
    [Lucocytes]      NVARCHAR (50) NULL,
    [MARTestIgG]     NVARCHAR (50) NULL,
    [FertSpermCount] FLOAT (53)    NULL,
    [Conclusion]     NTEXT         NULL,
    CONSTRAINT [PK_SG] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_SG_PatForm] FOREIGN KEY ([Id]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

