CREATE TABLE [dbo].[SickList] (
    [ID]                         INT            NOT NULL,
    [PatID]                      INT            NULL,
    [LN_CODE]                    NVARCHAR (12)  NULL,
    [PREV_LN_CODE]               NVARCHAR (12)  NULL,
    [PARENT_CODE]                NVARCHAR (12)  NULL,
    [LPU_NAME]                   NVARCHAR (90)  NULL,
    [LPU_ADDRESS]                NVARCHAR (100) NULL,
    [LPU_OGRN]                   NVARCHAR (15)  NULL,
    [VOUCHER_NO]                 NVARCHAR (10)  NULL,
    [VOUCHER_OGRN]               NVARCHAR (15)  NULL,
    [SERV1_AGE]                  INT            NULL,
    [SERV1_MM]                   INT            NULL,
    [SERV1_FIO]                  NVARCHAR (90)  NULL,
    [SERV2_AGE]                  INT            NULL,
    [SERV2_MM]                   INT            NULL,
    [SERV2_FIO]                  NVARCHAR (90)  NULL,
    [LN_LAST_NAME]               NVARCHAR (30)  NULL,
    [LN_FIRST_NAME]              NVARCHAR (30)  NULL,
    [LN_PATRONYMIC]              NVARCHAR (30)  NULL,
    [NEXT_LN_CODE]               NVARCHAR (12)  NULL,
    [LN_TREAT_HISTORY]           NVARCHAR (12)  NULL,
    [LN_EMPLOYER]                NVARCHAR (150) NULL,
    [TREAT1_DOCTOR_ROLE]         NVARCHAR (300) NULL,
    [TREAT1_DOCTOR]              NVARCHAR (90)  NULL,
    [TREAT2_DOCTOR_ROLE]         NVARCHAR (300) NULL,
    [TREAT2_DOCTOR]              NVARCHAR (90)  NULL,
    [TREAT3_DOCTOR_ROLE]         NVARCHAR (300) NULL,
    [TREAT3_DOCTOR]              NVARCHAR (90)  NULL,
    [TREAT1_DOCTOR2_ROLE]        NVARCHAR (300) NULL,
    [TREAT2_DOCTOR2_ROLE]        NVARCHAR (300) NULL,
    [TREAT1_CHAIRMAN_VK]         NVARCHAR (90)  NULL,
    [TREAT2_CHAIRMAN_VK]         NVARCHAR (90)  NULL,
    [LN_FINISH_DOCTOR]           NVARCHAR (90)  NULL,
    [TREAT3_CHAIRMAN_VK]         NVARCHAR (90)  NULL,
    [TREAT3_DOCTOR2_ROLE]        NVARCHAR (300) NULL,
    [OTHER_STATE_DT]             DATETIME       NULL,
    [RETURN_DATE_LPU]            DATETIME       NULL,
    [TREAT3_DT1]                 DATETIME       NULL,
    [TREAT3_DT2]                 DATETIME       NULL,
    [TREAT2_DT1]                 DATETIME       NULL,
    [TREAT2_DT2]                 DATETIME       NULL,
    [BIRTHDAY]                   DATETIME       NULL,
    [TREAT1_DT1]                 DATETIME       NULL,
    [TREAT1_DT2]                 DATETIME       NULL,
    [LN_DATE]                    DATETIME       NULL,
    [DATE1]                      DATETIME       NULL,
    [DATE2]                      DATETIME       NULL,
    [HOSPITAL_BREACH_DT]         DATETIME       NULL,
    [HOSPITAL_DT1]               DATETIME       NULL,
    [HOSPITAL_DT2]               DATETIME       NULL,
    [MSE_DT1]                    DATETIME       NULL,
    [MSE_DT2]                    DATETIME       NULL,
    [MSE_DT3]                    DATETIME       NULL,
    [MSE_RESULT]                 NVARCHAR (2)   NULL,
    [REASON1]                    NVARCHAR (2)   NULL,
    [REASON2]                    NVARCHAR (3)   NULL,
    [REASON3]                    NVARCHAR (2)   NULL,
    [SERV1_RELATION_CODE]        NVARCHAR (2)   NULL,
    [SERV2_RELATION_CODE]        NVARCHAR (2)   NULL,
    [HOSPITAL_BREACH_CODE]       NVARCHAR (2)   NULL,
    [MSE_INVALID_GROUP]          NVARCHAR (1)   NULL,
    [BOZ_FLAG]                   INT            NULL,
    [DUPLICATE_FLAG]             INT            NULL,
    [PRIMARY_FLAG]               INT            NULL,
    [LN_EMPL_FLAG]               INT            NULL,
    [PREGN12W_FLAG]              INT            NULL,
    [GENDER]                     INT            NULL,
    [Vozrast]                    INT            NULL,
    [DiagCode]                   NVARCHAR (8)   NULL,
    [Open_in_other_LPU]          INT            NULL,
    [Closed_in_other_LPU]        INT            NULL,
    [TREAT1_DOCTOR_CARDNUM]      INT            NULL,
    [TREAT1_CHAIRMAN_VK_CARDNUM] INT            NULL,
    [TREAT2_DOCTOR_CARDNUM]      INT            NULL,
    [TREAT2_CHAIRMAN_VK_CARDNUM] INT            NULL,
    [TREAT3_DOCTOR_CARDNUM]      INT            NULL,
    [TREAT3_CHAIRMAN_VK_CARDNUM] INT            NULL,
    [FINISH_DOCTOR_DEPT]         NVARCHAR (60)  NULL,
    [OpenDiagCode]               NVARCHAR (8)   NULL,
    [TREAT1_DOC_ID]              INT            NULL,
    [Proizv_name]                NVARCHAR (100) NULL,
    [Ceh]                        NVARCHAR (100) NULL,
    [CehCod]                     INT            NULL,
    [DiagNotOnlyFromMKB]         NVARCHAR (1)   NULL,
    [FINISH_DOCTOR_CARDNUM]      INT            NULL,
    [TabelNomer]                 NVARCHAR (100) NULL,
    [TREAT1_CHAIRMAN_VK_ID]      INT            NULL,
    [TREAT2_DOCTOR_ID]           INT            NULL,
    [TREAT2_CHAIRMAN_VK_ID]      INT            NULL,
    [TREAT3_DOCTOR_ID]           INT            NULL,
    [TREAT3_CHAIRMAN_VK_ID]      INT            NULL,
    [LN_FINISH_DOCTOR_ID]        INT            NULL,
    [TREAT1_dept1]               INT            NULL,
    [TREAT1_dept2]               INT            NULL,
    [TREAT2_dept1]               INT            NULL,
    [TREAT2_dept2]               INT            NULL,
    [TREAT3_dept1]               INT            NULL,
    [TREAT3_dept2]               INT            NULL,
    [FINISH_DOCTOR_DEPTID]       INT            NULL,
    CONSTRAINT [SickListPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [SickListToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

