CREATE TABLE [dbo].[SkriningovoeUziBeremennoy] (
    [ID]                  INT           NOT NULL,
    [PatID]               INT           NULL,
    [FulName]             NVARCHAR (50) NULL,
    [Age]                 NVARCHAR (50) NULL,
    [SrokBeremenosti]     INT           NULL,
    [LobnoZatRazmer]      FLOAT (53)    NULL,
    [BipRazmerGolovi]     FLOAT (53)    NULL,
    [OkrZhivota]          FLOAT (53)    NULL,
    [DlinBedrKostiL]      FLOAT (53)    NULL,
    [DlinBedrKostiP]      FLOAT (53)    NULL,
    [DlinKostGolenL]      FLOAT (53)    NULL,
    [DlinKostGolenP]      FLOAT (53)    NULL,
    [DlinPlechKostL]      FLOAT (53)    NULL,
    [DlinPlechKostP]      FLOAT (53)    NULL,
    [DlinKostPredplechL]  FLOAT (53)    NULL,
    [DlinKostPredplechP]  FLOAT (53)    NULL,
    [RazmPloda]           INT           NULL,
    [PredVesPloda]        INT           NULL,
    [DataIsl]             DATETIME      NULL,
    [DataPos]             DATETIME      NULL,
    [Zakluchenie]         NTEXT         NULL,
    [BokSheludochkiMozga] NVARCHAR (50) NULL,
    [Mozshechok]          NVARCHAR (50) NULL,
    [BolshayChisterna]    NVARCHAR (50) NULL,
    [Profil]              NVARCHAR (50) NULL,
    [Glaznici]            NVARCHAR (50) NULL,
    [NosogybnTreygol]     NVARCHAR (50) NULL,
    [Legkie]              NVARCHAR (50) NULL,
    [Kishecnik]           NVARCHAR (50) NULL,
    [Shelydok]            NVARCHAR (50) NULL,
    [SrezSerdca]          NVARCHAR (50) NULL,
    [Pozvonocnik]         NVARCHAR (50) NULL,
    [MocevoiPyziri]       NVARCHAR (50) NULL,
    [Pochki]              NVARCHAR (50) NULL,
    [PlacentaRaspol]      NVARCHAR (50) NULL,
    [NaDne]               FLOAT (53)    NULL,
    [TolshinaPlacenti]    NVARCHAR (50) NULL,
    [TolshinaDo]          FLOAT (53)    NULL,
    [StryktyraPlacenti]   NVARCHAR (50) NULL,
    [StepenZrelosti]      NVARCHAR (50) NULL,
    [Sootvetstvie]        NVARCHAR (50) NULL,
    [Kolvod]              NVARCHAR (50) NULL,
    [PypovinaIm]          NVARCHAR (50) NULL,
    [stenkiMatki]         NVARCHAR (50) NULL,
    [Vizyalizacia]        NVARCHAR (50) NULL,
    [Plodi]               NVARCHAR (50) NULL,
    [MiomatoznieYzli]     NVARCHAR (50) NULL,
    [OblostPredatkov]     NVARCHAR (50) NULL,
    [PeredZadSten]        NVARCHAR (50) NULL,
    [MestoPricrepl]       NVARCHAR (50) NULL,
    [KolPlodov]           NVARCHAR (1)  NULL,
    [Vrach1]              NVARCHAR (50) NULL,
    [Neproporcional]      NVARCHAR (1)  NULL,
    [PozvolautNe]         NVARCHAR (1)  NULL,
    CONSTRAINT [SkriningovoeUziBeremennoyPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [SkriningovoeUziBeremennoyToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

