CREATE TABLE [dbo].[Smad] (
    [ID]                                      INT           NOT NULL,
    [PatID]                                   INT           NULL,
    [Vrach]                                   NVARCHAR (50) NULL,
    [PolPatsienta]                            NVARCHAR (50) NULL,
    [Protokol]                                NTEXT         NULL,
    [SubmaksimalnayaChss]                     INT           NULL,
    [IshodnayaChssVMin]                       INT           NULL,
    [IshodnoeAd]                              INT           NULL,
    [IshodnoeAd1]                             INT           NULL,
    [MaksimalnayaChss]                        NVARCHAR (50) NULL,
    [MaksimalnoeAd]                           INT           NULL,
    [MaksimalnoeAd1]                          INT           NULL,
    [MetWt]                                   INT           NULL,
    [G]                                       INT           NULL,
    [VKmCh]                                   INT           NULL,
    [DolzhnayaNagruzkaMetWt]                  NVARCHAR (50) NULL,
    [ZhalobiVoVremyaTesta]                    NTEXT         NULL,
    [PrichinaOstanovki]                       NVARCHAR (50) NULL,
    [IzmeneniyaSTT]                           NTEXT         NULL,
    [NarusheniyaRitma]                        NTEXT         NULL,
    [TipReaktsii]                             NVARCHAR (50) NULL,
    [TolerantnostKFizicheskoyNagruzke]        NTEXT         NULL,
    [Primechaniya]                            NTEXT         NULL,
    [DataVizitaNachaloZapisi]                 DATETIME      NULL,
    [OkonchanieZapisi]                        DATETIME      NULL,
    [SredneeAdZaSutkiMmRtStNorma13085MmRtSt]  INT           NULL,
    [SredneeChssZaSutki]                      INT           NULL,
    [SredneeAdZaSutkiMmRtStNorma13085MmRtSt2] INT           NULL,
    [Dnem]                                    INT           NULL,
    [Dnem1]                                   INT           NULL,
    [Nochyu]                                  INT           NULL,
    [Nochyu2]                                 INT           NULL,
    [chssDnem]                                INT           NULL,
    [chssNochyu]                              INT           NULL,
    [ZaSutkiNorma020]                         INT           NULL,
    [ZaSutkiNorma0201]                        INT           NULL,
    [DnevnayaNormaDo25]                       INT           NULL,
    [DnevnayaNormaDo251]                      INT           NULL,
    [NochnayaNormaDo20]                       INT           NULL,
    [NochnayaNormaDo201]                      INT           NULL,
    [Sistolicheskogo]                         INT           NULL,
    [Diastolicheskogo]                        INT           NULL,
    CONSTRAINT [SmadPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [SmadToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

