CREATE TABLE [dbo].[SopostavlenieSmpIUslugLpu] (
    [ID]                           INT            NOT NULL,
    [PatID]                        INT            NULL,
    [MasterID]                     INT            NULL,
    [LPUServiceName]               NVARCHAR (400) NULL,
    [LPUServiceCode]               NVARCHAR (50)  NULL,
    [DServiceType]                 NVARCHAR (12)  NULL,
    [SubSMPName]                   NVARCHAR (400) NULL,
    [SubSMPCode]                   NVARCHAR (12)  NULL,
    [SubSMPSection]                NVARCHAR (1)   NULL,
    [Quant]                        FLOAT (53)     NULL,
    [Measure]                      NVARCHAR (50)  NULL,
    [SMPID]                        INT            NULL,
    [SubSMPID]                     INT            NULL,
    [LPUServiceID]                 INT            NULL,
    [chkbAllowToChangeDestService] NVARCHAR (1)   NULL,
    [AssignFrequency]              FLOAT (53)     NULL,
    [ODD]                          FLOAT (53)     NULL,
    [EKD]                          FLOAT (53)     NULL,
    [OddUnit]                      NVARCHAR (50)  NULL,
    [EkdUnit]                      NVARCHAR (50)  NULL,
    [ServiceLPU]                   NVARCHAR (50)  NULL,
    [AverageQuantity]              FLOAT (53)     NULL,
    [ebQuant]                      FLOAT (53)     NULL,
    [Vipolneno]                    NVARCHAR (1)   NULL,
    [DoctorID]                     INT            NULL,
    [DoctorName]                   NVARCHAR (50)  NULL,
    [PosGroup]                     NVARCHAR (50)  NULL,
    [GUID]                         NVARCHAR (32)  NULL,
    CONSTRAINT [SopostavlenieSmpIUslugLpuPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [SopostavlenieSmpIUslugLpuToMedicalcare] FOREIGN KEY ([MasterID]) REFERENCES [dbo].[Medicalcare] ([ID]) ON DELETE CASCADE
);

