CREATE TABLE [dbo].[StatisticheskayaKartaBolnogoStatsionaraForma066U99] (
    [ID]                                       INT           NOT NULL,
    [PatID]                                    INT           NULL,
    [DiagnozNapravivshegoUchrezhdeniya]        NVARCHAR (80) NULL,
    [DiagnozKlinicheskiyZaklyuchitelniy]       NVARCHAR (80) NULL,
    [OslozhnenieOsnovnogoDiagnoza]             NVARCHAR (80) NULL,
    [SoputstvuyusheeZabolevanie1]              NVARCHAR (80) NULL,
    [SoputstvuyusheeZabolevanie2]              NVARCHAR (80) NULL,
    [DiagnozPatologoanatomicheskiy]            NVARCHAR (50) NULL,
    [IspolzovanieSpetsialnoyApparaturi]        NVARCHAR (50) NULL,
    [Anesteziya]                               INT           NULL,
    [Data]                                     DATETIME      NULL,
    [PosleoperatsionnoeOslozhnenie]            NVARCHAR (50) NULL,
    [Hirurg]                                   INT           NULL,
    [Assistent]                                INT           NULL,
    [Anesteziolog]                             INT           NULL,
    [IshodPrebivaniyaVStatsionare]             INT           NULL,
    [IshodLecheniyaVStatsionare]               INT           NULL,
    [DataIVremyaVipiski]                       DATETIME      NULL,
    [KolVoKoykoDney]                           FLOAT (53)    NULL,
    [DataPostupleniya]                         DATETIME      NULL,
    [KodDiagnozaNapravivshegoUchrezhdeniya]    NVARCHAR (10) NULL,
    [KodKlinicheskogoZaklyuchitelnogoDiagnoza] NVARCHAR (10) NULL,
    [KodOslozhneniyaOsnovnogoDiagnoza]         NVARCHAR (10) NULL,
    [KodSoputstvuyushegoZabolevaniya1]         NVARCHAR (50) NULL,
    [OsnovnayaHirurgicheskayaOperatsiya]       NVARCHAR (50) NULL,
    [KodSoputstvuyushegoZabolevaniya2]         NVARCHAR (50) NULL,
    [MasterID]                                 INT           NULL,
    CONSTRAINT [StatisticheskayaKartaBolnogoStatsionaraForma066U99PrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [StatisticheskayaKartaBolnogoStatsionaraForma066U99ToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

