CREATE TABLE [dbo].[STREET] (
    [NAME]   NVARCHAR (40) NULL,
    [SOCR]   NVARCHAR (10) NULL,
    [CODE]   NVARCHAR (17) NULL,
    [INDEX]  NVARCHAR (6)  NULL,
    [GNINMB] NVARCHAR (4)  NULL,
    [UNO]    NVARCHAR (4)  NULL,
    [OCATD]  NVARCHAR (11) NULL
);

