CREATE TABLE [dbo].[TAP] (
    [ID]                       INT            NOT NULL,
    [PatID]                    INT            NULL,
    [DataPriema]               DATETIME       NULL,
    [SocStatus]                INT            NULL,
    [Invalidnost]              NVARCHAR (50)  NULL,
    [KodLgoti]                 INT            NULL,
    [Polis]                    NVARCHAR (50)  NULL,
    [Gorod]                    INT            NULL,
    [GorodText]                NVARCHAR (50)  NULL,
    [Vrach1]                   INT            NULL,
    [Vrach2]                   INT            NULL,
    [AttID]                    INT            NULL,
    [PaymentType]              INT            NULL,
    [PlaceAttendance]          INT            NULL,
    [PlaceAttendanceText]      NVARCHAR (50)  NULL,
    [VisitGoal]                INT            NULL,
    [VisitGoalText]            NVARCHAR (50)  NULL,
    [VisitResult]              INT            NULL,
    [VisitResultText]          NVARCHAR (50)  NULL,
    [DiagMain]                 NVARCHAR (6)   NULL,
    [DiagCharacter]            INT            NULL,
    [DiagCharacterText]        NVARCHAR (50)  NULL,
    [DispansUchet]             INT            NULL,
    [DispansUchetText]         NVARCHAR (50)  NULL,
    [Travma]                   INT            NULL,
    [TravmaText]               NVARCHAR (50)  NULL,
    [DiagSoput]                NVARCHAR (6)   NULL,
    [DiagSoputCharacter]       INT            NULL,
    [DiagSoputCharacterText]   NVARCHAR (50)  NULL,
    [DispansUchetSoput]        INT            NULL,
    [DispansUchetSoputText]    NVARCHAR (50)  NULL,
    [DiagChangedDict]          NVARCHAR (50)  NULL,
    [DiagChanged]              NVARCHAR (6)   NULL,
    [DateDiagChanged]          DATETIME       NULL,
    [ListokNetr]               INT            NULL,
    [ListokNetrText]           NVARCHAR (50)  NULL,
    [PrichinaVidachListka]     INT            NULL,
    [PrichinaVidachListkaText] NVARCHAR (50)  NULL,
    [VozrastLica]              NVARCHAR (50)  NULL,
    [SexLica]                  NVARCHAR (50)  NULL,
    [Recept1]                  NVARCHAR (50)  NULL,
    [Recept2]                  NVARCHAR (50)  NULL,
    [Recept3]                  NVARCHAR (50)  NULL,
    [Recept4]                  NVARCHAR (50)  NULL,
    [DiagUstanovlen]           NVARCHAR (50)  NULL,
    [DiagSoputUstanovlen]      NVARCHAR (50)  NULL,
    [Vrach1Dict]               INT            NULL,
    [Vrach2Dict]               INT            NULL,
    [NomerNapravleniya]        INT            NULL,
    [Vrach3Dict]               INT            NULL,
    [Vrach3]                   INT            NULL,
    [TypePriem]                NVARCHAR (50)  NULL,
    [VidPomoshi]               NVARCHAR (50)  NULL,
    [Sanatsiya]                BIT            NULL,
    [FormulaZuba]              NVARCHAR (20)  NULL,
    [Material]                 NVARCHAR (100) NULL,
    [Duration]                 INT            NULL,
    [IsStomatolog]             BIT            NULL,
    [VremyaPriema]             DATETIME       NULL,
    [Ceh]                      NVARCHAR (50)  NULL,
    [TabelNum]                 NVARCHAR (50)  NULL,
    [DopPriem]                 BIT            NULL,
    [Poverhnosti]              NVARCHAR (100) NULL,
    [VidMP]                    NVARCHAR (50)  NULL,
    CONSTRAINT [TAPPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [TAPToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

