CREATE TABLE [dbo].[TechenieRodov] (
    [ID]                                                 INT           NOT NULL,
    [PatID]                                              INT           NULL,
    [Data]                                               DATETIME      NULL,
    [ShvatkiNachalis]                                    FLOAT (53)    NULL,
    [VodiOtoshli]                                        FLOAT (53)    NULL,
    [KolichestvoVod]                                     INT           NULL,
    [KachestvoVod]                                       NVARCHAR (50) NULL,
    [PolnoeOtkritie]                                     FLOAT (53)    NULL,
    [NachaloPotug]                                       FLOAT (53)    NULL,
    [RebenokRodilsya]                                    FLOAT (53)    NULL,
    [Perviy]                                             NVARCHAR (50) NULL,
    [Data1]                                              DATETIME      NULL,
    [Vremya]                                             FLOAT (53)    NULL,
    [DictCombo1]                                         NVARCHAR (50) NULL,
    [DictCombo2]                                         NVARCHAR (50) NULL,
    [Pol]                                                NVARCHAR (50) NULL,
    [MassaVes]                                           INT           NULL,
    [Rost]                                               INT           NULL,
    [OkruzhnostGolovki]                                  INT           NULL,
    [Grudi]                                              INT           NULL,
    [Vtoroy]                                             NVARCHAR (50) NULL,
    [Data2]                                              DATETIME      NULL,
    [Vremya2]                                            FLOAT (53)    NULL,
    [DictCombo3]                                         NVARCHAR (50) NULL,
    [DictCombo4]                                         NVARCHAR (50) NULL,
    [Pol2]                                               NVARCHAR (50) NULL,
    [MassaVes2]                                          INT           NULL,
    [Rost2]                                              INT           NULL,
    [OkruzhnostGolovki1]                                 INT           NULL,
    [Grudi1]                                             INT           NULL,
    [ProfilaktikaGonoblenoreiNovorozhdennogoProizvedena] NVARCHAR (50) NULL,
    [OtsenkaSostoyaniyaNovorozhdennogoPoShkaleApgar]     INT           NULL,
    [PosledVidelilsya]                                   NVARCHAR (50) NULL,
    [Cherez]                                             FLOAT (53)    NULL,
    [DetskoeMesto]                                       NVARCHAR (50) NULL,
    [Obolochki]                                          NVARCHAR (50) NULL,
    [Dlina]                                              INT           NULL,
    [Vokrug]                                             NVARCHAR (50) NULL,
    [Osobennosti]                                        NVARCHAR (50) NULL,
    [KrovopoteryaVRodah]                                 INT           NULL,
    [PsihoprofilakticheskayaPodgotovka]                  NVARCHAR (1)  NULL,
    [MedikamentoznoeObezbolivanie]                       NVARCHAR (50) NULL,
    [Effekt]                                             NVARCHAR (50) NULL,
    [Obshaya]                                            INT           NULL,
    [IPeriod]                                            INT           NULL,
    [IIPeriod]                                           INT           NULL,
    [IIIPeriod]                                          INT           NULL,
    [PrinyalaRebenka]                                    NVARCHAR (50) NULL,
    [PosledOsmatrival]                                   NVARCHAR (50) NULL,
    [DezhurniyVrach]                                     NVARCHAR (50) NULL,
    [DictCombo5]                                         NVARCHAR (50) NULL,
    CONSTRAINT [TechenieRodovPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [TechenieRodovToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

