CREATE TABLE [dbo].[TitulniyListF003U] (
    [ID]                                      INT            NOT NULL,
    [PatID]                                   INT            NULL,
    [DataIVremyaPostupleniya]                 DATETIME       NULL,
    [DataIVremyaVipiski1]                     DATETIME       NULL,
    [DataIVremyaVipiski]                      DATETIME       NULL,
    [Otdelenie]                               INT            NULL,
    [PerevedenVOtdelenie]                     NVARCHAR (50)  NULL,
    [ProvedenoKoykoDney]                      INT            NULL,
    [VidiTransportirovki]                     INT            NULL,
    [GruppaKrovi]                             NVARCHAR (50)  NULL,
    [RezusPrinadlezhnost]                     NVARCHAR (50)  NULL,
    [PobochnoeDeystvieLekarstvNeperenosimost] NTEXT          NULL,
    [familia]                                 NVARCHAR (50)  NULL,
    [Otchestvo]                               NVARCHAR (50)  NULL,
    [Imya]                                    NVARCHAR (50)  NULL,
    [pol]                                     NVARCHAR (1)   NULL,
    [vozrast]                                 NVARCHAR (50)  NULL,
    [mesto]                                   NVARCHAR (50)  NULL,
    [adres]                                   NTEXT          NULL,
    [adres1]                                  NVARCHAR (50)  NULL,
    [rabota1]                                 NTEXT          NULL,
    [kemnapravlen]                            NVARCHAR (100) NULL,
    [chas]                                    NVARCHAR (50)  NULL,
    [GospitalizirovanVPlanovomPoryadke]       BIT            NULL,
    [DataUstanovleniya]                       DATETIME       NULL,
    [DataIVremyaPostupleniya1]                DATETIME       NULL,
    [Palata]                                  INT            NULL,
    [Extren]                                  BIT            NULL,
    [DiagNapravl]                             NVARCHAR (6)   NULL,
    [DiagPost]                                NVARCHAR (6)   NULL,
    [DiagKlin]                                NVARCHAR (6)   NULL,
    [Chasotk]                                 BIT            NULL,
    [Policy]                                  NVARCHAR (50)  NULL,
    [pressure]                                NVARCHAR (50)  NULL,
    [Temp]                                    NVARCHAR (50)  NULL,
    [weight]                                  NVARCHAR (50)  NULL,
    [CardNum]                                 INT            NULL,
    [DiagNapravlLabel]                        NTEXT          NULL,
    [Otdelenie_vipiski]                       INT            NULL,
    [tip_postupleniya]                        NVARCHAR (50)  NULL,
    [DiagPostLabel]                           NTEXT          NULL,
    [Status_vipiski]                          NVARCHAR (100) NULL,
    [DiagKlinLabel]                           NTEXT          NULL,
    [ID001]                                   INT            NULL,
    [Povtornost_postupleniya]                 NVARCHAR (50)  NULL,
    [polis]                                   NVARCHAR (100) NULL,
    [F20]                                     NVARCHAR (50)  NULL,
    [Gepatit]                                 NVARCHAR (50)  NULL,
    [EditBox1]                                NVARCHAR (50)  NULL,
    [Dift]                                    NVARCHAR (50)  NULL,
    [Fogk]                                    NVARCHAR (50)  NULL,
    [GepatitDat]                              NVARCHAR (50)  NULL,
    [KSG]                                     NVARCHAR (50)  NULL,
    [PrintSogl]                               NVARCHAR (1)   NULL,
    CONSTRAINT [TitulniyListF003UPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [TitulniyListF003UToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

