CREATE TABLE [dbo].[TitulniyListSankurKniga] (
    [ID]                                                                INT            NOT NULL,
    [PatID]                                                             INT            NULL,
    [familia]                                                           NVARCHAR (50)  NULL,
    [imia]                                                              NVARCHAR (50)  NULL,
    [otchestvo]                                                         NVARCHAR (50)  NULL,
    [BesedaOProtivopozharnoyBezopasnostiVnutrennemRasporyadkeProvedena] NVARCHAR (1)   NULL,
    [EditBox1]                                                          NVARCHAR (50)  NULL,
    [EditBox2]                                                          NVARCHAR (50)  NULL,
    [EditBox3]                                                          NVARCHAR (50)  NULL,
    [EditBox4]                                                          NVARCHAR (50)  NULL,
    [Memo1]                                                             NTEXT          NULL,
    [rost1]                                                             FLOAT (53)     NULL,
    [rost2]                                                             FLOAT (53)     NULL,
    [ves1]                                                              FLOAT (53)     NULL,
    [ves2]                                                              FLOAT (53)     NULL,
    [ads1]                                                              INT            NULL,
    [add1]                                                              INT            NULL,
    [ads2]                                                              INT            NULL,
    [add2]                                                              INT            NULL,
    [Combo1]                                                            NVARCHAR (50)  NULL,
    [Combo2]                                                            NVARCHAR (50)  NULL,
    [Combo3]                                                            NVARCHAR (50)  NULL,
    [Combo4]                                                            NVARCHAR (50)  NULL,
    [Memo2]                                                             NTEXT          NULL,
    [DiagCode1]                                                         NVARCHAR (50)  NULL,
    [Diagnozosnovnoy15]                                                 NVARCHAR (255) NULL,
    [DiagSoput3Cb]                                                      NVARCHAR (255) NULL,
    [DiagSoput4]                                                        NVARCHAR (50)  NULL,
    [DiagSoput4Cb]                                                      NVARCHAR (255) NULL,
    [sroks]                                                             DATETIME       NULL,
    [srokpo]                                                            DATETIME       NULL,
    [DiagSoput3]                                                        NVARCHAR (50)  NULL,
    [DictCombo1]                                                        NVARCHAR (50)  NULL,
    CONSTRAINT [TitulniyListSankurKnigaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [TitulniyListSankurKnigaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

