CREATE TABLE [dbo].[transfuziya] (
    [ID]                                           INT            NOT NULL,
    [Perelivanie]                                  NVARCHAR (20)  NULL,
    [Rh]                                           NVARCHAR (1)   NULL,
    [GruppaKrovi]                                  NVARCHAR (3)   NULL,
    [PokazaniyaKPerelivaniyu]                      NVARCHAR (80)  NULL,
    [DozaPerelitoyTransfuzionnoySredi]             INT            NULL,
    [NomerEtiketki]                                NVARCHAR (15)  NULL,
    [ZavodIzgotovitel]                             NVARCHAR (80)  NULL,
    [DataVipuska]                                  DATETIME       NULL,
    [SposobPerelivaniyaKrovi]                      NVARCHAR (50)  NULL,
    [TransfuzionnieReaktsii]                       NVARCHAR (10)  NULL,
    [OslozhneniyaPoslePerelivaniya]                NVARCHAR (1)   NULL,
    [oslogneniya]                                  NTEXT          NULL,
    [TransfuzionnayaSreda]                         NVARCHAR (30)  NULL,
    [GruppaKrovi1]                                 NVARCHAR (3)   NULL,
    [Rh1]                                          NVARCHAR (1)   NULL,
    [GemodinamichesKiePreparati]                   NVARCHAR (50)  NULL,
    [Dezintoksikatsionnie]                         NVARCHAR (50)  NULL,
    [PreparatiDlyaParenteralnogoBelkovogoPitaniya] NVARCHAR (50)  NULL,
    [Дата]                                         DATETIME       NULL,
    [PatFIO]                                       NVARCHAR (100) NULL,
    [Age]                                          NVARCHAR (15)  NULL,
    [CardNum]                                      NVARCHAR (10)  NULL,
    [Автор]                                        INT            NULL,
    [PatId]                                        INT            NULL,
    CONSTRAINT [transfuziyaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC)
);

