CREATE TABLE [dbo].[TrichologistFirstExamination] (
    [ID]                     INT           NOT NULL,
    [PatID]                  INT           NULL,
    [FirstHairLossDate]      NVARCHAR (50) NULL,
    [FirstHairLossNotes]     NTEXT         NULL,
    [RateOfHairLoss]         NVARCHAR (50) NULL,
    [Pillow]                 NVARCHAR (1)  NULL,
    [CombBrush]              NVARCHAR (1)  NULL,
    [SinkDrain]              NVARCHAR (1)  NULL,
    [NoneOfThem]             NVARCHAR (1)  NULL,
    [Shoulders]              NVARCHAR (1)  NULL,
    [Classification]         NVARCHAR (50) NULL,
    [Bitemporal]             NVARCHAR (1)  NULL,
    [Frontal]                NVARCHAR (1)  NULL,
    [Vertex]                 NVARCHAR (1)  NULL,
    [Back]                   NVARCHAR (1)  NULL,
    [OvalTop]                NVARCHAR (1)  NULL,
    [DiffuseHairLoss]        NVARCHAR (50) NULL,
    [Ariata]                 NVARCHAR (1)  NULL,
    [DifAreata]              NVARCHAR (1)  NULL,
    [Cicatricial]            NVARCHAR (1)  NULL,
    [Trichotillomania]       NVARCHAR (1)  NULL,
    [MouthEaten]             NVARCHAR (1)  NULL,
    [BackScalp]              NVARCHAR (50) NULL,
    [TopScalp]               NVARCHAR (50) NULL,
    [FrontLine]              NVARCHAR (50) NULL,
    [Sides]                  NVARCHAR (50) NULL,
    [OnTop]                  NVARCHAR (1)  NULL,
    [OnSide]                 NVARCHAR (1)  NULL,
    [OnBack]                 NVARCHAR (1)  NULL,
    [AllOver]                NVARCHAR (1)  NULL,
    [AllOverMoreOnTop]       NVARCHAR (1)  NULL,
    [Eyebrows]               NVARCHAR (1)  NULL,
    [Body]                   NVARCHAR (1)  NULL,
    [Hirsutism]              NVARCHAR (1)  NULL,
    [Program]                NVARCHAR (50) NULL,
    [MAGA]                   NVARCHAR (1)  NULL,
    [FAGA]                   NVARCHAR (1)  NULL,
    [TE]                     NVARCHAR (1)  NULL,
    [Systemic]               NVARCHAR (1)  NULL,
    [ScalpDisorders]         NVARCHAR (1)  NULL,
    [Areata]                 NVARCHAR (1)  NULL,
    [HairStructure]          NVARCHAR (1)  NULL,
    [Miscellaneous]          NVARCHAR (1)  NULL,
    [Seborreah]              NVARCHAR (1)  NULL,
    [Psoriasis]              NVARCHAR (1)  NULL,
    [SeborrheicDermatitis]   NVARCHAR (1)  NULL,
    [AroundPuberty]          NVARCHAR (1)  NULL,
    [AroundMenopause]        NVARCHAR (1)  NULL,
    [EmotioanalStress]       NVARCHAR (1)  NULL,
    [ScalpDisprder]          NVARCHAR (1)  NULL,
    [FebrilSevereIllness]    NVARCHAR (1)  NULL,
    [CrashDiet]              NVARCHAR (1)  NULL,
    [Diet]                   NVARCHAR (1)  NULL,
    [WeightLoss]             NVARCHAR (1)  NULL,
    [TheroidDisorder]        NVARCHAR (1)  NULL,
    [BirthControlPills]      NVARCHAR (1)  NULL,
    [Anemia]                 NVARCHAR (1)  NULL,
    [Minoxidil]              NVARCHAR (1)  NULL,
    [Drugs]                  NVARCHAR (1)  NULL,
    [HairCosmeticTreatments] NVARCHAR (1)  NULL,
    [IntensiveSports]        NVARCHAR (1)  NULL,
    [HairTransplantSurgery]  NVARCHAR (1)  NULL,
    [AutoimmuneImalanace]    NVARCHAR (1)  NULL,
    [PostSurgery]            NVARCHAR (1)  NULL,
    [HormonalImbalance]      NVARCHAR (1)  NULL,
    [Chemicals]              NVARCHAR (1)  NULL,
    [Family]                 NVARCHAR (1)  NULL,
    [AfterChildbirth]        NVARCHAR (1)  NULL,
    [Details]                NTEXT         NULL,
    [DocDate]                DATETIME      NULL,
    [DocTime]                DATETIME      NULL,
    [DoctorID]               INT           NULL,
    [Program0]               NVARCHAR (1)  NULL,
    [Program1]               NVARCHAR (1)  NULL,
    [Program2]               NVARCHAR (1)  NULL,
    [Program3]               NVARCHAR (1)  NULL,
    [Program4]               NVARCHAR (1)  NULL,
    [Program5]               NVARCHAR (1)  NULL,
    [Program6]               NVARCHAR (1)  NULL,
    CONSTRAINT [TrichologistFirstExaminationPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [TrichologistFirstExaminationToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

