CREATE TABLE [dbo].[TrichologistTrichogram] (
    [ID]                    INT           NOT NULL,
    [PatID]                 INT           NULL,
    [Density1]              IMAGE         NULL,
    [Density2]              IMAGE         NULL,
    [Density3]              IMAGE         NULL,
    [Density4]              IMAGE         NULL,
    [Density5]              IMAGE         NULL,
    [Density6]              IMAGE         NULL,
    [Density7]              IMAGE         NULL,
    [Density8]              IMAGE         NULL,
    [VellusLow0]            BIT           NULL,
    [VellusMed0]            BIT           NULL,
    [VellusHigh0]           BIT           NULL,
    [InterLow0]             BIT           NULL,
    [InterMed0]             BIT           NULL,
    [InterHigh0]            BIT           NULL,
    [TerminalLow0]          BIT           NULL,
    [TerminalMed0]          BIT           NULL,
    [TerminalHigh0]         BIT           NULL,
    [VellusLow1]            BIT           NULL,
    [VellusMed1]            BIT           NULL,
    [VellusHigh1]           BIT           NULL,
    [InterLow1]             BIT           NULL,
    [InterMed1]             BIT           NULL,
    [InterHigh1]            BIT           NULL,
    [TerminalLow1]          BIT           NULL,
    [TerminalMed1]          BIT           NULL,
    [TerminalHigh1]         BIT           NULL,
    [VellusLow2]            BIT           NULL,
    [VellusMed2]            BIT           NULL,
    [VellusHigh2]           BIT           NULL,
    [InterLow2]             BIT           NULL,
    [InterMed2]             BIT           NULL,
    [InterHigh2]            BIT           NULL,
    [TerminalLow2]          BIT           NULL,
    [TerminalMed2]          BIT           NULL,
    [TerminalHigh2]         BIT           NULL,
    [VellusLow3]            BIT           NULL,
    [VellusMed3]            BIT           NULL,
    [VellusHigh3]           BIT           NULL,
    [InterLow3]             BIT           NULL,
    [InterMed3]             BIT           NULL,
    [InterHigh3]            BIT           NULL,
    [TerminalLow3]          BIT           NULL,
    [TerminalMed3]          BIT           NULL,
    [TerminalHigh3]         BIT           NULL,
    [Scalp1]                IMAGE         NULL,
    [Scalp2]                IMAGE         NULL,
    [Scalp3]                IMAGE         NULL,
    [Scalp4]                IMAGE         NULL,
    [Scalp5]                IMAGE         NULL,
    [Scalp6]                IMAGE         NULL,
    [Scalp7]                IMAGE         NULL,
    [Scalp8]                IMAGE         NULL,
    [Paleness]              NVARCHAR (1)  NULL,
    [Elasticity]            NVARCHAR (1)  NULL,
    [Redness]               NVARCHAR (1)  NULL,
    [Itching]               NVARCHAR (1)  NULL,
    [Dandraft]              NVARCHAR (1)  NULL,
    [BlocPore]              NVARCHAR (1)  NULL,
    [SensibilityPain]       NVARCHAR (1)  NULL,
    [RedPore]               NVARCHAR (1)  NULL,
    [Oilyness]              NVARCHAR (1)  NULL,
    [Dryness]               NVARCHAR (1)  NULL,
    [Pruritis]              NVARCHAR (1)  NULL,
    [ScalpNote1]            NVARCHAR (50) NULL,
    [ScalpNote2]            NVARCHAR (50) NULL,
    [ScalpNote3]            NVARCHAR (50) NULL,
    [ScalpNote4]            NVARCHAR (50) NULL,
    [ScalpNote5]            NVARCHAR (50) NULL,
    [ScalpNote6]            NVARCHAR (50) NULL,
    [ScalpNote7]            NVARCHAR (50) NULL,
    [ScalpNote8]            NVARCHAR (50) NULL,
    [ScalpNote9]            NVARCHAR (50) NULL,
    [ScalpNote10]           NVARCHAR (50) NULL,
    [ScalpNote11]           NVARCHAR (50) NULL,
    [Roots1]                IMAGE         NULL,
    [Roots2]                IMAGE         NULL,
    [Roots3]                IMAGE         NULL,
    [Roots4]                IMAGE         NULL,
    [Roots5]                IMAGE         NULL,
    [Roots6]                IMAGE         NULL,
    [Roots7]                IMAGE         NULL,
    [Roots8]                IMAGE         NULL,
    [Normal]                NVARCHAR (1)  NULL,
    [RootNote1]             NVARCHAR (50) NULL,
    [RootNote2]             NVARCHAR (50) NULL,
    [Atrophic]              NVARCHAR (1)  NULL,
    [RootNote3]             NVARCHAR (50) NULL,
    [Distrophic]            NVARCHAR (1)  NULL,
    [RootNote4]             NVARCHAR (50) NULL,
    [Toxins]                NVARCHAR (1)  NULL,
    [RootNote5]             NVARCHAR (50) NULL,
    [Telogen]               NVARCHAR (1)  NULL,
    [RootNote6]             NVARCHAR (50) NULL,
    [Darkness]              NVARCHAR (1)  NULL,
    [RootNote7]             NVARCHAR (50) NULL,
    [Constriction]          NVARCHAR (1)  NULL,
    [Photos1]               IMAGE         NULL,
    [Photos2]               IMAGE         NULL,
    [Photos3]               IMAGE         NULL,
    [Photos4]               IMAGE         NULL,
    [Photos5]               IMAGE         NULL,
    [Photos6]               IMAGE         NULL,
    [Photos7]               IMAGE         NULL,
    [Photos8]               IMAGE         NULL,
    [Hair1]                 IMAGE         NULL,
    [Hair2]                 IMAGE         NULL,
    [Hair3]                 IMAGE         NULL,
    [Hair4]                 IMAGE         NULL,
    [Hair5]                 IMAGE         NULL,
    [Hair6]                 IMAGE         NULL,
    [Hair7]                 IMAGE         NULL,
    [Hair8]                 IMAGE         NULL,
    [Fragility]             NVARCHAR (1)  NULL,
    [HairNote1]             NVARCHAR (50) NULL,
    [Roughness]             NVARCHAR (1)  NULL,
    [HairNote2]             NVARCHAR (50) NULL,
    [ChemicalDamage]        NVARCHAR (1)  NULL,
    [HairNote3]             NVARCHAR (50) NULL,
    [SebumHairBasis]        NVARCHAR (1)  NULL,
    [HairNote4]             NVARCHAR (50) NULL,
    [SebumLightwiseTheHair] NVARCHAR (1)  NULL,
    [HairNote5]             NVARCHAR (50) NULL,
    [DrynessRoot]           NVARCHAR (1)  NULL,
    [HairNote6]             NVARCHAR (50) NULL,
    [Tongue1]               IMAGE         NULL,
    [Tongue2]               IMAGE         NULL,
    [Tongue3]               IMAGE         NULL,
    [Tongue4]               IMAGE         NULL,
    [Tongue5]               IMAGE         NULL,
    [Tongue6]               IMAGE         NULL,
    [Tongue7]               IMAGE         NULL,
    [Tongue8]               IMAGE         NULL,
    [DocDate]               DATETIME      NULL,
    [DocTime]               DATETIME      NULL,
    [DoctorID]              INT           NULL,
    CONSTRAINT [TrichologistTrichogramPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [TrichologistTrichogramToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

