CREATE TABLE [dbo].[USG1] (
    [Id]         INT           NOT NULL,
    [DocTypeId]  INT           NULL,
    [MasterID]   INT           NULL,
    [ExecDate]   DATETIME      NULL,
    [FDLM]       DATETIME      NULL,
    [Fetuses]    INT           NULL,
    [Predl]      VARCHAR (150) NULL,
    [BPR]        VARCHAR (150) NULL,
    [LZR]        VARCHAR (150) NULL,
    [Moz]        VARCHAR (150) NULL,
    [Zhivot]     VARCHAR (150) NULL,
    [Bedro]      VARCHAR (150) NULL,
    [Age]        INT           NULL,
    [Weight]     INT           NULL,
    [HeartD]     VARCHAR (150) NULL,
    [CSS]        INT           NULL,
    [IntZev]     VARCHAR (150) NULL,
    [PlazRasp]   VARCHAR (150) NULL,
    [PlazRasp1]  VARCHAR (150) NULL,
    [PlazThick]  VARCHAR (150) NULL,
    [PlazZrel]   VARCHAR (150) NULL,
    [PlazNiz]    VARCHAR (150) NULL,
    [PlazNiz1]   VARCHAR (150) NULL,
    [Obv]        VARCHAR (150) NULL,
    [Voda]       VARCHAR (150) NULL,
    [Poroki]     NTEXT         NULL,
    [Doppler]    NTEXT         NULL,
    [Zakl]       NTEXT         NULL,
    [Img1Id]     IMAGE         NULL,
    [Img2Id]     IMAGE         NULL,
    [Img3Id]     IMAGE         NULL,
    [Img4Id]     IMAGE         NULL,
    [Img5Id]     IMAGE         NULL,
    [OperId]     INT           NULL,
    [OriginalID] INT           NULL,
    CONSTRAINT [PK_USG1] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_USG1_ECFAnPreg] FOREIGN KEY ([MasterID]) REFERENCES [dbo].[ECFAnPreg] ([Id]) ON DELETE CASCADE
);

