CREATE TABLE [dbo].[USG2] (
    [Id]         INT           NOT NULL,
    [DocTypeId]  INT           NULL,
    [MasterID]   INT           NULL,
    [ExecDate]   DATETIME      NULL,
    [LMP]        DATETIME      NULL,
    [T1]         VARCHAR (255) NULL,
    [T2]         VARCHAR (255) NULL,
    [T3]         VARCHAR (255) NULL,
    [T4]         VARCHAR (255) NULL,
    [T5]         VARCHAR (255) NULL,
    [T51]        VARCHAR (255) NULL,
    [T6]         VARCHAR (255) NULL,
    [T7]         VARCHAR (255) NULL,
    [T8]         VARCHAR (255) NULL,
    [T9]         VARCHAR (255) NULL,
    [T10]        VARCHAR (255) NULL,
    [T11]        VARCHAR (255) NULL,
    [T12]        VARCHAR (255) NULL,
    [T13]        VARCHAR (255) NULL,
    [T14]        VARCHAR (255) NULL,
    [T15]        NTEXT         NULL,
    [Preg]       BIT           NULL,
    [Zakl]       NTEXT         NULL,
    [OperId]     INT           NULL,
    [OriginalID] INT           NULL,
    CONSTRAINT [PK_USG2] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_USG2_ECFAnPreg] FOREIGN KEY ([MasterID]) REFERENCES [dbo].[ECFAnPreg] ([Id]) ON DELETE CASCADE
);

