CREATE TABLE [dbo].[UziGlaza] (
    [ID]                                               INT          NOT NULL,
    [PatID]                                            INT          NULL,
    [Kontur]                                           INT          NULL,
    [EhoStruktura]                                     INT          NULL,
    [ZaSchetVklyucheniy]                               INT          NULL,
    [OtsloykaSetchatki]                                NVARCHAR (1) NULL,
    [PodSetchatoyObolochkoyOpredelyaetsyaUchastok]     INT          NULL,
    [HarakterniyDlya]                                  INT          NULL,
    [DopolnitelnieObrazovaniyaVRetrobulbarnoyOblasti]  NVARCHAR (1) NULL,
    [DopolnitelnieVklyucheniya]                        NVARCHAR (1) NULL,
    [Obizvestvleniya]                                  NVARCHAR (1) NULL,
    [KanalZritelnogoNerva]                             INT          NULL,
    [Data]                                             DATETIME     NULL,
    [NaVisotuDo]                                       INT          NULL,
    [Vid]                                              INT          NULL,
    [LokalizuetsyaV]                                   INT          NULL,
    [VProektsii]                                       INT          NULL,
    [Razmer]                                           INT          NULL,
    [EhoStrukturaL]                                    INT          NULL,
    [EhoGennost]                                       INT          NULL,
    [Forma]                                            INT          NULL,
    [STKonturL]                                        INT          NULL,
    [Chetkiy]                                          NVARCHAR (1) NULL,
    [NeChetkiy]                                        NVARCHAR (1) NULL,
    [KonturL]                                          INT          NULL,
    [STEhoStrukturaL]                                  INT          NULL,
    [OtsloykaSetchatkiL]                               NVARCHAR (1) NULL,
    [ZaSchetVklyucheniyL]                              INT          NULL,
    [HarakterniyDlyaL]                                 INT          NULL,
    [PodSetchatoyObolochkoyOpredelyaetsyaUchastokL]    INT          NULL,
    [DopolnitelnieObrazovaniyaVRetrobulbarnoyOblastiL] NVARCHAR (1) NULL,
    [DopolnitelnieVklyucheniyaL]                       NVARCHAR (1) NULL,
    [ObizvestvleniyaL]                                 NVARCHAR (1) NULL,
    [KanalZritelnogoNervaL]                            INT          NULL,
    [DopolnitelnieDannieUzi]                           NTEXT        NULL,
    [NaVisotuDoL]                                      INT          NULL,
    [Vid1]                                             INT          NULL,
    [LokalizuetsyaV1]                                  INT          NULL,
    [VProektsiiL]                                      INT          NULL,
    [RazmerL]                                          INT          NULL,
    [DOEhoStrukturaL]                                  INT          NULL,
    [DOEhoGennostL]                                    INT          NULL,
    [Chetkiy1]                                         NVARCHAR (1) NULL,
    [NeChetkiy1]                                       NVARCHAR (1) NULL,
    [DOKonturL]                                        INT          NULL,
    [Forma1]                                           INT          NULL,
    [Image]                                            IMAGE        NULL,
    [DopolnitelnieDannieUzi1]                          NTEXT        NULL,
    [NomerIssledovaniya1]                              INT          NULL,
    [Vrach1]                                           INT          NULL,
    [Zaklyuchenie2]                                    NTEXT        NULL,
    [Zaklyuchenie1]                                    NTEXT        NULL,
    [Zaklyuchenie]                                     NTEXT        NULL,
    CONSTRAINT [UziGlazaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UziGlazaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

