CREATE TABLE [dbo].[UziGinekologicheskoe] (
    [ID]                                  INT           NOT NULL,
    [PatID]                               INT           NULL,
    [Data]                                DATETIME      NULL,
    [NomerIssledovaniya]                  INT           NULL,
    [Polojenie]                           NVARCHAR (50) NULL,
    [ChetkieNechetkie]                    NVARCHAR (50) NULL,
    [RovnNerovn]                          NVARCHAR (50) NULL,
    [RazmeriMatki1]                       FLOAT (53)    NULL,
    [RazmeriMatki2]                       FLOAT (53)    NULL,
    [RazmeriMatki3]                       FLOAT (53)    NULL,
    [OdnorodnayaNeodnorodnaya]            NVARCHAR (50) NULL,
    [Zaschetchego]                        NVARCHAR (50) NULL,
    [Polost]                              NVARCHAR (50) NULL,
    [PolostKomment]                       NVARCHAR (50) NULL,
    [mEho]                                FLOAT (53)    NULL,
    [Den]                                 INT           NULL,
    [DenKomment]                          NVARCHAR (50) NULL,
    [Otrajenie]                           NVARCHAR (50) NULL,
    [Sootvetstv]                          NVARCHAR (50) NULL,
    [RazmerSheykiMatki]                   NVARCHAR (50) NULL,
    [RazmeriSheykiMatkikommenti]          NVARCHAR (50) NULL,
    [OdnorodnayaNeodnorodnayaSheykaMatki] NVARCHAR (50) NULL,
    [ZaschetchegoSheykaMatki]             NVARCHAR (50) NULL,
    [CervikalniyKanal]                    NVARCHAR (50) NULL,
    [RazmeriPrYaichn1]                    FLOAT (53)    NULL,
    [RazmeriPrYaichn2]                    FLOAT (53)    NULL,
    [RazmeriPrYaichn3]                    FLOAT (53)    NULL,
    [RazmeriPrYaichnF]                    FLOAT (53)    NULL,
    [RazmeriLevYaichn1]                   FLOAT (53)    NULL,
    [LevYaichn3]                          FLOAT (53)    NULL,
    [LevYaichnF]                          FLOAT (53)    NULL,
    [LevYaichn2]                          FLOAT (53)    NULL,
    [PatologicheskieNovoobrazovania]      NVARCHAR (50) NULL,
    [PatSheykiMatkikommenti]              NVARCHAR (50) NULL,
    [Zakluchenie]                         NTEXT         NULL,
    [Vrach]                               INT           NULL,
    CONSTRAINT [UziGinekologicheskoePrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UziGinekologicheskoeToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

