CREATE TABLE [dbo].[UziKishechnika] (
    [ID]                                                         INT          NOT NULL,
    [PatID]                                                      INT          NULL,
    [OpredelyaetsyaSimptomPovishennoyPnevmotizatsiiPologoOrgana] NVARCHAR (1) NULL,
    [LokalnoeUtolshenieStenkiNaProtyazhenii]                     FLOAT (53)   NULL,
    [TolshinaStenki]                                             INT          NULL,
    [VProsveteKishkiDopolnitelnoeObrazovanie]                    NVARCHAR (1) NULL,
    [SKLokalnoeUtolshenieStenkiNaProtyazhenii]                   FLOAT (53)   NULL,
    [SKTolshinaStenki]                                           INT          NULL,
    [SKVProsveteKishkiDopolnitelnoeObrazovanie]                  NVARCHAR (1) NULL,
    [VKLokalnoeUtolshenieStenkiNaProtyazhenii]                   FLOAT (53)   NULL,
    [VKProsveteKishkiDopolnitelnoeObrazovanie1]                  NVARCHAR (1) NULL,
    [VKTolshinaStenki]                                           INT          NULL,
    [SULokalnoeUtolshenieStenkiNaProtyazhenii1]                  FLOAT (53)   NULL,
    [SUTolshinaStenki1]                                          INT          NULL,
    [SUProsveteKishkiDopolnitelnoeObrazovanie2]                  NVARCHAR (1) NULL,
    [Razmerom]                                                   FLOAT (53)   NULL,
    [Razmerom1]                                                  FLOAT (53)   NULL,
    [Razmerom2]                                                  FLOAT (53)   NULL,
    [SKRazmerom]                                                 FLOAT (53)   NULL,
    [SKRazmerom1]                                                FLOAT (53)   NULL,
    [SKRazmerom2]                                                FLOAT (53)   NULL,
    [VKRazmerom]                                                 FLOAT (53)   NULL,
    [VKRazmerom1]                                                FLOAT (53)   NULL,
    [VKRazmerom2]                                                FLOAT (53)   NULL,
    [SURazmerom]                                                 FLOAT (53)   NULL,
    [SURazmerom1]                                                FLOAT (53)   NULL,
    [SKURazmerom2]                                               FLOAT (53)   NULL,
    [Data]                                                       DATETIME     NULL,
    [NomerIssledovaniya]                                         INT          NULL,
    [RekomendovanaKolonoskopiya]                                 NVARCHAR (1) NULL,
    [Zaklyuchenie]                                               INT          NULL,
    [DopolnitelnieDannieUzi]                                     NTEXT        NULL,
    [NUProsveteKishkiDopolnitelnoeObrazovanie]                   NVARCHAR (1) NULL,
    [NUTolshinaStenki]                                           INT          NULL,
    [NULokalnoeUtolshenieStenkiNaProtyazhenii]                   FLOAT (53)   NULL,
    [PUProsveteKishkiDopolnitelnoeObrazovanie]                   NVARCHAR (1) NULL,
    [PUTolshinaStenki]                                           INT          NULL,
    [PULokalnoeUtolshenieStenkiNaProtyazhenii]                   FLOAT (53)   NULL,
    [Vrach]                                                      INT          NULL,
    [PURazmerom]                                                 FLOAT (53)   NULL,
    [PURazmerom1]                                                FLOAT (53)   NULL,
    [PURazmerom2]                                                FLOAT (53)   NULL,
    [NURazmerom]                                                 FLOAT (53)   NULL,
    [NURazmerom1]                                                FLOAT (53)   NULL,
    [NURazmerom2]                                                FLOAT (53)   NULL,
    [Image]                                                      IMAGE        NULL,
    [DannieNaPechat]                                             NTEXT        NULL,
    CONSTRAINT [UziKishechnikaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UziKishechnikaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

