CREATE TABLE [dbo].[UziMyagkihTkaney] (
    [ID]                                  INT          NOT NULL,
    [PatID]                               INT          NULL,
    [Data]                                DATETIME     NULL,
    [NomerIssledovaniya]                  INT          NULL,
    [VProektsiiOpredelyaetsyaObrazovanie] NVARCHAR (1) NULL,
    [Kolichestvo]                         INT          NULL,
    [Razmer]                              FLOAT (53)   NULL,
    [Razmer1]                             FLOAT (53)   NULL,
    [Razmer2]                             FLOAT (53)   NULL,
    [Foram]                               INT          NULL,
    [Konturi]                             INT          NULL,
    [Chetkie]                             NVARCHAR (1) NULL,
    [NeChetkie]                           NVARCHAR (1) NULL,
    [EhoStruktura]                        INT          NULL,
    [EhoPlotnost]                         INT          NULL,
    [Kapsula]                             NVARCHAR (1) NULL,
    [Obodok]                              NVARCHAR (1) NULL,
    [Halo]                                NVARCHAR (1) NULL,
    [UsilenieZaDorzalnoyStenkoy]          NVARCHAR (1) NULL,
    [Obizvestvleniya]                     NVARCHAR (1) NULL,
    [DopolnitelnieDannieUzi]              NTEXT        NULL,
    [Zaklyuchenie]                        INT          NULL,
    [Zakluchenie]                         NTEXT        NULL,
    [Vrach]                               INT          NULL,
    [Image]                               IMAGE        NULL,
    CONSTRAINT [UziMyagkihTkaneyPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UziMyagkihTkaneyToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

