CREATE TABLE [dbo].[UziMochepolovoySistemiSchit] (
    [ID]                                                INT          NOT NULL,
    [PatID]                                             INT          NULL,
    [RaspolozheniPochki]                                INT          NULL,
    [RazmerLohankiDoMiktsii]                            INT          NULL,
    [PosleMiktsii1]                                     INT          NULL,
    [VRazmerah1]                                        INT          NULL,
    [SostavlyaetPochka]                                 FLOAT (53)   NULL,
    [SostavlyaetPochka1]                                FLOAT (53)   NULL,
    [FormaPochka]                                       INT          NULL,
    [EhoPlotnostParenhimiPochka]                        INT          NULL,
    [EhoStrukturaParenhimiPochka]                       INT          NULL,
    [EhoPlotnostPochechnogoSinusa]                      INT          NULL,
    [PochkaRotirovana]                                  NVARCHAR (1) NULL,
    [PochechniySinusNeRasshiren]                        NVARCHAR (1) NULL,
    [ChashechnoLohanochnayaSistemaNeRasshirena]         NVARCHAR (1) NULL,
    [SootnosheniePochechnogoSinusaIParenhimiPravilnoe]  NVARCHAR (1) NULL,
    [ChashechnoLohanochnayaSistema]                     INT          NULL,
    [ObuslovlennimiVeroyatno]                           INT          NULL,
    [RazmeriTsek]                                       FLOAT (53)   NULL,
    [RazmeriParenhimi]                                  FLOAT (53)   NULL,
    [RazmeriKs]                                         FLOAT (53)   NULL,
    [OpredelyayutsyaKonkrementiPochka]                  NVARCHAR (1) NULL,
    [SostavlyaetPochka2]                                FLOAT (53)   NULL,
    [VizualiziruetsyaPochka]                            INT          NULL,
    [DopolnitelnieObrazovaniyaPochka]                   NVARCHAR (1) NULL,
    [RazmerObrazovaniyaPochka]                          FLOAT (53)   NULL,
    [RazmerObrazovaniyaPochka1]                         FLOAT (53)   NULL,
    [SostavlyaetPochkaPochka2]                          FLOAT (53)   NULL,
    [FormaObrazovaniePochka]                            INT          NULL,
    [KonturiObrazovaniePochka]                          INT          NULL,
    [ChetkieObrazovaniePochka]                          INT          NULL,
    [Politsiklicheskie]                                 NVARCHAR (1) NULL,
    [EhoStrukturaObrazovaniePochka]                     INT          NULL,
    [EhoPlotnostObrazovaniePochka]                      INT          NULL,
    [BezOtrazheniyaUltrazvuka2]                         NVARCHAR (1) NULL,
    [SUsileniemZaDorzalnoyStenkoy2]                     NVARCHAR (1) NULL,
    [ImeetsyaKapsula]                                   NVARCHAR (1) NULL,
    [Peregorodki]                                       NVARCHAR (1) NULL,
    [Obizvestvleniya]                                   NVARCHAR (1) NULL,
    [VProektsiiPochaka]                                 INT          NULL,
    [KolichestvoObrazovaniePochka]                      INT          NULL,
    [LokalizatsiyaObrazovaniePochka]                    INT          NULL,
    [RazmerKonkrementPochka]                            FLOAT (53)   NULL,
    [RazmerKonkrementPochka1]                           FLOAT (53)   NULL,
    [SostavlyaetKonkrementPochka]                       FLOAT (53)   NULL,
    [RaspolozheniPochkiL]                               INT          NULL,
    [RazmerLohankiDoMiktsiiL]                           INT          NULL,
    [PosleMiktsii1L]                                    INT          NULL,
    [VizualiziruetsyaPochkaL]                           INT          NULL,
    [VRazmerahL]                                        INT          NULL,
    [SostavlyaetPochkaL]                                FLOAT (53)   NULL,
    [SostavlyaetPochka1L]                               FLOAT (53)   NULL,
    [FormaPochkaL]                                      INT          NULL,
    [EhoPlotnostParenhimiPochkaL]                       INT          NULL,
    [EhoStrukturaParenhimiPochkaL]                      INT          NULL,
    [EhoPlotnostPochechnogoSinusaL]                     INT          NULL,
    [PochkaRotirovanaL]                                 NVARCHAR (1) NULL,
    [PochechniySinusNeRasshirenL]                       NVARCHAR (1) NULL,
    [ChashechnoLohanochnayaSistemaNeRasshirenaL]        NVARCHAR (1) NULL,
    [SootnosheniePochechnogoSinusaIParenhimiPravilnoeL] NVARCHAR (1) NULL,
    [ChashechnoLohanochnayaSistemaL]                    INT          NULL,
    [ObuslovlennimiVeroyatnoL]                          INT          NULL,
    [RazmeriTsekL]                                      FLOAT (53)   NULL,
    [RazmeriParenhimiL]                                 FLOAT (53)   NULL,
    [RazmeriKsL]                                        FLOAT (53)   NULL,
    [OpredelyayutsyaKonkrementiL]                       NVARCHAR (1) NULL,
    [SostavlyaetPochka2L]                               FLOAT (53)   NULL,
    [DopolnitelnieObrazovaniyaPochkaL]                  NVARCHAR (1) NULL,
    [RazmerObrazovaniyaPochkaL]                         FLOAT (53)   NULL,
    [RazmerObrazovaniyaPochka1L]                        FLOAT (53)   NULL,
    [SostavlyaetPochkaPochka2L]                         FLOAT (53)   NULL,
    [FormaObrazovaniePochkaL]                           INT          NULL,
    [KonturiObrazovaniePochkaL]                         INT          NULL,
    [ChetkieObrazovaniePochkaL]                         INT          NULL,
    [PolitsiklicheskieL]                                NVARCHAR (1) NULL,
    [EhoStrukturaObrazovaniePochkaL]                    INT          NULL,
    [EhoPlotnostObrazovaniePochkaL]                     INT          NULL,
    [BezOtrazheniyaUltrazvukaL]                         NVARCHAR (1) NULL,
    [SUsileniemZaDorzalnoyStenkoyL]                     NVARCHAR (1) NULL,
    [ImeetsyaKapsulaL]                                  NVARCHAR (1) NULL,
    [PeregorodkiL]                                      NVARCHAR (1) NULL,
    [ObizvestvleniyaL]                                  NVARCHAR (1) NULL,
    [VProektsiiPochakaL]                                INT          NULL,
    [KolichestvoObrazovaniePochkaL]                     INT          NULL,
    [LokalizatsiyaObrazovaniePochkaL]                   INT          NULL,
    [RazmerKonkrementPochkaL]                           FLOAT (53)   NULL,
    [RazmerKonkrementPochka1L]                          FLOAT (53)   NULL,
    [SostavlyaetKonkrementPochkaL]                      FLOAT (53)   NULL,
    [Vid]                                               INT          NULL,
    [Razmer3]                                           FLOAT (53)   NULL,
    [Razmer4]                                           FLOAT (53)   NULL,
    [Razmer5]                                           FLOAT (53)   NULL,
    [Kontur1]                                           INT          NULL,
    [Chetkost]                                          INT          NULL,
    [KonturBugristiy]                                   NVARCHAR (1) NULL,
    [KonturPolitsiklicheskiy]                           NVARCHAR (1) NULL,
    [Kapsula1]                                          INT          NULL,
    [EhoPlotnost1]                                      INT          NULL,
    [Struktura1]                                        INT          NULL,
    [Kaltsifikati]                                      NVARCHAR (1) NULL,
    [OchagovieObrazovaniya]                             NVARCHAR (1) NULL,
    [Kolichestvo1]                                      INT          NULL,
    [Kontur11]                                          INT          NULL,
    [EhoPlotnost11]                                     INT          NULL,
    [Struktura11]                                       INT          NULL,
    [Razmeri]                                           FLOAT (53)   NULL,
    [Razmeri1]                                          FLOAT (53)   NULL,
    [Razmeri2]                                          FLOAT (53)   NULL,
    [Chetkost1]                                         INT          NULL,
    [Forma1]                                            INT          NULL,
    [KaltsifikatiOO]                                    NVARCHAR (1) NULL,
    [KapsulaOO]                                         NVARCHAR (1) NULL,
    [Obem]                                              FLOAT (53)   NULL,
    [Naplnenie]                                         INT          NULL,
    [Forma]                                             INT          NULL,
    [Kontur]                                            INT          NULL,
    [SoderzhimoePuzirya]                                INT          NULL,
    [Razmer]                                            FLOAT (53)   NULL,
    [Razmer1]                                           FLOAT (53)   NULL,
    [Razmer2]                                           FLOAT (53)   NULL,
    [DopolnitelnieObrazovaniya]                         NVARCHAR (1) NULL,
    [Lokalizatsiya]                                     INT          NULL,
    [Kolichestvo]                                       INT          NULL,
    [RazmerObrazovaniya2]                               FLOAT (53)   NULL,
    [RazmerObrazovaniya1]                               FLOAT (53)   NULL,
    [RazmerObrazovaniya]                                FLOAT (53)   NULL,
    [Konturi]                                           INT          NULL,
    [Struktura]                                         INT          NULL,
    [EhoPlotnost]                                       INT          NULL,
    [DopolnitelnieVklyucheniya]                         NVARCHAR (1) NULL,
    [Kapsula]                                           NVARCHAR (1) NULL,
    [ProrastanieVDrugieOrgani]                          NVARCHAR (1) NULL,
    [NeVizualiziruetsyYaichko]                          NVARCHAR (1) NULL,
    [SvobodnayaZhidkostVokrugYaichka]                   INT          NULL,
    [NeVizualiziruetsyaYaichkoL]                        NVARCHAR (1) NULL,
    [SvobodnayaZhidkostVokrugYaichkaL]                  INT          NULL,
    [LokalizatsiyaYaichko]                              INT          NULL,
    [RazmeromYaichko]                                   INT          NULL,
    [ObichnihRazmerovYaichko]                           INT          NULL,
    [ObichnihRazmerov1Yaichko]                          INT          NULL,
    [ObichnihRazmerovYaichko2]                          INT          NULL,
    [EhoStrukturaYaichko]                               INT          NULL,
    [EhoPlotnostYaichko]                                INT          NULL,
    [DopolnitelnieObrazovaniyaYaichko]                  NVARCHAR (1) NULL,
    [NalichieObodkaYaichko]                             NVARCHAR (1) NULL,
    [PeregorodkiYaichko]                                NVARCHAR (1) NULL,
    [ObizvestvleniyaYaichko]                            NVARCHAR (1) NULL,
    [UsilenieZaDorzalnoyStenkoyYaichko]                 NVARCHAR (1) NULL,
    [LokalizatsiyaYaichkoL]                             INT          NULL,
    [RazmeromYaichkoL]                                  INT          NULL,
    [ObichnihRazmerovYaichkoL]                          INT          NULL,
    [ObichnihRazmerov1YaichkoL]                         INT          NULL,
    [ObichnihRazmerovYaichkoL2]                         INT          NULL,
    [EhoStrukturaYaichkoL]                              INT          NULL,
    [EhoPlotnostYaichkoL]                               INT          NULL,
    [DopolnitelnieObrazovaniyaYaichkoL]                 NVARCHAR (1) NULL,
    [NalichieObodkaYaichkoL]                            NVARCHAR (1) NULL,
    [PeregorodkiYaichkoL]                               NVARCHAR (1) NULL,
    [ObizvestvleniyaYaichkoL]                           NVARCHAR (1) NULL,
    [UsilenieZaDorzalnoyStenkoyYaichkoL]                NVARCHAR (1) NULL,
    [Image]                                             IMAGE        NULL,
    [DopolnitelnieDannieUzi1]                           NTEXT        NULL,
    [Data]                                              DATETIME     NULL,
    [NomerIssledovaniya1]                               INT          NULL,
    [Vrach1]                                            INT          NULL,
    [Zaklyuchenie]                                      NTEXT        NULL,
    [Vrach]                                             INT          NULL,
    [NomerIssledovaniya]                                INT          NULL,
    CONSTRAINT [UziMochepolovoySistemiSchitPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UziMochepolovoySistemiSchitToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

