CREATE TABLE [dbo].[UZIMolochnihZhelezKratkoe] (
    [ID]               INT           NOT NULL,
    [PatID]            INT           NULL,
    [ExecDate]         DATETIME      NULL,
    [OperId]           INT           NULL,
    [FIO]              NVARCHAR (50) NULL,
    [DateMinstr]       DATETIME      NULL,
    [Menopauza]        FLOAT (53)    NULL,
    [StroenieMolJelez] NVARCHAR (50) NULL,
    [Zakluchenie]      NTEXT         NULL,
    [KonturiDop]       NTEXT         NULL,
    [Razmeri]          FLOAT (53)    NULL,
    [Razmeri1]         FLOAT (53)    NULL,
    [Razmeri2]         FLOAT (53)    NULL,
    [DiffIzmen]        NVARCHAR (50) NULL,
    [DiffDop]          NTEXT         NULL,
    [OchagObr]         NVARCHAR (50) NULL,
    [Sprava1]          NVARCHAR (1)  NULL,
    [Sleva1]           NVARCHAR (1)  NULL,
    [Localizaciya]     NTEXT         NULL,
    [Struktura]        NVARCHAR (50) NULL,
    [Konturi]          NVARCHAR (30) NULL,
    [Chetkost]         NVARCHAR (30) NULL,
    [StrukturaDop]     NTEXT         NULL,
    [Ehogennost]       NVARCHAR (50) NULL,
    [EhogennostDop]    NTEXT         NULL,
    [RegZonLimf]       NVARCHAR (50) NULL,
    [RegZonLimfDop]    NTEXT         NULL,
    [SootvDop]         NTEXT         NULL,
    [RashireniDo]      FLOAT (53)    NULL,
    [Sprava]           NVARCHAR (1)  NULL,
    [Sleva]            NVARCHAR (1)  NULL,
    [NeRasshireni]     NVARCHAR (1)  NULL,
    [Sootvetstvuyut]   NVARCHAR (1)  NULL,
    [FazaOrMenopauza]  NVARCHAR (50) NULL,
    CONSTRAINT [UZIMolochnihZhelezKratkoePrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UZIMolochnihZhelezKratkoeToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

