CREATE TABLE [dbo].[UziMolochnihZhelez] (
    [ID]                              INT          NOT NULL,
    [PatID]                           INT          NULL,
    [Data]                            DATETIME     NULL,
    [NomerIssledovaniya]              INT          NULL,
    [Struktura]                       INT          NULL,
    [MolochnieHodi]                   INT          NULL,
    [RasshireniDo]                    INT          NULL,
    [ZaSchet]                         INT          NULL,
    [DopolnitelnieObrazovaniya]       NVARCHAR (1) NULL,
    [Kolichestvo]                     INT          NULL,
    [Lokalizatsiya]                   INT          NULL,
    [Forma]                           INT          NULL,
    [Konturi]                         INT          NULL,
    [EhoPlotnost]                     INT          NULL,
    [Struktura1]                      INT          NULL,
    [Razmeri]                         FLOAT (53)   NULL,
    [Razmeri1]                        FLOAT (53)   NULL,
    [Razmeri2]                        FLOAT (53)   NULL,
    [Chetkost]                        INT          NULL,
    [SUsileniemZaDorzalnoyStenkoy]    NVARCHAR (1) NULL,
    [SGidrofilnimObodkom]             NVARCHAR (1) NULL,
    [SAkusticheskoyTenyu]             NVARCHAR (1) NULL,
    [DopolnitelnieDannieUzi]          NTEXT        NULL,
    [Zakluchenie]                     NTEXT        NULL,
    [LevayaStruktura]                 INT          NULL,
    [LevayaMolochnieHodi]             INT          NULL,
    [LevayaRasshireniDo]              INT          NULL,
    [LevayaZaSchet]                   INT          NULL,
    [LevayaDopolnitelnieObrazovaniya] NVARCHAR (1) NULL,
    [Kolichestvo1]                    INT          NULL,
    [Lokalizatsiya1]                  INT          NULL,
    [Forma1]                          INT          NULL,
    [Konturi1]                        INT          NULL,
    [EhoPlotnost1]                    INT          NULL,
    [Struktura11]                     INT          NULL,
    [Razmeri3]                        FLOAT (53)   NULL,
    [Razmeri11]                       FLOAT (53)   NULL,
    [Razmeri21]                       FLOAT (53)   NULL,
    [Chetkost1]                       INT          NULL,
    [SUsileniemZaDorzalnoyStenkoy1]   NVARCHAR (1) NULL,
    [SGidrofilnimObodkom1]            NVARCHAR (1) NULL,
    [SAkusticheskoyTenyu1]            NVARCHAR (1) NULL,
    [Vrach]                           INT          NULL,
    [Image]                           IMAGE        NULL,
    [Zaklyuchenie]                    NTEXT        NULL,
    CONSTRAINT [UziMolochnihZhelezPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UziMolochnihZhelezToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

