CREATE TABLE [dbo].[UziOrganovMalogoTaza] (
    [ID]                          INT           NOT NULL,
    [PatID]                       INT           NULL,
    [DMS]                         NVARCHAR (50) NULL,
    [Transabdominalnoe]           NVARCHAR (1)  NULL,
    [Transvaginalnoe]             NVARCHAR (1)  NULL,
    [SheykaMatki]                 NTEXT         NULL,
    [Razmeri]                     INT           NULL,
    [Konturi]                     NVARCHAR (50) NULL,
    [Raspolozhenie]               NVARCHAR (50) NULL,
    [Smeshena]                    NVARCHAR (50) NULL,
    [StrukturaMiometriya]         NVARCHAR (50) NULL,
    [IzmenenaPoPeredneyStenke]    NVARCHAR (50) NULL,
    [IzmenenaPoZadneyStenke]      NVARCHAR (50) NULL,
    [IzmenenaVOblastiDna]         NVARCHAR (50) NULL,
    [MiomatoznieUzli]             INT           NULL,
    [Subseroznie]                 NVARCHAR (1)  NULL,
    [Interstitsialnie]            INT           NULL,
    [Submukoznie]                 INT           NULL,
    [MEho]                        INT           NULL,
    [Struktura]                   NVARCHAR (50) NULL,
    [Drugoe]                      NTEXT         NULL,
    [PolostMatki]                 NVARCHAR (50) NULL,
    [Drugoe1]                     NTEXT         NULL,
    [PraviyYaichnik]              INT           NULL,
    [BezOsobennostey]             NVARCHAR (1)  NULL,
    [IzmenN]                      NVARCHAR (50) NULL,
    [LeviyYaichnik]               INT           NULL,
    [BezOsobennostey1]            NVARCHAR (1)  NULL,
    [IzmenN1]                     NVARCHAR (50) NULL,
    [PozadimatochnoeProstranstvo] NTEXT         NULL,
    [Zhidkost]                    NVARCHAR (50) NULL,
    [Kolichestvo]                 NVARCHAR (50) NULL,
    [Zaklyuchenie]                NTEXT         NULL,
    [Vrach]                       INT           NULL,
    [Data]                        DATETIME      NULL,
    [NomerIssledovaniya]          INT           NULL,
    CONSTRAINT [UziOrganovMalogoTazaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UziOrganovMalogoTazaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

