CREATE TABLE [dbo].[UZIpolovihOrganow] (
    [ID]                     INT           NOT NULL,
    [PatID]                  INT           NULL,
    [Predstavleny]           NTEXT         NULL,
    [Konturi1]               NVARCHAR (50) NULL,
    [Konturi2]               NVARCHAR (50) NULL,
    [Struktury]              NVARCHAR (50) NULL,
    [MemoKonturi]            NTEXT         NULL,
    [StrukturyMemo]          NTEXT         NULL,
    [Ehogennost1]            NTEXT         NULL,
    [RejimTSDK]              NTEXT         NULL,
    [SvobodnayaJidkost]      NVARCHAR (50) NULL,
    [SvobodnayaJidkostMemo]  NTEXT         NULL,
    [VeniSemennihKanatikov]  NVARCHAR (50) NULL,
    [VSKdiametr]             FLOAT (53)    NULL,
    [VSKhod]                 NTEXT         NULL,
    [OblastPridatkovYaichek] NVARCHAR (50) NULL,
    [OPYaMemo]               NTEXT         NULL,
    [ProbaValsalvi]          NVARCHAR (50) NULL,
    [Zakluchenie1]           NTEXT         NULL,
    [RazmeryPmm]             INT           NULL,
    [RazmeryP]               NVARCHAR (50) NULL,
    [MemoFormaP]             NTEXT         NULL,
    [FormaP]                 NVARCHAR (50) NULL,
    [RaspolojenieP]          NTEXT         NULL,
    [RazmeryPv]              FLOAT (53)    NULL,
    [RaspolojenieL]          NTEXT         NULL,
    [FormaL]                 NVARCHAR (50) NULL,
    [MemoFormaL]             NTEXT         NULL,
    [RazmeryL]               NVARCHAR (50) NULL,
    [RazmeryLmm]             INT           NULL,
    [RazmeryLv]              FLOAT (53)    NULL,
    [Golovka]                NVARCHAR (1)  NULL,
    [Pesherestie]            NVARCHAR (1)  NULL,
    [UZImemo]                NTEXT         NULL,
    [Struktura]              NTEXT         NULL,
    [Ehogennost2]            NTEXT         NULL,
    [Kontury]                NTEXT         NULL,
    [BelochnayaObolochka]    NTEXT         NULL,
    [Zakluchenie2]           NTEXT         NULL,
    [LSK]                    FLOAT (53)    NULL,
    [LekarProba]             NTEXT         NULL,
    [Vrach2]                 INT           NULL,
    [Apparatto]              NTEXT         NULL,
    CONSTRAINT [UZIpolovihOrganowPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UZIpolovihOrganowToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

