CREATE TABLE [dbo].[UziPredstatelnoyZhelezi] (
    [ID]                      INT           NOT NULL,
    [PatID]                   INT           NULL,
    [Razmer]                  FLOAT (53)    NULL,
    [Razmer1]                 FLOAT (53)    NULL,
    [Razmer2]                 FLOAT (53)    NULL,
    [Rovnie]                  NVARCHAR (10) NULL,
    [Chetkie]                 NVARCHAR (15) NULL,
    [Pokazaniyakissledovaniy] NVARCHAR (50) NULL,
    [Topografiya]             NVARCHAR (50) NULL,
    [Parenxima]               NVARCHAR (50) NULL,
    [Dopintra]                NVARCHAR (50) NULL,
    [Prostatotdel]            NVARCHAR (50) NULL,
    [StruturaTopografsemen]   NVARCHAR (50) NULL,
    [ObemOstMochi]            INT           NULL,
    [soxraneny]               NVARCHAR (15) NULL,
    [Data1]                   DATETIME      NULL,
    [NomerIssledovaniya]      INT           NULL,
    [IssledovaniyaNapPribore] NVARCHAR (50) NULL,
    [Hz]                      INT           NULL,
    [NeIzmeneny]              NVARCHAR (15) NULL,
    [Vpredelax]               NVARCHAR (15) NULL,
    [Kontury]                 NVARCHAR (50) NULL,
    [Gomogenaya]              NVARCHAR (15) NULL,
    [NeViyavlyayutsya]        NVARCHAR (15) NULL,
    [NeDilatirovan]           NVARCHAR (15) NULL,
    [NeIzmeneny2]             NVARCHAR (15) NULL,
    [DopolnitelnieDannieUzi1] NTEXT         NULL,
    [Rekomendovano1]          NTEXT         NULL,
    [Vrach1]                  INT           NULL,
    [VpredelaxKoment]         NVARCHAR (50) NULL,
    [Zaklyuchenie1]           NTEXT         NULL,
    [Image]                   IMAGE         NULL,
    CONSTRAINT [UziPredstatelnoyZheleziPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UziPredstatelnoyZheleziToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

