CREATE TABLE [dbo].[UziPredstatelnoyZheleziIMochevogoPuzirya] (
    [ID]                        INT          NOT NULL,
    [PatID]                     INT          NULL,
    [Data]                      DATETIME     NULL,
    [NomerIssledovaniya]        INT          NULL,
    [Naplnenie]                 INT          NULL,
    [Forma]                     INT          NULL,
    [Kontur]                    INT          NULL,
    [SoderzhimoePuzirya]        INT          NULL,
    [Razmer]                    FLOAT (53)   NULL,
    [Razmer1]                   FLOAT (53)   NULL,
    [Razmer2]                   FLOAT (53)   NULL,
    [DopolnitelnieObrazovaniya] NVARCHAR (1) NULL,
    [Lokalizatsiya]             INT          NULL,
    [Kolichestvo]               INT          NULL,
    [RazmerObrazovaniya2]       FLOAT (53)   NULL,
    [RazmerObrazovaniya1]       FLOAT (53)   NULL,
    [RazmerObrazovaniya]        FLOAT (53)   NULL,
    [Konturi]                   INT          NULL,
    [Struktura]                 INT          NULL,
    [EhoPlotnost]               INT          NULL,
    [DopolnitelnieVklyucheniya] NVARCHAR (1) NULL,
    [Kapsula]                   NVARCHAR (1) NULL,
    [ProrastanieVDrugieOrgani]  NVARCHAR (1) NULL,
    [Vid]                       INT          NULL,
    [RazmerPG]                  FLOAT (53)   NULL,
    [RazmerPG1]                 FLOAT (53)   NULL,
    [RazmerPG2]                 FLOAT (53)   NULL,
    [KonturPG]                  INT          NULL,
    [Chetkost]                  INT          NULL,
    [KonturBugristiy]           NVARCHAR (1) NULL,
    [KonturPolitsiklicheskiy]   NVARCHAR (1) NULL,
    [KapsulaPG]                 INT          NULL,
    [EhoPlotnostPG]             INT          NULL,
    [StrukturaPG]               INT          NULL,
    [Kaltsifikati]              NVARCHAR (1) NULL,
    [DopolnitelnieDannieUzi]    NTEXT        NULL,
    [Zaklyuchenie]              INT          NULL,
    [Vrach]                     INT          NULL,
    [OchagovieObrazovaniya]     NVARCHAR (1) NULL,
    [KolichestvoPG]             INT          NULL,
    [KonturPGOO]                INT          NULL,
    [ChetkostPGOO]              INT          NULL,
    [RazmeriPGOO1]              FLOAT (53)   NULL,
    [Razmeri1]                  FLOAT (53)   NULL,
    [RazmeriPGOO]               FLOAT (53)   NULL,
    [FormaPGOO]                 INT          NULL,
    [StrukturaPGOO]             INT          NULL,
    [EhoPlotnostPGOO]           INT          NULL,
    [KaltsifikatiPGOO]          NVARCHAR (1) NULL,
    [KapsulaPGOO]               NVARCHAR (1) NULL,
    [Image]                     IMAGE        NULL,
    [DannieNaPechat]            NTEXT        NULL,
    CONSTRAINT [UziPredstatelnoyZheleziIMochevogoPuziryaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UziPredstatelnoyZheleziIMochevogoPuziryaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

