CREATE TABLE [dbo].[UziShitovidnoyZheleziKratk] (
    [ID]                    INT           NOT NULL,
    [PatID]                 INT           NULL,
    [Zakluchenie]           NTEXT         NULL,
    [ExostryktyraParenximi] NVARCHAR (50) NULL,
    [ExogennostParenximi]   NVARCHAR (50) NULL,
    [PeresheekTolshina]     FLOAT (53)    NULL,
    [PerzadnLD]             FLOAT (53)    NULL,
    [PerzadnPD]             FLOAT (53)    NULL,
    [MedLarPD]              FLOAT (53)    NULL,
    [MedLarLD]              FLOAT (53)    NULL,
    [DLPD]                  FLOAT (53)    NULL,
    [DLLD]                  FLOAT (53)    NULL,
    [PravajaDolaObjem]      FLOAT (53)    NULL,
    [LevajaDolaObjem]       FLOAT (53)    NULL,
    [ChetkieNechetkie]      NVARCHAR (50) NULL,
    [Data]                  DATETIME      NULL,
    [Vrach]                 INT           NULL,
    [FIO]                   NVARCHAR (75) NULL,
    [Raspolojenie]          NVARCHAR (50) NULL,
    [RaspolojenieKomment]   NTEXT         NULL,
    [RovnNerovn]            NVARCHAR (50) NULL,
    [ConturyKomment]        NTEXT         NULL,
    [StrukturaKomment]      NTEXT         NULL,
    [ExogennostKomment]     NTEXT         NULL,
    [DopObrKomment]         NTEXT         NULL,
    [DopObr]                BIT           NULL,
    [OO]                    FLOAT (53)    NULL,
    [DPLD]                  FLOAT (53)    NULL,
    [DocNumber]             INT           NULL,
    CONSTRAINT [UziShitovidnoyZheleziKratkPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UziShitovidnoyZheleziKratkToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

