CREATE TABLE [dbo].[UziSosudovBryushnoyPolosti] (
    [ID]                                                      INT           NOT NULL,
    [PatID]                                                   INT           NULL,
    [Diametr]                                                 INT           NULL,
    [Sostavlyaet]                                             INT           NULL,
    [Konturi]                                                 INT           NULL,
    [StenkiAorta]                                             INT           NULL,
    [Utolshena]                                               INT           NULL,
    [Do]                                                      INT           NULL,
    [VnutrenniyKontur]                                        INT           NULL,
    [RassloenieStenki]                                        NVARCHAR (1)  NULL,
    [ProsvetSosuda]                                           INT           NULL,
    [ProsvetAorti]                                            INT           NULL,
    [DopolnitelnieEhoSignali]                                 NVARCHAR (1)  NULL,
    [DopolnitelnieVklyucheniya]                               NVARCHAR (1)  NULL,
    [Pulsatsiya]                                              INT           NULL,
    [OkklyuziyaAorti]                                         NVARCHAR (1)  NULL,
    [ArterialnayaPulsatsiyaNachinayaSMestaOkklyuziiIschezaet] NVARCHAR (1)  NULL,
    [ProsvetArteriiVisheMestaOkklyuziiBezOsobennostey]        NVARCHAR (1)  NULL,
    [VProsveteTromboticheskieMassi]                           NVARCHAR (1)  NULL,
    [StenozAorti]                                             NVARCHAR (1)  NULL,
    [EhoPlotnost]                                             INT           NULL,
    [TromboticheskieMassi]                                    NVARCHAR (1)  NULL,
    [NomerIssledovaniya]                                      INT           NULL,
    [Data]                                                    DATETIME      NULL,
    [Chetkost]                                                INT           NULL,
    [PodvsdoshDiametr]                                        INT           NULL,
    [PodvsdoshDo]                                             FLOAT (53)    NULL,
    [PodvsdoshStenkaArterii]                                  INT           NULL,
    [PodvsdoshTolshinaStenki]                                 FLOAT (53)    NULL,
    [PodvsdoshKontur]                                         NVARCHAR (50) NULL,
    [PodvsdoshProsvetSosuda]                                  INT           NULL,
    [PodvsdoshTromboticheskieMassi]                           NVARCHAR (1)  NULL,
    [AteroskleroticheskieBlyashki]                            NVARCHAR (1)  NULL,
    [LevayaPodvsdoshDiametr]                                  INT           NULL,
    [LevayaPodvsdoshStenkaArterii]                            INT           NULL,
    [LevayaPodvsdoshKontur]                                   NVARCHAR (50) NULL,
    [LevayaPodvsdoshTromboticheskieMassi]                     NVARCHAR (1)  NULL,
    [LevayaAteroskleroticheskieBlyashki]                      NVARCHAR (1)  NULL,
    [LevayaPodvsdoshProsvetSosuda]                            INT           NULL,
    [LevayaPodvsdoshDo1]                                      FLOAT (53)    NULL,
    [LevayaPodvsdoshTolshinaStenki]                           FLOAT (53)    NULL,
    [VBryushnoyChastiAortiPolostnoeObrazovanie]               NVARCHAR (1)  NULL,
    [Forma]                                                   INT           NULL,
    [StenkiObrazovaniya]                                      INT           NULL,
    [TolshinaStenokDo]                                        INT           NULL,
    [PulsatsiyaStenokSlabaya]                                 NVARCHAR (1)  NULL,
    [StenkiTromboticheskieMassi]                              NVARCHAR (1)  NULL,
    [LokalnoeIstonchenieStenkiAnevrizmi]                      NVARCHAR (1)  NULL,
    [RasprostranenieAnevrizmi]                                NVARCHAR (1)  NULL,
    [NarushenieTselostnostiStenkiAnevrizmi]                   NVARCHAR (1)  NULL,
    [ZabryushinnayaGematoma]                                  NVARCHAR (1)  NULL,
    [UplotnenieOkolososudistoyKletchatki]                     NVARCHAR (1)  NULL,
    [BrDiametr]                                               INT           NULL,
    [BrDo]                                                    INT           NULL,
    [BrProtyazhennost78Mm]                                    NVARCHAR (1)  NULL,
    [BrVid]                                                   INT           NULL,
    [BrRazmeri]                                               FLOAT (53)    NULL,
    [NPVBrDiametr]                                            INT           NULL,
    [NPVProtyazhennost78Mm]                                   NVARCHAR (1)  NULL,
    [NPVVid]                                                  INT           NULL,
    [NPVRazmeri]                                              FLOAT (53)    NULL,
    [NPVBrDo]                                                 INT           NULL,
    [NPVPulsatsiyaStenokVeni]                                 NVARCHAR (1)  NULL,
    [NPVSdavlenieNizhneyVeni]                                 NVARCHAR (1)  NULL,
    [DopolnitelnieDannieUzi]                                  NTEXT         NULL,
    [Zaklyuchenie]                                            INT           NULL,
    [Vrach]                                                   INT           NULL,
    [Image]                                                   IMAGE         NULL,
    [DannieNaPechat]                                          NTEXT         NULL,
    CONSTRAINT [UziSosudovBryushnoyPolostiPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UziSosudovBryushnoyPolostiToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

