CREATE TABLE [dbo].[UziSlyunnihZhelez] (
    [ID]                              INT          NOT NULL,
    [PatID]                           INT          NULL,
    [Data]                            DATETIME     NULL,
    [NomerIssledovaniya]              INT          NULL,
    [VRazmerah]                       INT          NULL,
    [Konturi]                         INT          NULL,
    [EhoStruktura]                    INT          NULL,
    [EhoPlotnost]                     INT          NULL,
    [Chetkie]                         NVARCHAR (1) NULL,
    [NeChetkie]                       NVARCHAR (1) NULL,
    [Razmeri]                         INT          NULL,
    [Razmeri1]                        INT          NULL,
    [Razmeri2]                        INT          NULL,
    [DopolnitelnieObrazovaniya]       NVARCHAR (1) NULL,
    [Obizvestvleniya]                 NVARCHAR (1) NULL,
    [AkusticheskayaTen]               NVARCHAR (1) NULL,
    [KamniVProtokah]                  NVARCHAR (1) NULL,
    [PravieEhoPlotnost]               INT          NULL,
    [PravieEhoStruktura]              INT          NULL,
    [PravieKonturi]                   INT          NULL,
    [PravieVRazmerah]                 INT          NULL,
    [PravieRazmeri]                   INT          NULL,
    [PravieRazmeri1]                  INT          NULL,
    [PravieRazmeri2]                  INT          NULL,
    [PravieNeChetkie]                 NVARCHAR (1) NULL,
    [PravieChetkie]                   NVARCHAR (1) NULL,
    [PravieKamniVProtokah]            NVARCHAR (1) NULL,
    [PravieDopolnitelnieObrazovaniya] NVARCHAR (1) NULL,
    [PravieObizvestvleniya]           NVARCHAR (1) NULL,
    [PravieAkusticheskayaTen]         NVARCHAR (1) NULL,
    [DopolnitelnieDannieUzi]          NTEXT        NULL,
    [Zaklyuchenie]                    INT          NULL,
    [Vrach]                           INT          NULL,
    [Image]                           IMAGE        NULL,
    [DannieNaPechat]                  NTEXT        NULL,
    CONSTRAINT [UziSlyunnihZhelezPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UziSlyunnihZhelezToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

