CREATE TABLE [dbo].[UziSosudovVerhnihKonechnostey] (
    [ID]                                INT          NOT NULL,
    [PatID]                             INT          NULL,
    [Data]                              DATETIME     NULL,
    [NomerIssledovaniya]                INT          NULL,
    [SonnoyArterii]                     INT          NULL,
    [ObsheySonnoyArterii]               INT          NULL,
    [PodklyuchichnoyArterii]            INT          NULL,
    [VnutrenneyYaremnoyVeni]            INT          NULL,
    [PodklyuchichnoyVeni]               INT          NULL,
    [NaruzhnoySonnoyArterii]            INT          NULL,
    [VnutrenneySonnoyArterii]           INT          NULL,
    [PodmishechnoyArterii]              INT          NULL,
    [PodlopatochnoyArterii]             INT          NULL,
    [EmboliyaSonnoyArterii]             NVARCHAR (1) NULL,
    [EmboliyaObsheySonnoyArterii]       NVARCHAR (1) NULL,
    [EmboliyaPodklyuchichnoyArterii]    NVARCHAR (1) NULL,
    [EmboliyaVnutrenneyYaremnoyVeni]    NVARCHAR (1) NULL,
    [EmboliyaPodklyuchichnoyVeni]       NVARCHAR (1) NULL,
    [EmboliyaNaruzhnoySonnoyArterii]    NVARCHAR (1) NULL,
    [EmboliyaVnutrenneySonnoyArterii]   NVARCHAR (1) NULL,
    [EmboliyaPodmishechnoyArterii]      NVARCHAR (1) NULL,
    [EmboliyaPodlopatochnoyArterii]     NVARCHAR (1) NULL,
    [IzvitostSonnoyArterii1]            NVARCHAR (1) NULL,
    [IzvitostObsheySonnoyArterii1]      NVARCHAR (1) NULL,
    [IzvitostPodklyuchichnoyArterii1]   NVARCHAR (1) NULL,
    [IzvitostVnutrenneyYaremnoyVeni1]   NVARCHAR (1) NULL,
    [IzvitostPodklyuchichnoyVeni]       NVARCHAR (1) NULL,
    [IzvitostNaruzhnoySonnoyArterii]    NVARCHAR (1) NULL,
    [IzvitostVnutrenneySonnoyArterii]   NVARCHAR (1) NULL,
    [IzvitostPodmishechnoyArterii]      NVARCHAR (1) NULL,
    [IzvitostPodlopatochnoyArterii]     NVARCHAR (1) NULL,
    [TrombPodlopatochnoyArterii]        NVARCHAR (1) NULL,
    [TrombPodmishechnoyArterii]         NVARCHAR (1) NULL,
    [TrombVnutrenneySonnoyArterii]      NVARCHAR (1) NULL,
    [TrombNaruzhnoySonnoyArterii]       NVARCHAR (1) NULL,
    [TrombPodklyuchichnoyVeni]          NVARCHAR (1) NULL,
    [TrombVnutrenneyYaremnoyVeni]       NVARCHAR (1) NULL,
    [TrombPodklyuchichnoyArterii]       NVARCHAR (1) NULL,
    [TrombObsheySonnoyArterii]          NVARCHAR (1) NULL,
    [TrombSonnoyArterii]                NVARCHAR (1) NULL,
    [PulsPodlopatochnoyArterii]         NVARCHAR (1) NULL,
    [PulsPodmishechnoyArterii]          NVARCHAR (1) NULL,
    [PulsVnutrenneySonnoyArterii]       NVARCHAR (1) NULL,
    [PulsNaruzhnoySonnoyArterii]        NVARCHAR (1) NULL,
    [PulsPodklyuchichnoyVeni]           NVARCHAR (1) NULL,
    [PulsVnutrenneyYaremnoyVeni]        NVARCHAR (1) NULL,
    [PulsPodklyuchichnoyArterii]        NVARCHAR (1) NULL,
    [PulsObsheySonnoyArterii]           NVARCHAR (1) NULL,
    [PulsSonnoyArterii]                 NVARCHAR (1) NULL,
    [AnevrizmaPodlopatochnoyArterii]    NVARCHAR (1) NULL,
    [AnevrizmaPodmishechnoyArterii]     NVARCHAR (1) NULL,
    [AnevrizmaVnutrenneySonnoyArterii]  NVARCHAR (1) NULL,
    [AnevrizmaNaruzhnoySonnoyArterii]   NVARCHAR (1) NULL,
    [AnevrizmaPodklyuchichnoyVeni]      NVARCHAR (1) NULL,
    [AnevrizmaVnutrenneyYaremnoyVeni]   NVARCHAR (1) NULL,
    [AnevrizmaPodklyuchichnoyArterii]   NVARCHAR (1) NULL,
    [AnevrizmaObsheySonnoyArterii]      NVARCHAR (1) NULL,
    [AnevrizmaSonnoyArterii]            NVARCHAR (1) NULL,
    [SosudiPravoyVerhneyKonechnosti]    NVARCHAR (1) NULL,
    [SonnoyArteriiL]                    INT          NULL,
    [ObsheySonnoyArteriiL]              INT          NULL,
    [PodklyuchichnoyArteriiL]           INT          NULL,
    [VnutrenneyYaremnoyVeniL]           INT          NULL,
    [PodklyuchichnoyVeniL]              INT          NULL,
    [NaruzhnoySonnoyArteriiL]           INT          NULL,
    [VnutrenneySonnoyArteriiL]          INT          NULL,
    [PodmishechnoyArteriiL]             INT          NULL,
    [PodlopatochnoyArteriiL]            INT          NULL,
    [EmboliyaSonnoyArteriiL]            NVARCHAR (1) NULL,
    [EmboliyaObsheySonnoyArteriiL]      NVARCHAR (1) NULL,
    [EmboliyaPodklyuchichnoyArteriiL]   NVARCHAR (1) NULL,
    [EmboliyaVnutrenneyYaremnoyVeniL]   NVARCHAR (1) NULL,
    [EmboliyaPodklyuchichnoyVeniL]      NVARCHAR (1) NULL,
    [EmboliyaNaruzhnoySonnoyArteriiL]   NVARCHAR (1) NULL,
    [EmboliyaVnutrenneySonnoyArteriiL]  NVARCHAR (1) NULL,
    [EmboliyaPodmishechnoyArteriiL]     NVARCHAR (1) NULL,
    [EmboliyaPodlopatochnoyArteriiL]    NVARCHAR (1) NULL,
    [IzvitostSonnoyArteriiL]            NVARCHAR (1) NULL,
    [IzvitostObsheySonnoyArteriiL]      NVARCHAR (1) NULL,
    [IzvitostPodklyuchichnoyArteriiL]   NVARCHAR (1) NULL,
    [IzvitostVnutrenneyYaremnoyVeniL]   NVARCHAR (1) NULL,
    [IzvitostPodklyuchichnoyVeniL]      NVARCHAR (1) NULL,
    [IzvitostNaruzhnoySonnoyArteriiL]   NVARCHAR (1) NULL,
    [IzvitostVnutrenneySonnoyArteriiL]  NVARCHAR (1) NULL,
    [IzvitostPodmishechnoyArteriiL]     NVARCHAR (1) NULL,
    [IzvitostPodlopatochnoyArteriiL]    NVARCHAR (1) NULL,
    [TrombPodlopatochnoyArteriiL]       NVARCHAR (1) NULL,
    [TrombPodmishechnoyArteriiL]        NVARCHAR (1) NULL,
    [TrombVnutrenneySonnoyArteriiL]     NVARCHAR (1) NULL,
    [TrombNaruzhnoySonnoyArteriiL]      NVARCHAR (1) NULL,
    [TrombPodklyuchichnoyVeniL]         NVARCHAR (1) NULL,
    [TrombVnutrenneyYaremnoyVeniL]      NVARCHAR (1) NULL,
    [TrombPodklyuchichnoyArteriiL]      NVARCHAR (1) NULL,
    [TrombObsheySonnoyArteriiL]         NVARCHAR (1) NULL,
    [TrombSonnoyArteriiL]               NVARCHAR (1) NULL,
    [PulsPodlopatochnoyArteriiL]        NVARCHAR (1) NULL,
    [PulsPodmishechnoyArteriiL]         NVARCHAR (1) NULL,
    [PulsVnutrenneySonnoyArteriiL]      NVARCHAR (1) NULL,
    [PulsNaruzhnoySonnoyArteriiL]       NVARCHAR (1) NULL,
    [PulsPodklyuchichnoyVeniL]          NVARCHAR (1) NULL,
    [PulsVnutrenneyYaremnoyVeniL]       NVARCHAR (1) NULL,
    [PulsPodklyuchichnoyArteriiL]       NVARCHAR (1) NULL,
    [PulsObsheySonnoyArteriiL]          NVARCHAR (1) NULL,
    [PulsSonnoyArteriiL]                NVARCHAR (1) NULL,
    [AnevrizmaPodlopatochnoyArteriiL]   NVARCHAR (1) NULL,
    [AnevrizmaPodmishechnoyArteriiL]    NVARCHAR (1) NULL,
    [AnevrizmaVnutrenneySonnoyArteriiL] NVARCHAR (1) NULL,
    [AnevrizmaNaruzhnoySonnoyArteriiL]  NVARCHAR (1) NULL,
    [AnevrizmaPodklyuchichnoyVeniL]     NVARCHAR (1) NULL,
    [AnevrizmaVnutrenneyYaremnoyVeniL]  NVARCHAR (1) NULL,
    [AnevrizmaPodklyuchichnoyArteriiL]  NVARCHAR (1) NULL,
    [AnevrizmaObsheySonnoyArteriiL]     NVARCHAR (1) NULL,
    [AnevrizmaSonnoyArteriiL]           NVARCHAR (1) NULL,
    [SosudiLevoyVerhneyKonechnosti1]    NVARCHAR (1) NULL,
    [DopolnitelnieDannieUzi]            NTEXT        NULL,
    [Zaklyuchenie]                      INT          NULL,
    [Lokalizatsiya]                     INT          NULL,
    [Lokalizatsiya1]                    INT          NULL,
    [Vrach]                             INT          NULL,
    [Image]                             IMAGE        NULL,
    [DannieNaPechat]                    NTEXT        NULL,
    CONSTRAINT [UziSosudovVerhnihKonechnosteyPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UziSosudovVerhnihKonechnosteyToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

