CREATE TABLE [dbo].[UziSosudovNizhnihKonechnostey] (
    [ID]                                         INT          NOT NULL,
    [PatID]                                      INT          NULL,
    [Data]                                       DATETIME     NULL,
    [NomerIssledovaniya]                         INT          NULL,
    [ObsheyBedrennoyVeni]                        NVARCHAR (1) NULL,
    [PoverhnostnoyBedrennoyVeni]                 NVARCHAR (1) NULL,
    [GlubokoyBedrennoyVeni]                      NVARCHAR (1) NULL,
    [ObsheyBedrennoyArterii]                     INT          NULL,
    [PoverhnostnoyBedrennoyArterii]              INT          NULL,
    [GlubokoyBedrennoyArterii]                   INT          NULL,
    [PodkolennoyVeni]                            INT          NULL,
    [ValsalvaObsheyBedrennoyArterii]             INT          NULL,
    [ValsalvaPoverhnostnoyBedrennoyArterii]      INT          NULL,
    [ValsalvaGlubokoyBedrennoyArterii]           INT          NULL,
    [ValsalvaPodkolennoyVeni]                    INT          NULL,
    [KlapaniObsheyBedrennoyVeni]                 INT          NULL,
    [KlapaniPoverhnostnoyBedrennoyVeni]          INT          NULL,
    [KlapaniGlubokoyBedrennoyVeni]               INT          NULL,
    [OBVRazmerom2]                               INT          NULL,
    [OBVRazmerom1]                               INT          NULL,
    [OBVRazmerom]                                INT          NULL,
    [PBVRazmerom2]                               INT          NULL,
    [PBVRazmerom1]                               INT          NULL,
    [PBVRazmerom]                                INT          NULL,
    [GBVRazmerom2]                               INT          NULL,
    [GBVRazmerom1]                               INT          NULL,
    [GBVRazmerom]                                INT          NULL,
    [SosudiPravoyNizhneyKonechnosti]             NVARCHAR (1) NULL,
    [DopolnitelnieDannieUzi]                     NTEXT        NULL,
    [Zaklyuchenie]                               INT          NULL,
    [Lokalizatsiya]                              INT          NULL,
    [Vrach]                                      INT          NULL,
    [LevoyObsheyBedrennoyVeni]                   NVARCHAR (1) NULL,
    [LevoyPoverhnostnoyBedrennoyVeni]            NVARCHAR (1) NULL,
    [LevoyGlubokoyBedrennoyVeni]                 NVARCHAR (1) NULL,
    [LevoyObsheyBedrennoyArterii]                INT          NULL,
    [LevoyPoverhnostnoyBedrennoyArterii]         INT          NULL,
    [LevoyGlubokoyBedrennoyArterii]              INT          NULL,
    [LevoyPodkolennoyVeni]                       INT          NULL,
    [LevoyValsalvaObsheyBedrennoyArterii]        INT          NULL,
    [LevoyValsalvaPoverhnostnoyBedrennoyArterii] INT          NULL,
    [LevoyValsalvaGlubokoyBedrennoyArterii]      INT          NULL,
    [LevoyValsalvaPodkolennoyVeni]               INT          NULL,
    [LevoyKlapaniObsheyBedrennoyVeni]            INT          NULL,
    [LevoyKlapaniPoverhnostnoyBedrennoyVeni]     INT          NULL,
    [LevoyKlapaniGlubokoyBedrennoyVeni]          INT          NULL,
    [OBVRazmeromL2]                              INT          NULL,
    [OBVRazmeromL1]                              INT          NULL,
    [OBVRazmeromL]                               INT          NULL,
    [PBVRazmeromL2]                              INT          NULL,
    [PBVRazmeromL1]                              INT          NULL,
    [PBVRazmeromL]                               INT          NULL,
    [GBVRazmeromL2]                              INT          NULL,
    [GBVRazmeromL1]                              INT          NULL,
    [GBVRazmeromL]                               INT          NULL,
    [SosudiLevoyNizhneyKonechnosti]              NVARCHAR (1) NULL,
    [Image]                                      IMAGE        NULL,
    [DannieNaPechat]                             NTEXT        NULL,
    CONSTRAINT [UziSosudovNizhnihKonechnosteyPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UziSosudovNizhnihKonechnosteyToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

