CREATE TABLE [dbo].[UziTimusa] (
    [ID]                         INT           NOT NULL,
    [PatID]                      INT           NULL,
    [Data]                       DATETIME      NULL,
    [NomerIssledovaniya]         INT           NULL,
    [ObMnieObrazovaniya]         NVARCHAR (1)  NULL,
    [Kolichestvo]                INT           NULL,
    [Razmer]                     FLOAT (53)    NULL,
    [Razmer1]                    FLOAT (53)    NULL,
    [Razmer2]                    FLOAT (53)    NULL,
    [Foram]                      INT           NULL,
    [Konturi]                    INT           NULL,
    [Chetkie]                    NVARCHAR (1)  NULL,
    [NeChetkie]                  NVARCHAR (1)  NULL,
    [EhoStruktura]               INT           NULL,
    [EhoPlotnost]                INT           NULL,
    [Kapsula]                    NVARCHAR (1)  NULL,
    [Obodok]                     NVARCHAR (1)  NULL,
    [Halo]                       NVARCHAR (1)  NULL,
    [UsilenieZaDorzalnoyStenkoy] NVARCHAR (1)  NULL,
    [Obizvestvleniya]            NVARCHAR (1)  NULL,
    [Zaklyuchenie]               NTEXT         NULL,
    [Vizualizatsiya]             NVARCHAR (50) NULL,
    [Konturi1]                   NVARCHAR (50) NULL,
    [Konturi2]                   NVARCHAR (50) NULL,
    [Razmeri]                    NVARCHAR (50) NULL,
    [Razmeri1]                   NVARCHAR (50) NULL,
    [Razmeri2]                   NVARCHAR (50) NULL,
    [Ehostruktura1]              NVARCHAR (50) NULL,
    [Ehogennost]                 NVARCHAR (50) NULL,
    [Vrach]                      NVARCHAR (50) NULL,
    CONSTRAINT [UziTimusaPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UziTimusaToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

