CREATE TABLE [dbo].[UziVPervomTrimestreBeremennosti] (
    [ID]                INT           NOT NULL,
    [PatID]             INT           NULL,
    [Zakluchenie]       NTEXT         NULL,
    [ktr]               FLOAT (53)    NULL,
    [SVD]               FLOAT (53)    NULL,
    [VorotnikovayaZona] FLOAT (53)    NULL,
    [bpr]               FLOAT (53)    NULL,
    [oj]                FLOAT (53)    NULL,
    [db]                FLOAT (53)    NULL,
    [NosovayaKosa]      FLOAT (53)    NULL,
    [Data]              DATETIME      NULL,
    [Srok]              INT           NULL,
    [Vizualizacia]      NVARCHAR (50) NULL,
    [JeltochniyMeshok]  FLOAT (53)    NULL,
    [Vrach]             INT           NULL,
    [DocNumber]         INT           NULL,
    [VnutrZiev]         NVARCHAR (50) NULL,
    [MiomatoznieUzli]   NVARCHAR (50) NULL,
    [Kolvo]             INT           NULL,
    [PlodEmbr]          NVARCHAR (50) NULL,
    [Opredelyaetsya]    NVARCHAR (16) NULL,
    [Sootvetstvuet]     NVARCHAR (16) NULL,
    [Nedelya]           INT           NULL,
    [Horion]            NVARCHAR (50) NULL,
    [Dohodit]           NVARCHAR (50) NULL,
    [LevYaichn]         FLOAT (53)    NULL,
    [ZheltoeTelo]       NVARCHAR (26) NULL,
    [PrYaichn]          FLOAT (53)    NULL,
    [ZheltoeTeloP]      NVARCHAR (26) NULL,
    [DPM]               DATETIME      NULL,
    [Dlina]             FLOAT (53)    NULL,
    CONSTRAINT [UziVPervomTrimestreBeremennostiPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UziVPervomTrimestreBeremennostiToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

