CREATE TABLE [dbo].[VetOsmotrPer] (
    [ID]                INT            NOT NULL,
    [PatID]             INT            NULL,
    [Data1]             DATETIME       NULL,
    [DanOsmPerv1]       NVARCHAR (50)  NULL,
    [DanOsmPerv]        NTEXT          NULL,
    [Obsheesost1]       NVARCHAR (50)  NULL,
    [Temper1]           FLOAT (53)     NULL,
    [sist1]             INT            NULL,
    [diast1]            INT            NULL,
    [Rost3]             INT            NULL,
    [Ves3]              FLOAT (53)     NULL,
    [snk]               INT            NULL,
    [Rekom]             NVARCHAR (50)  NULL,
    [PlanLech2]         NVARCHAR (255) NULL,
    [planlech1]         NVARCHAR (50)  NULL,
    [PlanLecheniya]     NTEXT          NULL,
    [Recomendacii]      NTEXT          NULL,
    [dieta]             NTEXT          NULL,
    [PlanObsledovaniya] NTEXT          NULL,
    [zhalobi1]          NVARCHAR (255) NULL,
    [Zhalobi]           NTEXT          NULL,
    [AnamnesisiMorbi]   NTEXT          NULL,
    [AnamnezZhizni1]    NTEXT          NULL,
    [AnamnezZhizni2]    NTEXT          NULL,
    [VredPriv]          NTEXT          NULL,
    [NoAllergy]         BIT            NULL,
    [Allergic6]         NVARCHAR (255) NULL,
    [Allergic1]         NVARCHAR (255) NULL,
    [Allergic]          NTEXT          NULL,
    [Allergic3]         NVARCHAR (255) NULL,
    [Allergic2]         NTEXT          NULL,
    [Allergic5]         NVARCHAR (255) NULL,
    [Allergic4]         NTEXT          NULL,
    [EpidAnamnes]       NTEXT          NULL,
    [Operatsii2]        NTEXT          NULL,
    [Transfuzii2]       NTEXT          NULL,
    [Inektsii2]         NTEXT          NULL,
    [Vrach2]            INT            NULL,
    [DocTime]           DATETIME       NULL,
    [Specalist]         NVARCHAR (50)  NULL,
    [diagnos]           NTEXT          NULL,
    [DinamikaSostPat]   NVARCHAR (50)  NULL,
    [PriemVStatsionare] NVARCHAR (1)   NULL,
    [DataPovtOsmotra]   DATETIME       NULL,
    [Primechanie]       NTEXT          NULL,
    [CHDD]              INT            NULL,
    [Puls]              INT            NULL,
    [Client]            NVARCHAR (50)  NULL,
    [Vid]               NVARCHAR (50)  NULL,
    [Klichka]           NVARCHAR (40)  NULL,
    [AnimalID]          NVARCHAR (20)  NULL,
    [Diagnoz]           NVARCHAR (255) NULL,
    [DiagCode]          NVARCHAR (20)  NULL,
    [Diagnoz1]          NVARCHAR (255) NULL,
    [DiagCode1]         NVARCHAR (20)  NULL,
    [Diagnoz2]          NVARCHAR (255) NULL,
    [DiagCode2]         NVARCHAR (20)  NULL,
    [Diagnoz3]          NVARCHAR (255) NULL,
    [DiagCode3]         NVARCHAR (20)  NULL,
    [AnamnezZhizni]     NTEXT          NULL,
    [Prognoz]           NVARCHAR (100) NULL,
    [LechVrach]         INT            NULL,
    CONSTRAINT [VetOsmotrPerPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [VetOsmotrPerToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

