CREATE TABLE [dbo].[Vipisnoyepikriz] (
    [FIO]                        NVARCHAR (100) NULL,
    [Vozrast]                    INT            NULL,
    [DataPostupleniya]           DATETIME       NULL,
    [DataVipiski]                DATETIME       NULL,
    [KlinicheskiyDiagnoz]        NTEXT          NULL,
    [TselGospitalizatsii]        NTEXT          NULL,
    [DinamikaZabolevaniya]       NTEXT          NULL,
    [ObshiyHirurg]               NVARCHAR (100) NULL,
    [Angiohirurg]                NVARCHAR (100) NULL,
    [Nevropatolog]               NVARCHAR (100) NULL,
    [Psihoterapevt]              NVARCHAR (100) NULL,
    [Okulist]                    NVARCHAR (100) NULL,
    [Urolog]                     NVARCHAR (100) NULL,
    [Otolaringolog]              NVARCHAR (100) NULL,
    [Ginekolog]                  NVARCHAR (100) NULL,
    [Ekg]                        NTEXT          NULL,
    [EhoKs]                      NTEXT          NULL,
    [UziUzdgTkdg]                NTEXT          NULL,
    [Fgs]                        NTEXT          NULL,
    [Fks]                        NTEXT          NULL,
    [DopolnitelnieIssledovaniya] NTEXT          NULL,
    [ProvedenoLechenie]          NTEXT          NULL,
    [LechashiyVrach]             NVARCHAR (50)  NULL,
    [ZavOtdeleniem]              NVARCHAR (50)  NULL,
    [Otdelenie]                  NVARCHAR (100) NULL,
    [ID]                         INT            NULL,
    [PatID]                      INT            NULL,
    [Kt]                         NTEXT          NULL,
    [RGrafiya]                   NTEXT          NULL,
    [Endokrinolog]               NVARCHAR (100) NULL,
    [Rekomendovano]              NTEXT          NULL,
    CONSTRAINT [VipisnoyepikrizToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

