CREATE TABLE [dbo].[VkladishDlyaBolnogoGrippomOrzAnginoyPervichnoe] (
    [ID]                    INT           NOT NULL,
    [PatID]                 INT           NULL,
    [Data]                  DATETIME      NULL,
    [Vrach]                 INT           NULL,
    [Osmotr]                NVARCHAR (50) NULL,
    [Zhalobi]               NTEXT         NULL,
    [BolVGorle]             NVARCHAR (50) NULL,
    [Slabost]               NVARCHAR (50) NULL,
    [Nachalo]               NVARCHAR (50) NULL,
    [Temp]                  FLOAT (53)    NULL,
    [Puls]                  INT           NULL,
    [Ad]                    INT           NULL,
    [ObsheeSostoyanie]      NVARCHAR (50) NULL,
    [Mindalini]             NVARCHAR (50) NULL,
    [Mindalini1]            NTEXT         NULL,
    [Kozha]                 NVARCHAR (50) NULL,
    [Kozha1]                NVARCHAR (50) NULL,
    [Limfouzli]             NVARCHAR (50) NULL,
    [Limfouzli1]            NVARCHAR (50) NULL,
    [SerdtseToni]           NVARCHAR (50) NULL,
    [LegkieDihanie]         NVARCHAR (50) NULL,
    [LegkieDihanie1]        NVARCHAR (50) NULL,
    [Hripi]                 NVARCHAR (50) NULL,
    [Hripi1]                NVARCHAR (50) NULL,
    [Zhivot]                NVARCHAR (50) NULL,
    [Zhivot1]               NVARCHAR (50) NULL,
    [Stul]                  NVARCHAR (50) NULL,
    [Osnovnoy]              NVARCHAR (50) NULL,
    [Soputstvuyushiy]       NTEXT         NULL,
    [BolnichniyListS]       DATETIME      NULL,
    [BolnichniyListPo]      DATETIME      NULL,
    [AktivnoePoseshenie]    NVARCHAR (1)  NULL,
    [YavkaVPolikliniku]     NVARCHAR (1)  NULL,
    [DataYavkaVPolikliniku] DATETIME      NULL,
    [YavkaVPolikliniku1]    NVARCHAR (50) NULL,
    [SerdtseToni1]          NVARCHAR (50) NULL,
    [Ad1]                   INT           NULL,
    CONSTRAINT [VkladishDlyaBolnogoGrippomOrzAnginoyPervichnoePrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [VkladishDlyaBolnogoGrippomOrzAnginoyPervichnoeToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

