CREATE TABLE [dbo].[ZapisProbi] (
    [ID]       INT           NOT NULL,
    [MasterID] INT           NULL,
    [Proba]    NVARCHAR (50) NULL,
    [Fms]      NVARCHAR (4)  NULL,
    [Fmd]      NVARCHAR (4)  NULL,
    [Oms]      NVARCHAR (4)  NULL,
    [Omd]      NVARCHAR (4)  NULL,
    [Fms1]     NVARCHAR (4)  NULL,
    [Fmd1]     NVARCHAR (4)  NULL,
    [Oms1]     NVARCHAR (4)  NULL,
    [Omd1]     NVARCHAR (4)  NULL,
    [Fms2]     NVARCHAR (4)  NULL,
    [Fmd2]     NVARCHAR (4)  NULL,
    [Oms2]     NVARCHAR (4)  NULL,
    [Omd2]     NVARCHAR (4)  NULL,
    [Fms3]     NVARCHAR (4)  NULL,
    [Fmd3]     NVARCHAR (4)  NULL,
    [Oms3]     NVARCHAR (4)  NULL,
    [Omd3]     NVARCHAR (4)  NULL,
    [Fms4]     NVARCHAR (4)  NULL,
    [Fmd4]     NVARCHAR (4)  NULL,
    [Oms4]     NVARCHAR (4)  NULL,
    [Omd4]     NVARCHAR (4)  NULL,
    [Fms5]     NVARCHAR (4)  NULL,
    [Fmd5]     NVARCHAR (4)  NULL,
    [Oms5]     NVARCHAR (4)  NULL,
    [Omd5]     NVARCHAR (4)  NULL,
    [Fms6]     NVARCHAR (4)  NULL,
    [Fmd6]     NVARCHAR (4)  NULL,
    [Oms6]     NVARCHAR (4)  NULL,
    [Omd6]     NVARCHAR (4)  NULL,
    [Fms7]     NVARCHAR (4)  NULL,
    [Fmd7]     NVARCHAR (4)  NULL,
    [Oms7]     NVARCHAR (4)  NULL,
    [Omd7]     NVARCHAR (4)  NULL,
    [Fms8]     NVARCHAR (4)  NULL,
    [Fmd8]     NVARCHAR (4)  NULL,
    [Oms8]     NVARCHAR (4)  NULL,
    [Omd8]     NVARCHAR (4)  NULL,
    CONSTRAINT [ZapisProbiPrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [ZapisProbiToOrtostaticheskayaProba] FOREIGN KEY ([MasterID]) REFERENCES [dbo].[OrtostaticheskayaProba] ([ID]) ON DELETE CASCADE
);

