CREATE TABLE [dbo].[ZhelchFraktsionnoeIssledovanie] (
    [ID]                               INT        NOT NULL,
    [PatID]                            INT        NULL,
    [NomerAnaliza]                     INT        NULL,
    [DataProvedeniyaAnaliza]           DATETIME   NULL,
    [NachaloVideleniyaZhelchi]         INT        NULL,
    [TsvetA]                           INT        NULL,
    [ProzrachnostA]                    INT        NULL,
    [KonsistentsiyaA]                  INT        NULL,
    [PH]                               FLOAT (53) NULL,
    [OtnositelnayaPlotnost]            FLOAT (53) NULL,
    [Kolichestvo]                      FLOAT (53) NULL,
    [IIFazaZakritogoSfinkteraOddi]     FLOAT (53) NULL,
    [IIIFazaVideleniyaZhelchiPortsiiA] FLOAT (53) NULL,
    [TsvetB]                           INT        NULL,
    [ProzrachnostB]                    INT        NULL,
    [KonsistentsiyaB]                  INT        NULL,
    [PHB]                              FLOAT (53) NULL,
    [OtnositelnayaPlotnostB]           FLOAT (53) NULL,
    [KolichestvoB]                     FLOAT (53) NULL,
    [TsvetC]                           INT        NULL,
    [ProzrachnostC]                    INT        NULL,
    [KonsistentsiyaC]                  INT        NULL,
    [PHC]                              FLOAT (53) NULL,
    [OtnositelnayaPlotnostC]           FLOAT (53) NULL,
    [KolichestvoC]                     FLOAT (53) NULL,
    [Vrach]                            INT        NULL,
    CONSTRAINT [ZhelchFraktsionnoeIssledovaniePrimKey] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [ZhelchFraktsionnoeIssledovanieToPatForm] FOREIGN KEY ([ID]) REFERENCES [dbo].[PatForm] ([ID]) ON DELETE CASCADE
);

