CREATE VIEW AA_IKR
AS
SELECT KODREL, NOMAMB, NOMERIB, ITR, SNTR, IFR, SNFR, S, PO, RG, DATOTCH, F24, F25, CITO, OLK2, OLK3, OLK4, OLK5, OLK6, OLK7, OLK8, OLK9, OLK10, OSL1KRD, OSL2KRD, OSL1, OSL2, GPP, GVPR, G
FROM [IKR] 
